.dockerignore, .github/workflows/docker.yml, Dockerfile
- Required GitHub Actions secrets: 
1. `DOCKER_USER`
1. `DOCKER_PASSWORD`
1. `DOCKER_ORG`
1. `DOCKER_REPOSITORY`
- Runs on alpine and includes terraform
- Build ARGS: `ARCH=linux` and  `TERRAFORM_VERSION=0.12.25`
- Image size: compressed 26MB, uncompressed 86MB
- Test Docker image- git clone this repo and then execute:
```
docker run  -v $PWD/:/code/  --rm unfor19/infracost -tfdir /code/examples/small_terraform
```
Closes #45
=> Feature docker

.github/workflows/go.yml, Dockerfile, Makefile, README.md, scripts/install_provider.sh
=> Add terraform-provider-infracost dependencies

examples/terraform/main.tf, internal/providers/terraform/aws/lambda_function_test.go, internal/providers/terraform/aws/nat_gateway_test.go, internal/providers/terraform/parser.go
See: github.com/infracost/terraform-provider-infracost/pull/3
=> Convert to using data sources for the terraform provider

pkg/schema/resource_data.go
Potential fix for https://github.com/infracost/infracost/issues/76
=> Fix nil map entry panic when Terraform JSON values are empty

README.md
relates to https://github.com/Homebrew/homebrew-core/pull/60777
fixes #73
=> chore(docs): add homebrew installation

.github/workflows/create-release.yml
Simplify and speed up a release workflow by using [git-release](https://github.com/marketplace/actions/git-release) action.
=> Simplify Release Workflow

.github/workflows/create-release.yml
=> Open Homebrew formula update PR on release

CONTRIBUTING.md
This is not done or polished but I'm going to merge it in case it helps people who are in the process of adding new resources
=> Initial docs on how new resources can be added

pkg/output/table.go
Old:
```
aws_autoscaling_group.asg1
├─ Compute (on-demand, t3.medium) (aws_launch_template.lt1)         1460  hours        0.0416       0.0832       60.7360
├─ Storage (block_device_mapping[0])                                  20  GB-months    0.1000       0.0027        2.0000
├─ Storage (block_device_mapping[1])                                  40  GB-months    0.1250       0.0068        5.0000
├─ Storage IOPS (block_device_mapping[1])                            400  IOPS-months  0.0650       0.0356       26.0000
└─ Storage (root_block_device)                                        16  GB-months    0.1000       0.0022        1.6000
Total                                                                                               0.1306       95.3360
```
New:
``` …
```
=> feat(output): add table tree hierarchy for subresources

.github/workflows/create-release.yml, .github/workflows/generate-docs.yml, .gitignore, Makefile, cmd/infracost-generate-docs/main.go, docs/templates/supported_resources.md, internal/docs/generator.go, internal/providers/terraform/aws/autoscaling_group.go, internal/providers/terraform/aws/db_instance.go, internal/providers/terraform/aws/docdb_cluster_instance.go, internal/providers/terraform/aws/dynamodb_table.go, internal/providers/terraform/aws/ebs_snapshot.go, internal/providers/terraform/aws/ebs_snapshot_copy.go, internal/providers/terraform/aws/ebs_volume.go, internal/providers/terraform/aws/ecs_service.go, internal/providers/terraform/aws/elasticsearch_domain.go, internal/providers/terraform/aws/elb.go, internal/providers/terraform/aws/instance.go, internal/providers/terraform/aws/lambda_function.go, internal/providers/terraform/aws/lb.go, internal/providers/terraform/aws/nat_gateway.go, internal/providers/terraform/aws/rds_cluster_instance.go, internal/providers/terraform/aws/resource_registry.go, internal/providers/terraform/parser.go, internal/providers/terraform/resource_registry.go, pkg/schema/registry_item.go
=> Automatic resources doc generator

docs/templates/supported_resources.md, internal/providers/terraform/aws/lb.go, internal/providers/terraform/aws/resource_registry.go, internal/providers/terraform/resource_registry.go, pkg/schema/registry_item.go
=> Remove alias from registry items and docs

cmd/infracost/main.go, internal/providers/terraform/cmd.go, internal/providers/terraform/provider.go
=> Fix large terraform log lines

internal/providers/terraform/aws/dynamodb_table.go, internal/providers/terraform/aws/dynamodb_table_test.go
=> DyanmoDB add resources level 1 support

internal/providers/terraform/aws/dms.go, internal/providers/terraform/aws/dms_test.go, internal/providers/terraform/aws/resource_registry.go
Fix #145 
AWS Pricing: https://aws.amazon.com/dms/pricing/
Terraform: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_replication_instance
=> Add aws dms support

README.md
=> Adding docker usage to readme

internal/providers/terraform/aws/autoscaling_group.go
=> fix(aws): divide by zero

internal/providers/terraform/provider.go
We can't reliably tell if init needs to be run, so safer just now to just always run it
=> fix(terraform): always run init

internal/providers/terraform/aws/dms.go
=> Fix aws dms region

internal/providers/terraform/aws/dms.go
Reverts infracost/infracost#178
=> Revert "Fix aws dms region"

docs/generated/supported_resources.md, examples/terraform/main.tf, internal/providers/terraform/aws/resource_registry.go, internal/providers/terraform/aws/sqs_queue.go, internal/providers/terraform/aws/sqs_queue_test.go
Output from Tests below.
```
=== RUN   TestSQSQueue_usage
✔ Running terraform init
✔ Running terraform plan
✔ Running terraform show
--- PASS: TestSQSQueue_usage (8.79s)
PASS
```
This requires the following PR for the terraform provider merging.
https://github.com/infracost/terraform-provider-infracost/pull/9
=> Add support for SQS

.github/workflows/go.yml, examples/terraform/data.tf, examples/terraform/main.tf
That’s needed for the SQS resource
=> fix(example): add provider version to force update

internal/providers/terraform/parser.go, internal/providers/terraform/parser_internal_test.go
=> Add support for region string variable

cmd/infracost/default.go, cmd/infracost/main.go, cmd/infracost/register.go, go.mod, go.sum, internal/config/config.go, internal/config/config_file.go, internal/update/update.go
Add API key automatically to config file
=> Simplify register process

internal/providers/terraform/aws/route53_record.go
Closes #215
@aliscott FYI I checked all other occurrences and we're already handling this case.
=> fix(aws): handle case where references is empty

CONTRIBUTING.md, internal/providers/terraform/aws/autoscaling_group.go, internal/schema/resource.go
=> Function re-use across resources

.github/ISSUE_TEMPLATE/config.yml, internal/providers/terraform/aws/lambda_function.go, internal/providers/terraform/aws/lambda_function_test.go
I found out about this from https://news.ycombinator.com/item?id=25267029
=> fix(aws): lambda has changed from 100ms to 1ms billing

scripts/price_explorer/2_find_product_families.sh
e.g. AWS CloudWatch and KMS have null values
=> fix: productFamily can be null

internal/providers/terraform/google/compute_address.go, internal/providers/terraform/google/compute_address_test.go, internal/providers/terraform/google/registry.go
Fix #232 
@aliscott This is the best I could do based on my discussion with @alikhajeh1 
It would be great if you can double-check the logic and coding style since it's been a while since I committed code to infracost.
=> Add google_compute_address

.github/ISSUE_TEMPLATE/config.yml, README.md, docs/templates/supported_resources.md
More people seem to have it installed and other related communities (FinOps, terraform, pulumi, atlantis…) are there.
=> docs: switch to Slack

internal/providers/terraform/aws/eks_node_group.go
=> fix(eks_node_group): fix bug with empty array

internal/providers/terraform/aws/ecr_repository.go, internal/providers/terraform/aws/ecr_repository_test.go, internal/providers/terraform/aws/registry.go
**Objective**:
Adds support for `ecr_repository`
** Closes ** #152 
```
WWWWWWWWWWWWWWWWWWWWWW
NAME                     MONTHLY QTY  UNIT       PRICE   HOURLY COST  MONTHLY COST  
WWWWWWWWWWWWWWWWWWWWWWWWWWW
aws_ecr_repository.this                                                             
└─ Storage                         -  GB-months  0.1000            -             -  
Total                                                              -             -  
OVERALL TOTAL (USD)                                                -             -  
WWWWWWWWWWWWWWWWWWWWWWWWWWW
```
=> feat(aws): Added support for AWS ECR

README.md, cmd/infracost/main.go, scripts/ci/diff.sh
Before, this was working ok on push events, but not pull_request events
=> fix(diff script): handle GH PR events

internal/providers/terraform/aws/fsx_windows_file_system.go, internal/providers/terraform/aws/fsx_windows_file_system_test.go, internal/providers/terraform/aws/registry.go
=> feat(aws): add support for AWS fsx windows fs

internal/output/output.go, internal/output/templates.go, internal/providers/terraform/parser.go, internal/providers/terraform/parser_internal_test.go, internal/schema/resource.go, internal/schema/resource_data.go
=> Add tags to HTML and JSON output

scripts/install_provider.sh
Little guard to make sure `wget` is installed and remove the error noise
=> Checking for wget before running install_provider script

cmd/infracost/report.go
Fixes #309 
Using full given path rather than base file path
=> Using given path instead of file base path

cmd/infracost/main.go, scripts/report_all.sh, scripts/terragrunt/report_all.sh
Closes https://github.com/infracost/infracost/issues/188
=> Add report_all.sh script for multi-project runs

CONTRIBUTING.md
@sinabakh can you possibly review this quick change to see if it makes sense?
=> docs: add note about price tier units

infracost-usage-example.yml, internal/providers/terraform/aws/cloudfront_distribution.go
=> Fix aws cloudfront usage data naming

infracost-usage-example.yml, internal/providers/terraform/aws/vpc_endpoint.go
Closes https://github.com/infracost/infracost/issues/342
=> fix: return the correct NoPrice/IsSkipped resource

internal/providers/terraform/aws/ssm_activation_test.go, internal/providers/terraform/aws/ssm_parameter_test.go
Adds additional tests for SSM to include usage data.
=> Added usage tests to SSM resources.

CONTRIBUTING.md, infracost-usage-example.yml, internal/providers/terraform/aws/registry.go, internal/providers/terraform/aws/secretsmanager_secret.go, internal/providers/terraform/aws/secretsmanager_secret_test.go
**Objective**: closes #336 
Adds support for `aws_secretsmanager_secret` `aws_secretsmanager_secret_policy`  `aws_secretsmanager_secret_rotation` `aws_secretsmanager_secret_version`
```
aws_secretsmanager_secret.my_secret                                                                          
├─ Secret                                               1  secret         0.4000       0.0005        0.4000  
└─ API calls                                          100  10k API Calls  0.0500       0.0068        5.0000  
Total                                                                                  0.0074        5.4000  
```
=> feat(aws): Adds support for AWS Secrets Manager.

CONTRIBUTING.md, cmd/infracost/register.go, internal/providers/terraform/aws/ebs_volume.go
Tiers have been introduced to io2 IOPS, we only support the first tier as mentioned in the docs
=> chore: fix aws_ebs_volume io2 returning multiple prices

internal/providers/terraform/provider.go
=> Run terraform init selectively

internal/update/update.go
Also skip checking if brew is installed if we're on the latest version.
=> fix(update): fix update check for brew

CONTRIBUTING.md, scripts/price_explorer/README.md
@ekifel can you possibly review this?
=> docs: add MongoDB lookup docs

infracost-example.yml, scripts/ci/atlantis_diff.sh
1. Handle Atlantis merge checkout-strategy #402 
2. Handle case of new projects in Atlantis where the base branch doesn't have the Terraform files yet #403
=> fix: two Atlantis bugs

CONTRIBUTING.md, infracost-usage-example.yml
Based on reviewing https://github.com/infracost/infracost/pull/398
@ekifel can you please give this a quick review?
=> docs: update contributing guide 

infracost-usage-example.yml, internal/providers/terraform/aws/autoscaling_group.go, internal/providers/terraform/aws/autoscaling_group_test.go, internal/providers/terraform/aws/ecs_service.go, internal/providers/terraform/aws/ecs_service_test.go
=> Feat: ECS on EC2

internal/schema/diff.go, internal/schema/diff_test.go
=> fix: nil pointer exception in diff calculation

internal/providers/terraform/aws/registry.go
Fixes https://github.com/infracost/infracost/issues/444
=> feat(aws): add aws_resourcegroups_group to list of free resources

Dockerfile
=> chore(deps): update tf and tg versions

Dockerfile
Fixes curl vulnerability [CVE-2020-8177](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-8177).
=> chore(deps): update alpine version

internal/providers/terraform/aws/elasticsearch_domain.go, internal/providers/terraform/aws/elasticsearch_domain_test.go
=> fix: aws elasticsearch domain storage type name

infracost-usage-example.yml, internal/providers/terraform/google/storage_bucket.go, internal/providers/terraform/google/storage_bucket_test.go
=> feat: add google stroage bucket data transfer costs

internal/providers/terraform/google/storage_bucket.go, internal/providers/terraform/google/storage_bucket_test.go
=> fix: google storage bucket storage and bucket prices

.github/workflows/go.yml, Dockerfile, go.mod, go.sum
- update go to v1.16
- update action workflow config
=> chore(deps): update go to v1.16

CONTRIBUTING.md, infracost-usage-example.yml, internal/providers/terraform/aws/dx_connection.go, internal/providers/terraform/aws/dx_connection_test.go, internal/providers/terraform/aws/registry.go
fixes #414 
With usage-file
```
aws_dx_connection.my_dx_connection                                                                     
├─ DX connection                                        730  hours  0.3000       0.3000      219.0000  
└─ Outbound data transfer to dx location EqDC2          100  GB     0.0200       0.0027        2.0000  
Total                                                                            0.3027      221.0000  
```
Without usage-file
```
aws_dx_connection.my_dx_connection                                                                     
├─ DX connection                                        730  hours  0.3000       0.3000      219.0000  
└─ Outbound data transfer to dx location EqDC2            -  GB     0.0200            -             -  
Total …
```
=> feat(aws): Adds support for direct connect connection(s)

.github/workflows/create-release.yml, Makefile, README.md
Still need to update the docs here (separate repo):
https://www.infracost.io/docs/#installation
=> chore(arm64) build Mac M1 binaries; closes #428

internal/providers/terraform/parser.go
Also check the ARN attribute for when building references between resources.
Fixes https://github.com/infracost/infracost/issues/349#issuecomment-790625130
=> Fix ECS service costs when using Terraform state file

CONTRIBUTING.md
Some of the language specify of code block is missing
=> docs: update contributing docs code block language

CONTRIBUTING.md, internal/providers/terraform/aws/dx_gateway_association.go
=> fix(aws): fix DX Gateway Associate region when using Terraform state

internal/providers/terraform/aws/elasticsearch_domain.go, internal/providers/terraform/aws/elasticsearch_domain_test.go
Fixes https://github.com/infracost/infracost/issues/522
=> Fix aws_elasticsearch_domain nil pointer issues

infracost-usage-example.yml, internal/providers/terraform/aws/registry.go, internal/providers/terraform/aws/route53_health_check.go, internal/providers/terraform/aws/route53_health_check_test.go
adds support for ``aws_route53_health_check``
Closes #474 
```
Detected Terraform directory at examples/test-example
✔ Running terraform plan
✔ Running terraform show
✔ Calculating monthly cost estimate
NAME                                             MONTHLY QTY  UNIT    PRICE   HOURLY COST  MONTHLY COST
aws_route53_health_check.aws-endpoints
├─ Health check (basic)                                    1  months  0.5000       0.0007        0.5000
├─ Health check (optional, https)                          1  months  1.0000       0.0014        1.0000
├─ Health check (optional, fast interval)                  1  months  1.0000       0.0014        1.0000
├─ Health check (optional, latency measurement)            1  months  1.0000       0.0014        1.0000
└─ Health check (optional, string …
```
=> feat(AWS): Added Route53 Health checks

cmd/infracost/run.go, infracost-usage-example.yml, internal/config/config.go, internal/providers/terraform/aws/dx_connection.go, internal/providers/terraform/aws/route53_health_check.go, internal/usage/usage_file.go, main.go
=> Sync usage data

scripts/ci/atlantis_diff.sh, scripts/ci/diff.sh
This should help for cases like #540.
=> fix(ci): increase precision for percentage calculations

infracost-usage-example.yml, internal/providers/terraform/google/container_registry.go, internal/providers/terraform/google/container_registry_test.go, internal/providers/terraform/google/registry.go
#473 
`<pre>                                                                                                                                                    
google_container_registry.my_registry                                                                                                             
<font color="#555753">├─ Storage (standard)</font>                                                                     <font color="#555753">150</font>  <font color="#555753">GiB-months</font>      <font color="#555753">0.0260</font>       <font color="#555753">0.0053</font>        <font color="#555753">3.9000</font>  
<font color="#555753">├─ Object adds, bucket/object list (class A)</font>                                                <font color="#555753">4</font>  <font …
=> feat: add google_container_registry

README.md, internal/update/update.go, scripts/install.sh
It would be better to open an issue and discuss it first but since it was faster to implement it I wanted to propose the change with its code.
What's your opinion regarding having such a script and making the installation seem more user-friendly (maybe).
=> feat: add installer script

infracost-usage-example.yml, internal/providers/terraform/azure/linux_virtual_machine.go, internal/providers/terraform/azure/managed_disk.go, internal/providers/terraform/azure/managed_disk_internal_test.go, internal/providers/terraform/azure/managed_disk_test.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/virtual_machine.go, internal/providers/terraform/azure/windows_virtual_machine.go
Resource details: https://github.com/infracost/infracost/issues/567
Example without usage file:
```
azurerm_managed_disk.premium
└─ Storage (P4)                                                1  months                     $4.80
azurerm_managed_disk.standard
├─ Storage (S4)                                                1  months                     $1.54
└─ Disk operations                               Cost depends on usage: $0.0005 per 10k operations
azurerm_managed_disk.standard_ssd
├─ Storage (E4)                                                1  months                     $2.40
└─ Disk operations                               Cost depends on usage: $0.002 per 10k operations
azurerm_managed_disk.ultra
├─ Storage (ultra, 8 GiB)                                  5,840  GiB-hours …
```
=> Add Azure managed disk

CONTRIBUTING.md
=> docs: set proper language for code blocks in  CONTRIBUTING.md

infracost-usage-example.yml, internal/providers/terraform/azure/mariadb_server.go, internal/providers/terraform/azure/mariadb_server_test.go, internal/providers/terraform/azure/registry.go
Issue #573 
```
Name                                               Quantity  Unit            Monthly Cost
azurerm_mariadb_server.my_server                                                          
├─ Compute (MO_Gen5_16)                                 730  hours              $1,379.41 
├─ Storage                                                5  GB-months              $0.57 
└─ Additional backup storage                          2,000  GB-months            $200.00 
azurerm_mariadb_server.without_usage                                                      
├─ Compute (GP_Gen5_4)                                  730  hours                $255.79 
├─ Storage                                               40  GB-months              $4.60 
└─ Additional backup storage …
```
=> feat(azure): Add support for Azure MariaDB database

infracost-usage-example.yml, internal/providers/terraform/azure/mariadb_server.go, internal/providers/terraform/azure/postgresql_server.go, internal/providers/terraform/azure/postgresql_server_test.go, internal/providers/terraform/azure/registry.go
Issue #572 
```
Name                                          Quantity  Unit       Monthly Cost 
azurerm_postgresql_server.my_server                                             
├─ Compute (MO_Gen5_16)                            730  hours         $1,379.41 
├─ Storage                                           5  GB-months         $0.57 
└─ Additional backup storage                     2,000  GB-months       $200.00 
azurerm_postgresql_server.without_usage                                                   
├─ Compute (MO_Gen5_16)                                 730  hours              $1,379.41 
├─ Storage                                                5  GB-months              $0.57 
└─ Additional backup storage                  Cost depends on usage: $0.10 per GB-months …
```
=> feat(azure): Add support for Azure PostgreSQL Server

infracost-usage-example.yml, internal/providers/terraform/azure/mysql_server.go, internal/providers/terraform/azure/mysql_server_test.go, internal/providers/terraform/azure/registry.go
Issue #571 
```
Name                                               Quantity  Unit            Monthly Cost 
azurerm_mysql_server.my_server                                                            
├─ Compute (MO_Gen5_16)                                 730  hours              $1,379.41 
├─ Storage                                                5  GB-months              $0.57 
└─ Additional backup storage                          2,000  GB-months            $200.00 
azurerm_mysql_server.without_usage                                                        
├─ Compute (MO_Gen5_16)                                 730  hours              $1,379.41 
├─ Storage                                                5  GB-months              $0.57 
└─ Additional backup storage …
```
=> feat(azure): add support for Azure MySQL Server

internal/providers/terraform/azure/mariadb_server.go
=> fix(azure): fix PostgreSQL test multiple products warning 

cmd/infracost/breakdown.go, cmd/infracost/output.go, cmd/infracost/run.go, internal/config/config.go, internal/output/output.go, internal/output/table.go
Issue #524
Previous PR with discusses: [here](https://github.com/infracost/infracost/pull/601)
=> feat(cli): add '--fields' flag to specify table output 

infracost-usage-example.yml, internal/providers/terraform/aws/autoscaling_group_test.go, internal/providers/terraform/aws/eks_node_group.go, internal/providers/terraform/aws/eks_node_group_test.go, internal/providers/terraform/aws/instance.go, internal/providers/terraform/aws/instance_test.go, internal/providers/terraform/aws/rds_cluster_instance.go, internal/providers/terraform/aws/rds_cluster_instance_test.go
=> chore: refactor virtual_cpu_count to vcpu_count so it matches the cloud

internal/output/diff.go
Issue #598 
Cases:
```
Monthly cost change for .
Amount:  +$3,790 ($0.00 -> $3,790)
```
```
Monthly cost change for .
Amount:  +$2,790 ($1,000 -> $3,790)
Percent: +279%
```
```
Monthly cost change for .
Amount:  -$2,510 ($6,300 -> $3,790)
Percent: -40%
```
=> feat(fix): Double negative for percentage in diff output

infracost-usage-example.yml, internal/providers/terraform/azure/app_service_environment.go, internal/providers/terraform/azure/app_service_environment_test.go, internal/providers/terraform/azure/app_service_plan.go, internal/providers/terraform/azure/app_service_plan_test.go, internal/providers/terraform/azure/registry.go
Output:
```
azurerm_app_service_environment.my_service                                     
├─ Stamp fee                                          730  hours       $991.34 
└─ Instance usage (I1)                                730  hours       $208.05 
azurerm_app_service_plan.example                                               
└─ Instance usage (PC2)                               730  hours       $118.59 
PROJECT TOTAL                                                        $1,757.98 ``
```
=> feat(azure):Add Azure App Service Plan and Environment #561

infracost-usage-example.yml, internal/providers/terraform/azure/function_app.go, internal/providers/terraform/azure/function_app_test.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/testdata/function_app_test/function_app_test.golden, internal/providers/terraform/azure/testdata/function_app_test/function_app_test.tf, internal/providers/terraform/azure/testdata/function_app_test/function_app_test.usage.yml
Issue #627 
Outputs: golden test file.
=> feat(azure): Add support for Azure Functions 

infracost-usage-example.yml, internal/providers/terraform/azure/container_registry.go, internal/providers/terraform/azure/container_registry_test.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/testdata/container_registry_test/container_registry_test.golden, internal/providers/terraform/azure/testdata/container_registry_test/container_registry_test.tf, internal/providers/terraform/azure/testdata/container_registry_test/container_registry_test.usage.yml
=> feat(azure): Add support for Azure Container Registry

internal/providers/terraform/aws/ec2_client_vpn_endpoint_test.go, internal/providers/terraform/aws/ec2_client_vpn_network_association_test.go, internal/providers/terraform/aws/ec2_traffic_mirror_session_test.go, internal/providers/terraform/aws/ec2_transit_gateway_peering_attachment_test.go, internal/providers/terraform/aws/ecr_repository_test.go, internal/providers/terraform/aws/testdata/ec2_client_vpn_endpoint_test/ec2_client_vpn_endpoint_test.golden, internal/providers/terraform/aws/testdata/ec2_client_vpn_endpoint_test/ec2_client_vpn_endpoint_test.tf, internal/providers/terraform/aws/testdata/ec2_client_vpn_network_association_test/ec2_client_vpn_network_association_test.golden, internal/providers/terraform/aws/testdata/ec2_client_vpn_network_association_test/ec2_client_vpn_network_association_test.tf, internal/providers/terraform/aws/testdata/ec2_traffic_mirror_session_test/ec2_traffic_mirror_session_test.golden, internal/providers/terraform/aws/testdata/ec2_traffic_mirror_session_test/ec2_traffic_mirror_session_test.tf, internal/providers/terraform/aws/testdata/ec2_transit_gateway_peering_attachment_test/ec2_transit_gateway_peering_attachment_test.golden, internal/providers/terraform/aws/testdata/ec2_transit_gateway_peering_attachment_test/ec2_transit_gateway_peering_attachment_test.tf, internal/providers/terraform/aws/testdata/ecr_repository_test/ecr_repository_test.golden, internal/providers/terraform/aws/testdata/ecr_repository_test/ecr_repository_test.tf, internal/providers/terraform/aws/testdata/ecr_repository_test/ecr_repository_test.usage.yml
=> test(aws): Add some aws golden tests

infracost-usage-example.yml, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/storage_account.go, internal/providers/terraform/azure/storage_account_test.go, internal/providers/terraform/azure/testdata/storage_account_test/storage_account_test.golden, internal/providers/terraform/azure/testdata/storage_account_test/storage_account_test.tf, internal/providers/terraform/azure/testdata/storage_account_test/storage_account_test.usage.yml
Issue #574 
Output examples: in golden test. 
Details: 
- Terraform supports Premium and Standard account tiers.
- For Standard tier possible redundancy is: LRS, GRS, RA_GRS
- For Premium tier possible redundancy is: LRS, ZRS
=> feat(azure): Add support for Azure Block Blob Storage Account

internal/providers/terraform/azure/public_ip.go, internal/providers/terraform/azure/public_ip_prefix.go, internal/providers/terraform/azure/public_ip_prefix_test.go, internal/providers/terraform/azure/public_ip_test.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/testdata/public_ip_prefix_test/public_ip_prefix_test.golden, internal/providers/terraform/azure/testdata/public_ip_prefix_test/public_ip_prefix_test.tf, internal/providers/terraform/azure/testdata/public_ip_test/public_ip_test.golden, internal/providers/terraform/azure/testdata/public_ip_test/public_ip_test.tf
=> feat(azure): Add support for Azure IP address 

internal/providers/terraform/azure/integration_service_environment.go, internal/providers/terraform/azure/integration_service_environment_test.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/testdata/integration_service_environment_test/integration_service_environment_test.golden, internal/providers/terraform/azure/testdata/integration_service_environment_test/integration_service_environment_test.tf
=> feat(azure): Add support for Azure Logic App Integration Service Environments

infracost-usage-example.yml, internal/providers/terraform/azure/kubernetes_cluster.go, internal/providers/terraform/azure/kubernetes_cluster_node_pool.go, internal/providers/terraform/azure/kubernetes_cluster_node_pool_test.go, internal/providers/terraform/azure/kubernetes_cluster_test.go, internal/providers/terraform/azure/managed_disk.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/testdata/kubernetes_cluster_node_pool_test/kubernetes_cluster_node_pool_test.golden, internal/providers/terraform/azure/testdata/kubernetes_cluster_node_pool_test/kubernetes_cluster_node_pool_test.tf, internal/providers/terraform/azure/testdata/kubernetes_cluster_node_pool_test/kubernetes_cluster_node_pool_test.usage.yml, internal/providers/terraform/azure/testdata/kubernetes_cluster_test/kubernetes_cluster_test.golden, internal/providers/terraform/azure/testdata/kubernetes_cluster_test/kubernetes_cluster_test.tf, internal/providers/terraform/azure/testdata/kubernetes_cluster_test/kubernetes_cluster_test.usage.yml, internal/providers/terraform/azure/virtual_machine.go
=> feat(azure): Add support for Azure Kubernetes Service

infracost-usage-example.yml, internal/providers/terraform/azure/databricks_workspace.go, internal/providers/terraform/azure/databricks_workspace_test.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/testdata/databricks_workspace_test/databricks_workspace_test.golden, internal/providers/terraform/azure/testdata/databricks_workspace_test/databricks_workspace_test.tf, internal/providers/terraform/azure/testdata/databricks_workspace_test/databricks_workspace_test.usage.yml
=> feat(azure): Add support for Azure Databricks

infracost-usage-example.yml, internal/providers/terraform/aws/data_transfer_test.go, internal/providers/terraform/aws/testdata/data_transfer_test/data_transfer_test.golden, internal/providers/terraform/aws/testdata/data_transfer_test/data_transfer_test.tf, internal/providers/terraform/aws/testdata/data_transfer_test/data_transfer_test.usage.yml
Changes:
* Add `transfer_data` golden file tests
* Fix a typo in usage file examples
=> Test aws add data transfer test

internal/providers/terraform/azure/cosmosdb_cassandra_keyspace.go, internal/providers/terraform/azure/testdata/kubernetes_cluster_test/kubernetes_cluster_test.golden, internal/providers/terraform/azure/testdata/kubernetes_cluster_test/kubernetes_cluster_test.tf, internal/providers/terraform/azure/testdata/virtual_machine_scale_set_test/virtual_machine_scale_set_test.golden, internal/providers/terraform/azure/testdata/virtual_machine_scale_set_test/virtual_machine_scale_set_test.tf
Fixes of these cases: 
https://github.com/infracost/infracost/issues/591#issuecomment-848972038
https://github.com/infracost/infracost/issues/675#issuecomment-848976179
https://github.com/infracost/infracost/issues/669#issuecomment-848968240
=> fix(test): fixed no/multiple products warnings in tests

internal/config/environment.go, scripts/ci/diff.sh, scripts/ci/jenkins_diff.sh, scripts/ci/sleep.sh
Fixes https://github.com/infracost/infracost/issues/531 
This works with Azure DevOps Pipelines that use either: the built-in Azure DevOps git repos or GitHub repos. If users ask for it, we can add support for the other options (e.g. bitbucket repos).
@sinabakh can you possibly review this PR?
=> Add CI/CD integration for Azure DevOps

internal/output/format.go, internal/providers/terraform/aws/testdata/cloudfront_distribution_test/cloudfront_distribution_test.golden, internal/providers/terraform/aws/testdata/cloudwatch_event_bus_test/cloudwatch_event_bus_test.golden, internal/providers/terraform/aws/testdata/docdb_cluster_snapshot_test/docdb_cluster_snapshot_test.golden, internal/providers/terraform/aws/testdata/docdb_cluster_test/docdb_cluster_test.golden, internal/providers/terraform/aws/testdata/elasticache_cluster_test/elasticache_cluster_test.golden, internal/providers/terraform/aws/testdata/elasticache_replication_group_test/elasticache_replication_group_test.golden, internal/providers/terraform/aws/testdata/nat_gateway_test/nat_gateway_test.golden, internal/providers/terraform/aws/testdata/redshift_cluster_test/redshift_cluster_test.golden, internal/providers/terraform/aws/testdata/s3_bucket_analytics_configuration_test/s3_bucket_analytics_configuration_test.golden, internal/providers/terraform/aws/testdata/s3_bucket_inventory_test/s3_bucket_inventory_test.golden, internal/providers/terraform/aws/testdata/s3_bucket_test/s3_bucket_test.golden, internal/providers/terraform/aws/testdata/step_function_test/step_function_test.golden, internal/providers/terraform/azure/testdata/cosmosdb_cassandra_keyspace_test/cosmosdb_cassandra_keyspace_test.golden, internal/providers/terraform/azure/testdata/firewall_test/firewall_test.golden, internal/providers/terraform/azure/testdata/function_app_test/function_app_test.golden, internal/providers/terraform/azure/testdata/nat_gateway_test/nat_gateway_test.golden, internal/providers/terraform/azure/testdata/storage_account_test/storage_account_test.golden, internal/providers/terraform/google/testdata/compute_router_nat_test/compute_router_nat_test.golden, internal/providers/terraform/google/testdata/storage_bucket_test/storage_bucket_test.golden
=> fix(output): Make price rounding more correctly

infracost-usage-example.yml, internal/providers/terraform/azure/api_management.go, internal/providers/terraform/azure/api_management_test.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/testdata/api_management_test/api_management_test.golden, internal/providers/terraform/azure/testdata/api_management_test/api_management_test.tf, internal/providers/terraform/azure/testdata/api_management_test/api_management_test.usage.yml
=> feat(azure): Add support for Azure API Management

infracost-usage-example.yml, internal/providers/terraform/azure/postgresql_flexible_server.go, internal/providers/terraform/azure/postgresql_flexible_server_test.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/testdata/postgresql_flexible_server_test/postgresql_flexible_server_test.golden, internal/providers/terraform/azure/testdata/postgresql_flexible_server_test/postgresql_flexible_server_test.tf, internal/providers/terraform/azure/testdata/postgresql_flexible_server_test/postgresql_flexible_server_test.usage.yml
Issue #722 
[Estimate](https://azure.com/e/b64ef47123094fd48ff8afe58456b824) for comparing costs with golden file.
=> feat(azure): Add support for PostgreSQL Flexible Server

cmd/infracost/output.go, cmd/infracost/run.go, internal/config/project_metadata.go, internal/config/util.go, internal/output/diff.go, internal/output/output.go, internal/output/table.go, internal/output/templates.go, internal/providers/terraform/dir_provider.go, internal/providers/terraform/plan_json_provider.go, internal/providers/terraform/plan_provider.go, internal/providers/terraform/state_json_provider.go, internal/providers/terraform/tftest/tftest.go, internal/schema/project.go, internal/schema/project_test.go, internal/schema/provider.go
* Adds overall total to table and HTML outputs
* Moves `path` to metadata and adds `name` in JSON output
Closes #734, and decided to not fix #735.
=> v0.9 changes

internal/providers/terraform/azure/cdn_endpoint.go, internal/providers/terraform/azure/cosmosdb_cassandra_keyspace.go, internal/providers/terraform/azure/cosmosdb_cassandra_table.go, internal/providers/terraform/azure/cosmosdb_gremlin_database.go, internal/providers/terraform/azure/cosmosdb_gremlin_graph.go, internal/providers/terraform/azure/cosmosdb_mongo_collection.go, internal/providers/terraform/azure/cosmosdb_mongo_database.go, internal/providers/terraform/azure/cosmosdb_sql_container.go, internal/providers/terraform/azure/cosmosdb_sql_database.go, internal/providers/terraform/azure/cosmosdb_table.go, internal/providers/terraform/azure/dns_zone.go, internal/providers/terraform/azure/testdata/cosmosdb_cassandra_table_test/cosmosdb_cassandra_table_test.golden, internal/providers/terraform/azure/testdata/cosmosdb_cassandra_table_test/cosmosdb_cassandra_table_test.tf, internal/providers/terraform/azure/testdata/cosmosdb_table_test/cosmosdb_table_test.golden, internal/providers/terraform/azure/testdata/cosmosdb_table_test/cosmosdb_table_test.tf
This might happen if the reference is defined in another module.
=> fix(azure): handle cases where references are not available

infracost-usage-example.yml, internal/providers/terraform/azure/mssql_database.go, internal/providers/terraform/azure/testdata/mssql_database_test/mssql_database_test.golden, internal/providers/terraform/azure/testdata/mssql_database_test/mssql_database_test.tf, internal/providers/terraform/azure/testdata/mssql_database_test/mssql_database_test.usage.yml
=> feat(azure): Add support for TDU purchase model for Azure MSSQL 

internal/config/environment.go, internal/schema/project.go, scripts/ci/diff.sh
* Fixes password in VCS url
* Fixes non-word characters in repo names
* Fixes http instead of https
=> Fix project name for integrations

infracost-usage-example.yml, internal/providers/terraform/azure/automation_account.go, internal/providers/terraform/azure/automation_account_test.go, internal/providers/terraform/azure/automation_dsc_configuration.go, internal/providers/terraform/azure/automation_dsc_configuration_test.go, internal/providers/terraform/azure/automation_dsc_nodeconfiguration.go, internal/providers/terraform/azure/automation_dsc_nodeconfiguration_test.go, internal/providers/terraform/azure/automation_job_schedule.go, internal/providers/terraform/azure/automation_job_schedule_test.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/testdata/automation_account_test/automation_account_test.golden, internal/providers/terraform/azure/testdata/automation_account_test/automation_account_test.tf, internal/providers/terraform/azure/testdata/automation_account_test/automation_account_test.usage.yml, internal/providers/terraform/azure/testdata/automation_dsc_configuration_test/automation_dsc_configuration_test.golden, internal/providers/terraform/azure/testdata/automation_dsc_configuration_test/automation_dsc_configuration_test.tf, internal/providers/terraform/azure/testdata/automation_dsc_configuration_test/automation_dsc_configuration_test.usage.yml, internal/providers/terraform/azure/testdata/automation_dsc_nodeconfiguration_test/automation_dsc_nodeconfiguration_test.golden, internal/providers/terraform/azure/testdata/automation_dsc_nodeconfiguration_test/automation_dsc_nodeconfiguration_test.tf, internal/providers/terraform/azure/testdata/automation_dsc_nodeconfiguration_test/automation_dsc_nodeconfiguration_test.usage.yml, internal/providers/terraform/azure/testdata/automation_job_schedule_test/automation_job_schedule_test.golden, internal/providers/terraform/azure/testdata/automation_job_schedule_test/automation_job_schedule_test.tf, internal/providers/terraform/azure/testdata/automation_job_schedule_test/automation_job_schedule_test.usage.yml
=> feat(azure):Add support for Azure Automation

internal/output/combined.go
This was introduced in v0.9 when we decided to re-add the total costs to the JSON, but missed them when combining infracost JSON files.
=> Fixes total monthly and hourly cost not populated for `infracost output`

infracost-usage-example.yml, internal/providers/terraform/aws/cloudformation_stack.go, internal/providers/terraform/aws/cloudformation_stack_set.go, internal/providers/terraform/aws/cloudformation_stack_set_test.go, internal/providers/terraform/aws/cloudformation_stack_test.go, internal/providers/terraform/aws/registry.go, internal/providers/terraform/aws/testdata/cloudformation_stack_set_test/cloudformation_stack_set_test.golden, internal/providers/terraform/aws/testdata/cloudformation_stack_set_test/cloudformation_stack_set_test.tf, internal/providers/terraform/aws/testdata/cloudformation_stack_set_test/cloudformation_stack_set_test.usage.yml, internal/providers/terraform/aws/testdata/cloudformation_stack_test/cloudformation_stack_test.golden, internal/providers/terraform/aws/testdata/cloudformation_stack_test/cloudformation_stack_test.tf, internal/providers/terraform/aws/testdata/cloudformation_stack_test/cloudformation_stack_test.usage.yml
=> feat(aws): Add pricing support for AWS CloudFormation

internal/providers/terraform/dir_provider.go
=> Issue Fix: Running with HCL JSON fails

infracost-usage-example.yml, internal/providers/terraform/google/bigquery_dataset.go, internal/providers/terraform/google/bigquery_dataset_test.go, internal/providers/terraform/google/bigquery_table.go, internal/providers/terraform/google/bigquery_table_test.go, internal/providers/terraform/google/registry.go, internal/providers/terraform/google/testdata/bigquery_dataset_test/bigquery_dataset_test.golden, internal/providers/terraform/google/testdata/bigquery_dataset_test/bigquery_dataset_test.tf, internal/providers/terraform/google/testdata/bigquery_dataset_test/bigquery_dataset_test.usage.yml, internal/providers/terraform/google/testdata/bigquery_table_test/bigquery_table_test.golden, internal/providers/terraform/google/testdata/bigquery_table_test/bigquery_table_test.tf, internal/providers/terraform/google/testdata/bigquery_table_test/bigquery_table_test.usage.yml
=> feat(google): add support for Google BigQuery

infracost-usage-example.yml, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/search_service.go, internal/providers/terraform/azure/search_service_test.go, internal/providers/terraform/azure/testdata/search_service_test/search_service_test.golden, internal/providers/terraform/azure/testdata/search_service_test/search_service_test.tf, internal/providers/terraform/azure/testdata/search_service_test/search_service_test.usage.yml
=> feat(azure): add support for Azure Cognitive Search

internal/providers/terraform/aws/autoscaling_group.go, internal/providers/terraform/aws/testdata/autoscaling_group_test/autoscaling_group_test.golden, internal/providers/terraform/aws/testdata/eks_node_group_test/eks_node_group_test.golden
=> bug(aws): root block device calculation - autoscaling launch template.

cmd/infracost/breakdown.go, cmd/infracost/completion.go, cmd/infracost/diff.go, cmd/infracost/main.go, cmd/infracost/output.go, cmd/infracost/run.go
=> feat(ci): add support for shell-completion

internal/ui/spin.go
=> feat(cli): Update spinner for Windows OS

internal/providers/terraform/azure/hdinsight_hadoop_cluster.go, internal/providers/terraform/azure/testdata/automation_account_test/automation_account_test.tf, internal/providers/terraform/azure/testdata/automation_dsc_configuration_test/automation_dsc_configuration_test.tf, internal/providers/terraform/azure/testdata/automation_dsc_nodeconfiguration_test/automation_dsc_nodeconfiguration_test.tf, internal/providers/terraform/azure/testdata/automation_job_schedule_test/automation_job_schedule_test.tf, internal/providers/terraform/azure/testdata/hdinsight_hadoop_cluster_test/hdinsight_hadoop_cluster_test.golden, internal/providers/terraform/azure/testdata/hdinsight_hbase_cluster_test/hdinsight_hbase_cluster_test.golden, internal/providers/terraform/azure/testdata/hdinsight_interactive_query_cluster_test/hdinsight_interactive_query_cluster_test.golden, internal/providers/terraform/azure/testdata/hdinsight_kafka_cluster_test/hdinsight_kafka_cluster_test.golden, internal/providers/terraform/azure/testdata/hdinsight_spark_cluster_test/hdinsight_spark_cluster_test.golden, internal/providers/terraform/azure/virtual_machine.go
=> feat(azure): update VM output in Azure HDInsight resources

internal/providers/terraform/dir_provider.go
A new error was added in https://github.com/hashicorp/terraform/commit/9b1bd19ca5ac15325fb663743503e83e0d8a0689#diff-2bb17b35251ba77935e5edc3a7f8443f80b3ac91d268c10d1ef0eaeca2ab832eR576.
This also removes a check for a duplicate check.
=> Fix init detection

internal/providers/terraform/azure/linux_virtual_machine.go, internal/providers/terraform/azure/windows_virtual_machine.go
This updates it so it works with Azure CosmosDB
=> Update regexes so they work with more regex engines

infracost-usage-example.yml, internal/providers/terraform/aws/kinesis_firehose_delivery_stream.go, internal/providers/terraform/aws/kinesis_firehose_delivery_stream_test.go, internal/providers/terraform/aws/registry.go, internal/providers/terraform/aws/testdata/kinesis_firehose_delivery_stream_test/kinesis_firehose_delivery_stream_test.golden, internal/providers/terraform/aws/testdata/kinesis_firehose_delivery_stream_test/kinesis_firehose_delivery_stream_test.tf, internal/providers/terraform/aws/testdata/kinesis_firehose_delivery_stream_test/kinesis_firehose_delivery_stream_test.usage.yml
=> feat(aws): Add support for Kinesis Firehose 

internal/providers/terraform/aws/efs_file_system.go, internal/providers/terraform/aws/testdata/efs_file_system_test/efs_file_system_test.golden, internal/providers/terraform/aws/testdata/efs_file_system_test/efs_file_system_test.tf, internal/providers/terraform/aws/testdata/efs_file_system_test/efs_file_system_test.usage.yml
=> feat(aws): Add support for Amazon EFS One zone

infracost-usage-example.yml, internal/providers/terraform/aws/testdata/efs_file_system_test/efs_file_system_test.tf, internal/providers/terraform/azure/lb.go, internal/providers/terraform/azure/lb_outbound_rule.go, internal/providers/terraform/azure/lb_outbound_rule_test.go, internal/providers/terraform/azure/lb_rule.go, internal/providers/terraform/azure/lb_rule_test.go, internal/providers/terraform/azure/lb_test.go, internal/providers/terraform/azure/nat_gateway.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/testdata/lb_outbound_rule_test/lb_outbound_rule_test.golden, internal/providers/terraform/azure/testdata/lb_outbound_rule_test/lb_outbound_rule_test.tf, internal/providers/terraform/azure/testdata/lb_rule_test/lb_rule_test.golden, internal/providers/terraform/azure/testdata/lb_rule_test/lb_rule_test.tf, internal/providers/terraform/azure/testdata/lb_test/lb_test.golden, internal/providers/terraform/azure/testdata/lb_test/lb_test.tf, internal/providers/terraform/azure/testdata/lb_test/lb_test.usage.yml
=> feat(azure): Add support for Azure Load Balancer 

infracost-usage-example.yml, internal/providers/terraform/azure/kubernetes_cluster.go, internal/providers/terraform/azure/testdata/kubernetes_cluster_test/kubernetes_cluster_test.golden, internal/providers/terraform/azure/testdata/kubernetes_cluster_test/kubernetes_cluster_test.tf, internal/providers/terraform/azure/testdata/kubernetes_cluster_test/kubernetes_cluster_test.usage.yml
=> feat(azure):Add support for Azure Kubernetes Load Balancer and HTTP Application Routing 

infracost-usage-example.yml, internal/providers/terraform/azure/application_insights.go, internal/providers/terraform/azure/application_insights_test.go, internal/providers/terraform/azure/application_insights_web_t.go, internal/providers/terraform/azure/application_insights_web_t_test.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/testdata/application_insights_test/application_insights_test.golden, internal/providers/terraform/azure/testdata/application_insights_test/application_insights_test.tf, internal/providers/terraform/azure/testdata/application_insights_test/application_insights_test.usage.yml, internal/providers/terraform/azure/testdata/application_insights_web_t_test/application_insights_web_t_test.golden, internal/providers/terraform/azure/testdata/application_insights_web_t_test/application_insights_web_t_test.tf
=> feat(azure): add support for Azure Application Insights

scripts/ci/atlantis_diff.sh, scripts/ci/diff.sh, scripts/ci/jenkins_diff.sh
Closes https://github.com/infracost/infracost-azure-devops/issues/1
=> feat(ci): use show_skipped env to control the output

internal/providers/terraform/aws/api_gateway_stage.go, internal/providers/terraform/aws/apigatewayv2_api.go, internal/providers/terraform/aws/autoscaling_group.go, internal/providers/terraform/aws/cloudfront_distribution.go, internal/providers/terraform/aws/cloudwatch_metric_alarm.go, internal/providers/terraform/aws/data_transfer.go, internal/providers/terraform/aws/db_instance.go, internal/providers/terraform/aws/ebs_volume.go, internal/providers/terraform/aws/ec2_transit_gateway_vpc_attachment.go, internal/providers/terraform/aws/ecs_service.go, internal/providers/terraform/aws/eks_node_group.go, internal/providers/terraform/aws/elasticache_cluster.go, internal/providers/terraform/aws/elasticsearch_domain.go, internal/providers/terraform/aws/fsx_windows_file_system.go, internal/providers/terraform/aws/instance.go, internal/providers/terraform/aws/lb.go, internal/providers/terraform/aws/mq_broker.go, internal/providers/terraform/aws/rds_cluster.go, internal/providers/terraform/aws/redshift_cluster.go, internal/providers/terraform/aws/s3_bucket.go, internal/providers/terraform/aws/sns_topic_subscription.go, internal/providers/terraform/aws/ssm_parameter.go, internal/providers/terraform/aws/step_function.go, internal/providers/terraform/aws/vpc_endpoint.go
- Second PR to fix https://github.com/infracost/infracost/issues/729. This takes care of fixing the case comparison for the aws.
=> Fix case comparisons for aws

internal/providers/terraform/azure/cosmosdb_cassandra_keyspace.go, internal/providers/terraform/azure/firewall.go, internal/providers/terraform/azure/function_app.go, internal/providers/terraform/azure/key_vault_key.go, internal/providers/terraform/azure/kubernetes_cluster.go, internal/providers/terraform/azure/kubernetes_cluster_node_pool.go, internal/providers/terraform/azure/managed_disk.go, internal/providers/terraform/azure/mariadb_server.go, internal/providers/terraform/azure/mssql_database.go, internal/providers/terraform/azure/mysql_server.go, internal/providers/terraform/azure/notification_hub_namespace.go, internal/providers/terraform/azure/postgresql_flexible_server.go, internal/providers/terraform/azure/postgresql_server.go, internal/providers/terraform/azure/storage_account.go, internal/providers/terraform/azure/virtual_machine.go, internal/providers/terraform/azure/virtual_machine_scale_set.go, internal/providers/terraform/azure/windows_virtual_machine.go
PR to fix case comparisons for Azure
Issue: https://github.com/infracost/infracost/issues/729
=> fix(azure): case comparison

internal/providers/terraform/aws/kinesisanalyticsv2_application.go
Make sure it only includes the non-Interactive usagetype
=> fix(aws): fix Kinesis picking up multiple products

internal/providers/terraform/azure/registry.go
Azure Lighthouse Free Pricing Reference: https://azure.microsoft.com/en-us/services/azure-lighthouse/#pricing
=> added free resources for Azure Lighthouse and Management Locks

README.md, internal/providers/terraform/azure/registry.go
Azure DNS, Backup, Managed Applications, Azure Sentinel, Azure SQL, Azure Database, Azure VM Scale Sets, Availability Sets
=> added multiple free resources

examples/terraform/main.tf, internal/providers/terraform/aws/testdata/instance_test/instance_test.tf, internal/providers/terraform/tftest/tftest.go
https://github.com/hashicorp/terraform-provider-aws/issues/20287
=> chore: terraform-provider-aws fixed bug in v3.53.0

internal/providers/terraform/aws/autoscaling_group_test.go, internal/providers/terraform/aws/instance_test.go, internal/providers/terraform/aws/testdata/autoscaling_group_test/autoscaling_group_test.golden, internal/providers/terraform/aws/testdata/instance_test/instance_test.golden, internal/providers/terraform/azure/cosmosdb_cassandra_table_test.go, internal/providers/terraform/azure/cosmosdb_table_test.go, internal/providers/terraform/azure/dns_aaaa_record_test.go, internal/providers/terraform/azure/function_app_test.go, internal/providers/terraform/azure/hdinsight_hadoop_cluster_test.go, internal/providers/terraform/azure/hdinsight_hbase_cluster_test.go, internal/providers/terraform/azure/hdinsight_interactive_query_cluster_test.go, internal/providers/terraform/azure/hdinsight_kafka_cluster_test.go, internal/providers/terraform/azure/hdinsight_spark_cluster_test.go, internal/providers/terraform/azure/mssql_database_test.go, internal/providers/terraform/azure/testdata/cosmosdb_cassandra_table_test/cosmosdb_cassandra_table_test.golden, internal/providers/terraform/azure/testdata/cosmosdb_table_test/cosmosdb_table_test.golden, internal/providers/terraform/azure/testdata/function_app_test/function_app_test.golden, internal/providers/terraform/azure/testdata/hdinsight_hadoop_cluster_test/hdinsight_hadoop_cluster_test.golden, internal/providers/terraform/azure/testdata/hdinsight_hbase_cluster_test/hdinsight_hbase_cluster_test.golden, internal/providers/terraform/azure/testdata/hdinsight_interactive_query_cluster_test/hdinsight_interactive_query_cluster_test.golden, internal/providers/terraform/azure/testdata/hdinsight_kafka_cluster_test/hdinsight_kafka_cluster_test.golden, internal/providers/terraform/azure/testdata/hdinsight_spark_cluster_test/hdinsight_spark_cluster_test.golden, internal/providers/terraform/azure/testdata/mssql_database_test/mssql_database_test.golden, internal/providers/terraform/azure/testdata/vpn_gateway_test/vpn_gateway_test.golden, internal/providers/terraform/azure/vpn_gateway_test.go, internal/providers/terraform/tftest/tftest.go
test(aws): Capture logs for aws golden file tests
=> test: Capture logs in golden file tests

.github/workflows/go.yml, cmd/infracost/main.go
=> Fix infracost outputting to stdout

scripts/ci/diff.sh
Related to https://github.com/infracost/infracost/issues/943
=> feat(ci): enable Azure DevOps users to customize comment status

cmd/infracost/run.go, internal/providers/terraform/aws/dynamodb_table.go, internal/providers/terraform/aws/lambda_function.go, internal/resources/aws/dynamodb_table.go, internal/resources/aws/dynamodb_table_estimate_test.go, internal/resources/aws/estimate_test.go, internal/resources/aws/lambda_function.go, internal/resources/aws/lambda_function_estimate_test.go, internal/resources/aws/util.go, internal/usage/aws/cloudwatch.go, internal/usage/aws/configuration.go, internal/usage/aws/dynamodb.go, internal/usage/aws/lambda.go, internal/usage/aws/s3.go, internal/usage/aws/testing.go, internal/usage/aws/util.go
This estimates:
- DynamoDB storage & read/write request units.
- Lambda requests & duration
=> AWS SDK bindings & DynamoDB/Lambda estimation

internal/providers/terraform/azure/registry.go
NAT Gateway and Public IPs are already charged separately
=> added nat gateway associations as free resources

internal/providers/terraform/azure/app_service_custom_hostname_binding.go, internal/providers/terraform/azure/testdata/app_service_custom_hostname_binding_test/app_service_custom_hostname_binding_test.tf
=> fix: handle empty sslState

internal/providers/terraform/azure/registry.go
PR for https://github.com/infracost/infracost/issues/888
=> add virtual_desktop_hostpool as free resource

cmd/infracost/run.go, go.mod, go.sum, internal/providers/terraform/aws/autoscaling_group.go, internal/providers/terraform/aws/instance.go, internal/resources/aws/autoscaling_group.go, internal/resources/aws/autoscaling_group_estimate_test.go, internal/resources/aws/eks_node_group.go, internal/resources/aws/eks_node_group_estimate_test.go, internal/resources/aws/instance.go, internal/resources/aws/instance_estimate_test.go, internal/resources/aws/launch_configuration.go, internal/resources/aws/launch_template.go, internal/usage/aws/ec2.go
It took me awhile to wrap my head around ASG, LaunchTemplate and LaunchConfiguration but after some fiddling with TF plans and some grepping of AWS docs, I've got a somewhat elegant solution for OS estimation.
=> feat: detect instance operating system

cmd/infracost/run.go
Another option might be to set `runCtx.Config.SyncUsageFile` to false if the `--usage-file` flag isn't passed in.
=> Fix sync usage nil pointers

internal/providers/terraform/azure/bastion_host.go, internal/providers/terraform/azure/bastion_host_test.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/testdata/bastion_host_test/bastion_host_test.golden, internal/providers/terraform/azure/testdata/bastion_host_test/bastion_host_test.tf, internal/providers/terraform/azure/testdata/bastion_host_test/bastion_host_test.usage.yml
**Objective**:
Add support for bastion_host.
**Status**:
**Useful links**:
Pricing:
https://azure.microsoft.com/en-us/pricing/details/azure-bastion/
Terraform:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/bastion_host
Fix #939
=> feat(azure): add bastion_host

cmd/infracost/output.go
Also now shows an error if the path is invalid
=> fix: fix output paths containing ~

cmd/infracost/output_test.go, cmd/infracost/testdata/output_format_github_comment/output_format_github_comment.golden, cmd/infracost/testdata/output_format_github_comment_no_change/output_format_github_comment_no_change.golden, cmd/infracost/testdata/terraform_v0.14_breakdown.json, cmd/infracost/testdata/terraform_v0.14_nochange_breakdown.json, internal/output/combined.go, internal/output/diff.go, internal/output/markdown.go, internal/output/templates.go, scripts/ci/diff.sh
The first commit updates the golenfile to capture test cases we're interested in.  Subsequent commits should be a single change + the updated golden files, so it's probably easiest to review each commit in sequence.
=> Fix/output GitHub comment

Dockerfile
Fixes https://github.com/infracost/infracost/issues/1114
=> Bump terraform version in Dockerfile

internal/providers/terraform/aws/testdata/config_configuration_recorder_test/config_configuration_recorder_test.golden, internal/providers/terraform/aws/testdata/config_configuration_recorder_test/config_configuration_recorder_test.tf, internal/providers/terraform/aws/testdata/eks_cluster_test/eks_cluster_test.golden, internal/providers/terraform/aws/testdata/eks_cluster_test/eks_cluster_test.tf, internal/providers/terraform/aws/testdata/mwaa_environment_test/mwaa_environment_test.golden, internal/providers/terraform/aws/testdata/mwaa_environment_test/mwaa_environment_test.tf, internal/providers/terraform/aws/testdata/wafv2_web_acl_test/wafv2_web_acl_test.golden, internal/providers/terraform/aws/testdata/wafv2_web_acl_test/wafv2_web_acl_test.tf
https://github.com/infracost/infracost/pull/1028#discussion_r746980579
Just a proof of concept for a few resource types
There are still more resource dependencies throughout `testdata` that could be hardcoded as well if this idea seems good
=> refactor: hardcode resource dependencies in testdata

CONTRIBUTING.md
Related to https://github.com/infracost/docs/pull/117
=> docs: update supported resources link in contributing guide

cmd/infracost/configure.go, cmd/infracost/testdata/configure_help_flag/configure_help_flag.golden, cmd/infracost/testdata/configure_no_args/configure_no_args.golden, internal/apiclient/client.go, internal/apiclient/pricing.go, internal/config/config.go, internal/config/configuration.go
Docs: https://github.com/infracost/docs/pull/130
=> Add configure options for tls_ca_cert_file and tls_insecure_skip_verify

internal/providers/terraform/azure/testdata/storage_account_test/storage_account_test.golden
The Cloud Pricing API update brought new changes for the StorageV2 pricing.
=> fix(azure): update golden file output for Azure Storage Account

cmd/infracost/main.go, cmd/infracost/run.go, internal/providers/detect.go, internal/providers/terraform/dir_provider.go, internal/providers/terraform/plan_provider.go, internal/providers/terraform/terragrunt_provider.go
This removes three possible race conditions, including the one in https://github.com/infracost/infracost/issues/1202.
There's still possible race conditions with the logging, but I've been looking at how we can change the logging and spinners anyway which will remove these, and the logging race conditions shouldn't cause any issues at the moment anyway.
=> Fix race conditions

.github/workflows/check-resources.yml, cmd/resourcecheck/main.go
Adds resourcecheck cmd to test regions are implemented, sends slack notification if we are missing a newly added resource:
Runs on a daily schedule
=> feat: add resourcecheck cmd

cmd/infracost/output.go
In case when the output command receives only one file and it already
has its share URL, sending its data to Dashboard would create a
redundant duplicate.
=> chore: optimize run's share URL generation for output command

internal/providers/terraform/dir_provider.go
=> fix: Make sure terraform/grunt version is prefixed with v

internal/apiclient/client.go, internal/providers/terraform/aws/testdata/vpn_connection_test/vpn_connection_test.tf
This fixes a regression introduced in v0.9.15
=> Fix: obey the http(s)_proxy set in the environment

internal/providers/terraform/aws/registry.go, internal/providers/terraform/aws/route53_record.go, internal/providers/terraform/aws/route53_resolver_endpoint.go, internal/providers/terraform/aws/vpc_endpoint.go, internal/resources/aws/route53_record.go, internal/resources/aws/route53_resolver_endpoint.go, internal/resources/aws/vpc_endpoint.go
As part of https://github.com/infracost/infracost/issues/1288
=> Migrate AWS resources (aws_vpc_endpoint, aws_route53_resolver_endpoint, aws_route53_record)

cmd/infracost/breakdown_test.go, cmd/infracost/cmd_test.go, cmd/infracost/run.go, cmd/infracost/testdata/breakdown_invalid_path/breakdown_invalid_path.golden, cmd/infracost/testdata/breakdown_plan_error/breakdown_plan_error.golden, cmd/infracost/testdata/breakdown_terraform_sync_usage_file/infracost-usage.yml, internal/providers/detect.go, internal/providers/terraform/cloud.go, internal/providers/terraform/dir_provider.go, internal/providers/terraform/terragrunt_provider.go
* Add https://infracost.io/troubleshoot link, and make this the last line of the error.
* Fix terragrunt commands showing `terraform plan failed`, instead show `terragrunt run-all plan failed`
=> Update error messages to link to troubleshooting page

.github/workflows/create-release.yml, Makefile
Fixes https://github.com/infracost/infracost/issues/1317
=> Add Linux ARM 64 releases

internal/providers/terraform/azure/testdata/storage_account_test/storage_account_test.golden
Pricing has updated. Couldn't find any announcement, but the pricing
pages show new prices.
=> fix(azure): Update tests for Azure Storage Account resource

internal/providers/terraform/azure/event_hubs_namespace.go, internal/providers/terraform/azure/testdata/event_hubs_namespace_test/event_hubs_namespace_test.golden, internal/providers/terraform/azure/testdata/event_hubs_namespace_test/event_hubs_namespace_test.tf, internal/providers/terraform/azure/testdata/event_hubs_namespace_test/event_hubs_namespace_test.usage.yml
=> feat: Add support for Premium Azure Event Hubs

.github/workflows/create-release.yml, Makefile
=> feat: add zip archives to release

cmd/infracost/run.go, cmd/infracost/run_test.go
sums project specific reporting metrics into singular value
=> fix: add run time values into singular attribute

Dockerfile
- Bump the alpine base image to the latest stable, 3.15
=> chore: update alpine image

internal/apiclient/errors.go, internal/providers/terraform/dir_provider.go, internal/providers/terraform/terragrunt_provider.go
* Sanitize all Terraform/Terragrunt errors
* Strip paths/URLs from errors
=> Sanitize errors

cmd/infracost/fig_autocomplete.go, cmd/infracost/main.go, cmd/infracost/testdata/help/help.golden, cmd/infracost/testdata/help_flag/help_flag.golden, cmd/infracost/testdata/no_args/no_args.golden, go.mod, go.sum
This does not completely close (#1118), but I am almost done with creating a GH action that will allow to automatically push new versions of the spec to the autocomplete repo and I will open another PR soon!
=> feat: add `fig-autocomplete` subcommand

scripts/ci/README.md, scripts/ci/atlantis_diff.sh, scripts/ci/comment.sh, scripts/ci/diff.sh, scripts/ci/jenkins_diff.sh
* adds deprecation overview to ci README
* adds warning comment in scripts
* adds warning log to scripts
=> fix: add deprecation warning to ci bash scripts

.github/workflows/code-scanning.yml, README.md
Adds codeql workflow which is run on pr, master and on a cron schedule (weekly)
=> feat: add codeql vulnerability scanning

cmd/infracost/hcl_test.go, cmd/infracost/testdata/hclprovider_alias/hclprovider_alias.golden, cmd/infracost/testdata/hclprovider_alias/main.tf, internal/providers/terraform/hcl_provider.go
Closes: #1524
Fixes issues in HCL where provider aliases were not being resolved as they were being parsed (correctly) as references in HCL
=> fix: provider alias references

internal/providers/terraform/aws/ecs_cluster.go, internal/providers/terraform/aws/ecs_cluster_capacity_providers.go, internal/providers/terraform/aws/ecs_service.go, internal/providers/terraform/aws/registry.go, internal/providers/terraform/aws/testdata/ecs_service_test/ecs_service_test.golden, internal/providers/terraform/aws/testdata/ecs_service_test/ecs_service_test.tf
=> fix: Detect ECS Fargate launch type from capacity providers

infracost-usage-example.yml, internal/prices/prices.go, internal/providers/terraform/aws/sns_topic_test.go, internal/providers/terraform/aws/testdata/sns_topic_test/sns_topic_test.golden, internal/providers/terraform/aws/testdata/sns_topic_test/sns_topic_test.tf, internal/providers/terraform/aws/testdata/sns_topic_test/sns_topic_test.usage.yml, internal/resources/aws/sns_topic.go, internal/schema/cost_component.go
=> feat: Add support for SNS Topic notification costs

.github/workflows/create-release.yml
=> ci(fig): update autocomplete spec automatically

internal/comment/azure_repos.go, internal/comment/bitbucket.go, internal/comment/github.go, internal/comment/gitlab.go
Fixes https://github.com/infracost/actions/issues/60
=> fix: Match on the whole markdown tag when finding existing comments

cmd/infracost/diff.go, cmd/infracost/diff_test.go, cmd/infracost/output.go, cmd/infracost/run.go, cmd/infracost/testdata/breakdown_help/breakdown_help.golden, cmd/infracost/testdata/diff_help/diff_help.golden, cmd/infracost/testdata/diff_with_config_file_compare_to_deleted_project/diff_with_config_file_compare_to_deleted_project.golden, cmd/infracost/testdata/diff_with_config_file_compare_to_deleted_project/prior.json, cmd/infracost/testdata/diff_with_config_file_compare_to_deleted_project/prod/main.tf, cmd/infracost/testdata/flag_errors_config_file_and_terraform_workspace/flag_errors_config_file_and_terraform_workspace.golden, cmd/infracost/testdata/flag_errors_no_path/flag_errors_no_path.golden, cmd/infracost/testdata/flag_errors_path_and_config_file/flag_errors_path_and_config_file.golden, cmd/infracost/testdata/output_help/output_help.golden, internal/output/combined.go, internal/output/output.go, internal/schema/project.go
several minor fixes and tweaks to `--compare-to` flag:
* fixes panic error
* protects `--compare-to` flag with invalid output formats
* if project exists in prior state but not in current, show 100% deletion
* tweak help text
=> fix: compare-to tweaks

internal/providers/terraform/azure/public_ip.go
fixes azure public ip cost component which reflects the pricing page: https://azure.microsoft.com/en-us/pricing/details/ip-addresses/
=> fix(azure): fix public ip standard pricing

internal/providers/terraform/google/testdata/redis_instance_test/redis_instance_test.golden, internal/resources/google/redis_instance.go
=> fix(google): Fix Redis instance monthly pricing

internal/providers/terraform/azure/linux_virtual_machine.go, internal/providers/terraform/azure/testdata/linux_virtual_machine_test/linux_virtual_machine_test.golden, internal/providers/terraform/azure/testdata/linux_virtual_machine_test/linux_virtual_machine_test.tf
=> fix: Ignore price for B1s - Free azure instance

internal/providers/terraform/google/compute_forwarding_rule.go, internal/providers/terraform/google/registry.go, internal/providers/terraform/google/sql_database_instance.go, internal/resources/google/sql_database_instance.go
Migrate sql_database_instance alongside few case fix in registry file.
=> refactor(google): resource migrations batch 11

internal/providers/terraform/google/compute_region_instance_group_manager.go, internal/providers/terraform/google/compute_region_per_instance_config.go, internal/providers/terraform/google/compute_region_per_instance_config_test.go, internal/providers/terraform/google/registry.go, internal/providers/terraform/google/testdata/compute_region_per_instance_config_test/compute_region_per_instance_config_test.golden, internal/providers/terraform/google/testdata/compute_region_per_instance_config_test/compute_region_per_instance_config_test.tf
Closes #1656.
Exact same logic as in #1645.
=> feat(google): add support for google_compute_region_per_instance_config

internal/hcl/remote_variables_loader.go
=> chore: fallback to the workspace defined by TF env for remote var loading

internal/hcl/evaluator.go
Fixes https://github.com/infracost/infracost/issues/1730
=> fix: match modules based on key which should always be unique

internal/providers/terraform/terragrunt_hcl_provider.go
When `dependency` blocks and added to a terragrunt file through an `include` block. The `dependency` blocks found in the included child file should be added to the parent. This PR fixes an issue where the child included blocks were overwriting the parent as they were using a different filename. This only happened sporadically as the returned list of dependencies was a map, meaning only every so often the child `dependency` would appear after the parent `dependency` with the same name. The fix is to check that a `dependency` with the same name hasn't already been declared when parsing includes.
=> fix: included dependency blocks with same name overwriting the parent

cmd/infracost/comment.go, cmd/infracost/configure.go, cmd/infracost/diff.go, cmd/infracost/main.go, cmd/infracost/output.go, cmd/infracost/run.go, internal/apiclient/dashboard.go, internal/config/config.go, internal/config/configuration.go, internal/providers/cloudformation/template_provider.go, internal/providers/terraform/dir_provider.go, internal/providers/terraform/hcl_provider.go, internal/providers/terraform/plan_json_provider.go, internal/providers/terraform/plan_provider.go, internal/providers/terraform/state_json_provider.go, internal/providers/terraform/terragrunt_hcl_provider.go, internal/providers/terraform/terragrunt_provider.go
Adds configuration through `INFRACOST_ENABLE_CLOUD` and `enable_cloud` config option.
=> chore: add enable cloud var

internal/providers/terraform/azure/mssql_database.go, internal/providers/terraform/azure/testdata/mssql_database_test/mssql_database_test.golden, internal/providers/terraform/azure/testdata/mssql_database_test/mssql_database_test.tf
fixes panic when `sku_name` is not set
=> fix: fallback to default sku if not set

cmd/infracost/breakdown_test.go, cmd/infracost/testdata/breakdown_terraform_directory_with_default_var_files/hcl.tfvars, cmd/infracost/testdata/breakdown_terraform_directory_with_default_var_files/hcl.tfvars.json, internal/hcl/parser.go
closes https://github.com/infracost/infracost/issues/1773
=> fix: support input JSON input variable files

internal/providers/terraform/azure/cosmosdb_cassandra_keyspace.go, internal/providers/terraform/azure/cosmosdb_cassandra_keyspace_test.go, internal/providers/terraform/azure/testdata/cosmosdb_cassandra_keyspace_test_with_blank_geo_location/cosmosdb_cassandra_keyspace_test_with_blank_geo_location.golden, internal/providers/terraform/azure/testdata/cosmosdb_cassandra_keyspace_test_with_blank_geo_location/cosmosdb_cassandra_keyspace_test_with_blank_geo_location.tf, internal/providers/terraform/azure/testdata/cosmosdb_cassandra_keyspace_test_with_blank_geo_location/cosmosdb_cassandra_keyspace_test_with_blank_geo_location.usage.yml
closes https://github.com/infracost/infracost/issues/1835
=> fix: blank geo_locations causing panic errors

infracost-usage-example.yml, internal/providers/terraform/azure/iothub.go, internal/providers/terraform/azure/iothub_test.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/testdata/iothub_test/iothub_test.golden, internal/providers/terraform/azure/testdata/iothub_test/iothub_test.tf, internal/providers/terraform/azure/testdata/iothub_test/iothub_test.usage.yml, internal/resources/azure/iothub.go
Add support for Azure IoT Hub resources. Fixes #1616.
https://azure.microsoft.com/en-us/services/iot-hub/
https://azure.microsoft.com/en-us/pricing/details/iot-hub/
None
=> feat(Azure): Add IoT Hub resources

cmd/infracost/auth.go, cmd/infracost/register.go, cmd/infracost/testdata/completion_shell_bash/completion_shell_bash.golden, cmd/infracost/testdata/help/help.golden, cmd/infracost/testdata/help_flag/help_flag.golden, cmd/infracost/testdata/no_args/no_args.golden, cmd/infracost/testdata/register_help_flag/register_help_flag.golden
* hides register command
* adds warning string when register is called and delegates to login command
* adds warning string for register help and shows login command help
* unhides auth command
=> refactor: change register command to point to auth login

internal/config/project_context.go, internal/vcs/metadata.go, internal/vcs/metadata_test.go
Adds further VCS metadata for:
* Azure DevOps
* Bitbucket
* Atlantis
* Circle CI
=> feat: add metadata support for additional VCS systems

internal/hcl/evaluator.go
fixes: https://github.com/infracost/infracost/issues/1946
Resolves issue where calling `AsValueMap` for a non-valid type will panic. We now skip the `AsValueMap` call and send a debug write:
```
DEBU[0000] skipping unexpected value value type: 'cty.ListVal([]cty.Value{cty.StringVal("test")})' for existing for_each context value  block="test.test[\"two\"]" module_name=root ...
```
This unexpected value case should, in reality, never happen, as we always expect the existing values to be a valid `ObjectType`. So there's probably a hidden bug somewhere here. However, I could not replicate it with any HCL test cases. These log lines should give us valid context for the future so that we could solve any pricing bugs that arise from this case.
=> fix: catch evaluator panic if value map is not a `cty.ObjectType`

internal/providers/terraform/azure/function_app.go, internal/providers/terraform/azure/util.go, internal/resources/azure/mysql_flexible_server.go
Following changes to the Azure Price List API
=> Fix `azurerm_function_app` and  `azurerm_mysql_flexible_server`

internal/apiclient/dashboard.go, internal/providers/terraform/aws/data_transfer_test.go
Separated these changes from #2016 as unrelated. Also, it will fix the CI faster.
=> chore: Fix tests

cmd/infracost/testdata/breakdown_terraform_sync_usage_file/infracost-usage.yml, cmd/infracost/testdata/breakdown_terraform_sync_usage_file/infracost-usage.yml.golden, go.mod, go.sum, infracost-usage-example.yml, internal/providers/terraform/parser.go, internal/schema/usage_data.go, internal/usage/reference_file.go, internal/usage/sync.go, internal/usage/testdata/usage_file/usage_file.golden, internal/usage/testdata/usage_file/usage_file_existing_usage.yml, internal/usage/testdata/usage_file_empty/usage_file_empty.golden, internal/usage/testdata/usage_file_no_usage/usage_file_no_usage.golden, internal/usage/usage_file.go
=> feat: resource type usage data

internal/config/run_context.go
adds support to override the ci platform through INFRACOST_CI_PLATFORM env var.
=> refactor: CI_PLATFORM env var to allow override for the ci platform

internal/output/format_test.go
@hugorut  I haven't been able to reproduce the FAIL but I'm guessing this will help.
=> test: fix intermittent currency format failure

internal/providers/terraform/aws/testdata/fsx_windows_file_system_test/fsx_windows_file_system_test.golden, internal/providers/terraform/aws/testdata/fsx_windows_file_system_test/fsx_windows_file_system_test.tf, internal/providers/terraform/aws/testdata/fsx_windows_file_system_test/fsx_windows_file_system_test.usage.yml, internal/resources/aws/fsx_windows_file_system.go
=> fix(aws/fsx-windows): no prices for SSD

internal/providers/terraform/aws/fsx_openzfs_file_system.go, internal/providers/terraform/aws/fsx_openzfs_file_system_test.go, internal/providers/terraform/aws/registry.go, internal/providers/terraform/aws/testdata/fsx_openzfs_file_system_test/fsx_openzfs_file_system_test.golden, internal/providers/terraform/aws/testdata/fsx_openzfs_file_system_test/fsx_openzfs_file_system_test.tf, internal/providers/terraform/aws/testdata/fsx_openzfs_file_system_test/fsx_openzfs_file_system_test.usage.yml, internal/resources/aws/fsx_openzfs_file_system.go
This PR will add the support for the Terraform resource `aws_fsx_openzfs_file_system`.
=> feat: new resource aws_fsx_openzfs_file_system

internal/providers/terraform/azure/registry.go
Added Entry for free service  "azurerm_attestation_provider"
**Terraform Resource** : https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/attestation
**Pricing Details:** https://azure.microsoft.com/en-in/pricing/details/azure-attestation/#pricing
=> feat(azure): added resource azurerm_attestation_provider

internal/resources/aws/config_config_rule.go, internal/resources/azure/mysql_flexible_server.go, internal/resources/google/storage_bucket.go
See comment messages for detailed descriptions:
1. AWS - new SKUs were matched by the price filter.
2. Google - new SKUs with new pricing. Fix makes the cost component to use the current pricing, but we'll need to update it closer to Apr 1st. Here's the issue to track the progress: #2242.
3. Azure - attribute changed the name.
=> fix: Fix tests for cloud resources

internal/scan/terraform.go
Resolves issue where policies that set attributes on CoreResources was affecting the Infracost output. This was because the underlying CoreResource was a pointer. So setting struct fields would alter the resource when before fetching the prices.
=> fix: copy CoreResource before costing policy

cmd/infracost/run.go, cmd/infracost/testdata/breakdown_invalid_path/breakdown_invalid_path.golden
=> enhance: Update instructions for project validation errors

internal/hcl/evaluator.go, internal/providers/terraform/testdata/hcl_provider_test/populates_warnings_on_missing_vars/main.tf
* adds more ignored variables to list
* changes pattern to match both `_` and `-` separated vars
* ignores case of variable
=> chore: add more ignored variables to evaluator

internal/providers/terraform/azure/registry.go
Related docs PR: https://github.com/infracost/docs/pull/394
=> enhance(azure): add additional free Azure resources

cmd/infracost/generate.go, cmd/infracost/generate_test.go, cmd/infracost/main.go, cmd/infracost/testdata/completion_shell_bash/completion_shell_bash.golden, cmd/infracost/testdata/generate_config/generate_config.golden, cmd/infracost/testdata/generate_config/infracost.yml.tmpl, cmd/infracost/testdata/help/help.golden, cmd/infracost/testdata/help_flag/help_flag.golden, cmd/infracost/testdata/no_args/no_args.golden, go.mod, go.sum, internal/config/template/parser.go, internal/config/template/parser_test.go, internal/config/template/testdata/different_env_dirs/infracost.golden.yml, internal/config/template/testdata/different_env_dirs/infracost.yml.tmpl, internal/config/template/testdata/different_env_files/infracost.golden.yml, internal/config/template/testdata/different_env_files/infracost.yml.tmpl, internal/config/template/testdata/include_directory_based_on_file/infracost.golden.yml, internal/config/template/testdata/include_directory_based_on_file/infracost.yml.tmpl, internal/config/template/testdata/with_string_manipulation_functions/infracost.golden.yml, internal/config/template/testdata/with_string_manipulation_functions/infracost.yml.tmpl, internal/config/template/testdata/with_string_matching_functions/infracost.golden.yml, internal/config/template/testdata/with_string_matching_functions/infracost.yml.tmpl
Adds support for Infracost template files using go text/templates.
=> feat: Infracost template file support

cmd/infracost/breakdown_test.go, cmd/infracost/testdata/breakdown_with_local_path_data_block/breakdown_with_local_path_data_block.golden, cmd/infracost/testdata/breakdown_with_local_path_data_block/config/config.json, cmd/infracost/testdata/breakdown_with_local_path_data_block/dev/main.tf, internal/hcl/block.go, internal/hcl/evaluator.go, internal/hcl/parser.go
Adds limited support for `local_file` data blocks, setting a `content` attribute which can be used downstream.
=> feat: support local_file data blocks

infracost-usage-example.yml, internal/providers/terraform/azure/backup_protected_vm.go, internal/providers/terraform/azure/recovery_services_vault.go, internal/providers/terraform/azure/recovery_services_vault_test.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/testdata/recovery_services_vault_test/recovery_services_vault_test.golden, internal/providers/terraform/azure/testdata/recovery_services_vault_test/recovery_services_vault_test.tf, internal/providers/terraform/azure/testdata/recovery_services_vault_test/recovery_services_vault_test.usage.yml, internal/resources/azure/backup_protected_vm.go, internal/resources/azure/recovery_services_vault.go
Fixes: https://github.com/infracost/infracost/issues/1395
This as been a pain and I've rewritten this more times than I can count as there were lots of avenues I went down that didn't work or were actually incorrect. The end result is pretty simplistic, but other routes I tried, turned out to be wildly different from pricing page or just didn't encapsulate the right things.
I'm at the point where this lines up with everything and it covers the resource, however I need a fresh pair of eyes on it as I'm unsure what to add/keep, and want to draw a line in the sand as i've spent way too much time on this.
---
The multiple prices log lines are expected, there are multiple prices in the DB for some reason, sku is different but attributes and prices are the same.
=> feat: support for recovery_services_vault and backup_protected_vm

internal/providers/terraform/azure/logic_app_integration_account.go, internal/providers/terraform/azure/logic_app_integration_account_test.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/testdata/logic_app_integration_account_test/logic_app_integration_account_test.golden, internal/providers/terraform/azure/testdata/logic_app_integration_account_test/logic_app_integration_account_test.tf, internal/providers/terraform/azure/testdata/logic_app_integration_account_test/logic_app_integration_account_test.usage.yml, internal/resources/azure/logic_app_integration_account.go, internal/schema/cost_component.go, internal/schema/resource.go
This is a simple resource with a single cost component but required adding `MonthToHourUnitMultiplier` and `UnitRounding` to display the monthly prices as hourly.
=> feat: support for azurerm_logic_app_integration_account

internal/providers/terraform/azure/kubernetes_cluster.go, internal/providers/terraform/azure/testdata/cdn_endpoint_test/cdn_endpoint_test.tf, internal/providers/terraform/azure/testdata/kubernetes_cluster_test/kubernetes_cluster_test.tf, internal/providers/terraform/azure/testdata/sql_managed_instance_test/sql_managed_instance_test.golden, internal/resources/azure/sql_managed_instance.go, internal/resources/azure/storage_account.go
For Standard GRS and LRS lookup either Other or Read operations because they seem to switch up in the API.
=> enhance(azure): fix read operation lookups for Azure storage accounts

infracost-usage-example.yml
Missed this as part of https://github.com/infracost/infracost/pull/2425
=> enhance(azure): add usage example for Azure Network Monitor

infracost-usage-example.yml, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/servicebus_namespace.go, internal/providers/terraform/azure/servicebus_namespace_test.go, internal/providers/terraform/azure/testdata/servicebus_namespace_test/servicebus_namespace_test.golden, internal/providers/terraform/azure/testdata/servicebus_namespace_test/servicebus_namespace_test.tf, internal/providers/terraform/azure/testdata/servicebus_namespace_test/servicebus_namespace_test.usage.yml, internal/resources/azure/servicebus_namespace.go
Fixes https://github.com/infracost/infracost/issues/1432
=> feat(azure): Add support for `azure_servicebus_namespace`

infracost-usage-example.yml, internal/providers/terraform/azure/image.go, internal/providers/terraform/azure/image_test.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/snapshot.go, internal/providers/terraform/azure/snapshot_test.go, internal/providers/terraform/azure/testdata/image_test/image_test.golden, internal/providers/terraform/azure/testdata/image_test/image_test.tf, internal/providers/terraform/azure/testdata/image_test/image_test.usage.yml, internal/providers/terraform/azure/testdata/snapshot_test/snapshot_test.golden, internal/providers/terraform/azure/testdata/snapshot_test/snapshot_test.tf, internal/providers/terraform/azure/testdata/snapshot_test/snapshot_test.usage.yml, internal/resources/azure/image.go
adds support for azure images and snapshots which provide a way to backup/create new VMs/disks.
=> feat: azurerm_image, azurerm_snapshot

cmd/infracost/testdata/output_format_git_hub_comment_with_all_error/output_format_git_hub_comment_with_all_error.golden, cmd/infracost/testdata/output_format_git_hub_comment_with_project_errors/output_format_git_hub_comment_with_project_errors.golden, internal/output/diff.go, internal/output/table.go
Show errored project in the diff output just as they are shown in the breakdown.
=> fix: show errored projects in diff view

cmd/infracost/generate.go, internal/config/template/parser.go, internal/config/template/parser_test.go, internal/config/template/testdata/with_top_level_template_data/infracost.golden.yml, internal/config/template/testdata/with_top_level_template_data/infracost.yml.tmpl, internal/resources/azure/servicebus_namespace.go
=> Revert "Revert "feat: default variables for infracost config template files""

cmd/infracost/testdata/comment_azure_repos_pull_request/comment_azure_repos_pull_request.golden, cmd/infracost/testdata/comment_git_hub_commit/comment_git_hub_commit.golden, cmd/infracost/testdata/comment_git_hub_guardrail_success_with_comment/comment_git_hub_guardrail_success_with_comment.golden, cmd/infracost/testdata/comment_git_hub_pull_request/comment_git_hub_pull_request.golden, cmd/infracost/testdata/comment_git_hub_show_all_projects/comment_git_hub_show_all_projects.golden, cmd/infracost/testdata/comment_git_hub_show_changed_projects/comment_git_hub_show_changed_projects.golden, cmd/infracost/testdata/comment_git_hub_with_guardrail_check_path/comment_git_hub_with_guardrail_check_path.golden, cmd/infracost/testdata/comment_git_lab_commit/comment_git_lab_commit.golden, cmd/infracost/testdata/comment_git_lab_merge_request/comment_git_lab_merge_request.golden, cmd/infracost/testdata/output_format_azure_repos_comment/output_format_azure_repos_comment.golden, cmd/infracost/testdata/output_format_azure_repos_comment_multiple_skipped/output_format_azure_repos_comment_multiple_skipped.golden, cmd/infracost/testdata/output_format_azure_repos_comment_no_change/output_format_azure_repos_comment_no_change.golden, cmd/infracost/testdata/output_format_bitbucket_comment_with_project_names/output_format_bitbucket_comment_with_project_names.golden, cmd/infracost/testdata/output_format_git_hub_comment/output_format_git_hub_comment.golden, cmd/infracost/testdata/output_format_git_hub_comment_multiple_skipped/output_format_git_hub_comment_multiple_skipped.golden, cmd/infracost/testdata/output_format_git_hub_comment_no_change/output_format_git_hub_comment_no_change.golden, cmd/infracost/testdata/output_format_git_hub_comment_no_project/output_format_git_hub_comment_no_project.golden, cmd/infracost/testdata/output_format_git_hub_comment_show_all_projects/output_format_git_hub_comment_show_all_projects.golden, cmd/infracost/testdata/output_format_git_hub_comment_with_all_error/output_format_git_hub_comment_with_all_error.golden, cmd/infracost/testdata/output_format_git_hub_comment_with_project_errors/output_format_git_hub_comment_with_project_errors.golden, cmd/infracost/testdata/output_format_git_hub_comment_with_project_names/output_format_git_hub_comment_with_project_names.golden, cmd/infracost/testdata/output_format_git_hub_comment_with_project_names_with_metadata/output_format_git_hub_comment_with_project_names_with_metadata.golden, cmd/infracost/testdata/output_format_git_hub_comment_without_module_path/output_format_git_hub_comment_without_module_path.golden, cmd/infracost/testdata/output_format_git_lab_comment/output_format_git_lab_comment.golden, cmd/infracost/testdata/output_format_git_lab_comment_multiple_skipped/output_format_git_lab_comment_multiple_skipped.golden, cmd/infracost/testdata/output_format_git_lab_comment_no_change/output_format_git_lab_comment_no_change.golden, internal/output/markdown.go, internal/output/templates/markdown-html.tmpl, internal/output/templates/markdown.tmpl
* adds p tags for correct spacing
* removes unecesary project counts section
Get the peas
=> fix: add paragraph line spacing to comment

cmd/infracost/breakdown_test.go, cmd/infracost/testdata/breakdown_terragrunt_source_map/breakdown_terragrunt_source_map.golden, cmd/infracost/testdata/breakdown_terragrunt_source_map/terragrunt.hcl, internal/config/config.go, internal/config/terraform_source_map.go, internal/hcl/modules/loader.go, internal/hcl/modules/loader_test.go, internal/hcl/modules/testdata/modules_with_source_map/main.tf, internal/hcl/parser_test.go, internal/providers/terraform/hcl_provider.go, internal/providers/terraform/hcl_provider_test.go, internal/providers/terraform/terragrunt_hcl_provider.go
Docs: https://github.com/infracost/docs/pull/492
=> feat: add `INFRACOST_TERRAFORM_SOURCE_MAP` environment variable

Makefile, cmd/infracost/testdata/breakdown_with_default_tags/breakdown_with_default_tags.golden, cmd/infracost/testdata/breakdown_with_default_tags/main.tf, internal/providers/terraform/aws/aws.go, internal/providers/terraform/provider_schemas/aws.tag_block.json, internal/providers/terraform/provider_schemas/tag_support.go
(mostly for aws autoscale groups)
=> enhance: add support for tag blocks

cmd/infracost/testdata/breakdown_auto_with_multi_varfile_projects/breakdown_auto_with_multi_varfile_projects.golden, internal/providers/terraform/hcl_provider.go, internal/resources/google/sql_database_instance.go
This also includes a fix for Google SQL.
=> fix: ensure auto-detected projects are always sorted consistently

cmd/infracost/main.go, go.mod, go.sum
Adds option to configure profiling through OS variables.
=> chore: add memory and cpu profiling options

internal/providers/terraform/aws/aws.go
This change modifies the parser to add volume tags to the resource tags with `volume_tags` prefix if found.
=> feat: add volume tags to the resource if present

cmd/infracost/testdata/breakdown_format_json_with_tags/breakdown_format_json_with_tags.golden, cmd/infracost/testdata/breakdown_format_json_with_tags/main.tf, internal/providers/terraform/aws/aws.go, internal/providers/terraform/aws/tags.go, internal/providers/terraform/azure/azure.go, internal/providers/terraform/google/google.go, internal/providers/terraform/parser.go
Propagates tag_specifications to aws_instance and aws_autoscaling_group from launch_templates.
=> feat: add support for launch_template tags

cmd/infracost/breakdown_test.go, cmd/infracost/testdata/breakdown_terragrunt_get_env_config_file/breakdown_terragrunt_get_env_config_file.golden, cmd/infracost/testdata/breakdown_terragrunt_get_env_config_file/infracost.yml, cmd/infracost/testdata/breakdown_terragrunt_get_env_config_file/main.tf, cmd/infracost/testdata/breakdown_terragrunt_get_env_config_file/terragrunt.hcl, internal/providers/terraform/terragrunt_hcl_provider.go
Fixes https://github.com/infracost/infracost/issues/2579.
=> fix: ensure we support env vars specified in config files for Terragrunt projects

cmd/infracost/comment_test.go, cmd/infracost/testdata/comment_backoff_retry/comment_backoff_retry.golden, cmd/infracost/testdata/comment_backoff_retry/infracost.json, internal/comment/handler.go
Retries comment logic if the handler receives an unexpected error.
=> refactor: add backoff retry logic to comment handler

internal/hcl/evaluator.go, internal/hcl/parser_test.go
=> fix: correctly label data blocks during for_each expansion

cmd/infracost/breakdown_test.go, cmd/infracost/cmd_test.go, cmd/infracost/diff_test.go, cmd/infracost/testdata/breakdown_with_policy_data_upload_hcl/breakdown_with_policy_data_upload_hcl.golden, cmd/infracost/testdata/breakdown_with_policy_data_upload_hcl/main.tf, cmd/infracost/testdata/breakdown_with_policy_data_upload_plan_json/breakdown_with_policy_data_upload_plan_json.golden, cmd/infracost/testdata/breakdown_with_policy_data_upload_plan_json/main.tf, cmd/infracost/testdata/breakdown_with_policy_data_upload_plan_json/plan.json, cmd/infracost/testdata/breakdown_with_policy_data_upload_plan_json/regenerate_plan_json.sh, cmd/infracost/testdata/diff_with_policy_data_upload/baseline.json, cmd/infracost/testdata/diff_with_policy_data_upload/diff_with_policy_data_upload.golden, cmd/infracost/testdata/diff_with_policy_data_upload/main.tf, internal/apiclient/client.go, internal/apiclient/dashboard.go, internal/apiclient/policy.go, internal/apiclient/policyv2.go, internal/apiclient/pricing_test.go, internal/apiclient/tag_policy.go, internal/apiclient/usage.go, internal/config/config.go, internal/output/combined.go, internal/output/output.go, internal/providers/terraform/hcl_provider.go, internal/providers/terraform/plan_json_provider.go, internal/scan/terraform.go, internal/schema/policy.go, internal/schema/project.go, schema/infracost.schema.json
Adds the policy v2 client to prepare for additional policy scanning.
=> feat: Add policy v2

internal/apiclient/client.go, internal/apiclient/policy.go
Changes headers sent to Infracost managed services if new `ics` token is set.
=> feat: support infracost service tokens

internal/providers/terraform/aws/testdata/kinesis_stream_test/kinesis_stream_test.golden, internal/providers/terraform/aws/testdata/kinesis_stream_test/kinesis_stream_test.tf, internal/providers/terraform/aws/testdata/kinesis_stream_test/kinesis_stream_test.usage.yml, internal/resources/aws/kinesis_stream.go
=> fix: Fix AWS kinises price lookup for non us-east-1 regions

cmd/infracost/generate.go, cmd/infracost/generate_test.go, cmd/infracost/testdata/generate_config_auto_detect/apps/bar/main.tf, cmd/infracost/testdata/generate_config_auto_detect/apps/foo/main.tf, cmd/infracost/testdata/generate_config_auto_detect/generate_config_auto_detect.golden, internal/hcl/parser.go
`infracost generate config` now supports creating a config file from the native "auto-detect" functionality. If no `template-path` or `template` is provided, generate will output the auto-detected projects.
=> feat: add autodetect output option to `generate config`

internal/providers/terraform/google/testdata/compute_address_test/compute_address_test.golden, internal/providers/terraform/google/testdata/compute_address_test/compute_address_test.tf, internal/resources/google/compute_address.go
=> fix: Fix price lookup for google_compute_address in different regions

cmd/infracost/generate.go, cmd/infracost/generate_test.go, cmd/infracost/testdata/generate_config_auto_detect/generate_config_auto_detect.golden, cmd/infracost/testdata/generate_config_detected_projects/dev/main.tf, cmd/infracost/testdata/generate_config_detected_projects/dev/terraform.tfvars, cmd/infracost/testdata/generate_config_detected_projects/generate_config_detected_projects.golden, cmd/infracost/testdata/generate_config_detected_projects/infracost.yml.tmpl, cmd/infracost/testdata/generate_config_detected_projects/prod/main.tf, cmd/infracost/testdata/generate_config_detected_projects/prod/terraform.tfvars, internal/config/template/parser.go, internal/hcl/parser.go, internal/hcl/project_locator.go, internal/hcl/project_locator_test.go
Reverts infracost/infracost#2786
=> Revert "Revert "Add discovered projects""

cmd/infracost/testdata/breakdown_format_json_with_tags/breakdown_format_json_with_tags.golden, infracost-usage-example.yml, internal/providers/terraform/aws/neptune_cluster_instance.go, internal/providers/terraform/aws/testdata/lb_test/lb_test.tf, internal/providers/terraform/aws/testdata/neptune_cluster_instance_test/neptune_cluster_instance_test.golden, internal/providers/terraform/aws/testdata/neptune_cluster_instance_test/neptune_cluster_instance_test.tf, internal/providers/terraform/azure/managed_disk.go, internal/providers/terraform/azure/testdata/api_management_test/api_management_test.golden, internal/providers/terraform/azure/testdata/mssql_database_test/mssql_database_test.golden, internal/providers/terraform/azure/testdata/security_center_subscription_pricing_test/security_center_subscription_pricing_test.golden, internal/providers/terraform/azure/testdata/security_center_subscription_pricing_test/security_center_subscription_pricing_test.usage.yml, internal/providers/terraform/azure/testdata/sql_database_test/sql_database_test.golden, internal/providers/terraform/google/network_engress_internal.go, internal/providers/terraform/google/testdata/compute_instance_test/compute_instance_test.golden, internal/providers/terraform/google/testdata/container_cluster_test/container_cluster_test.golden, internal/providers/terraform/google/testdata/container_node_pool_test/container_node_pool_test.golden, internal/resources/aws/config_configuration_recorder.go, internal/resources/aws/docdb_cluster_instance.go, internal/resources/aws/instance.go, internal/resources/aws/lb.go, internal/resources/aws/neptune_cluster.go, internal/resources/aws/neptune_cluster_instance.go, internal/resources/aws/route53_resolver_endpoint.go, internal/resources/azure/image.go, internal/resources/azure/logic_app_standard.go, internal/resources/azure/security_center_subscription_pricing.go, internal/resources/azure/sql_database.go, internal/resources/google/cloudfunctions_function.go, internal/resources/google/network_egress_internal.go, internal/testutil/testutil.go
Fixes various cost component lookups and golden tests based on new prices.
The only important change is for Azure Security Center since some of usage attributes had to be updated to map to the new pricing structure Azure has.
=> Cost component fixes

internal/providers/terraform/aws/acmpca_certificate_authority.go, internal/providers/terraform/aws/testdata/acmpca_certificate_authority_test/acmpca_certificate_authority_test.golden, internal/providers/terraform/aws/testdata/acmpca_certificate_authority_test/acmpca_certificate_authority_test.tf, internal/providers/terraform/aws/testdata/acmpca_certificate_authority_test/acmpca_certificate_authority_test.usage.yml, internal/resources/aws/acmpca_certificate_authority.go
=> feat: Add support for aws certificate authority short-lived certificates

Dockerfile, Dockerfile.ci, go.mod
~will redo the PR after https://github.com/infracost/infracost/pull/2875~
=> feat: update to use go 1.22.0

cmd/infracost/testdata/diff_prior_empty_project_json/diff_prior_empty_project_json.golden
Fixes failing diff test which started failing when unrebased PR was merged after usage changes were in the main branch.
=> fix: failing diff test

internal/apiclient/usage.go, internal/prices/usages.go
Improves the performance of usage API queries by batching graphql requests (10 per http request) and issuing the queries concurrently.
=> perf: batch usage api queries

cmd/infracost/comment.go, cmd/infracost/output.go, cmd/infracost/run.go, cmd/infracost/testdata/breakdown_help/breakdown_help.golden, cmd/infracost/testdata/comment_azure_repos_help/comment_azure_repos_help.golden, cmd/infracost/testdata/comment_bitbucket_help/comment_bitbucket_help.golden, cmd/infracost/testdata/comment_git_hub_help/comment_git_hub_help.golden, cmd/infracost/testdata/comment_git_lab_help/comment_git_lab_help.golden, cmd/infracost/testdata/diff_compare_to_error/diff_compare_to_error.golden, cmd/infracost/testdata/diff_compare_to_error_terragrunt/diff_compare_to_error_terragrunt.golden, cmd/infracost/testdata/diff_help/diff_help.golden, cmd/infracost/testdata/flag_errors_config_file_and_terraform_workspace/flag_errors_config_file_and_terraform_workspace.golden, cmd/infracost/testdata/flag_errors_no_path/flag_errors_no_path.golden, cmd/infracost/testdata/flag_errors_path_and_config_file/flag_errors_path_and_config_file.golden, cmd/infracost/testdata/output_help/output_help.golden
Update the --show-skipped usage docs to reflect that we no longer show free resources.
=> fix: Update --show-skipped description to not show free resources

cmd/infracost/testdata/comment_git_hub_show_all_projects/comment_git_hub_show_all_projects.golden, cmd/infracost/testdata/comment_git_hub_show_changed_projects/comment_git_hub_show_changed_projects.golden, cmd/infracost/testdata/comment_git_hub_with_additional_comment_path/comment_git_hub_with_additional_comment_path.golden, cmd/infracost/testdata/output_format_git_hub_comment_show_all_projects/output_format_git_hub_comment_show_all_projects.golden, cmd/infracost/testdata/output_format_git_hub_comment_without_module_path/output_format_git_hub_comment_without_module_path.golden, internal/output/diff.go, internal/output/markdown.go, internal/output/templates/markdown-html-usage-api.tmpl, internal/output/templates/markdown-usage-api.tmpl
Cleanup diff and comment output:
* Remove new monthly cost column from diff table
* Singularize baseline & usage "costs"
* Zero cost change should be formatted with a plus sign when displaying diffs
=> enhance: tweak diff and comment output

internal/providers/terraform/azure/registry.go
Adds Azure App Configuration resources, both features/keys are not charges as part of the App Configuration billing.
=> feat: add azure app configuration free resources

cmd/infracost/testdata/comment_azure_repos_pull_request/comment_azure_repos_pull_request.golden, cmd/infracost/testdata/comment_bitbucket_commit/comment_bitbucket_commit.golden, cmd/infracost/testdata/comment_bitbucket_exclude_details/comment_bitbucket_exclude_details.golden, cmd/infracost/testdata/comment_bitbucket_pull_request/comment_bitbucket_pull_request.golden, cmd/infracost/testdata/comment_git_hub_commit/comment_git_hub_commit.golden, cmd/infracost/testdata/comment_git_hub_pull_request/comment_git_hub_pull_request.golden, cmd/infracost/testdata/comment_git_hub_show_all_projects/comment_git_hub_show_all_projects.golden, cmd/infracost/testdata/comment_git_hub_show_changed_projects/comment_git_hub_show_changed_projects.golden, cmd/infracost/testdata/comment_git_hub_with_additional_comment_path/comment_git_hub_with_additional_comment_path.golden, cmd/infracost/testdata/comment_git_lab_commit/comment_git_lab_commit.golden, cmd/infracost/testdata/comment_git_lab_merge_request/comment_git_lab_merge_request.golden, cmd/infracost/testdata/output_format_azure_repos_comment/output_format_azure_repos_comment.golden, cmd/infracost/testdata/output_format_azure_repos_comment_multiple_skipped/output_format_azure_repos_comment_multiple_skipped.golden, cmd/infracost/testdata/output_format_bitbucket_comment_with_project_names/output_format_bitbucket_comment_with_project_names.golden, cmd/infracost/testdata/output_format_git_hub_comment/output_format_git_hub_comment.golden, cmd/infracost/testdata/output_format_git_hub_comment_multiple_skipped/output_format_git_hub_comment_multiple_skipped.golden, cmd/infracost/testdata/output_format_git_hub_comment_show_all_projects/output_format_git_hub_comment_show_all_projects.golden, cmd/infracost/testdata/output_format_git_hub_comment_with_project_errors/output_format_git_hub_comment_with_project_errors.golden, cmd/infracost/testdata/output_format_git_hub_comment_with_project_names/output_format_git_hub_comment_with_project_names.golden, cmd/infracost/testdata/output_format_git_hub_comment_with_project_names_with_metadata/output_format_git_hub_comment_with_project_names_with_metadata.golden, cmd/infracost/testdata/output_format_git_hub_comment_without_module_path/output_format_git_hub_comment_without_module_path.golden, cmd/infracost/testdata/output_format_git_lab_comment/output_format_git_lab_comment.golden, cmd/infracost/testdata/output_format_git_lab_comment_multiple_skipped/output_format_git_lab_comment_multiple_skipped.golden, internal/output/templates/markdown-html-usage-api.tmpl, internal/output/templates/markdown-usage-api.tmpl
GitHub (has title as tooltip):
GitLab (has title as tooltip):
Azure Repos (has title as tooltip):
Bitbucket (no tooltip):
=> enhance: Remove links from usage cost headers to reduce noise in comments

cmd/infracost/run.go, internal/prices/prices.go, internal/prices/prices_test.go
Change the `pricesNotFound` property so that it can be correctly aggregated in reporting.
=> fix: `pricesNotFoundList` env property

cmd/infracost/testdata/generate/env_var_dot_extensions/expected.golden, cmd/infracost/testdata/generate/env_var_dot_extensions/infracost.yml.tmpl, cmd/infracost/testdata/generate/env_var_dot_extensions/tree.txt, internal/hcl/project_locator.go
This was missed from https://github.com/infracost/infracost/pull/3032
=> fix: ensure hidden files are properly recognised as env var files

cmd/infracost/breakdown_test.go, cmd/infracost/testdata/breakdown_terraform_file_funcs/breakdown_terraform_file_funcs.golden, cmd/infracost/testdata/breakdown_terraform_file_funcs/instance.json, cmd/infracost/testdata/breakdown_terraform_file_funcs/main.tf, cmd/infracost/testdata/breakdown_terraform_file_funcs/sym-instance.json, cmd/infracost/testdata/breakdown_terraform_file_funcs/templ.tftpl, cmd/infracost/testdata/breakdown_terragrunt_file_funcs/breakdown_terragrunt_file_funcs.golden, cmd/infracost/testdata/breakdown_terragrunt_file_funcs/instance.json, cmd/infracost/testdata/breakdown_terragrunt_file_funcs/main.tf, cmd/infracost/testdata/breakdown_terragrunt_file_funcs/sym-instance.json, cmd/infracost/testdata/breakdown_terragrunt_file_funcs/templ.tftpl, cmd/infracost/testdata/breakdown_terragrunt_file_funcs/terragrunt.hcl, cmd/infracost/testdata/instance.json, cmd/infracost/testdata/templ.tftpl, internal/hcl/evaluator.go, internal/hcl/funcs/crypto.go, internal/hcl/funcs/crypto_test.go, internal/hcl/funcs/filesystem.go, internal/hcl/funcs/filesystem_test.go, internal/hcl/graph.go, internal/hcl/graph_vertex_module_call.go, internal/hcl/parser.go, internal/providers/terraform/terragrunt_hcl_provider.go
Adds support for the `templatefile` function and adds coverage for various other
file functions.
=> feat: add templatefile support

internal/hcl/parser.go
=> fix: capacity and length were in the wrong order

internal/resources/azure/container_registry.go
This could cause a nil ptr panic before if this value was blank
=> fix(azure): default included storage for Azure Container Registry

internal/providers/terraform/aws/registry.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/google/registry.go
Also adds all the free resources from https://github.com/infracost/infracost/issues/2998
=> Add more free resources

internal/hcl/attribute.go, internal/hcl/parser_test.go
Before when we mocked index expressions, we would get an 'Invalid index' diagnostic, since we'd mock the key to value that was never in the collection.
This updates it to first check if the mocking causes an 'Invalid index' diagnostic, and if it does we return the first element from the collection. This may be the incorrect value, but seems the safest since at least the value returned will be the expected type.
If we see other diagnostics we return an empty string value. This may cause issues if the collection isn't meant to be a list of strings, but since we can't evaluate it this seems the safest.
=> fix: index expression mocking

internal/providers/terraform/azure/registry.go
Add support for free resources :
- azurerm_dev_test_global_vm_shutdown_schedule
- azurerm_dev_test_policy
- azurerm_dev_test_schedule
- azurerm_dev_test_lab
PR on the documentation : https://github.com/infracost/docs/pull/638
=> feat(azure): add free azure devtest lab resources

cmd/infracost/comment_azure_repos.go, cmd/infracost/comment_bitbucket.go, cmd/infracost/comment_github.go, cmd/infracost/comment_github_test.go, cmd/infracost/comment_gitlab.go, internal/apiclient/dashboard.go, internal/prices/prices_test.go, internal/providers/terraform/aws/testdata/lightsail_instance_test/lightsail_instance_test.golden, internal/providers/terraform/google/testdata/compute_instance_test/compute_instance_test.golden, internal/providers/terraform/google/testdata/container_cluster_test/container_cluster_test.golden, internal/providers/terraform/google/testdata/container_node_pool_test/container_node_pool_test.golden
- save pr comment to infracost cloud
- update some golden test for integration
=> feat: Save PR Comment to Infracost Cloud

internal/providers/terraform/aws/registry.go
https://aws.amazon.com/iam/identity-center/faqs/
=> add all AWS SSO (Identity Center) resources as free

internal/hcl/project_locator.go
This PR changes the parent Terragrunt config detection to parse the list of detected config files into a Tree before trying to determine which Terragrunt files are parent configuration. This significantly speeds up the time to detect parent configs as we need many less io operations to determine which files are parents. On a large repo with ~6k Terragrunt config files the speed of infracost generate went from ~50s to ~1.5s after this change.
=> fix: speed up parent Terragrunt config detection

internal/hcl/parser.go, internal/hcl/parser_test.go, internal/providers/terraform/aws/testdata/sns_topic_test/sns_topic_test.golden, internal/providers/terraform/azure/testdata/virtual_machine_test/virtual_machine_test.golden, internal/providers/terraform/google/testdata/compute_instance_test/compute_instance_test.golden, internal/providers/terraform/google/testdata/container_cluster_test/container_cluster_test.golden, internal/providers/terraform/google/testdata/container_node_pool_test/container_node_pool_test.golden
- add function to unique the sorted dependencies when creating the config file
- add tests to validate
This.....
```
version: 0.1
- path: mgmt
name: management
dependency_paths:
- mgmt/**
- modules/role/**
- modules/role/**
- modules/role/**
- modules/role/**
```
Becomes this.....
```
version: 0.1
- path: mgmt
name: management
dependency_paths:
- mgmt/**
- modules/role/**
```
=> fix: No duplicate dependencies

cmd/infracost/testdata/generate/wildcard_env_names/expected.golden, cmd/infracost/testdata/generate/wildcard_env_names/infracost.yml.tmpl, cmd/infracost/testdata/generate/wildcard_env_names/tree.txt, internal/config/template/parser.go, internal/hcl/project_locator.go
* support ? wildcards in env_names
* add lower function to config
=> Config file updates

internal/config/template/parser.go
Naming this so it's consistent with sprig
=> enhance: add `splitList` config file function

go.mod, go.sum, internal/config/config.go, internal/hcl/modules/fetch.go, internal/hcl/modules/fetch_test.go, internal/hcl/modules/loader.go, internal/hcl/modules/loader_test.go, internal/hcl/modules/s3_cache.go, internal/hcl/parser_test.go, internal/providers/terraform/hcl_provider.go, internal/providers/terraform/hcl_provider_test.go
Adds an optional S3 bucket cache before fetching modules with go-getter.
=> feat: add a remote S3 cache to the module loader

internal/providers/terraform/hcl_provider.go
Ensure that the dump location is created or fall back to the original path
=> fix: tidy up infracost dump path creation

cmd/infracost/breakdown_test.go, cmd/infracost/testdata/breakdown_terraform_provided_default_envs/breakdown_terraform_provided_default_envs.golden, cmd/infracost/testdata/breakdown_terraform_provided_default_envs/infracost.yml, cmd/infracost/testdata/breakdown_terraform_provided_default_envs/mod/main.tf, internal/hcl/parser.go
=> Revert "Revert "feat: add detected env name to input vars/workspace""

internal/config/template/parser.go
We can use `os.Stat` instead of walking
=> enhance: improve performance of `pathExists`

internal/providers/terraform/terragrunt_hcl_provider.go
If two Infracost projects point to the same Terragrunt directory we can see race conditons when writing and parsing the generated files.
=> fix: race condition caused by terragrunt generate blocks

internal/providers/terraform/aws/testdata/db_instance_test/db_instance_test.golden, internal/providers/terraform/aws/testdata/rds_cluster_instance_test/rds_cluster_instance_test.golden, internal/providers/terraform/azure/testdata/mysql_flexible_server_test/mysql_flexible_server_test.golden, internal/providers/terraform/azure/testdata/mysql_flexible_server_test/mysql_flexible_server_test.tf, internal/providers/terraform/google/testdata/compute_disk_test/compute_disk_test.tf, internal/providers/terraform/google/testdata/compute_image_test/compute_image_test.tf, internal/resources/azure/mysql_flexible_server.go, internal/resources/google/sql_database_instance.go
* exclude Google Extended support instances
* update mappings for Azure MySQL Flexible Server
=> fix: golden tests

internal/config/configuration.go, internal/config/template/parser_test.go, internal/config/template/testdata/with_is_production/infracost.golden.yml
fixes issue where the production filters logic diverges from the dashboard logic
=> fix: do substring match and not direct comparison is no wildcards used

internal/config/config.go, internal/config/config_file.go, internal/config/terraform_source_map.go, internal/hcl/modules/loader.go, internal/hcl/modules/loader_test.go, internal/hcl/modules/testdata/regex_sourcemap/main.tf, internal/hcl/parser_test.go, internal/providers/terraform/hcl_provider.go, internal/providers/terraform/hcl_provider_test.go, schema/config.schema.json
Adds a more complex regex source map which handles complex rules.
=> feat: add config file regex source map

internal/hcl/project_locator.go
Adds useful autodetect debug lines
=> fix: add additional debug for project locator

.terraformrc, internal/providers/terraform/azure/postgresql_flexible_server.go, internal/providers/terraform/azure/testdata/postgresql_flexible_server_test/postgresql_flexible_server_test.golden, internal/providers/terraform/azure/testdata/postgresql_flexible_server_test/postgresql_flexible_server_test.tf, internal/providers/terraform/azure/testdata/postgresql_flexible_server_test/postgresql_flexible_server_test.usage.yml, internal/resources/azure/postgresql_flexible_server.go
=> Fix postgres issue when high availability is enabled

.github/workflows/go.yml, .golangci.bck.yml, .golangci.yml, Dockerfile, Dockerfile.ci, cmd/infracost/generate.go, go.mod, internal/providers/terraform/terragrunt_hcl_provider.go, internal/resources/aws/launch_configuration.go, internal/resources/aws/launch_template.go, internal/resources/azure/vpn_gateway_connection.go
Updates Go version from 1.24.6 to 1.25.1 in go.mod and Dockerfiles.
=> chore: upgrade to Go 1.25.1
