infracost/infracost

cmd/infracost/main.go, internal/terraform/aws/base.go, pkg/base/costs.go, pkg/config/config.go, pkg/output/table.go, pkg/parsers/terraform/terraform.go
Both of these changes simplify `git diff` being used to compare infracost outputs.
The sorting is done based on `Resource.Address` (e.g. `aws_autoscaling_group.lt1` then `aws_elb.elb1`). Within each resource;
- the `PriceComponentCosts` are sorted by `Name` (e.g. `GB` then `Instance hours`)
- the sub-resources are sorted by `Address` (similar to top-level resources)
Alphabetical sorting works better than numerical sorting based on hourly/monthly cost since the costs might change across infracost runs for the same resource thus making it harder to `git diff` the output.
=> Add `--no-color` and sort output to simplify diffs

pkg/parsers/terraform/terraform.go
Outputs from terraform show commands can be too long. We are also seeing errors with logrus with large logs.
=> Don't log the command output.

internal/terraform/aws/ec2_launch_template.go
When my launch template ```desired_capacity``` is set to ```0``` I get a division by zero error.
```hcl-terraform
resource "aws_autoscaling_group" "demo" {
availability_zones = ["eu-west-2a","eu-west-2b","eu-west-2c"]
desired_capacity   = 0
max_size           = 1
min_size           = 0
launch_template {
id      = aws_launch_template.demo.id
version = "$Latest"
}
}
```
Running the program results in the following stack trace in release ```0.4.0```.
```
panic: decimal division by 0
goroutine 1 [running]:
github.com/shopspring/decimal.Decimal.QuoRem(0xc00006d390, 0x0, 0xc00006d370, 0x0, 0xc000000010, 0x100e0d6, 0xc0002764e0, 0x20, 0x20)
/Users/ali/go/pkg/mod/github.com/shopspring/decimal@v1.2.0/decimal.go:500 +0x375
github.com/shopspring/decimal.Decimal.DivRound(0xc00006d390, 0x0, …
```
=> Prevent a division by zero error on launch template quantity

internal/terraform/aws/rds_instance.go
Example resource that was not matching a price before this commit:
```
resource "aws_db_instance" "issue1” {
allocated_storage    = 20
engine               = "oracle-se2"
instance_class       = "db.r5.2xlarge"
}
```
This might have caused https://github.com/aliscott/cloud-pricing-api/issues/2, I'll ask the issue creator to confirm.
=> Fix, what looks like, a typo

examples/terraform/main.tf, internal/terraform/aws/rds_instance.go
AWS has the engine listed as postgres instead of postgresql: https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html
This resolves https://github.com/aliscott/cloud-pricing-api/issues/2#issuecomment-677532438
=> Make postgres engine match API spec

Makefile, README.md, internal/terraform/aws/ec2_instance_test.go, internal/terraform/aws/elb.go, internal/terraform/aws/nat_gateway.go, internal/terraform/aws/nat_gateway_test.go, internal/testutil/testutil.go, pkg/config/config.go, pkg/costs/breakdown.go, pkg/costs/query.go, pkg/resource/resource_test.go
We use the price hashes returned from the pricing API to validate we are mapping the correct prices. This means if the price changes, the tests won't break.
Currently only tests for `aws_nat_gateway` and `aws_instance` have been added.
=> Add initial work on integration tests

internal/providers/terraform/aws/resource_registry.go, internal/providers/terraform/parser.go, internal/providers/terraform/resource_registry.go, pkg/schema/resource.go
So I designed a kind of registry object in the way that:
* Each cloud provider has its own registry so it reduces the cost of conflicts
* Reduce the amount of switch-case duplicate codes
However, because of the Golang limitations it's not possible to have such kind of code:
```
func AwsInstance(d *schema.ResourceData) *schema.Resource {
...
}
terraform.AddResourceType("aws_instance", AwsInstance)
```
And that's because you can't have non-declrative statements in the root of files.
=> Change createResource logic to registry based

scripts/install_provider.sh
We need the bare version without the v prefix in the path to the provider
=> Fix the provider install script

Makefile, internal/providers/terraform/aws/docdb_cluster_instance.go, internal/providers/terraform/aws/docdb_cluster_instance_test.go, internal/providers/terraform/aws/resource_registry.go
**Objective**:
Add support for `aws_docdb_cluster_instance`.
```
aws_docdb_cluster_instance.db
├─ Backup Storage                                         0  GB-month     0.0210       0.0000        0.0000
├─ CPU Credits                                            0  vCPU-hour    0.0900       0.0000        0.0000
├─ Database Instance (on_demand, db.t3.medium)          730  hours        0.0780       0.0780       56.9400
├─ I/O                                                    0  requests      2e-07       0.0000        0.0000
└─ Storage                                                0  GB-month     0.1000       0.0000        0.0000
Total                                                                                  0.0780       56.9400
```
**Pricing details**:
The …
=> Add support for aws_docdb_cluster_instance - used as an example of how to add new resources

scripts/price_explorer/2_find_product_families.sh, scripts/price_explorer/3_find_attribute_keys.sh, scripts/price_explorer/README.md
=> Change price explorer scritps for a better output and fix bug

cmd/infracost/main.go, internal/providers/terraform/cmd.go
Sample output of `infracost --version`
```
Infracost v0.5.1-15-g779d8bf-dirty
Terraform v0.12.29
Your version of Terraform is out of date! The latest version
is 0.13.2. You can update by downloading from https://www.terraform.io/downloads.html
```
Fixes #97
=> Add version flag

internal/providers/terraform/aws/dynamodb_table.go, internal/providers/terraform/aws/dynamodb_table_test.go
**Status:**
**Issues:**
- Fixes #83 
Useful links:
- Overview: https://aws.amazon.com/dynamodb/
- Pricing: https://aws.amazon.com/dynamodb/pricing/on-demand/
- Terraform: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table
=> Add support for on-demand DynamoDB

cmd/infracost/main.go, internal/providers/terraform/parser.go, internal/providers/terraform/provider.go, pkg/output/json.go, pkg/output/table.go, pkg/schema/resource.go
Fixes #84 
Here's a sample output with no flag:
```
NAME           MONTHLY QTY  UNIT  PRICE  HOURLY COST  MONTHLY COST  
OVERALL TOTAL                                 0.0000        0.0000  
3 out of 3 resources were skipped, 1 are free, and 2 aren't supported in Infracost yet(https://www.infracost.io/docs/supported_resources), re-run with --show-skipped to see the list.
```
And with `--show-skipped` flag:
```
NAME           MONTHLY QTY  UNIT  PRICE  HOURLY COST  MONTHLY COST  
OVERALL TOTAL                                 0.0000        0.0000  
Skipped aws_proxy_configuration.my_proxy_configuration | This resource is free.
Skipped aws_dynamodb_table.my_dynamodb_table | This resource is not currently supported.
Skipped aws_db_instance.my_db_instance | This resource is not currently …
```
=> Show skipped resources

docs/generated/supported_resources.md, internal/providers/terraform/aws/instance.go, internal/providers/terraform/aws/instance_test.go, pkg/prices/query.go, pkg/schema/filters.go
**Depends on https://github.com/infracost/cloud-pricing-api/pull/21 and https://github.com/infracost/infracost/pull/126**
**Objective**:
Add EC2 detailed monitoring costs for `aws_instance`.
```
aws_instance.web_app
├─ CPU credits                                       0  vCPU-hours  0.0500       0.0000        0.0000
├─ EC2 detailed monitoring                           7  metrics     0.3000       0.0029        2.1000
├─ Linux/UNIX usage (on-demand, t3.micro)          730  hours       0.0104       0.0104        7.5920
└─ root_block_device
└─ Storage                                       15  GB-months   0.1000       0.0021        1.5000
Total                                                                            0.0153       11.1920 …
```
=> Add EC2 detailed monitoring

cmd/infracost/main.go
Added example commands with the `UsageText` property of the cli app.
=> fix: clarify infracost usage with adding example commands for help command

docs/generated/supported_resources.md, internal/providers/terraform/aws/autoscaling_group.go, internal/providers/terraform/aws/autoscaling_group_test.go, internal/providers/terraform/aws/instance.go, internal/providers/terraform/aws/instance_test.go
**Objective**:
Add more options for `aws_autoscaling_group`.
```
aws_autoscaling_group.asg1
└─ aws_launch_configuration.lc1
├─ EC2 detailed monitoring                           14  metrics      0.3000       0.0058        4.2000
├─ Linux/UNIX usage (on-demand, m3.medium)         1460  hours        0.0740       0.1480      108.0400
└─ root_block_device
└─ Storage                                        16  GB-months    0.1000       0.0022        1.6000
Total                                                                                 0.1559      113.8400
aws_autoscaling_group.asg2
└─ aws_launch_template.lt1
├─ EBS-Optimized usage                             1460  hours        0.0200       0.0400       29.2000
├─ EC2 detailed monitoring                           14 …
```
=> Add more Autoscaling Group prices and costs

internal/providers/terraform/aws/autoscaling_group.go, internal/providers/terraform/aws/autoscaling_group_test.go, internal/providers/terraform/aws/ebs_snapshot.go, internal/providers/terraform/aws/ebs_snapshot_copy_test.go, internal/providers/terraform/aws/ebs_snapshot_test.go, internal/providers/terraform/aws/ebs_volume.go, internal/providers/terraform/aws/ebs_volume_test.go, internal/providers/terraform/aws/instance.go, internal/providers/terraform/aws/instance_test.go
**Objective**:
Add more options for `aws_ebs_volume`, `aws_ebs_snapshot` and `aws_ebs_snapshot_copy`.
```
aws_ebs_snapshot.gp2
├─ EBS snapshot storage                                            10  GB-months         0.0500       0.0007        0.5000
├─ Fast snapshot restore                                            0  DSU-hours         0.7500       0.0000        0.0000
├─ GetSnapshotBlock API requests                                    0  requests           3e-06       0.0000        0.0000
├─ ListChangedBlocks and ListSnapshotBlocks API requests            0  requests           6e-07       0.0000        0.0000
└─ PutSnapshotBlock API requests                                    0  requests           6e-06       0.0000        0.0000
Total …
```
=> Add more EBS prices and costs

.dockerignore
The version is found by using git SHAs so we need to include the .git directory in the builder stage of the Dockerfile.
=> Fix 'infracost --version' in the docker image

internal/providers/terraform/aws/ecs_service.go, internal/providers/terraform/aws/ecs_service_test.go
If no task definition was provided we had a nil pointer issue.
We can't yet show costs for EXTERNAL ECS deployments, but we can show the prices.
=> fix(aws): fix ECS service nil pointer

internal/providers/terraform/aws/lightsail_instance.go, internal/providers/terraform/aws/lightsail_instance_test.go, internal/providers/terraform/aws/resource_registry.go
**Objective**:
Add support for `aws_lightsail_instance`.
```
aws_lightsail_instance.pricing_api
└─ Virtual server (Linux/UNIX)               730  hours      0.1075       0.1075       78.4969
Total                                                                     0.1075       78.4969
```
**Status**:
**Issues**:
- Terraform only supports the Lightsail bundles so we can't add support for the CDN, managed DBs, load balancer, etc.
- Lightsail prices are listed per 744-hour month on the AWS Lightsail pricing page, but are actually charged at an hourly rate. We use 730-hour months since that's what most other AWS pricing seems to use.
**Useful links**:
- Pricing: https://aws.amazon.com/lightsail/pricing/
- Terraform: …
=> Add support for AWS Lightsail instances

CONTRIBUTING.md, examples/terraform/main.tf, internal/providers/terraform/aws/eip.go, internal/providers/terraform/aws/eip_test.go, internal/providers/terraform/aws/elb.go, internal/providers/terraform/aws/elb_test.go, internal/providers/terraform/aws/free_resources.go, internal/providers/terraform/aws/lb.go, internal/providers/terraform/aws/lb_test.go, internal/providers/terraform/aws/nat_gateway.go, internal/providers/terraform/aws/nat_gateway_test.go, internal/providers/terraform/aws/resource_registry.go, internal/providers/terraform/aws/route53_record.go, internal/providers/terraform/aws/route53_zone.go, internal/providers/terraform/aws/route53_zone_test.go, internal/providers/terraform/parser.go, internal/providers/terraform/parser_internal_test.go
**Objective**:
Add support for `aws_eip`.
```
NAME                                        MONTHLY QTY  UNIT         PRICE   HOURLY COST  MONTHLY COST
aws_eip.free
└─ IP address (if unused)                             -  hours        0.0050            -             -
Total                                                                                   -             -
```
**Status**:
**Issues**:
- Whilst we could show costs for this, I think it's best not to as we don't know for sure if the EIP is unused (that requires us to check the user's AWS account)
- Remapping and carrier costs can’t be supported as Terraform doesn’t seem to support them (they should be minor). Finding additional EIPs is not yet supported.
**Useful links**:
- Pricing: …
=> Add aws_eip

cmd/infracost/default.go, cmd/infracost/main.go, internal/providers/terraform/aws/autoscaling_group.go, internal/providers/terraform/aws/ebs_snapshot.go, internal/providers/terraform/aws/ebs_snapshot_copy.go, internal/providers/terraform/aws/ebs_volume.go, internal/providers/terraform/aws/ecs_service.go, internal/providers/terraform/aws/instance.go, internal/providers/terraform/aws/route53_record.go, internal/providers/terraform/parser.go, internal/providers/terraform/parser_internal_test.go, internal/providers/terraform/provider.go, internal/schema/registry_item.go
This adds an `--use-tfstate` flag which allows the user to use the state instead of a plan of the Terraform code.
This works by running `terraform show -json` inside the Terraform directory so it works with both local and remote state.
=> Add --use-tfstate flag

internal/providers/terraform/aws/apigatewayv2_api.go, internal/providers/terraform/aws/apigatewayv2_api_internal_test.go, internal/providers/terraform/aws/apigatewayv2_api_test.go, internal/providers/terraform/aws/free_resources.go, internal/providers/terraform/aws/resource_registry.go
**Objective**:
Adds support for ```api_gatewayv2_api```
```
NAME                                      MONTHLY QTY  UNIT      PRICE  HOURLY COST  MONTHLY COST  
aws_apigatewayv2_api.http                                                                          
├─ Requests (first 300m)                      1000000  requests  1e-06       0.0014        1.0000  
└─ Requests (over 300m)                             0  requests  9e-07       0.0000        0.0000  
Total                                                                        0.0014        1.0000  
aws_apigatewayv2_api.websocket                                                                     
├─ Requests (first 1B message transfers)   1000000000  requests  1e-06       1.3699     1000.0000  
└─ Requests (over …
```
=> Added API Gateway v2 HTTP & Websocket support

internal/providers/terraform/provider.go
Although this doesn’t seem to be doing what it’s meant to in Terraform 0.12.0 or 0.13.5, it might be fixed in future versions
=> fix(terraform): set input=false as we do in other places

internal/providers/terraform/aws/free_resources.go, internal/providers/terraform/aws/msk_cluster.go, internal/providers/terraform/aws/msk_cluster_test.go, internal/providers/terraform/aws/resource_registry.go
**Objective**:
Adds support for ```msk_cluster```
** Closes ** #205 
```
NAME                                      MONTHLY QTY  UNIT       PRICE   HOURLY COST  MONTHLY COST  
aws_msk_cluster.test                                                                                 
├─ MSK (broker instance, kafka.t3.small)        2,920  hours      0.0456       0.1824      133.1520  
└─ MSK storage                                  4,000  GB-months  0.1000       0.5479      400.0000  
Total                                                                          0.7303      533.1520  
OVERALL TOTAL (USD)                                                            0.7303      533.1520  
```
**Pricing details:**
The Amazon MSK service provides 2 pricing components described in …
=> feat(aws): Adds support for AWS MSK

internal/providers/terraform/aws/cloudwatch_dashboard.go, internal/providers/terraform/aws/cloudwatch_dashboard_test.go, internal/providers/terraform/aws/cloudwatch_log_group.go, internal/providers/terraform/aws/cloudwatch_log_group_test.go, internal/providers/terraform/aws/cloudwatch_metric_alarm.go, internal/providers/terraform/aws/cloudwatch_metric_alarm_internal_test.go, internal/providers/terraform/aws/cloudwatch_metric_alarm_test.go, internal/providers/terraform/aws/registry.go
**Objective**:
Adds support for cloudwatch_dashboard & cloudwatch_metric_alarm.
** Closes ** #54 
**Example output**: 
```
NAME                                              MONTHLY QTY  UNIT     PRICE   HOURLY COST  MONTHLY COST  
aws_cloudwatch_dashboard.main                                                                              
└─ Dashboard                                                1  monthly  3.0000       0.0041        3.0000  
Total                                                                                0.0041        3.0000  
aws_cloudwatch_metric_alarm.expression                                                                     
└─ Standard resolution                                      1  alarm    0.1000       0.0001        0.1000  
Total …
```
=> feat(aws): Adds support for Cloudwatch dashboards & metric alarms.  

internal/config/config.go, internal/providers/terraform/aws/eks_node_group.go, internal/providers/terraform/aws/instance.go
this should fix these:
```
=== RUN   TestAutoscalingGroup_launchConfiguration_cpuCredits
time="2020-11-28T17:38:03Z" level=warning msg="Multiple products found for aws_launch_configuration.lc1 CPU credits, using the first product"
TestEKSNodeGroup_default
time="2020-11-28T17:38:37Z" level=warning msg="Multiple products found for aws_launch_template.lt1 CPU credits, using the first product"
TestInstance_cpuCredits
time="2020-11-28T17:40:22Z" level=warning msg="Multiple products found for aws_eks_node_group.example CPU credits, using the first product"
```
=> fix(aws): instance types for t3 were matching t3a too

internal/providers/terraform/aws/kms_external_key.go, internal/providers/terraform/aws/kms_key.go, internal/providers/terraform/aws/kms_key_external_test.go, internal/providers/terraform/aws/kms_key_test.go, internal/providers/terraform/aws/registry.go
Fixes #213
Given a key definition:
```
resource "aws_kms_key" "kms" {}
```
Report the basic key usage:
```
aws_kms_key.kms
└─ CMK                                                1  months       1.0000       0.0014        1.0000
Total                                                                              0.0014        1.0000
```
This PR does not cover cumulative costs incurred by yearly key rotation and does not cover key usage.
=> Adding basic KMS resource

cmd/infracost/default.go, cmd/infracost/report.go, internal/output/html.go, internal/output/output.go, internal/output/table.go, internal/output/templates.go, internal/prices/query.go, internal/schema/resource.go
This also updates the JSON output to show the unsupported resources in a structured format, e.g.
```json
"resourceSummary": {
"unsupportedCounts": {
"aws_simpledb_domain": 3,
"aws_docdb_cluster": 1
}
}
```
=> feat(output): add skipped resources message to report

internal/providers/terraform/aws/registry.go, internal/providers/terraform/aws/sns_topic.go, internal/providers/terraform/aws/sns_topic_subscription.go, internal/providers/terraform/aws/sns_topic_subscription_test.go, internal/providers/terraform/aws/sns_topic_test.go
**Objective**:
Adds support for `sns_topic` & `sns_topic_subscription`
** Closes ** #229 
```
NAME                             MONTHLY QTY  UNIT              PRICE   HOURLY COST  MONTHLY COST  
aws_sns_topic.this                                                                                 
└─ Requests                                -  1M requests       0.5000            -             -  
Total                                                                             -             -  
aws_sns_topic_subscription.this                                                                    
└─ HTTP notifications                      -  1M notifications  0.6000            -             -  
Total                                                                             - …
```
=> feat(aws): Adds basic SNS support

internal/providers/terraform/aws/registry.go, internal/providers/terraform/aws/vpc_endpoint.go, internal/providers/terraform/aws/vpc_endpoint_test.go
**Objective**:
Adds support for `vpc_endpoint` 
** Partially Closes ** #191  
```
WWWWWWWWWWWWWWWWWWWWWW
NAME                                 MONTHLY QTY  UNIT   PRICE   HOURLY COST  MONTHLY COST  
WWWWWWWWWWWWWWWWWWWWWWWWWWW
aws_vpc_endpoint.endpoint                                                                   
├─ VPC Interface endpoint                    730  hours  0.0110       0.0110        8.0300  
└─ Data processed                              -  GB     0.0100            -             -  
Total                                                                 0.0110        8.0300  
aws_vpc_endpoint.gw                                                                         
├─ VPC GatewayLoadBalancer endpoint          730  hours  0.0112       0.0112 …
```
=> feat(aws): Added support for VPC Endpoint(s)

internal/providers/terraform/provider.go
Update error message `Please set your TERRAFORM_CLOUD_API_TOKEN environment variable.` to use new `TERRAFORM_CLOUD_TOKEN`.
=> update error message to reflect change in env var

internal/providers/terraform/cloud.go
See https://www.terraform.io/docs/commands/cli-config.html and https://github.com/hashicorp/setup-terraform/blob/master/lib/setup-terraform.js#L92
=> fix(terraform): fix typo in non-windows terraform CLI config file

CONTRIBUTING.md, README.md
1. Merge macOS/Linux install steps
2. Link to docker and windows
2. Move development details to contributing page
3. Inline CI/CD and supported resources sections
=> docs: update readme to be shorter and clearer

.github/workflows/create-release.yml, Makefile
Saves a few watt-hours for people using the CLI with newer Mac hardware.
=> chore: darwin-arm64 binaries

.github/workflows/create-release.yml, Makefile
Reverts infracost/infracost#287
darwin-arm64 binaries should wait until golang 1.16 release
=> Revert "chore: darwin-arm64 binaries"

internal/providers/terraform/aws/vpc_endpoint.go, internal/providers/terraform/aws/vpc_endpoint_test.go
VPC endpoints can create multiple interfaces across subnets. The initial implementation missed this and didn't check to see if the optional TF resource specified ``subnet_ids``. I've updated the tests to cater for this. 
fixes #327 
output from when two subnets are specified.  
```
✔ Running terraform init
✔ Running terraform plan
✔ Running terraform show
✔ Calculating cost estimate
NAME                   MONTHLY QTY  UNIT   PRICE   HOURLY COST  MONTHLY COST
aws_vpc_endpoint.this
├─ Interface endpoint        1,460  hours  0.0100       0.0200       14.6000
└─ Data processed                -  GB     0.0100            -             -
Total                                                   0.0200       14.6000
OVERALL TOTAL (USD)                                     0.0200       14.6000
```
=> fix(vpc_endpoint): Fix bug with counting interfaces. 

internal/providers/terraform/aws/ec2_transit_gateway_peering_attachment.go, internal/providers/terraform/aws/ec2_transit_gateway_vpc_attachment.go, internal/providers/terraform/parser.go
These resources don't return an ARN from the AWS API so we can't tell the region, but we can get it from their transit gateway
=> fix(aws): Use EC2 Transit Gateway's region for the attachments

CONTRIBUTING.md
The current version of snippet in CONTRIBUTING.md file leads to failure once build. 
This PR will fix the problem by using int64 variable for [NewFromInt function](https://github.com/shopspring/decimal/blob/v1.2.0/decimal.go#L93)
=> Fix contributing file snippet

CONTRIBUTING.md, infracost-usage-example.yml, internal/providers/terraform/aws/secretsmanager_secret.go, internal/providers/terraform/google/dns_managed_zone.go, internal/providers/terraform/google/dns_managed_zone_test.go, internal/providers/terraform/google/dns_record_set.go, internal/providers/terraform/google/dns_record_set_test.go, internal/providers/terraform/google/registry.go
Closes https://github.com/infracost/infracost/issues/254 and https://github.com/infracost/infracost/issues/253
Also adds other free google resources and fixes a typo in aws_secretsmanager_secret
Example output:
```
NAME                                               MONTHLY QTY  UNIT        PRICE   HOURLY COST  MONTHLY COST
google_dns_managed_zone.example_zone
└─ Managed zone                                              1  months      0.2000       0.0003        0.2000
Total                                                                                    0.0003        0.2000
google_dns_record_set.frontend
└─ Queries                                                   1  1M queries  0.4000       0.0005        0.4000
Total …
```
=> feat(google): add Cloud DNS resources

infracost-usage-example.yml, internal/providers/terraform/google/pubsub_subscription.go, internal/providers/terraform/google/pubsub_subscription_test.go, internal/providers/terraform/google/pubsub_topic.go, internal/providers/terraform/google/pubsub_topic_test.go, internal/providers/terraform/google/registry.go, internal/providers/terraform/google/util.go
Google pubsub has 1 price that applies for both the ingestion and delivery of messages. I show the same price with a slightly different name in the subscription and topic resources. I only show the retained and snapshot prices in the subscription as they apply on a per-subscription basis so it seems best to only show them there.
```
NAME                                          MONTHLY QTY  UNIT         PRICE    HOURLY COST  MONTHLY COST
google_pubsub_subscription.my_subscription
├─ Message delivery data                            7.416  TiB          40.0000       0.4064      296.6400
├─ Retained acknowledged message storage              605  GiB-months    0.2700       0.2238      163.3500
└─ Snapshot message backlog storage                  70.6  GiB-months    0.2700       0.0261 …
```
=> Add support for Google PubSub resources

infracost-usage-example.yml, internal/providers/terraform/google/compute_router_nat.go, internal/providers/terraform/google/compute_router_nat_test.go, internal/providers/terraform/google/registry.go
Google Compute Router NAT has two prices - one per assigned VM and one for data processed.
For the assigned VM price, once the VM count reaches 32 then the price does not increase further.
Terraform resource: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_router_nat
Pricing page: https://cloud.google.com/nat/pricing
Example:
```
google_compute_router_nat.my_nat
├─ Per assigned VM (up to 32)                          4  VMs          0.0014        8e-06        0.0056
└─ Data processed                                  1,000  GB           0.0450       0.0616       45.0000
Total                                                                               0.0617       45.0056
```
=> Add support for Google Compute Router NAT

infracost-usage-example.yml, internal/providers/terraform/aws/codebuild_project.go, internal/providers/terraform/aws/codebuild_project_test.go, internal/providers/terraform/aws/registry.go
Issue #193  
```
NAME                                          MONTHLY QTY  UNIT     PRICE   HOURLY COST  MONTHLY COST  
aws_codebuild_project.my_project                                                                       
└─ Linux (general1.2xlarge)                        10,000  minutes  0.2500       3.4247    2,500.0000  
Total                                                                            3.4247    2,500.0000 
```
When user wants to use this resource, Amazon requires fields such as "BUILD_GENERAL1_SMALL" and "LINUX_CONTAINER" for "Compute Type" and "Type" in the environment. But when we requesting the price of CodeBuild, it does not allow transferring the environment.type - this is the reason why I had to create and use the usagetype attribute.
=> AWS CodeBuild support

internal/providers/terraform/parser.go
S3 buckets ARNs look like `arn:aws:s3:::bucket1` so they don't include a region key. In this case S3 buckets also pass a "region" value in the response so we can parse that out and use it as the region.
=> fix(terraform): parse region from values if exists

cmd/infracost/default.go, cmd/infracost/deprecations.go
Shows the following output:
```
Flag --tfdir is deprecated and will be removed in v0.8.0. Please use --terraform-dir.
Flag --output/-o is deprecated and will be removed in v0.8.0. Please use --format.
```
=> fix(flags): fix -o flag deprecation

cmd/infracost/default.go, cmd/infracost/report.go, internal/config/config.go
`--no-color` flag on `infracost report` returns the following error:
```
flag provided but not defined: -no-color
```
This fixes an issue with the configuration option to behave like `--show-skipped`.
=> fix(flags): Adding no-color support to report

internal/providers/terraform/aws/autoscaling_group_test.go, internal/providers/terraform/aws/ebs_volume.go, internal/providers/terraform/aws/ebs_volume_test.go, internal/providers/terraform/aws/instance_test.go
Fix #296 
List of gp2 occurrences (all might not need change):
=> feat: add gp3 support

infracost-usage-example.yml, internal/providers/terraform/aws/efs_file_system.go, internal/providers/terraform/aws/efs_file_system_test.go, internal/providers/terraform/aws/registry.go
Objective: closes #388 
```
aws_efs_file_system.ia_access                                                                              
├─ Storage (standard)                                 230  GB-months    0.3300       0.1040       75.9000  
├─ Storage (infrequent access)                        100  GB-months    0.0250       0.0034        2.5000  
└─ Requests (infrequent access)                       100  GB           0.0110       0.0015        1.1000  
Total                                                                                0.1089       79.5000  
aws_efs_file_system.my_file_system                                                                         
├─ Storage (standard)                                 230  GB-months    0.3300       0.1040       75.9000  
└─ Provisioned …
```
=> feat(aws): Adds support for EFS.

Dockerfile
`--update` shouldn't be used when `--no-cache` is already there.
=> chore: remove additional `--update` for apk in Dockerfile

Dockerfile
There were two `-y` for `apt-get` 😅
=> chore: remove duplicated `-y` for `apt-get` in Dockerfile

scripts/ci/atlantis_diff.sh, scripts/ci/diff.sh
Part of [Issue](https://github.com/infracost/infracost-gh-action/issues/22)
New argument: post_condition
Could be:
post_condition:'{"always":"true"}' - always post comments
post_condition:'{"has_diff":"true"}' - post comments if it has output
post_condition:'{"percentage_threshold":"2"}' - post comment if absolute_percent more than percentage_threshold
=> Add 'post_condition' arg in CI script

infracost-usage-example.yml, internal/providers/terraform/google/compute_image.go, internal/providers/terraform/google/compute_image_test.go, internal/providers/terraform/google/compute_machine_image.go, internal/providers/terraform/google/compute_machine_image_test.go, internal/providers/terraform/google/registry.go, internal/providers/terraform/tftest/tftest.go
Issue #437 
With output: 
```
NAME                                           MONTHLY QTY  UNIT       PRICE   HOURLY COST  MONTHLY COST
google_compute_image.my_image                                                                             
└─ Storage                                             100  GB-months  0.0500       0.0068        5.0000  
Total                                                                               0.0068        5.0000
google_compute_machine_image.my_machine_image                                                             
└─ Storage                                           1,000  GB-months  0.0500       0.0685       50.0000  
Total                                                                               0.0685       50.0000 
```
Without output: 
``` …
```
=> feat(google): Add support for Google Compute Image

Dockerfile
`zip` is actually not needed in the Dockerfile, but install `zip` by default will also install the suggested `unzip` package, so that the later commands can use `unzip` without a problem, but `zip` really doesn't need to be installed here 😄 
This will help to speed up the builder stage a little bit 😀
=> chore(deps): install unzip instead of zip package in Dockerfile

Dockerfile
Change the file permision in the builder stage, save an image layer and
the duplicated file caused by permission change.
Result as below, saved the size of `infracost` the binary itself(about 16MB):
```
REPOSITORY      TAG        IMAGE ID         CREATED              SIZE
infracost       after      0a932e916231     3 minutes ago        638MB
infracost       before     37edb87395bb     8 minutes ago        654MB
```
=> chore: reorder Dockerfile instruction to minimize image size

internal/providers/terraform/google/redis_instance.go, internal/providers/terraform/google/redis_instance_test.go, internal/providers/terraform/google/registry.go
Issue #439 
```
NAME                                          MONTHLY QTY  UNIT      PRICE   HOURLY COST  MONTHLY COST
google_redis_instance.cache                                                                             
└─ Redis instance (Standard, M3)                   14,600  GB-hours  0.0460       0.9200      671.6000  
Total                                                                             0.9200      671.6000 
google_redis_instance.cache                                                                             
└─ Redis instance (Basic, M2)                       7,300  GB-hours  0.0270       0.2700      197.1000  
Total                                                                             0.2700      197.1000
```
=> feat(google): Add support for Google Memorystore Redis

internal/usage/usage_file.go
Fixes #557
FYI I tested the sync feature working with TF sub-resources as well as resources such as aws_cloudfront_distribution that have nested blocks in our usage-file.
=> fix: handle modules appearing in resource names

cmd/infracost/run.go, internal/providers/detect.go
#535 
`<pre>make -s run ARGS=&quot;breakdown --path plan&quot;
<font color="#EF2929">Error:</font> No such file or directory plan
Use the <font color="#34E2E2">--path</font> flag to specify the path to one of the following:
- Terraform plan JSON file
- Terraform directory
- Terraform plan file
- Terraform state JSON file
</pre>`
`<pre> make -s run ARGS=&quot;breakdown --path plan.json&quot;
<font color="#EF2929">Error:</font> Could not detect path type for plan.json
Use the <font color="#34E2E2">--path</font> flag to specify the path to one of the following:
- Terraform plan JSON file
- Terraform directory
- Terraform plan file
- Terraform state JSON file
</pre>`
=> feat: add error message to breakdown/cli

infracost-usage-example.yml, internal/providers/terraform/google/registry.go, internal/providers/terraform/google/sql_database_instance.go, internal/providers/terraform/google/sql_database_instance_test.go
Issue #386
```
NAME                                          MONTHLY QTY  UNIT       PRICE   HOURLY COST  MONTHLY COST
google_sql_database_instance.my_instance                                                                 
├─ vCPUs (regional)                                11,680  hours      0.0826       1.3216      964.7680  
├─ Memory (regional)                               43,800  GB         0.0140       0.8400      613.2000  
├─ Storage (SSD, regional)                            100  GB-months  0.3400       0.0466       34.0000  
├─ Backups                                          1,000  GB-months  0.0800       0.1096       80.0000  
├─ IP address (if unused)                             730  hours      0.0100       0.0100        7.3000  
└─ Replica …
```
=> feat(google): add support for Google SQL

internal/usage/usage_file.go
=> fix: skip syncing resources without name

internal/providers/terraform/dir_provider.go
@aliscott feel free to close this PR if this code is meant to mention the old env name. A user using the latest infracost-atlantis integration saw this error, so I wondered if we should update this:
```
Error: Terraform binary "/usr/local/bin/terraform0.13.4" could not be found.
Set a custom Terraform binary in your Infracost config or using the environment variable TERRAFORM_BINARY.
```
=> fix: update name of old env

infracost-usage-example.yml, internal/providers/terraform/azure/linux_virtual_machine.go, internal/providers/terraform/azure/linux_virtual_machine_scale_set.go, internal/providers/terraform/azure/linux_virtual_machine_scale_set_test.go, internal/providers/terraform/azure/linux_virtual_machine_test.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/virtual_machine.go, internal/providers/terraform/azure/windows_virtual_machine.go, internal/providers/terraform/azure/windows_virtual_machine_scale_set.go, internal/providers/terraform/azure/windows_virtual_machine_scale_set_test.go, internal/providers/terraform/azure/windows_virtual_machine_test.go
**Without usage:**
```
Name                                                        Quantity  Unit                Monthly Cost
azurerm_linux_virtual_machine_scale_set.standard_f2
├─ Instance usage (pay as you go, F2)                          1,460  hours                    $144.54
├─ Ultra disk reservation (if unattached)            Cost depends on usage: $0.006 per vCPU-hours
└─ os_disk
├─ Storage (S4)                                                 2  months                     $3.07
└─ Disk operations                                Cost depends on usage: $0.0005 per 10k operations
azurerm_windows_virtual_machine_scale_set.basic_a2
├─ Instance usage (pay as you go, A2)                          2,190  hours                    $291.27
└─ os_disk
├─ Storage (S4) …
```
=> Add Azure VM scale sets

internal/providers/terraform/azure/app_service_certificate_order.go, internal/providers/terraform/azure/app_service_certificate_order_test.go, internal/providers/terraform/azure/registry.go
**Objective**:
Add support for azurerm_app_service_certificate_order.
Fixes https://github.com/infracost/infracost/issues/570
Example output without usage-file:
```
Running "infracost breakdown --path ." against a main.tf with:
resource "azurerm_app_service_certificate_order" "example" {
name                = "example-cert-order"
resource_group_name = "fake"
location            = "global"
distinguished_name  = "CN=example.com"
product_type        = "Wildcard"
}
Name                                           Quantity  Unit   Monthly Cost
azurerm_app_service_certificate_order.example
└─ SSL certificate (Wildcard)                    0.0833  years        $25.00
Example output with usage-file: Not applicable
```
**Pricing details**:
Azure pricing page used the same prices for non-Gov and US …
=> feat(azure): add azurerm_app_service_certificate_order

Dockerfile
This fixes #607 to allow terraform to pull remote git modules
=> fix(docker): add git to docker image

infracost-usage-example.yml, internal/providers/terraform/aws/autoscaling_group.go, internal/providers/terraform/aws/autoscaling_group_test.go, internal/providers/terraform/aws/eks_node_group.go, internal/providers/terraform/aws/eks_node_group_test.go, internal/providers/terraform/aws/instance.go, internal/providers/terraform/aws/instance_test.go, internal/providers/terraform/aws/util.go
Issue #529 
Output examples:
```
Name                                                         Quantity  Unit            Monthly Cost 
aws_autoscaling_group.my_asg                                                                        
└─ aws_launch_configuration.lc1                                                                     
├─ Instance usage (Linux/UNIX, reserved, t3.medium)         10,950  hours                $285.80 
├─ EC2 detailed monitoring                                     105  metrics               $31.50 
├─ CPU credits                                       Cost depends on usage: $0.05 per vCPU-hours 
├─ root_block_device                                                                             
│  └─ Storage (general purpose SSD, gp2)                       150 …
```
=> feat(aws): add support for AWS EC2 RI prices

infracost-usage-example.yml, internal/providers/terraform/aws/autoscaling_group.go, internal/providers/terraform/aws/autoscaling_group_test.go, internal/providers/terraform/aws/docdb_cluster_instance.go, internal/providers/terraform/aws/docdb_cluster_instance_test.go, internal/providers/terraform/aws/eks_node_group.go, internal/providers/terraform/aws/eks_node_group_test.go, internal/providers/terraform/aws/instance.go, internal/providers/terraform/aws/instance_test.go, internal/providers/terraform/aws/rds_cluster_instance.go, internal/providers/terraform/aws/rds_cluster_instance_test.go
fixes #554 
Allows usage data to be provided for the following resources.
`aws_autoscaling_group` both `aws_launch_configurations` & `aws_launch_templates`
`aws_eks_node_group`
`aws_instance`
The following values can now be added to your usage file, to estimate EC2 CPU credit usage over a given month. 
```yaml
cpu_credit_hrs: 350 # Number of hours in the month where you expect to burst the instance
virtual_cpu_count: 2 # Number of vCPUs that the instance type as.
```
=> feat(aws): Refactored CPU credits to use usage file.

infracost-usage-example.yml, internal/providers/terraform/azure/mariadb_server.go, internal/providers/terraform/azure/mssql_database.go, internal/providers/terraform/azure/mssql_database_test.go, internal/providers/terraform/azure/mysql_server.go, internal/providers/terraform/azure/postgresql_server.go, internal/providers/terraform/azure/registry.go
Issue #569 
Output examples: 
```
With usage-file: 
Name                                          Quantity  Unit         Monthly Cost
azurerm_mssql_database.my_database                                                
├─ Compute (serverless, GP_S_Gen5_4)               600  vCore-hours       $313.05 
├─ Storage                                           5  GB-months           $0.57 
└─ Long-term retention                           1,000  GB-months          $50.00 
azurerm_mssql_database.my_database                                              
├─ Compute (provisioned, HS_Gen5_8)                730  hours           $1,066.73 
├─ Read replicas                                   730  hours           $1,066.73 
├─ SQL License                                   5,840  hours             $583.80 
└─ …
```
=> feat(azure): Add support for Azure MSSQL Database

scripts/ci/jenkins_diff.sh
The `jenkins_diff.sh` does relatively the same task as the other diff scripts, here is a list of changes:
* `path` variable is changed to `iac_path`
* Remove support for deprecated flags
* Remove `post_condition`
* Add `fail_condition` with the `percentage_threshold` field to fail the pipeline if the change is over the threshold
* Add a function to wrap the diff output in a simple HTML page
* Add few utility functions to make the script work with Jenkins
* Diff-output is always printed in the output
* Save the diff output HTML in a file for further use
Here's a sample `Jenkinsfile` config:
```Jenkinsfile
pipeline {
agent any
stages {
stage('infracost-breakdown') {
agent {
docker {
image 'infracost-local'
args '--user=root --entrypoint='
}
}
environment {
INFRACOST_API_KEY = …
```
=> feat: add jenkins support

internal/providers/terraform/azure/app_service_certificate_binding.go, internal/providers/terraform/azure/app_service_certificate_binding_test.go, internal/providers/terraform/azure/registry.go
Solves https://github.com/infracost/infracost/issues/596
**Objective:**
Add support for aws_docdb_cluster_instance.
**Example output without usage-file:**
```
Project: examples/terraform
Name                                                Quantity  Unit    Monthly Cost 
azurerm_app_service_certificate_binding.ipexample                                  
└─ IP SSL certificate                                      1  months        $39.00 
azurerm_app_service_certificate_binding.sniexample                                 
└─ IP SSL certificate                                      1  months         $9.00 
PROJECT TOTAL                                                               $48.00 
Example output with usage-file: N/A
```
**Pricing details:**
I updated the issue with a question: …
=> feat(azure): azurerm_app_service_certificate_binding

Makefile
=> fix(build): add .exe to windows binary

infracost-usage-example.yml, internal/providers/terraform/azure/key_vault_certificate.go, internal/providers/terraform/azure/key_vault_certificate_test.go, internal/providers/terraform/azure/key_vault_key.go, internal/providers/terraform/azure/key_vault_key_test.go, internal/providers/terraform/azure/key_vault_managed_hardware_security_module.go, internal/providers/terraform/azure/key_vault_managed_hardware_security_module_test.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/testdata/key_vault_certificate_test/key_vault_certificate_test.golden, internal/providers/terraform/azure/testdata/key_vault_certificate_test/key_vault_certificate_test.tf, internal/providers/terraform/azure/testdata/key_vault_certificate_test/key_vault_certificate_test.usage.yml, internal/providers/terraform/azure/testdata/key_vault_key_test/key_vault_key_test.golden, internal/providers/terraform/azure/testdata/key_vault_key_test/key_vault_key_test.tf, internal/providers/terraform/azure/testdata/key_vault_key_test/key_vault_key_test.usage.yml, internal/providers/terraform/azure/testdata/key_vault_managed_hardware_security_module_test/key_vault_managed_hardware_security_module_test.golden, internal/providers/terraform/azure/testdata/key_vault_managed_hardware_security_module_test/key_vault_managed_hardware_security_module_test.tf
Issue #647 
Links:
[Terraform](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_key)
[Pricing page](https://azure.microsoft.com/en-us/pricing/details/key-vault/)
Details:
About Managed HSM Pools - I think we should add resource [azurerm_key_vault_managed_hardware_security_module](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_managed_hardware_security_module) to cover it, but Terraform added it in v2.57.0 azurerm provider, but only v2.56 is available for now.
=> feat(azure): Add support for Azure Key Vault

internal/providers/terraform/azure/firewall.go, internal/providers/terraform/azure/testdata/firewall_test/firewall_test.golden, internal/providers/terraform/azure/testdata/firewall_test/firewall_test.tf, internal/providers/terraform/azure/testdata/firewall_test/firewall_test.usage.yml
Issue #672 
Details:
I compare `d.Get()` with empty array because defaulty exists empty array of virtual hub block: `"virtual_hub":[]` and it means that `d.Get("virtual_hub").Type` will never return `gjson.Null`
=> feat(azure): Add support for Azure Firewall with Secured Virtual Hub

infracost-usage-example.yml, internal/providers/terraform/aws/mq_broker.go, internal/providers/terraform/aws/testdata/mq_broker_test/mq_broker_test.golden, internal/providers/terraform/aws/testdata/mq_broker_test/mq_broker_test.tf
- Terraform string values are case-insensitive for most part, changed the
Regex lookups to be case-insensitive
- Simplified the logic and fix a bug that was causing a warning before “Multiple products found for aws_mq_broker.my_aws_mq_broker_activemq_single_standby_ebs Storage (ActiveMQ, EBS), using the first product”
=> fix(aws): fix a few issues in the Amazon MQ resource

internal/output/output.go
Issue #712 
```
9 resource types weren't estimated as they're not supported yet.
Please watch/star https://github.com/infracost/infracost as new resources are added regularly.
4 x azurerm_firewall
2 x azurerm_virtual_machine
1 x azurerm_cosmosdb_account
1 x azurerm_cosmosdb_cassandra_keyspace
1 x azurerm_cosmosdb_cassandra_table
1 x azurerm_network_interface
1 x azurerm_resource_group
1 x azurerm_subnet
1 x azurerm_virtual_network
```
=> fix(output): Added count-alphabet sort for skipped resources to avoid random output

infracost-usage-example.yml, internal/providers/terraform/aws/data_transfer.go, internal/providers/terraform/aws/testdata/data_transfer_test/data_transfer_test.golden, internal/providers/terraform/aws/testdata/data_transfer_test/data_transfer_test.usage.yml
Fix #713 
The changes can be divided into few sections:
Two regions `us-iso-east-1` and `us-isob-east-1` are totally missing in pricing API and amazon pages and I couldn't find much information for them. So I removed them.
One region's name was wrong which I assume might have changed recently. The `ap-northeast-3`'s name was changed from `Asia Pacific (Osaka-Local)` to `Asia Pacific (Osaka)`
As I understood, since data transfer to all regions seems to have the same price the default `us-west-1` is selected. It caused two problems:
1. When the region is `us-west-1` itself, we should query data output to some other region. I used `us-west-2`.
2. Chinese regions `cn-north-1` and `cn-northwest-1` have data transfer prices just between themselves.
The pricing is actually a stepped price (like …
=> fix(aws): data transfer costs

infracost-usage-example.yml, internal/providers/terraform/aws/rds_cluster.go, internal/providers/terraform/aws/testdata/rds_cluster_instance_test/rds_cluster_instance_test.golden, internal/providers/terraform/aws/testdata/rds_cluster_test/rds_cluster_test.golden
CR = change-record, where we calculate it as follows:
averageStatements.Mul(decimal.NewFromInt(730)).Mul(changeRecords).Mul(windowHours)
So I think it’s clearer if we remove the hours and call it “change-records” as we’re already taking into account the hours
=> fix(aws): remove hours from units as we already take that into account

internal/providers/terraform/azure/testdata/cosmosdb_cassandra_keyspace_test/cosmosdb_cassandra_keyspace_test.golden, internal/providers/terraform/azure/testdata/cosmosdb_cassandra_table_test/cosmosdb_cassandra_table_test.golden, internal/providers/terraform/azure/testdata/cosmosdb_gremlin_database_test/cosmosdb_gremlin_database_test.golden, internal/providers/terraform/azure/testdata/cosmosdb_gremlin_graph_test/cosmosdb_gremlin_graph_test.golden, internal/providers/terraform/azure/testdata/cosmosdb_mongo_collection_test/cosmosdb_mongo_collection_test.golden, internal/providers/terraform/azure/testdata/cosmosdb_mongo_database_test/cosmosdb_mongo_database_test.golden, internal/providers/terraform/azure/testdata/cosmosdb_sql_container_test/cosmosdb_sql_container_test.golden, internal/providers/terraform/azure/testdata/cosmosdb_sql_database_test/cosmosdb_sql_database_test.golden, internal/providers/terraform/azure/testdata/cosmosdb_table_test/cosmosdb_table_test.golden
Updated after price rounding merge. And it looks like Azure added support for continuous backups in `westus` region last night
=> fix(tests): Update Cosmos DB tests after merge

internal/providers/terraform/azure/linux_virtual_machine.go, internal/providers/terraform/azure/testdata/kubernetes_cluster_node_pool_test/kubernetes_cluster_node_pool_test.golden, internal/providers/terraform/azure/testdata/kubernetes_cluster_test/kubernetes_cluster_test.golden, internal/providers/terraform/azure/testdata/linux_virtual_machine_scale_set_test/linux_virtual_machine_scale_set_test.golden, internal/providers/terraform/azure/testdata/linux_virtual_machine_test/linux_virtual_machine_test.golden, internal/providers/terraform/azure/testdata/virtual_machine_scale_set_test/virtual_machine_scale_set_test.golden, internal/providers/terraform/azure/testdata/virtual_machine_test/virtual_machine_test.golden, internal/providers/terraform/azure/testdata/windows_virtual_machine_scale_set_test/windows_virtual_machine_scale_set_test.golden, internal/providers/terraform/azure/testdata/windows_virtual_machine_test/windows_virtual_machine_test.golden, internal/providers/terraform/azure/testdata/windows_virtual_machine_test/windows_virtual_machine_test.tf, internal/providers/terraform/azure/windows_virtual_machine.go
Terraform supports 396 different VM instance types but Azure's pricing data is missing prices for 4, I can understand promo ones missing prices but not sure why ND40s_v3 doesn’t have prices. We can create a GH issue if a user hits these and ask MS for help.
Standard_ND40s_v3
Standard_NV12_Promo
Standard_NV24_Promo
Standard_NV6_Promo
Fixes #756
=> fix(azure): use more robust filters

infracost-usage-example.yml, internal/providers/terraform/aws/testdata/waf_web_acl_test/waf_web_acl_test.tf, internal/providers/terraform/azure/function_app.go, internal/providers/terraform/azure/testdata/function_app_test/function_app_test.golden, internal/providers/terraform/azure/testdata/function_app_test/function_app_test.tf, internal/providers/terraform/azure/testdata/function_app_test/function_app_test.usage.yml
- Handle azurerm_app_service_plan being unavailable by falling back to
any available usage file params
- fix bug in gbSecond calculation
- fix bug in Executions cost calc as the Azure pricing API returns
the price per 10 units
Fixes #757
=> fix(azure): make Function pricing calcs more robust

CONTRIBUTING.md, internal/output/diff.go, internal/output/table.go
This was making it hard to read on some terminals and given it was the
most useful data we show for these lines, it seemed better to unfaint it.
before:
after:
=> feat(cli): don’t use faint colors for “cost depends on usage” lines

internal/providers/terraform/azure/storage_account.go, internal/providers/terraform/azure/testdata/storage_account_test/storage_account_test.golden, internal/providers/terraform/azure/testdata/storage_account_test/storage_account_test.tf
Issue #783 
The problem was because Azure removed `List Operations` cost component and added `Write Operations` for Hot RA-GRS (we used `List Operations` for it before as they costs are equals). And they did it for `eastus` region, which uses in tests. 
So, I did a little refactoring and now we using `westus` region - all of cost components exists for this location.
=> fix(azure): refactoring of Azure storage account test

scripts/ci/diff.sh
This is just an MVP. There’s a lot more we can do, e.g. add the repo URL and improve the formatting. Here's what the output looks like:
=> feat(ci): add MVP of posting a comment to Slack webhook URLs

CONTRIBUTING.md, internal/providers/terraform/azure/util.go
This makes it clear where the region is being checked from and in what order.
Otherwise, it’s easy to forget to including resource_group_name in ReferenceAttributes.
@tim775 / @aliscott any thoughts on this? It came up when I was reviewing https://github.com/infracost/infracost/pull/787/files and https://github.com/infracost/infracost/pull/789/files
=> chore: make the resource_group_name explicit

infracost-usage-example.yml, internal/providers/terraform/aws/backup_vault.go, internal/providers/terraform/aws/backup_vault_test.go, internal/providers/terraform/aws/registry.go, internal/providers/terraform/aws/testdata/backup_vault_test/backup_vault_test.golden, internal/providers/terraform/aws/testdata/backup_vault_test/backup_vault_test.tf, internal/providers/terraform/aws/testdata/backup_vault_test/backup_vault_test.usage.yml
Issue #344 
Details: 
- I didn't find cost component for `AWS Storage Gateway Volume Backup`, searched by services, prices - nothing. 
- Didn't add part with cross-region data transfer as we already have resource `aws_data_transfer` which cover all of that functionality
- I compared prices all of non-usage cost components (`Monthly cost depends on...`) from Golden file with [AWS Pricing page](https://aws.amazon.com/backup/pricing/), they are equals
=> feat(aws): Add support for AWS Backup resource

internal/usage/usage_file.go
Don't warn about the usage file not being specified unless the `--sync-usage-file` flag has also been specified.
Fixes #832
One thing I'd like to check is that the output when the `--sync-usage-file` flag is specified is a little verbose:
```shell
$ infracost breakdown --path plan.json --format=json --log-level=warn --sync-usage-file
Warning: Ignoring sync-usage-file as no usage-file is specified.
time="2021-06-25T16:33:25+01:00" level=warning msg="Can't sync usage file as it's not specified"
```
It's because there's an earlier check here: https://github.com/infracost/infracost/blob/87a41b5a32e85b065eb64d3d0564c39105cc2b6b/cmd/infracost/run.go#L279
Maybe the warning could just be removed completely? I just didn't want to do that without checking.
=> fix: don't warn about usage file if not syncing

scripts/ci/atlantis_diff.sh
This enables users to generate the plan JSON from the plan binary file
as part of their Atlantis config so Infracost doesn’t need to invoke
“terraform show”
Here's how this could be used in Atlantis configs, notice the manual `terraform show` step, which can be customized as needed based on which Terraform version or binary is being used:
```
workflows:
infracost:
plan:
steps:
- init
- plan
- env:
name: INFRACOST_API_KEY
command: echo "MY_API_KEY" 
- run: terraform show -no-color -json $PLANFILE > $PLANFILE.json 
- run: /home/atlantis/infracost_atlantis_diff.sh
- run: rm -rf $PLANFILE.json
```
This issue was reported in the [Atlantis community Slack](https://atlantis-community.slack.com/archives/C5MGGAV0C/p1624923969118900)
=> feat(Atlantis): check if $PLANFILE.json exist and use that first

scripts/ci/diff.sh
Otherwise Azure DevOps users need to set it manually
=> fix(ci): default the GH API URL

internal/providers/terraform/aws/testdata/vpc_endpoint_test/vpc_endpoint_test.golden, internal/providers/terraform/aws/testdata/vpc_endpoint_test/vpc_endpoint_test.tf, internal/providers/terraform/aws/testdata/vpc_endpoint_test/vpc_endpoint_test.usage.yml, internal/providers/terraform/aws/vpc_endpoint.go
This was detected by the integration test warnings on the master branch:
```
=== CONT  TestAwsStepFunctionGoldenFile
time="2021-07-13T10:26:25Z" level=warning msg="Multiple prices found for aws_vpc_endpoint.interface_withUsage Data processed, using the first price"
time="2021-07-13T10:26:25Z" level=warning msg="Multiple prices found for aws_vpc_endpoint.interface Data processed, using the first price"
time="2021-07-13T10:26:25Z" level=warning msg="Multiple prices found for aws_vpc_endpoint.multiple_interfaces Data processed, using the first price"
```
It was caused by this: https://aws.amazon.com/about-aws/whats-new/2021/07/aws-lowers-data-processing-charges-aws-privatelink/
I verified the prices by calculating the costs manually.
=> feat(aws): update aws_vpc_endpoint to use new pricing

cmd/infracost/register.go
Issue: https://github.com/infracost/infracost/issues/858
First Flow:
If the Key is not present:
1. We will prompt for name and email, generate the key and save it. 
Second Flow:
If the Key is present:
1. Ask the user `Would you like to generate a new one?` 
2. If no to 1, we exit. 
3. If yes to 1, we prompt for name, email, and generate the key and show them.
4. Then we prompt for `Would you like to overwrite your existing saved API key?`
5. If no to 4, we exit. 
6. If yes to 4, we save the new API key.
=> fix: register command

.env, cmd/infracost/configure.go, cmd/infracost/main.go, cmd/infracost/register.go, internal/config/config.go, internal/config/credentials.go, internal/config/migrate.go
This command allow you to configure Infracost CLI globally with an API key and pricing API endpoint (if self-hosting this).
Currently I've added it as the following commands:
```
infracost configure get <key>
infracost configure set <key> <value>
```
So you'd use it like:
```
infracost configure set pricing_api_endpoint http://self-hosted-pricing-api.internal
infracost configure set api_key MY_API_KEY
```
I was wondering if anyone has any thoughts/suggestions for what this command should be called? I considered calling it `infracost config` but was worried that would cause confusion with the `--config-file` flag which allows you to pass run configuration in.
=> feat: Add configure command

internal/providers/terraform/azure/active_directory_domain_service.go, internal/providers/terraform/azure/active_directory_domain_service_replica_set.go, internal/providers/terraform/azure/active_directory_domain_service_replica_set_test.go, internal/providers/terraform/azure/active_directory_domain_service_test.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/testdata/active_directory_domain_service_replica_set_test/active_directory_domain_service_replica_set_test.golden, internal/providers/terraform/azure/testdata/active_directory_domain_service_replica_set_test/active_directory_domain_service_replica_set_test.tf, internal/providers/terraform/azure/testdata/active_directory_domain_service_test/active_directory_domain_service_test.golden, internal/providers/terraform/azure/testdata/active_directory_domain_service_test/active_directory_domain_service_test.tf
**Objective:**
Add support for `azurerm_active_directory_domain_service`.
**Status:**
**Issues:**
Did not add support for `azurerm_active_directory_domain_service_replica_set` as I'd like to get some feedback before proceeding with it since this PR is the first I'm raising for infracost.
**Useful links:**
Pricing: https://azure.microsoft.com/en-us/pricing/details/active-directory-ds/
Terraform: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/active_directory_domain_service
=> feat(azure): add azurerm_active_directory_domain_service

cmd/infracost/output.go, cmd/infracost/run.go
Fixes #876 
Add`all` for the `--fields` argument, which causes the output to contain all the supported fileds: price, monthlyQuantity, unit, hourlyCost, monthlyCost.
**CLI command executed**
```sh
make run ARGS="breakdown --path examples/terraform --usage-file=examples/terraform/infracost-usage.yml --fields=all: 
```
**Output returned**
```
Name                                                           Price  Monthly Qty  Unit         Hourly Cost  Monthly Cost 
aws_instance.web_app                                                                                                      
├─ Instance usage (Linux/UNIX, on-demand, m5.4xlarge)          $0.77          730  hours              $0.77       $560.64 
├─ root_block_device …
```
=> feat(cli): Add 'all' option for fields argument

cmd/infracost/output.go, cmd/infracost/testdata/output_help/output_help.golden
Without this the glob pattern is expanded by shells so the CLI sees the first path as the flag value, followed by arguments (that are ignored)
Partly addresses https://github.com/infracost/infracost/issues/927
=> fix(cli): include quotes in help text

internal/providers/terraform/aws/fsx_windows_file_system.go
AWS have added support for NetAPP ONTAP to FSx which means multiple products were returned for our filters.
This filesystem isn't supported yet by Terraform (see https://github.com/hashicorp/terraform-provider-aws/issues/20778)
=> fix(aws): update filters to exclude non-Windows file systems

internal/providers/terraform/cmd.go
As discussed in #943.
Instead of hard failing if the user has a non-existent `TF_CLI_CONFIG_FILE` when trying to copy it to a temporary file, this logs a warning and will just create a new blank temporary file. @alikhajeh1 do you think there's any issues with this? I'm hesitant in case it hides an error the user would want to know about.
=> Warn on invalid TF_CLI_CONFIG_FILE instead of error

internal/providers/cloudformation/aws/dynamodb_table.go, internal/providers/terraform/aws/dynamodb_table.go, internal/providers/terraform/aws/lambda_function.go, internal/providers/terraform/aws/nat_gateway.go, internal/resources/aws/dynamodb_table.go, internal/resources/aws/dynamodb_table_estimate_test.go, internal/resources/aws/lambda_function.go, internal/resources/aws/lambda_function_estimate_test.go, internal/resources/aws/nat_gateway.go
I'm wondering if we should use struct methods for the generic resources by default, to avoid potential name clashes as we move over more resources to this format. Here's an example for the DynamoDB resource.
What do you think @tim775?
=> Proposal: use struct methods instead of functions for resources

internal/providers/terraform/parser.go, internal/providers/terraform/parser_test.go
Fix address parsing when the index part has a `.` in it, e.g `aws_instance.my_instance["index.1"]`. Also adds some more tests for the parser.
=> fix(terraform): fix address parsing

CONTRIBUTING.md, internal/providers/terraform/aws/testdata/waf_web_acl_test/waf_web_acl_test.golden, internal/providers/terraform/aws/testdata/waf_web_acl_test/waf_web_acl_test.tf, internal/providers/terraform/aws/testdata/waf_web_acl_test/waf_web_acl_test.usage.yml, internal/providers/terraform/aws/testdata/wafv2_web_acl_test/wafv2_web_acl_test.golden, internal/providers/terraform/aws/waf_web_acl.go, internal/providers/terraform/aws/wafv2_web_acl.go
Previously this was returning no matches for non-us-east-1 regions
Fixes #958
=> fix: don’t use hard-coded filters for us-east-1

.github/workflows/create-release.yml, .github/workflows/go.yml, Dockerfile, go.mod, go.sum
- bump to use go1.17
- `go mod tidy` to list indirect deps in `go.mod`
- update `golang.org/x/sys` for go1.17 runtime
=> build: bump to use go1.17

cmd/infracost/run.go
This is an intent to fix https://github.com/infracost/infracost/issues/884. 
The CLI errors if any of the project options (terraform-*, path, and usage-file) are used in conjunction with the --config-file flag independent of the use of environment variables or flags. 
This PR fixes another small bug:  Don't override terraform-workspace flag by ENV variable
- Old behavior: INFRACOST_TERRAFORM_WORKSPACE environment variable overrides --terraform-workspace flag
- New behavior: INFRACOST_TERRAFORM_WORKSPACE environment variable does not overrides --terraform-workspace flag
as mentioned in https://www.infracost.io/docs/multi_project/config_file#precedence.
Any feedback welcome.
=> 884 error on terraform env var with config file

internal/providers/terraform/dir_provider.go
This messes with Terragrunt detection and Terraform needs .tf files anyway.
=> fix: don't detect Terraform dir by looking for .hcl files.

infracost-usage-example.yml, internal/providers/terraform/aws/ebs_snapshot.go, internal/providers/terraform/aws/testdata/ebs_snapshot_copy_test/ebs_snapshot_copy_test.golden, internal/providers/terraform/aws/testdata/ebs_snapshot_test/ebs_snapshot_test.golden, internal/providers/terraform/aws/testdata/ebs_snapshot_test/ebs_snapshot_test.usage.yml
Objective: Fixes https://github.com/infracost/infracost/issues/940
Edit support for aws_ebs_snapshot,  added fast_snapshot_restore_hours as usage-based cost component.
Example output without usage-file:
```
Running "infracost breakdown --path ." against a main.tf with:
resource "aws_ebs_volume" "example" {
availability_zone = "us-west-2a"
size              = 40
tags = {
Name = "HelloWorld"
}
}
resource "aws_ebs_snapshot" "example_snapshot" {
volume_id = aws_ebs_volume.example.id
tags = {
Name = "HelloWorld_snap"
}
}
Name                                                            Monthly Qty  Unit                        Monthly Cost 
aws_ebs_snapshot.example_snapshot                                                                                     
├─ EBS snapshot storage …
```
=> feat(aws) edited aws_ebs_snapshot fast_snapshot_restore_hour optional

scripts/ci/diff.sh
PRs for the integrations, to go out once this is released:
* https://github.com/infracost/infracost-gh-action/pull/35
* https://github.com/infracost/infracost-orb/pull/16
* https://github.com/infracost/infracost-azure-devops/pull/7
=> Make update the default when posting to GitHub

scripts/ci/atlantis_diff.sh, scripts/ci/diff.sh, scripts/ci/jenkins_diff.sh
This adds a project table to the top of the PR comments for GitHub, GitLab and Azure Devops.
It has the following functionality:
* If there's only one project don't show the "All projects" line
* Doesn't show projects with no changes, instead it lists them below the table
* Truncates the middle of project names to limit them to 64 characters
This also updates the atlantis and jenkins diff scripts to keep them more inline with our standard diff script.
Once this is merged we can update the screenshots in the READMEs and docs.
See https://github.com/infracost/infracost/pull/1090 for previous work.
=> Add project list to top of PR comments

infracost-usage-example.yml, internal/providers/terraform/aws/registry.go, internal/providers/terraform/aws/testdata/transfer_server_test/transfer_server_test.golden, internal/providers/terraform/aws/testdata/transfer_server_test/transfer_server_test.tf, internal/providers/terraform/aws/testdata/transfer_server_test/transfer_server_test.usage.yml, internal/providers/terraform/aws/transfer_server.go, internal/providers/terraform/aws/transfer_server_test.go, internal/resources/aws/transfer_server.go
Add support for AWS Transfer Family resources.  Fixes #1030 
The main resource which contains cost components is `aws_transfer_server`:
- Supports 3 protocols `FTP`/`FTPS`/`SFTP`, each is billed hourly when enabled, if no protocols are defined the default is `FTPS`.
- Has 2 usage-based components for downloaded and uploaded data, measured in GB.
- Both S3 and EFS storage types have same pricing, however the Pricing API includes EFS prices only for SFTP protocol. For that reason the Infracost resource uses "S3" to match the prices.
- Pricing details: https://aws.amazon.com/aws-transfer-family/pricing/
None
=> feat(aws): Add AWS Transfer Family resources

cmd/infracost/testdata/output_format_github_comment/output_format_github_comment.golden, internal/output/markdown.go, scripts/ci/diff.sh
Should change depending on if we're using a symbol or currency code, e.g. `-$22.78` and `INR -22.78`. This also fixes displaying 2dp for all negative values, and adds thousands separators.
=> Fix diff symbol

internal/providers/terraform/plan_cache.go
This is useful when re-running the CLI to debug or do what-if analysis.
=> feat: increase TF plan cache from 10 to 30mins

infracost-usage-example.yml, internal/providers/terraform/azure/frontdoor.go, internal/providers/terraform/azure/frontdoor_firewall_policy.go, internal/providers/terraform/azure/frontdoor_firewall_policy_test.go, internal/providers/terraform/azure/frontdoor_test.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/testdata/frontdoor_firewall_policy_test/frontdoor_firewall_policy_test.golden, internal/providers/terraform/azure/testdata/frontdoor_firewall_policy_test/frontdoor_firewall_policy_test.tf, internal/providers/terraform/azure/testdata/frontdoor_firewall_policy_test/frontdoor_firewall_policy_test.usage.yml, internal/providers/terraform/azure/testdata/frontdoor_test/frontdoor_test.golden, internal/providers/terraform/azure/testdata/frontdoor_test/frontdoor_test.tf, internal/providers/terraform/azure/testdata/frontdoor_test/frontdoor_test.usage.yml, internal/resources/azure/frontdoor.go, internal/resources/azure/frontdoor_firewall_policy.go, internal/resources/azure/util.go
Add support for `azurerm_frontdoor` and `azurerm_frontdoor_firewall_policy`.  Fixes #909
- Azure has two Front Door services: "Standard" and newer "Standard/Premium (Preview)". This PR introduces the "Standard" one.
- Pricing for outbound data transfer depends on the region, in the Pricing API the regions are represented as zones (Zone 1 - Zone 5, US Gov Zone 1).
- Pricing API has 2 prices for Routing rules quantity. The item with `startUsage: 0` is free (for first 5 rules), however Azure's pricing page bills all the rules. Using the price with `startUsage: 5` instead.
None
=> feat(azure): add resources for Azure Front Door service

infracost-usage-example.yml, internal/providers/terraform/google/registry.go, internal/providers/terraform/google/secret_manager_secret.go, internal/providers/terraform/google/secret_manager_secret_test.go, internal/providers/terraform/google/secret_manager_secret_version.go, internal/providers/terraform/google/secret_manager_secret_version_test.go, internal/providers/terraform/google/testdata/secret_manager_secret_test/secret_manager_secret_test.golden, internal/providers/terraform/google/testdata/secret_manager_secret_test/secret_manager_secret_test.tf, internal/providers/terraform/google/testdata/secret_manager_secret_test/secret_manager_secret_test.usage.yml, internal/providers/terraform/google/testdata/secret_manager_secret_version_test/secret_manager_secret_version_test.golden, internal/providers/terraform/google/testdata/secret_manager_secret_version_test/secret_manager_secret_version_test.tf, internal/providers/terraform/google/testdata/secret_manager_secret_version_test/secret_manager_secret_version_test.usage.yml, internal/resources/google/secret_manager_secret.go, internal/resources/google/secret_manager_secret_version.go, internal/resources/google/util.go
Add support for Google Secret Manager resources.  Fixes #1023.
- Free Tier pricing is excluded.
- The cost of active secret versions depends on the number of replication locations. If it's more than one then the price is multiplied by the locations' quantity.
- Both enabled and disabled secret versions are treated as "active".
None
=> feat(google): add Google Secret Manager resources

examples/terragrunt/prod/terragrunt.hcl, internal/providers/terraform/terragrunt_provider.go
terragrunt run-all doesn't have consistent ordering, so this sorts the projects so our tests are consistent
=> Use consistent ordering for Terragrunt projects

internal/providers/cloudformation/aws/registry.go, internal/providers/terraform/aws/data_transfer.go, internal/providers/terraform/aws/registry.go, internal/providers/terraform/aws/testdata/data_transfer_test/data_transfer_test.golden, internal/resources/aws/data_transfer.go, internal/resources/aws/util.go
The previous fix to the golden file tried to resolve double products
found for `ap-southeast-1` region. First product has `APS1` prefix (correct)
and the second one has `APS4` (incorrect one). The fix worked until
the product results order returned `APS1` records first. But it was not
guaranteed. Mostly like it's an issue on AWS side.
Introducing an additional filter with the prefix should match exactly
the correct product. It might not work for regions that don't have such
prefix in `usagetype`.
=> chore(aws): fix double products for aws_data_transfer resource

cmd/infracost/breakdown_test.go, cmd/infracost/testdata/instance_with_attachment_after_deploy.json, cmd/infracost/testdata/instance_with_attachment_after_deploy/instance_with_attachment_after_deploy.golden, cmd/infracost/testdata/instance_with_attachment_before_deploy.json, cmd/infracost/testdata/instance_with_attachment_before_deploy/instance_with_attachment_before_deploy.golden, internal/providers/terraform/aws/instance.go, internal/schema/resource_data.go
This fixes an issue with an EC2 instance with an EBS attachment showing the cost for the volume twice, once under the instance, and once under the volume resource. This only happens after the instance has been deployed.
=> Instance with EBS attachment showing volume twice

CONTRIBUTING.md, cmd/infracost/testdata/breakdown_terraform_use_state_v0_12/breakdown_terraform_use_state_v0_12.golden, cmd/infracost/testdata/breakdown_terraform_use_state_v0_14/breakdown_terraform_use_state_v0_14.golden, cmd/infracost/testdata/breakdown_terraform_v0_12/breakdown_terraform_v0_12.golden, cmd/infracost/testdata/breakdown_terraform_v0_14/breakdown_terraform_v0_14.golden, cmd/infracost/testdata/diff_terraform_v0_12/diff_terraform_v0_12.golden, cmd/infracost/testdata/diff_terraform_v0_14/diff_terraform_v0_14.golden, infracost-usage-example.yml, internal/providers/terraform/aws/testdata/db_instance_test/db_instance_test.golden
The example file is used by the sync-usage-file feature so it’s important
that it remains uptodate
=>  fix: add missing resource to the usage file

infracost-usage-example.yml, internal/providers/terraform/azure/hdinsight_hadoop_cluster_test.go, internal/providers/terraform/azure/hdinsight_hbase_cluster_test.go, internal/providers/terraform/azure/hdinsight_interactive_query_cluster_test.go, internal/providers/terraform/azure/hdinsight_kafka_cluster_test.go, internal/providers/terraform/azure/hdinsight_spark_cluster_test.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/storage_account.go, internal/providers/terraform/azure/storage_account_test.go, internal/providers/terraform/azure/synapse_spark_pool_test.go, internal/providers/terraform/azure/synapse_sql_pool_test.go, internal/providers/terraform/azure/synapse_workspace_test.go, internal/providers/terraform/azure/testdata/function_app_test/function_app_test.golden, internal/providers/terraform/azure/testdata/hdinsight_hadoop_cluster_test/hdinsight_hadoop_cluster_test.golden, internal/providers/terraform/azure/testdata/hdinsight_hbase_cluster_test/hdinsight_hbase_cluster_test.golden, internal/providers/terraform/azure/testdata/hdinsight_interactive_query_cluster_test/hdinsight_interactive_query_cluster_test.golden, internal/providers/terraform/azure/testdata/hdinsight_kafka_cluster_test/hdinsight_kafka_cluster_test.golden, internal/providers/terraform/azure/testdata/hdinsight_spark_cluster_test/hdinsight_spark_cluster_test.golden, internal/providers/terraform/azure/testdata/private_endpoint_test/private_endpoint_test.golden, internal/providers/terraform/azure/testdata/storage_account_test/storage_account_test.golden, internal/providers/terraform/azure/testdata/storage_account_test/storage_account_test.tf, internal/providers/terraform/azure/testdata/storage_account_test/storage_account_test.usage.yml, internal/providers/terraform/azure/testdata/synapse_spark_pool_test/synapse_spark_pool_test.golden, internal/providers/terraform/azure/testdata/synapse_sql_pool_test/synapse_sql_pool_test.golden, internal/providers/terraform/azure/testdata/synapse_workspace_test/synapse_workspace_test.golden, internal/resources/azure/storage_account.go, internal/resources/azure/util.go
Add support for StorageV2 in `azurerm_storage_account`.  Fixes #951.
- Pricing differs when NFSv3 is enabled.
- Not all regions support GZRS and RA-GZRS redundancy types. Also some regions don't have pricing for redundancy types that are common everywhere else. More [info](https://docs.microsoft.com/en-us/azure/storage/common/storage-redundancy).
- For some regions Azure Pricing page can show prices that are not matched in Pricing API thus CLI won't show such cost components.
None
=> feat(azure): add StorageV2 support to Azure Storage Account

internal/providers/terraform/azure/testdata/function_app_test/function_app_test.golden, internal/providers/terraform/azure/testdata/hdinsight_hadoop_cluster_test/hdinsight_hadoop_cluster_test.golden, internal/providers/terraform/azure/testdata/hdinsight_hbase_cluster_test/hdinsight_hbase_cluster_test.golden, internal/providers/terraform/azure/testdata/hdinsight_interactive_query_cluster_test/hdinsight_interactive_query_cluster_test.golden, internal/providers/terraform/azure/testdata/hdinsight_kafka_cluster_test/hdinsight_kafka_cluster_test.golden, internal/providers/terraform/azure/testdata/hdinsight_spark_cluster_test/hdinsight_spark_cluster_test.golden, internal/providers/terraform/azure/testdata/postgresql_flexible_server_test/postgresql_flexible_server_test.golden, internal/providers/terraform/azure/testdata/storage_account_test/storage_account_test.golden, internal/providers/terraform/azure/testdata/synapse_spark_pool_test/synapse_spark_pool_test.golden, internal/providers/terraform/azure/testdata/synapse_sql_pool_test/synapse_sql_pool_test.golden, internal/providers/terraform/azure/testdata/synapse_workspace_test/synapse_workspace_test.golden, internal/resources/aws/s3_storage_class_helpers.go
There are currently 2 products with `Requests-Tier4` usagetype: one for
Glacier and one for Standard. Glacier related product records have values
in `operation` attribute, but it is an empty string for Standard
storage. The `operation` regex with empty string returned both products.
SQL query for pricing:
```sql
select 
attributes->>'usagetype' as usagetype
, attributes->>'operation' as operation
, region
, prices
, *
from products 
where "vendorName" = 'aws' 
and service = 'AmazonS3' 
and region = 'us-east-1' 
and attributes->>'usagetype' = 'Requests-Tier4'
order by 
attributes->>'usagetype'
```
From Azure announcement: https://techcommunity.microsoft.com/t5/azure-database-for-postgresql/azure-database-for-postgresql-flexible-server-is-now-ga/ba-p/2987030
> As of December 1st, 2021, the …
=> fix: Update pricing for AWS/Azure resources

cmd/infracost/breakdown_test.go, cmd/infracost/diff_test.go, cmd/infracost/testdata/breakdown_with_target/breakdown_with_target.golden, cmd/infracost/testdata/diff_with_target/diff_with_target.golden, cmd/infracost/testdata/plan_with_target.json, internal/providers/terraform/parser.go
This fixes https://github.com/infracost/infracost/issues/1152.
When `infracost diff` or `infracost breakdown` is run on a plan that has been generated with `-target`, we now only show the resources matching the target.
@alikhajeh1 the issue you had when reproducing this is related to: https://github.com/hashicorp/terraform/issues/23297. Basically, if the provider version has been updated since the last time the state was refreshed, this error can occur. The fix is to run `terraform refresh` first. We should consider adding a custom error wrapper for this case, but I've left it out of this PR for now.
=> fix: fix diff showing all resources when `-target` is used with Terrarform.

internal/providers/terraform/aws/autoscaling_group.go, internal/providers/terraform/aws/testdata/autoscaling_group_test/autoscaling_group_test.golden, internal/providers/terraform/aws/testdata/autoscaling_group_test/autoscaling_group_test.tf, internal/providers/terraform/parser.go, internal/resources/aws/launch_configuration.go, internal/resources/aws/launch_template.go
This fixes the https://registry.terraform.io/modules/HDE/autoscaling/aws/latest module not showing any results when it creates a launch configuration or launch template. It does this by adding special mappings for those cases.
This also fixes the case if the `desired_capacity` attribute is missing by using a default instance count of 1, so we still show a result for this case. The alternative is setting nil quantity values in this case so we show the `Monthly cost depends on usage` message, but this seemed clearer to me.
Fixes https://github.com/infracost/infracost/issues/1180.
=> Fix ASG module when creating launch configuration/template

internal/config/config.go, internal/providers/terraform/cmd.go, internal/providers/terraform/terragrunt_provider.go
@aliscott This includes the `--terraform-plan-flags` when running terragrunt info-all AND when running terraform init.  I'm not sure about using them during init, maybe we should only do that when it is a terragrunt init?
=> fix: use --terraform-plan-flags during init and info

internal/providers/terraform/aws/testdata/transfer_server_test/transfer_server_test.golden, internal/providers/terraform/aws/transfer_server.go, internal/providers/terraform/azure/postgresql_flexible_server.go, internal/resources/aws/transfer_server.go
Found a bug in my code while writing a new contributing code. According to TF registry the default protocol should be `SFTP`: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transfer_server#protocols.
I've also refactored the cost components to be the same as in the guide. We're pushing to have the same style across resources, so I decided it will be a good reference.
=> fix(aws): Fix aws_transfer_server default protocol

internal/providers/terraform/aws/testdata/dynamodb_table_test/dynamodb_table_test.tf, internal/resources/aws/dynamodb_table.go
The previous fix applied to us-east-1 region only, other regions include
region's abbreviation in `usagetype`, for example `USE2-TimedStorage-ByteHrs`.
The fix makes sure to match this, but not `USE2-IA-TimedStorage-ByteHrs`.
Fixes #1194.
=> fix(aws): update usage type filter for AWS DynamoDB Table resource

cmd/infracost/output.go, cmd/infracost/output_test.go, cmd/infracost/testdata/output_format_git_hub_comment/output_format_git_hub_comment.golden, cmd/infracost/testdata/output_format_git_hub_comment_multiple_skipped/output_format_git_hub_comment_multiple_skipped.golden, cmd/infracost/testdata/output_format_git_hub_comment_no_change/output_format_git_hub_comment_no_change.golden, cmd/infracost/testdata/output_format_git_lab_comment/output_format_git_lab_comment.golden, cmd/infracost/testdata/output_format_git_lab_comment_multiple_skipped/output_format_git_lab_comment_multiple_skipped.golden, cmd/infracost/testdata/output_format_git_lab_comment_no_change/output_format_git_lab_comment_no_change.golden, cmd/infracost/testdata/output_help/output_help.golden, internal/providers/terraform/azure/testdata/express_route_connection_test/express_route_connection_test.tf, internal/providers/terraform/azure/testdata/express_route_gateway_test/express_route_gateway_test.tf, internal/providers/terraform/azure/testdata/point_to_site_vpn_gateway_test/point_to_site_vpn_gateway_test.tf, internal/providers/terraform/azure/testdata/virtual_hub_test/virtual_hub_test.tf, internal/providers/terraform/azure/testdata/vpn_gateway_connection_test/vpn_gateway_connection_test.tf, internal/providers/terraform/azure/testdata/vpn_gateway_test/vpn_gateway_test.tf, internal/providers/terraform/dir_provider.go
Initially this is the same as the GitHub one, but we can update it in the future to use some more GitLab specific markdown features.
=> Add GitLab comment output format

infracost-usage-example.yml, internal/providers/terraform/google/artifact_registry_repository.go, internal/providers/terraform/google/artifact_registry_repository_test.go, internal/providers/terraform/google/registry.go, internal/providers/terraform/google/testdata/artifact_registry_repository_test/artifact_registry_repository_test.golden, internal/providers/terraform/google/testdata/artifact_registry_repository_test/artifact_registry_repository_test.tf, internal/providers/terraform/google/testdata/artifact_registry_repository_test/artifact_registry_repository_test.usage.yml, internal/resources/google/artifact_registry_repository.go, internal/resources/google/util.go
Add support for Google Artifact Registry Repository 
Pricing details can be found here: https://cloud.google.com/artifact-registry/pricing and is broken down into:
**Storage costs:**
priced at $0.10 a month after artifact registry usage is > 0.5 GB. We ignore the free tier as there is no way to currently tell if other artifact registry resources have gone beyond this free usage tier.
**Network costs:**
1. free within the same region
2. free from multi-region to a region within the same continent, e.g. europe -> europe-west1
3. $0.01 when between different regions in North America continent
4. $0.02 when between different regions in Europe continent
5. $0.05 when between different regions in AsiaPacific continent
6. $0.15 when between any region and Oceania continent
7. $0.08 for all other …
=> feat(google): add artifact registry repository

contributing/add_new_resource_guide.md
Adds helper appendix to adding new resource docs to make sure developers know to use the shared `RegionsUsage` struct. This means we only have one place to maintain region keys and it's easier for contributors to get up and running.
=> docs: add region usage appendix

infracost-usage-example.yml, internal/providers/terraform/aws/cloudtrail.go, internal/providers/terraform/aws/cloudtrail_test.go, internal/providers/terraform/aws/registry.go, internal/providers/terraform/aws/testdata/cloudtrail_test/cloudtrail_test.golden, internal/providers/terraform/aws/testdata/cloudtrail_test/cloudtrail_test.tf, internal/providers/terraform/aws/testdata/cloudtrail_test/cloudtrail_test.usage.yml, internal/providers/terraform/azure/testdata/storage_account_test/storage_account_test.golden, internal/resources/aws/cloudtrail.go, internal/resources/aws/util.go
Add support for aws cloudtrail, Fixes #1038
1. Additional Management events delivered to S3, charged at $2.00 per 100k management events delivered. Management events are normally priced as free, however if a user specifies an additional replication of events this is charged. We only show this cost therefore if Cloudtrail.IncludeManagementEvents is set.
2. Data events delivered to S3, charged at $0.10 per 100k events delivered.
3. CloudTrail Insights, charged at $0.35 per 100k events analyzed. This again is configured optionally on a Cloudtrail instance. Hence, we only include the cost component if Cloudtrail.IncludeInsightEvents.
All gravy
=> feat(aws): add aws cloudtrail resource

internal/providers/terraform/azure/testdata/storage_account_test/storage_account_test.golden, internal/providers/terraform/azure/testdata/storage_account_test/storage_account_test.tf
Azure pricing records for Hot LRS operations are identical apart from
meterName. CPAPI calculates productHashes not including the meterName
attribute thus different operations may be overriden by each other
during update jobs. Disabling the Hot LRS example unblocks CLI's CI
while we can come up with a solution.
=> chore(azure): disable Hot LRS example for Azure StorageV2 account resource

cmd/infracost/output.go, cmd/infracost/run.go, internal/apiclient/client.go, internal/apiclient/dashboard.go, internal/apiclient/errors.go, internal/apiclient/pricing.go, internal/config/run_context.go, internal/prices/prices.go, internal/providers/terraform/tftest/tftest.go
* Adds uuid to run context which is populated to ApiClient
* Remove `X-Trace-Id` header which was unused and replace with `X-Infracost-Trace-Id` populated with run context uuid
See https://github.com/infracost/cloud-pricing-api/pull/137 for pricing api implementation
See https://github.com/infracost/dashboard/pull/26 for dashboard implementation
=> feat: add run uuid to cli

cmd/infracost/run.go, internal/apiclient/dashboard.go, internal/output/output.go, schema/infracost.schema.json
With self-hosted Cloud Pricing API the request to Infracost Dashboard
will not be authenticated.
Related to #1212.
=> fix: do not send run results to Dashboard when using self-hosted CPAPI

internal/providers/terraform/aws/elasticache_replication_group.go
Fixes: https://github.com/infracost/infracost/issues/1213
Solves issue where terraform state was causing resources to have no price change in `infracost diff` due to `cluster_mode` block addition.
=> fix(aws): solve cluster_mode inconsistency with terraform state

internal/resources/aws/util.go
Adds new `Asia Pacific (Jakarta)` region to shared usage structs so they are available in usage files. Solves missing resource alert.
=> feat(aws): add ap-southeast-3 region to shared usage

cmd/infracost/output.go, cmd/infracost/output_test.go, cmd/infracost/testdata/output_format_azure_repos_comment/output_format_azure_repos_comment.golden, cmd/infracost/testdata/output_format_azure_repos_comment_multiple_skipped/output_format_azure_repos_comment_multiple_skipped.golden, cmd/infracost/testdata/output_format_azure_repos_comment_no_change/output_format_azure_repos_comment_no_change.golden, cmd/infracost/testdata/output_help/output_help.golden, scripts/ci/comment.sh
Adds `azure-repos-comment` output, which closes #1208
I've tested the markdown output on azure repos and it works 👌 , see below:
=> feat(azure): add azure-repos-comment output

cmd/infracost/run.go
This makes the indenation on the "Calculating monthly cost estimate" spinner consistent with the other spinner lines.  It looks like they have been inconsistent for a while, but recent changes removed the blank line so it is now more apparent.
Old:
```
Detected Terraform directory at ./examples/terraform
✔ Checking for cached plan... found
✔ Calculating monthly cost estimate 
```
With this fix:
```
Detected Terraform directory at ./examples/terraform
✔ Checking for cached plan... found
✔ Calculating monthly cost estimate 
```
=> fix: Indent the "Calculating monthly cost estimate" spinner

.github/workflows/create-release.yml
I tested this logic on a temp tag I created with an action here: https://github.com/infracost/infracost/runs/4701823103?check_suite_focus=true
=> Fix CI Dockerfile pushing to ci-latest instead of latest

cmd/infracost/breakdown_test.go, cmd/infracost/cmd_test.go, cmd/infracost/run.go, cmd/infracost/testdata/breakdown_terragrunt_with_dashboard_enabled/breakdown_terragrunt_with_dashboard_enabled.golden
fixes #1281
* Solves issue where enable dashboard with a terragrunt run caused fatal panic. This was due to the project ctx not mapping 1-1 with the output projects. This PR solves this by creating same length `projectContexts` as output `projects`.
* Adds goldenfile coverage for dashboard enabled
=> fix: solve range panic with terragrunt due to mismatch in project ctx

internal/providers/terraform/azure/linux_virtual_machine.go, internal/providers/terraform/azure/windows_virtual_machine.go, internal/providers/terraform/parser.go
Fixes the case here: https://github.com/infracost/infracost/issues/1298
In the Azure API instance types 'Standard_DS1_v2' and 'DS1_v2' are equivalent. But in the pricing database they are stored in the 'Standard_DS1_v2' format. This makes sure we are able to get prices for both formats.
Also removes the log `Falling back to default region (eastus)` for Azure resources, since they mostly use a different method for finding their region and do so at a resource level.
=> Fix Azure VM instance type prefixes

.github/workflows/create-release.yml, .github/workflows/update-download-redirects.yml
@aliscott This is the GH action method of udpating the release redirects which would require add IAM permissions to use amplify update-app.  I think it's the way to go, but I looked into doing this in the amplify pipeline and it is possible by adding something like this to the build script:
```
postBuild:
commands:
- | 
latestCLI=$(curl -s https://github.com/infracost/infracost/releases/latest/download/infracost-linux-amd64.tar.gz | pcregrep -o1 'https://github.com/infracost/infracost/releases/download/(v\d+\.\d+\.\d+)/infracost-linux-amd64.tar.gz')
majorMinor=$(echo $latestCLI | pcregrep -o1 '(v\d+\.\d+)\.\d+')
updatedRules=$(aws amplify get-app --app-id $AMPLIFY_ID | \
jq -r '.app.customRules |
del( .[] | select( .source == "/downloads/'$majorMinor'/<*>" ) ) |
. += [{ "source": …
```
=> feat: Add gh action to update download redirects on release

cmd/infracost/comment.go, cmd/infracost/comment_azure_repos.go, cmd/infracost/comment_github.go, cmd/infracost/comment_gitlab.go, cmd/infracost/testdata/comment/comment.golden, cmd/infracost/testdata/comment_azure_repos_help/comment_azure_repos_help.golden, cmd/infracost/testdata/comment_git_hub_help/comment_git_hub_help.golden, cmd/infracost/testdata/comment_git_lab_help/comment_git_lab_help.golden, cmd/infracost/testdata/comment_help/comment_help.golden
@vdmgolub can you please review this? This keeps the style of our help texts the same as previous commands. 
I included update behavior in the top-level comment help so it's clear there is an option for it, but I left it out in the sub-command as that help text shows that it's the default.
If you're ok with these, can you please update the golden files and merge?
=> docs: simplify help texts

cmd/infracost/testdata/comment_azure_repos_pull_request/comment_azure_repos_pull_request.golden, cmd/infracost/testdata/comment_git_hub_commit/comment_git_hub_commit.golden, cmd/infracost/testdata/comment_git_hub_pull_request/comment_git_hub_pull_request.golden, cmd/infracost/testdata/comment_git_lab_commit/comment_git_lab_commit.golden, cmd/infracost/testdata/comment_git_lab_merge_request/comment_git_lab_merge_request.golden, internal/output/templates.go
GitLab doesn't unescape the double quotes thus not showing the Yes/No
URLs correctly. Removing the escaping fixed it. GitHub/Azure Repos
worked well too.
GitLab: https://gitlab.com/infracost/gitlab-ci-demo/-/merge_requests/23#note_827909510
GitHub: https://github.com/vdmgolub/infracost-test/pull/6#issuecomment-1026800345
Azure Repos: last comment https://dev.azure.com/infracost/base/_git/azure-devops-repo-demo/pullrequest/65
=> fix: Remove double quotes escaping from feedback urls in comment templates

internal/hcl/block.go, internal/hcl/evaluator.go
fixes golden file tests for a number of resources that use `resource.my_resource.id` and then Infracost looks up a reference based on this `id`
=> fix: add in hcl only identifiers so that resources can reference 

internal/hcl/attribute.go, internal/hcl/reference.go, internal/providers/terraform/hcl_provider.go
1. Fixes test/parsing so that HCL blocks are marshalled recursively. This solves Infracost lookup on resources that have many nested blocks. e.g. `aws_cloudfront_distribution`, where Infracost needs to fetch `origin_shield.enabled`/`origin_shield_region`
```
resource "aws_cloudfront_distribution" "s3_distribution_0_with_shield" {
origin {
domain_name = aws_s3_bucket.b.bucket_regional_domain_name
origin_id   = local.s3_origin_id
...
origin_shield {
enabled              = true
origin_shield_region = "sa-east-1"
}
}
enabled             = true
...  
}
```
2. Fixes issue where attributes referenced which were non `id` based, e.g. name, were not being evaluated correctly. We now add the `expressions` into the HCL plan JSON output so Infracost can lookup attributes based on this. e.g.:
``` …
```
=> fix: recursive block evaluation in output

cmd/infracost/comment.go, cmd/infracost/comment_azure_repos.go, cmd/infracost/comment_github.go, cmd/infracost/comment_gitlab.go, cmd/infracost/output.go
If Dashboard support is enabled the `comment` command will combine the
provided reports and send them to Infracost Dashboard similar to
`output` command's behavior.
=> chore: Generate share links for comment command

internal/providers/terraform/aws/cloudtrail.go, internal/providers/terraform/aws/kinesis_firehose_delivery_stream.go, internal/providers/terraform/aws/neptune_cluster_snapshot.go, internal/providers/terraform/aws/rds_cluster.go, internal/providers/terraform/aws/transfer_server.go, internal/providers/terraform/azure/firewall.go, internal/providers/terraform/azure/util.go, internal/providers/terraform/azure/vpn_gateway.go, internal/providers/terraform/google/container_node_pool.go, internal/providers/terraform/hcl_provider.go, internal/schema/resource_data.go
* add top provider region information to HCL output so that prices reflect both top level provider and aliased providers
* remove "count" attribute from output which was causing duplication of prices
* add defaults to a number of resources so that the HCL output is in line with what the Terraform schema displays in docs.
* changes the method for azure `location` retrieval to format the strings as they are returned from the azure provider
---
With these changes only one test is failing across all the provider golden files (`aws_autoscaling_group`) 🍾
=> fix: provider region specification and provide sane defaults

cmd/infracost/register.go, internal/apiclient/dashboard.go
Adds extra step in register for both regenerating and new users:
**First time registering - answers Y**
**First time registering  - answers N**
**Reregistering, says Y to API key then answers Y to docs**
**Reregistering, says N to API key then answers Y to docs**
=> chore: change register prompts

internal/resources/aws/data_transfer.go
AWS now shows IntraRegion data transfer with two usage types "<regioncode>-DataTransfer-xAZ-Out-Bytes" and "<regioncode>-DataTransfer-Regional-Bytes"
=> fix: Update AWS data transfer filters to match pricing data changes.

infracost-usage-example.yml, internal/providers/terraform/azure/log_analytics_workspace.go, internal/providers/terraform/azure/log_analytics_workspace_test.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/testdata/log_analytics_workspace_test/log_analytics_workspace_test.golden, internal/providers/terraform/azure/testdata/log_analytics_workspace_test/log_analytics_workspace_test.tf, internal/providers/terraform/azure/testdata/log_analytics_workspace_test/log_analytics_workspace_test.usage.yml, internal/resources/azure/log_analytics_workspace.go
Add support for azurerm_log_analytics_workspace . Fixes #1258
1. Log data ingestion, which can be either:
a) Pay-as-you-go, which is only valid for a sku of `PerGB2018` and uses a usage param
b) Billed per commitment tiers, which is only valid for a sku of `CapacityReservation`
2. Log retention, which is free up to 31 days and then is billed for each additional GB retained after the free tier.
3. Data export, which is billed per monthly GB exported and is defined from a usage param.
Outside the above rules - if the workspace has sku of Free we return as a free resource & if the workspace sku
is in a list of unsupported skus then we mark as skipped with a warning.
I have left out `azurerm_log_analytics_cluster` inline with the reasoning outlined here: …
=> feat: add azure log analytics workspace

cmd/infracost/breakdown_test.go, cmd/infracost/cmd_test.go, cmd/infracost/run.go, cmd/infracost/testdata/breakdown_terraform_directory_with_hclvar_flags/breakdown_terraform_directory_with_hclvar_flags.golden, cmd/infracost/testdata/breakdown_terraform_directory_with_vars/breakdown_terraform_directory_with_vars.golden, examples/terraformwithvars/blocks.auto.tfvars, examples/terraformwithvars/infracost-usage.yml, examples/terraformwithvars/input.tfvars, examples/terraformwithvars/main.tf, examples/terraformwithvars/terraform.tfvars, examples/terraformwithvars/volume-type.auto.tfvars, internal/config/config.go, internal/hcl/parser.go, internal/providers/terraform/hcl_provider.go
Adds variable file and flag support for hcl, through:
* parsing `terraform-plan-flags`
* `var` and `var-file` flags
* parsing default `terraform.tfvars` file and `.auto.tfvars` files
=> feat: add hcl variable inputs from terraform plan flags

.github/workflows/create-release.yml, Makefile, scripts/install.sh
Adds checksums to release artefacts.
We then recommend users check these as part of install process, as outlined here: https://github.com/infracost/docs/pull/161
=> feat: add sha checksum to binaries

cmd/infracost/breakdown_test.go, cmd/infracost/configure.go, cmd/infracost/run.go, cmd/infracost/run_test.go, internal/config/config.go, internal/config/configuration.go, internal/config/project_context.go
Adds HCL support for parallel running if the provider is `DirProvider`. 
* add various reporting metrics to allow for comparison of approaches. (timings of load resources, percentage difference)
* add configuration property to disable parallel running if needed
=> feat: add parallel running of hcl provider in breakdown

cmd/infracost/cmd_test.go, cmd/infracost/main.go, cmd/infracost/output.go, cmd/infracost/run.go, cmd/infracost/testdata/breakdown_terraform_out_file_html/breakdown_terraform_out_file_html.golden, cmd/infracost/testdata/breakdown_terraform_out_file_json/breakdown_terraform_out_file_json.golden, cmd/infracost/testdata/breakdown_terraform_out_file_table/breakdown_terraform_out_file_table.golden, cmd/infracost/testdata/diff_terraform_out_file/diff_terraform_out_file.golden, cmd/infracost/testdata/output_terraform_out_file_html/output_terraform_out_file_html.golden, cmd/infracost/testdata/output_terraform_out_file_json/output_terraform_out_file_json.golden, cmd/infracost/testdata/output_terraform_out_file_table/output_terraform_out_file_table.golden
We shouldn't output this to the stderr if the user has specified a log level. Instead we should log it as an info level log.
=> Log out-file message if log-level is set

cmd/infracost/register.go, internal/ui/promts.go
The prompt libraries like promptui or survey produce double output on Windows.
Using simple prompts solves the issue, but doesn't alter experience for
Linux/macOS users.
Fixes #924 and #1265.
=> fix: Use simple prompts for register commands on Windows

internal/providers/terraform/google/compute_instance.go
For `n2d-highcpu-2` machine type it returned two prices for
`n2d-highcpu-2` and `n2d-highcpu-224`. Setting line begin/end in the
regex solves incorrect match.
Fixes #1392.
=> fix: Update filter for google_container_node_pool resource

.github/workflows/create-release.yml
Adds  `update-choco-version` job that triggers the workflow defined in `chocolatey-packages`. Relevant PR here: https://github.com/infracost/chocolatey-packages/pull/1
=> feat: on release trigger chocolatey-packages workflow

cmd/infracost/testdata/comment_bitbucket_commit/comment_bitbucket_commit.golden, cmd/infracost/testdata/comment_bitbucket_pull_request/comment_bitbucket_pull_request.golden, internal/output/markdown.go, internal/output/slack_message.go, internal/output/templates.go
This template is designed to be the basic version of the output and
currently emojis can break with some database backends in Bitbucket
Server so removing the emoji from this template.
This would close #1396
=> Remove emoji from basic Markdown template.

cmd/infracost/run.go, cmd/infracost/run_test.go
Adds reporting data if tf_var env is found when using hcl. This can help us understand potential discrepancies between hcl and tf runs.
=> chore: report if tf_var is set if running hcl

internal/hcl/attribute.go, internal/hcl/block.go, internal/hcl/evaluator.go
* Removes attribute evaluation messages caused by partial context at time of evaluation
* Adds verbose env var `INFRACOST_HCL_DEBUG_VERBOSE` that can show these messages, as this could help us track a bug down in the future
* Change context evaluation log message to be more clear
* Changes fake "arn" attribute on hcl resources to be the format AWS defines so we skip the : `Unexpected ARN format` debug line
=> fix: cleanup hcl debug for verbose messages

cmd/infracost/run.go, internal/hcl/modules/cache.go, internal/hcl/modules/cache_test.go, internal/hcl/modules/fetch.go, internal/hcl/modules/loader.go, internal/hcl/modules/loader_test.go, internal/hcl/parser.go
@aliscott I briefly tested this before running into the the module loader bugs that we discussed. Might need another test locally to make sure though.
=> fix: load manifest from .terraform if exists

cmd/infracost/run.go, internal/output/output.go, internal/ui/strings.go
Colored links have poor readability in terminals that don't support high
contrast colors.
Black background:
White background:
Windows Command Prompt:
With `--no-color` flag:
=> chore: Change styling of output URLs

internal/providers/terraform/aws/elasticache_replication_group.go, internal/providers/terraform/aws/testdata/elasticache_replication_group_test/elasticache_replication_group_test.golden, internal/providers/terraform/aws/testdata/elasticache_replication_group_test/elasticache_replication_group_test.tf, internal/providers/terraform/aws/testdata/elasticache_replication_group_test/elasticache_replication_group_test.usage.yml, internal/resources/aws/elasticache_cluster.go, internal/resources/aws/elasticache_replication_group.go
The first commit adds support for renamed terraform attributes related to the number of shards/replicas.  The second commit adds app autoscaling support.
=> feat: Add application autoscaling support for ElastiCache replication groups

cmd/infracost/comment.go, cmd/infracost/comment_azure_repos.go, cmd/infracost/comment_bitbucket.go, cmd/infracost/comment_github.go, cmd/infracost/comment_gitlab.go
Current behavior when the flag is followed by other flags:
```bash
Error: invalid argument "--bitbucket-token" for "--pull-request" flag: strconv.ParseInt: parsing "--bitbucket-token": invalid syntax
exit status 1
make: *** [run] Error 1
```
The updated error:
```bash
Error: invalid argument "--bitbucket-token" for "--pull-request" flag: must be integer
exit status 1
make: *** [run] Error 1
```
When the flag goes last (current behavior with or without the fix):
```bash
Error: flag needs an argument: --pull-request
exit status 1
make: *** [run] Error 1
```
=> fix: Validate PR/MR number in comment commands

Dockerfile, Dockerfile.ci
Current version: https://alpine.pkgs.org/3.15/alpine-main-aarch64/jq-1.6-r1.apk.html
Vulnerability: https://nvd.nist.gov/vuln/detail/CVE-2016-4074
=> chore: Install jq-1.6 in Dockerfile.ci

internal/providers/terraform/azure/app_service_plan.go, internal/providers/terraform/azure/testdata/app_service_plan_test/app_service_plan_test.golden, internal/providers/terraform/azure/testdata/app_service_plan_test/app_service_plan_test.tf
`capacity` is an optional argument. If not specified the resource is not
estimated. The pricing calculator starts with 1 instances, thus we
assume the default capacity would be 1 as well.
Fixes #1384 and #1433.
=> feat(azure): Set default capacity for Azure App Service Plan

infracost-usage-example.yml, internal/providers/terraform/aws/elastic_beanstalk_environment.go, internal/providers/terraform/aws/elastic_beanstalk_environment_test.go, internal/providers/terraform/aws/registry.go, internal/providers/terraform/aws/testdata/elastic_beanstalk_environment_test/elastic_beanstalk_environment_test.golden, internal/providers/terraform/aws/testdata/elastic_beanstalk_environment_test/elastic_beanstalk_environment_test.tf, internal/providers/terraform/aws/testdata/elastic_beanstalk_environment_test/elastic_beanstalk_environment_test.usage.yml, internal/resources/aws/elastic_beanstalk_environment.go
Add support for `aws_elastic_beanstalk_environment` and `aws_elastic_beanstalk_application` as FREE. Fixes #1410.
Price breakdown for elastic beanstalk environments is ec2 instances associated with the environment multiplied by the minimum ASG numbers.
Additional costs are associated for the load balancer type. If StreamLogs is enabled, there can be usage costs for cloudwatch metrics, including ingest, scanning and storage in GB.
None
=> feat(aws): add elastic beanstalk environment

internal/comment/azure_repos.go, internal/comment/bitbucket.go, internal/update/update.go
If request fails the response body may not contain a proper JSON object
thus the unmarshaling error message may be confusing for users.
Example of response:
```
Error: Error getting comments: 401 Unauthorized
```
=> fix: Check status of API requests before unmarshaling response body

.github/workflows/create-release.yml, tools/release/main.go
Changes release workflow to use GO script in the repository. Tested and working as per this release https://github.com/hugorut/infracost/releases/tag/v0.9.24 (on personal fork)
* side note - i've introduced a `tools` directory with this, where I think we should move some of the codegen and other standalone go scripts so they don't pollute the main binary
=> feat: change release workflow to use internal script

.golangci.yml, cmd/infracost/comment.go
Solves issue if a valid policy file type is provided in `--policy-path` but the contents is malformed.
=> fix: panic error if policy body is invalid

internal/providers/terraform/google/sql_database_instance.go, internal/providers/terraform/google/testdata/sql_database_instance_test/sql_database_instance_test.golden, internal/providers/terraform/google/testdata/sql_database_instance_test/sql_database_instance_test.tf
* When state was applied `replica_configuration` was set to an empty value, so this was adding a subresource for the replica when it shouldn't have been
* A public v4 IP is added to the DB instances by default
=> fix: Google SQL Database Instance default values

internal/providers/terraform/google/container_cluster.go, internal/providers/terraform/google/util.go, internal/resources/google/container_cluster.go
The `google_container_cluster` resource pulls all existing node pools into its `node_pool` attribute when deployed. This duplicates the default pool and any node pools defined in `google_container_node_pool` resources. To fix this we:
1. Only add the default node pool subresource if it doesn't already exist in the `node_pool` array. If it does exist in that array, we add it as part of that.
2. Check for node pools defined in other resources, and only add them as subresources if they are not.
=> fix: fix google_container_cluster duplicating node pools when applied

infracost-usage-example.yml, internal/providers/terraform/aws/networkfirewall_firewall.go, internal/providers/terraform/aws/networkfirewall_firewall_test.go, internal/providers/terraform/aws/registry.go, internal/providers/terraform/aws/testdata/networkfirewall_firewall_test/networkfirewall_firewall_test.golden, internal/providers/terraform/aws/testdata/networkfirewall_firewall_test/networkfirewall_firewall_test.tf, internal/providers/terraform/aws/testdata/networkfirewall_firewall_test/networkfirewall_firewall_test.usage.yml, internal/resources/aws/networkfirewall_firewall.go
Add support for AWS Network Firewall resources.
Pricing information: https://aws.amazon.com/network-firewall/pricing/
The `aws_networkfirewall_firewall` resources is billed like a NAT gateway (hours + traffic).
All the others resources are free.
Not sure how to take into account the discount on the NAT gateway granted by Network Firewall:
> Use one hour & one GB of NAT gateway at no additional cost for every hour & GB charged for Network Firewall endpoints.
=> feat(aws): add AWS Network Firewall resources

internal/hcl/reference.go, internal/providers/terraform/aws/eks_node_group.go, internal/providers/terraform/aws/testdata/eks_node_group_test/eks_node_group_test.golden, internal/providers/terraform/aws/testdata/eks_node_group_test/eks_node_group_test.tf
* Fixes issue with `aws_eks_node_group` where  `instance_types` was not set https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group we now use the default `t3.medium`
* Fixes issue where `cty.Value` was unknown and causing panic when trying to set attribute
=> fix: hcl panic errors

cmd/infracost/run.go
Fixes #1450.
This automatically disables spinners which currently cause issues
for some CI users. Infracost GitHub Actions already set logging by
default, this change unifies the behavior across all CI platforms.
=> feat: Set log level to 'info' when CI is detected

infracost-usage-example.yml, internal/providers/terraform/google/registry.go, internal/providers/terraform/google/service_networking_connection.go, internal/providers/terraform/google/service_networking_connection_test.go, internal/providers/terraform/google/testdata/service_networking_connection_test/service_networking_connection_test.golden, internal/providers/terraform/google/testdata/service_networking_connection_test/service_networking_connection_test.tf, internal/providers/terraform/google/testdata/service_networking_connection_test/service_networking_connection_test.usage.yml
Add support for google_service_networking_connection. Fixes #1360.
Private service connections are essentially VPC to VPC connections and and can generate "internal" egress costs in the same manner as a VPN Gateway.  Therefore this resource has the same usage cost components for egress traffic as VPN gateway:
```
monthly_egress_data_transfer_gb: # Monthly VM-VM data transfer from VPN gateway to the following, in GB:
same_region: 250                # VMs in the same Google Cloud region.
us_or_canada: 100               # From a Google Cloud region in the US or Canada to another Google Cloud region in the US or Canada.
europe: 70                      # Between Google Cloud regions within Europe.
asia: 50                        # Between Google Cloud regions within Asia.
south_america: 100 …
```
=> feat: Add google_service_networking_connection

internal/providers/terraform/azure/registry.go
It represents a container in Storage Account (which can be treated as a folder).
`azurerm_storage_account` already includes "List and Create container
operations" cost component which includes the container creation. As
Azure billing page doesn't provide the data per container and only
cumulative operations count, we can treat this resource as free.
Docs: https://github.com/infracost/docs/pull/193/commits/a44334d5fd34c3b45cec958e5d732d2cb727196a
Resolves #1257.
=> feat(azure): Add azurerm_storage_container resource as free

cmd/resourcegen/embed/providers/terraform/$cloud_provider$/$filename$_test.go.tmpl
As we test resources using golden files by default, having `GoldenFile`
in the test names seems redundant.
=> chore: Update test naming in resourcegen templates

internal/providers/terraform/aws/api_gateway_stage.go, internal/providers/terraform/aws/testdata/api_gateway_stage_test/api_gateway_stage_test.golden, internal/providers/terraform/aws/testdata/api_gateway_stage_test/api_gateway_stage_test.tf, internal/resources/aws/api_gateway_stage.go
Fixes #1505 - Api Gateway should not estimate charges for cache unless the cache is enabled.
=> fix: Honor cache enabled flag for API Gateway

internal/providers/terraform/aws/testdata/vpc_endpoint_test/vpc_endpoint_test.golden, internal/providers/terraform/aws/testdata/vpc_endpoint_test/vpc_endpoint_test.tf, internal/providers/terraform/aws/vpc_endpoint.go
Fixes issue where the `subnet_ids` attribute was empty as it contained ids for subnets yet to be created. This meant that we were calculating the wrong number of interfaces for the cost component.
=> fix: vpc endpoint subnet_ids attribute empty without apply state

internal/providers/terraform/aws/testdata/sfn_state_machine_test/sfn_state_machine_test.golden, internal/resources/aws/sfn_state_machine.go
Fixes https://github.com/infracost/cloud-pricing-api/issues/186
=> fix: Use correct unit multiplier for state machine transitions

internal/providers/terraform/google/container_cluster.go
fixes issues where `google_container_cluster` resource is unable to fetch references with the `terraform-use-state` flag.
=> fix: google_container_cluster missing reference with terraform-use-state

internal/providers/terraform/aws/dynamodb_table.go, internal/providers/terraform/aws/testdata/dynamodb_table_test/dynamodb_table_test.golden, internal/providers/terraform/aws/testdata/dynamodb_table_test/dynamodb_table_test.tf
Set's the default value of `billing_mode` to `PROVISIONED` as per the terraform docs: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table#billing_mode
This was causing the resource to return zero cost:
```
Name                                                            Monthly Qty  Unit                  Monthly Cost
aws_dynamodb_table.my_dynamodb_table_with_no_billing_mode
├─ Data storage                                            Monthly cost depends on usage: $0.25 per GB
├─ Point-In-Time Recovery (PITR) backup storage            Monthly cost depends on usage: $0.20 per GB
├─ On-demand backup storage                                Monthly cost depends on usage: $0.10 per GB
├─ Table data restored                                     Monthly cost …
```
=> fix: default billing value for dynamodb for HCL

internal/providers/terraform/aws/testdata/autoscaling_group_test/autoscaling_group_test.golden
The default value of `enable_monitoring` has been changed to 'true' in
the terraform-aws-autoscaling module:
https://github.com/terraform-aws-modules/terraform-aws-autoscaling/commit/8e2e285b031faafe298de5d1d738e9743e607b3d#diff-05b5a57c136b6ff596500bcbfdcff145ef6cddea2a0e86d184d9daa9a65a288eR271
=> chore(aws): Fix autoscaling group tests

cmd/infracost/breakdown.go, cmd/infracost/testdata/breakdown_help/breakdown_help.golden, cmd/infracost/testdata/flag_errors_config_file_and_terraform_workspace/flag_errors_config_file_and_terraform_workspace.golden, cmd/infracost/testdata/flag_errors_no_path/flag_errors_no_path.golden, cmd/infracost/testdata/flag_errors_path_and_config_file/flag_errors_path_and_config_file.golden
updates flag description to be more consistent and shorter
=> chore: update terraform-parse-hcl flag naming

internal/hcl/attribute.go, internal/hcl/block.go, internal/hcl/evaluator.go, internal/providers/terraform/aws/testdata/autoscaling_group_test/autoscaling_group_test.golden, internal/providers/terraform/aws/testdata/autoscaling_group_test/autoscaling_group_test.tf, internal/providers/terraform/hcl_provider.go, internal/providers/terraform/parser.go
Fixes issues where `count` traversal expressions were not being properly evaluated. This was for two reasons:
1. When a block was cloned due to a count the context value was still an object. e.g:
```go
map[string]interface{
"aws_launch_configuration": map[string]interface{
"test_count": map[string]interface{
"id": ...
},
"test_count[1]": map[string]interface{
"id": ...
}
}
}
```
It should instead look like:
```go
map[string]interface{
"aws_launch_configuration": map[string]interface{
"test_count": []map[string]interface{
{
"id": ...
},
{
"id": ...
}
}
}
}
}
```
This meant that only the first resource in the `count` was being pulled as a reference. All references that used a count > 0 were returning null as there were no items in the context value list past 1 (under the hood the hcl …
=> fix(hcl): properly evaluate count expressions

infracost-usage-example.yml, internal/providers/terraform/azure/mysql_flexible_server.go, internal/providers/terraform/azure/mysql_flexible_server_test.go, internal/providers/terraform/azure/postgresql_flexible_server.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/testdata/mysql_flexible_server_test/mysql_flexible_server_test.golden, internal/providers/terraform/azure/testdata/mysql_flexible_server_test/mysql_flexible_server_test.tf, internal/providers/terraform/azure/testdata/mysql_flexible_server_test/mysql_flexible_server_test.usage.yml, internal/providers/terraform/azure/testdata/postgresql_flexible_server_test/postgresql_flexible_server_test.usage.yml, internal/providers/terraform/azure/util.go, internal/resources/azure/mysql_flexible_server.go, internal/resources/azure/postgresql_flexible_server.go
Add support for Azure MySQL Flexible Server. Fixes #792.
https://azure.microsoft.com/en-gb/pricing/details/mysql/flexible-server/
None
=> feat(azure): Add MySQL Flexible Server resources

internal/providers/terraform/aws/kinesis_firehose_delivery_stream.go, internal/providers/terraform/aws/testdata/kinesis_firehose_delivery_stream_test/kinesis_firehose_delivery_stream_test.golden, internal/providers/terraform/aws/testdata/kinesis_firehose_delivery_stream_test/kinesis_firehose_delivery_stream_test.tf
Similar issue to https://github.com/infracost/infracost/pull/1504 where the `subnet_ids` attribute is empty if it contains ids for subnets yet to be created. This meant that we were wrongly excluding the `VPC AZ delivery` cost component.
=> fix: aws_kinesis_firehose_delivery_stream subnet_ids attribute empty without apply state

cmd/infracost/hcl_test.go, cmd/infracost/testdata/hclmodule_output_counts/hclmodule_output_counts.golden, cmd/infracost/testdata/hclmodule_output_counts/main.tf, cmd/infracost/testdata/hclmodule_output_counts/modules/test/main.tf, internal/hcl/evaluator.go
fixes issue where module outputs used in count evaluation were not available when expanding counts. This meant that the resources that were marked as disabled were being falsely generated. e.g:
```
module "this" {
source  = "./modules/test"
enabled = false
}
resource "aws_eip" "t" {
count = module.this.enabled ? 1 : 0
tags = {
"test" : module.this.enabled
}
}
```
in this case `module.this.enabled` would not be in the evaluation context meaning that we would use a fallback and expand the block to a count of 1.
---
Depends on https://github.com/infracost/infracost/pull/1542
=> fix(hcl): module outputs evaluated before count expansion

internal/hcl/attribute.go, internal/hcl/block.go, internal/hcl/evaluator.go, internal/hcl/module.go, internal/hcl/parser.go, internal/hcl/parser_test.go, internal/hcl/reference.go, internal/providers/terraform/hcl_provider.go, internal/providers/terraform/hcl_provider_test.go, internal/providers/terraform/testdata/hcl_provider_test/renders_module_resources/expected.json, internal/providers/terraform/testdata/hcl_provider_test/renders_module_resources/main.tf, internal/providers/terraform/testdata/hcl_provider_test/renders_module_resources/module/gateway/main.tf, internal/providers/terraform/testdata/hcl_provider_test/renders_multiple_count_resources_correctly/expected.json, internal/providers/terraform/testdata/hcl_provider_test/renders_multiple_count_resources_correctly/main.tf, internal/providers/terraform/testdata/hcl_provider_test/renders_multiple_count_resources_correctly/modules/autoscaling/main.tf, internal/providers/terraform/testdata/hcl_provider_test/structures_module_expressions_correctly_with_count/expected.json, internal/providers/terraform/testdata/hcl_provider_test/structures_module_expressions_correctly_with_count/main.tf, internal/providers/terraform/testdata/hcl_provider_test/structures_module_expressions_correctly_with_count/modules/module1/main.tf, internal/providers/terraform/testdata/hcl_provider_test/structures_module_expressions_correctly_with_count/modules/module1/modules/module2/main.tf, internal/providers/terraform/tftest/tftest.go
This fixes issue where resources built with HCL were not able to fetch references for a non `id` or `arn` attribute if the resource had a count. For example a resource like:
```
resource "aws_ecs_service" "test" {
count                              = 2
name                               = "test"
task_definition                = "${join("", aws_ecs_task_definition.default.*.family)}:${join("", aws_ecs_task_definition.default.*.revision)}"
...
}
```
would be unable to resolve the `aws_ecs_task_definition`. This was because the Plan JSON generated by the `hcl_provider` had some discrepancies. Especially in the `configuration` section of the plan JSON. 
1. Resources were being added to the `resources` list in the configuration block and not being deduped for their index:
```
[
{
"address": …
```
=> fix(hcl): count references not evaluating

internal/providers/terraform/azure/testdata/cosmosdb_gremlin_graph_test/cosmosdb_gremlin_graph_test.tf
The attribute is case-sensitive now. Fixed after provider's v3 release here:
https://github.com/hashicorp/terraform-provider-azurerm/pull/16152.
=> chore(azure): Fix tests for CosmosDB related resource

cmd/infracost/run.go, internal/config/run_context.go, internal/hcl/evaluator.go, internal/hcl/modules/loader.go, internal/hcl/parser.go, internal/providers/detect.go, internal/providers/terraform/hcl_provider.go, internal/ui/print.go, internal/ui/spin.go
Improves HCL provider status outputs.
1. Adds two spinners to the HCL provider logic that loads modules and evaluates blocks. Output now looks like:
```
Detected Terraform directory (HCL) at ***
✔ Downloading Terraform modules
✔ Evaluating Terraform directory
✔ Retrieving cloud prices to calculate costs
Project: ***
```
2. adds warning log for missing vars:
```
✔ Downloading Terraform modules
Warning: Input values were not provided for the following Terraform variables: 'variable.foo', 'variable.baz'. Use --terraform-var-file or --terraform-var to specify input vars.
✔ Evaluating Terraform directory
✔ Retrieving cloud prices to calculate costs
```
3. Adds error messaging for incompatible project types:
**terragrunt**
```
Error: Terragrunt projects are not yet supported by the parse HCL …
```
=> chore: improve hcl provider output messaging

.github/workflows/post-release.yml
After the new release is published we can safely trigger release
workflows in other repos.
Atlantis repo: https://github.com/infracost/infracost-atlantis/pull/51
Related: https://github.com/infracost/infracost/pull/1560
=> chore: Add post-release workflow

.github/workflows/create-release.yml
This enables us to lock down our org-wide default to just `contents: read`.
See: https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/
After this, I'll update the org-wide default, and then we can merge https://github.com/infracost/infracost/pull/1565.
=> chore: add explicit permission for release job

internal/providers/terraform/aws/instance.go, internal/providers/terraform/aws/testdata/instance_test/instance_test.golden, internal/providers/terraform/aws/testdata/instance_test/instance_test.tf, internal/providers/terraform/aws/testdata/instance_test/instance_test.usage.yml
Launch template can also define EBS volumes that can be overriden by Instance's block. This will be addressed separately.
=> feat(aws): Add launch template support for Instance resource

cmd/infracost/cmd_test.go, cmd/infracost/hcl_test.go, cmd/infracost/testdata/hclmodule_output_counts_nested/hclmodule_output_counts_nested.golden, cmd/infracost/testdata/hclmodule_output_counts_nested/main.tf, cmd/infracost/testdata/hclmodule_output_counts_nested/modules/sub/main.tf, cmd/infracost/testdata/hclmodule_output_counts_nested/modules/test/main.tf, internal/hcl/block.go, internal/hcl/evaluator.go
Fixed issue where modules that used outputs from a module that appeared after them in the file structure received null values. 
For example:
```
module "sub" {
source = "./modules/sub"
some_var = module.this.output
}
module "this" {
source  = "./modules/test"
enabled = false
}
```
`module.sub` would receive a `null` value for `some_var`. This caused discrepancies in HCL cost estimates as resources that depended on these module inputs were provided with incorrect values.
This problem was caused by the fact we evaluated module blocks by order of occurrence in the HCL file.
This PR resolves this issue by sorting module blocks by reference so that we evaluate blocks whose outputs are used by other modules first.
=> fix(hcl): evalute modules in order of reference

internal/extclient/authed_client.go, internal/hcl/parser.go, internal/hcl/remote_variables_loader.go, internal/providers/terraform/hcl_provider.go
Happy path:
```
Detected Terraform directory (HCL) at examples/tfc/
✔ Downloading Terraform remote variables
✔ Downloading Terraform modules
✔ Evaluating Terraform directory
✔ Retrieving cloud prices to calculate costs
Project: infracost/infracost/examples/tfc
...
```
Invalid token:
```
Detected Terraform directory (HCL) at examples/tfc/
✖ Downloading Terraform remote variables
Error: the provided token is invalid
```
Cloud settings not detected:
```
Detected Terraform directory (HCL) at examples/tfc/
✔ Downloading Terraform modules
✔ Evaluating Terraform directory
✔ Retrieving cloud prices to calculate costs
Project: infracost/infracost/examples/tfc
...
```
For remote backend + name prefix, when `--terraform-workspace` is not specified:
```
Detected Terraform directory (HCL) at …
```
=> feat: Load TFC remote execution variables for HCL parsing

cmd/infracost/run.go, internal/providers/terraform/tftest/tftest.go, internal/usage/aws/configuration.go, internal/usage/sync.go
We were setting os.Setenv at the top level to make sure that the sync usage functionality got any AWS_* creds set in the config file's env block. However, this can cause race conditions across goroutines, so instead we pass the project's env vars through to where we load the AWS config and use a mutex when loading this.
=> fix: fix polluting the OS env variables

.github/workflows/post-release.yml
changes post release workflows to use a correctly scoped personal access token
=> fix: change post release workflow to use PAT

internal/hcl/remote_variables_loader.go
only new up a spinner if the execution mode is remote
=> fix: remove spinner if workspace does not use remote execution

cmd/infracost/main.go
=> feat: Enable -no-color option by default for CI

internal/providers/terraform/aws/testdata/sns_topic_test/sns_topic_test.golden, internal/providers/terraform/aws/testdata/sns_topic_test/sns_topic_test.tf, internal/resources/aws/sns_topic.go
- Only us-east-1 has 'DeliveryAttempts-HTTP' usagetype value, the other
regions also include the region code like 'UE2-DeliveryAttempts-HTTP'.
- SMS pricing is available only for 3 regions. As SMS pricing is complex
and depends on country and/or carrier, the cost component is
simplified. As custom price is expected, the search filters are also
simplified.
=> fix(aws): Fix SNS Topic notification price filters

internal/comment/github.go
API throws an error on fetching comments with string ID.
Fixes #1635.
=> fix: Update commit type for GitHub GraphQL query

internal/providers/terraform/parser.go, internal/providers/terraform/parser_test.go
Fixes #1545.
As described in the issue, terraform resources created via `for_each` and referenced with `each.key` are ignored due to the address not matching.
This PR adds support for `each.key` references the exact same way it was done with `count.index`, bringing the expected results to the two examples provided in the issue:
**Terraform code:**
```terraform
provider "aws" {
region                      = "us-east-1"
skip_credentials_validation = true
skip_requesting_account_id  = true
access_key                  = "mock_access_key"
secret_key                  = "mock_secret_key"
}
resource "aws_ebs_volume" "my_volume" {
for_each          = toset(["us-east-1a", "us-east-1b"])
availability_zone = each.key
size              = 20
}
resource "aws_ebs_snapshot" "my_snapshot" {
for_each  = …
```
=> fix: support for references with for_each

internal/providers/terraform/terragrunt_hcl_provider.go
This only outputs the Terragrunt library logs when log-level is `debug`. It also outputs the full Terragrunt log so timestamps, etc are repeated, e.g:
```
infracost breakdown --path=/path/to/project --terraform-parse-hcl --log-level=debug
time="2022-05-11T16:24:49+01:00" level=info msg="Detected Terragrunt directory (HCL) at /path/to/project"
time="2022-05-11T16:24:49+01:00" level=debug library=terragrunt msg="time=2022-05-11T16:24:49+01:00 level=debug msg=Did not find any locals block: skipping evaluation. prefix=[/path/to/project/dev] "
```
=> enhance: add logging for the Terragrunt library logs

internal/providers/terraform/google/compute_instance_group_manager.go, internal/providers/terraform/google/compute_per_instance_config.go, internal/providers/terraform/google/compute_per_instance_config_test.go, internal/providers/terraform/google/registry.go, internal/providers/terraform/google/testdata/compute_per_instance_config_test/compute_per_instance_config_test.golden, internal/providers/terraform/google/testdata/compute_per_instance_config_test/compute_per_instance_config_test.tf
Closes #1644.
I was not entirely sure on how to implement this as `google_compute_per_instance_config` is a free resource that will increase the cost of `google_compute_instance_group_manager`.
I added a reversed reference from the `google_compute_instance_group_manager` resource to the `google_compute_per_instance_config` to increase the `target_size` and compute the actual cost, and did not add any cost for the `google_compute_per_instance_config` resource.
=> feat: Add support for google_compute_per_instance_config

internal/providers/terraform/google/compute_instance_group_manager.go, internal/providers/terraform/google/compute_region_instance_group_manager.go, internal/providers/terraform/google/testdata/compute_instance_group_manager_test/compute_instance_group_manager_test.golden, internal/providers/terraform/google/testdata/compute_instance_group_manager_test/compute_instance_group_manager_test.tf, internal/providers/terraform/google/testdata/compute_region_instance_group_manager_test/compute_region_instance_group_manager_test.golden, internal/providers/terraform/google/testdata/compute_region_instance_group_manager_test/compute_region_instance_group_manager_test.tf, internal/resources/google/compute_instance_group_manager.go, internal/resources/google/compute_region_instance_group_manager.go
Closes #1654.
This PR fixes the computation of local scratch disk in GCP's zonal and regional instance group manager, by adding the scratch disk logic already existing in `google_compute_instance`.
The following output takes the issue example and shows the fix:
```
Name                                                 Monthly Qty  Unit   Monthly Cost 
google_compute_instance_group_manager.default                                         
├─ Instance usage (Linux/UNIX, on-demand, f1-micro)        2,920  hours        $15.53 
├─ SSD provisioned storage (pd-ssd)                        1,500  GB          $255.00 
├─ Local SSD provisioned storage                           1,500  GB          $120.00 
└─ NVIDIA Tesla K80 (on-demand)                            5,840  hours     $1,839.60 
OVERALL …
```
=> fix(google): compute scratch disk for compute(_region)_instance_group_manager

internal/providers/terraform/aws/aws.go, internal/providers/terraform/azure/azure.go, internal/providers/terraform/google/compute_instance_group_manager.go, internal/providers/terraform/google/compute_region_instance_group_manager.go, internal/providers/terraform/google/google.go, internal/providers/terraform/parser.go, internal/providers/terraform/registry.go, internal/schema/registry_item.go
This PR closes #1652.
I tried to (at least partially) rework `parser.go` move the provider-specific logic out of this file and into the specific packages.
I feel that the `internal/providers/terraform/*` packages could deserve to be implemented as interfaces (with GetResources(), GetFreeResources(), GetUsageOnlyResources() on top of the funcs I added in the `internal/providers/terraform/*/[provider].go` files), though it means refactoring lots of stuff in `parser.go` and `registry.go` and I'm not sure this PR is the right one for that (+ I feel a bit lazy tonight...).
Let me know what you think!
=> refactor: rework reference mapping

internal/providers/terraform/azure/mssql_database.go
If the attribute was not specified, the plan JSON had the key with null
value thus `Exists()` method returned true and the attribute ended up
with an empty string.
Updated other attributes to follow the latest good practice to check for
empty values.
=> fix(azure): Fix MSSQL Database License Type retrieval

internal/providers/terraform/terragrunt_hcl_provider.go
If someone runs into an error when running HCL parsing with Terragrunt, we weren't clarifying that the errors were from the Terragrunt libs. This updates that and points them to generate a plan JSON for just now.
Example:
=> enhance: add a better error message for errors originating from the Terragrunt libs

cmd/infracost/breakdown_test.go, cmd/infracost/run.go, cmd/infracost/testdata/breakdown_terragrunt_hcldeps_output/breakdown_terragrunt_hcldeps_output.golden, cmd/infracost/testdata/breakdown_terragrunt_hcldeps_output/dev/terragrunt.hcl, cmd/infracost/testdata/breakdown_terragrunt_hcldeps_output/modules/example/main.tf, cmd/infracost/testdata/breakdown_terragrunt_hcldeps_output/prod/terragrunt.hcl, cmd/infracost/testdata/breakdown_terragrunt_hcldeps_output/terragrunt.hcl, examples/terraform/main.tf, internal/hcl/block.go, internal/hcl/evaluator.go, internal/hcl/parser.go, internal/providers/detect.go, internal/providers/terraform/hcl_provider.go, internal/providers/terraform/hcl_provider_test.go, internal/providers/terraform/terragrunt_hcl_provider.go, internal/providers/terraform/tftest/tftest.go
fixes: https://github.com/infracost/infracost/issues/1641
Changes the Terragrunt HCL parser to build `outputs` for each Terragrunt project run. These outputs are then used by Terragrunt projects that make use of `dependency` blocks. How this works:
1. TerragruntHCLParser has the Terragrunt stack output set on it every run. This contains tree information about which Terragrunt projects there are, and which of those have dependencies.
2. `runTerragrunt` method now evaluates the blocks for the project rather than just returning directory information. This allows us to fetch the `output` blocks.
3. `runTerragrunt` uses `ParseConfigFile` and explicitly passes a `cty.Value` of the `outputs` from any dependency projects used. If none are used we have a mock `cty.Value` which bypasses the …
=> fix: parse outputs from Terragrunt dependencies

cmd/infracost/main.go, cmd/infracost/run.go, internal/apiclient/errors.go, internal/providers/terraform/terragrunt_hcl_provider.go
This pr fixes two issues which were causing panics not to be reported to sentry:
1. The terragrunt process runs in a child goroutine so we need to properly recover from the panic
2. Stripping metadata from the panic errors caused sentry to not pick up on the `runtime/debug` error
=> fix: panic errors not being reported to sentry

internal/resources/aws/elastic_beanstalk_environment.go
Fixes #1675.
Test:
1. Update `examples/terraform` to include:
```terraform
resource "aws_elastic_beanstalk_application" "tftest" {
name        = "tf-test-name"
description = "tf-test-desc"
}
resource "aws_elastic_beanstalk_environment" "tfenvtest" {
name                = "tf-test-name"
application         = aws_elastic_beanstalk_application.tftest.name
solution_stack_name = "64bit Amazon Linux 2015.03 v2.0.3 running Go 1.4"
}
```
2. Run
```
make run ARGS="breakdown --path=examples/terraform --sync-usage-file --usage-file /tmp/infracost-usage.yml"
```
Result: shows breakdown
```
Evaluating Terraform directory at examples/terraform
✔ Downloading Terraform modules
✔ Evaluating Terraform directory
✔ Syncing usage data from cloud
└─ Synced 0 of 2 resources
✔ Downloading Terraform modules
✔ …
```
=> fix(aws): Fix usage schema for Elastic Beanstalk Environment

internal/hcl/evaluator.go, internal/hcl/reference.go, internal/hcl/reference_test.go
Fixes https://github.com/infracost/infracost/issues/1715
I changed variable evaluation in 0.10.1 to try and convert variable types to what the variable `type` attribute. This introduced a regression where `cty.Nil` values were changed to `cty.String` or `cty.Number` or `cty.Bool` but having their underlying value as nil. 
This means that expressions like:
```
switch key.Type() {
case cty.String:
r.key = fmt.Sprintf("[%q]", key.AsString())
}
```
Will panic. `cty.NullValue` should not be used and instead, we should fall back to how it was before with `cty.Nil`.
=> fix: dont use cty.Null values as problematic for type checking

cmd/infracost/breakdown_test.go, cmd/infracost/testdata/breakdown_multi_project_skip_paths_root_level/breakdown_multi_project_skip_paths_root_level.golden, cmd/infracost/testdata/breakdown_multi_project_skip_paths_root_level/dev/main.tf, cmd/infracost/testdata/breakdown_multi_project_skip_paths_root_level/prod/main.tf, cmd/infracost/testdata/breakdown_multi_project_skip_paths_root_level/shown/main.tf, internal/hcl/parser.go
Fixes: https://github.com/infracost/infracost/issues/1713#issue-1256882215
* Solves issue with `--exclude-path` being used with multiple directories. Before we were assigning variables to a function in a loop. This meant that the excluded patterns were always being used as the last value in the loop. I've reworked the logic to build all matches into a single evaluation step.
* Reworks internals to parse all directories before filtering so that we don't show module pricing. Before we were doing the ignored directory check at a lower level. This meant that we weren't properly filtering out modules that were used in skipped directories. We now do it at the top level once all directories have been evaluated.
=> fix: issues with multiple exclude-path flags being used

internal/apiclient/auth.go
fixes issue where any non-expected headers sent from the browser kill the login process
=> fix: allow all headers sent to local auth server

Dockerfile, Dockerfile.ci
This PR makes the docker process run as a non root user.
Some state and cache files are created when running the infracost docker process and I noticed that on my CI/CD server those files became owned by root causing some issues when trying to clean them up afterwards on subsequent pipeline runs.
As best practice we try to run docker processes with a non-privileged user in order to prevent any security issues and I took this opportunity to tackle it on infracost.
There is a slight difference when running the docker process with these changes and I didn't find where I could document it.
Previous to these changes we did:
```
docker run -e INFRACOST_API_KEY -v "$PWD":/root --rm infracost/infracost:ci-<version> breakdown --path . --format json --out-file infracost.json
```
With these changes: …
=> feat: Don't run docker process as root

internal/config/project_context.go, internal/config/run_context.go
Introduces mutex to protect context values. This prevents concurrent map write panic.
=> fix: introduce mutex lock for context reading/writing

cmd/infracost/breakdown_test.go, cmd/infracost/testdata/breakdown_terragrunt_hcldeps_output/prod2/config.yml, cmd/infracost/testdata/breakdown_terragrunt_hcldeps_output/prod2/terragrunt.hcl, cmd/infracost/testdata/breakdown_terragrunt_hcldeps_output_mocked/breakdown_terragrunt_hcldeps_output_mocked.golden, cmd/infracost/testdata/breakdown_terragrunt_hcldeps_output_mocked/dev/template.yml, cmd/infracost/testdata/breakdown_terragrunt_hcldeps_output_mocked/dev/terragrunt.hcl, cmd/infracost/testdata/breakdown_terragrunt_hcldeps_output_mocked/modules/example/main.tf, cmd/infracost/testdata/breakdown_terragrunt_hcldeps_output_mocked/modules/example2/main.tf, cmd/infracost/testdata/breakdown_terragrunt_hcldeps_output_mocked/prod/terragrunt.hcl, cmd/infracost/testdata/breakdown_terragrunt_hcldeps_output_mocked/prod2/terragrunt.hcl, cmd/infracost/testdata/breakdown_terragrunt_hcldeps_output_mocked/terragrunt.hcl, internal/hcl/attribute.go, internal/hcl/block.go, internal/hcl/evaluator.go, internal/hcl/parser.go, internal/hcl/parser_test.go, internal/providers/terraform/hcl_provider_test.go, internal/providers/terraform/terragrunt_hcl_provider.go, internal/providers/terraform/testdata/hcl_provider_test/structures_module_expressions_correctly_with_count/expected.json, internal/resources/aws/rds_cluster_instance.go
closes https://github.com/infracost/infracost/issues/1718, https://github.com/infracost/infracost/issues/1641, https://github.com/infracost/infracost/issues/1756
Fixes various issues that have been exposed by trying to fetch values for attributes that don't exist.
1. When fetching an attribute value we now check `diags` error returned. If the message returned is an instance of "Unsupported Attribute" we attempt to set a dummy attribute on the global evaluation context.
2. If the message returned is an "Iteration over non-iterable value" then we change the dummy attribute to a list
3. Fixes issues with each & count attributes being set as the wrong context value when running in the evaluation loop. We now set them correctly within the `evaluation` step
4. Inits the `HCLProvider` with raw …
=> fix: add dummy return types for attributes that cannot be evaluated

internal/providers/terraform/hcl_provider.go, internal/providers/terraform/testdata/hcl_provider_test/renders_multiple_count_resources_correctly/expected.json, internal/providers/terraform/testdata/hcl_provider_test/renders_multiple_count_resources_correctly/main.tf
solves issue where count attribute set as a constant string, e.g:
```
count = "2"
```
would panic as the cty type was invalid
=> fix: panic from count constant value being a string

go.mod, go.sum
Reverts infracost/infracost#1757
Some element of this change has severely impacted the speed with which we parse Terragrunt projects. I'm reverting until we know more. Thanks @dgokcin for your help 😍
=> Revert "chore(deps): bump github.com/gruntwork-io/terragrunt from 0.36.9 to 0.37.4"

internal/hcl/parser.go, internal/hcl/parser_test.go
When an invalid `cty.Type` is passed as a raw input type we recover from panic to ignore setting any input vars on the HCL parser. However the defer func does not return a valid option which means that it introduces a runtime error further down the program operation.
=> fix: defer function not returning an empty option func when recovering

internal/config/project_context.go, internal/vcs/metadata.go
Changes `vcs` package to include a keyed mutex so that go routines wait for cloned repos to be available. Fixes issue where commit ref is not available in `config-file` project run.
=> fix: introduce keyed mutex to wait for clone to finish before access

.github/workflows/go.yml, cmd/infracost/breakdown_test.go, cmd/infracost/hcl_test.go, cmd/infracost/main.go, cmd/infracost/testdata/breakdown_with_private_terraform_registry_module/breakdown_with_private_terraform_registry_module.golden, cmd/infracost/testdata/breakdown_with_private_terraform_registry_module/main.tf, examples/terraform/main.tf, go.mod, go.sum, internal/config/config_test.go, internal/credentials/terraform.go, internal/hcl/modules/cache.go, internal/hcl/modules/cache_test.go, internal/hcl/modules/credentials_source.go, internal/hcl/modules/fetch.go, internal/hcl/modules/loader.go, internal/hcl/modules/loader_test.go, internal/hcl/modules/registry.go, internal/hcl/parser.go, internal/providers/terraform/cloud.go, internal/providers/terraform/dir_provider.go, internal/providers/terraform/hcl_provider.go
Closes https://github.com/infracost/infracost/issues/1667
* Uses https://github.com/hashicorp/terraform-svchost discovery mechanism to try and resolve the real location for the module
* Adds credential support based off of `disco` mechanism
* Adds private module tests and reworks CI pipeline to include Terraform Cloud tokens for test
=> fix: resolve private Terraform registry modules

internal/hcl/remote_variables_loader.go
Closes #1786
Remote variables should also be fetched if the TFC workspace is set to `agent` execution mode.
I thought it's just better to flip the if-statement and check if `local` execution mode is set and then skip fetching the remote variables.
=> fix: loading remote variables

internal/providers/terraform/azure/mssql_database_test.go, internal/providers/terraform/azure/testdata/mssql_database_test_with_blank_location/mssql_database_test_with_blank_location.golden, internal/providers/terraform/azure/testdata/mssql_database_test_with_blank_location/mssql_database_test_with_blank_location.tf, internal/providers/terraform/azure/testdata/mssql_database_test_with_blank_location/mssql_database_test_with_blank_location.usage.yml, internal/providers/terraform/azure/util.go, internal/providers/terraform/parser.go, internal/providers/terraform/tftest/tftest.go
closes https://github.com/infracost/infracost/issues/1824
Solves issues where mock values for cloud attributes were causing the default region not to be used. `e.g.`
```
data "azurerm_resource_group" "main" {
name = "test"
}
resource "azurerm_mssql_server" "blank_location" {
location = data.azurerm_resource_group.main.location <== this would evaluate as `location-mock`
...
}
resource "azurerm_mssql_database" "blank_server_location" {
name      = "acctest-db-e"
sku_name = "S3"
server_id = azurerm_mssql_server.blank_location.id
}
```
So blank string checks were being skipped as `location-mock` was seen as a valid region. We now check if the returned value is a mock and treat it as a blank value.
=> fix: mock attribute overriding the default location

internal/hcl/attribute.go
We still want to log the stacktrace in case it is a valid error but these errors can be issues in the underlying hcl and cty libs, e.g. https://github.com/zclconf/go-cty/pull/128
=> chore: add message clarifying debug log can be ignored

internal/hcl/block.go
This happens if the user runs Infracost against code that has an empty resource block
Fixes https://github.com/infracost/infracost/issues/1843
=> fix: fix entry in nil map panic

internal/hcl/attribute.go, internal/hcl/attribute_test.go, internal/hcl/block.go, internal/hcl/evaluator.go, internal/hcl/remote_variables_loader.go, internal/providers/terraform/hcl_provider.go
fixes https://github.com/infracost/infracost/issues/1846
I've changed code logic to call `Attribute.AsString` and `Attribute.AsInt` respectively. These are panic safe methods and do some naive type conversion for acceptable types.
=> fix: using unsafe As methods in `go-cty` lib

internal/hcl/attribute.go, internal/hcl/attribute_test.go
Resolves https://github.com/infracost/infracost/issues/1789 
The hcl libs don't expect `cty.NilVal` to be used in expression evaluation They instead favour types like `cty.DynamicVal` to express unknown or invalid variables. The steps that produced a panic were as such:
1. The user provides the following block:
```
locals {
original_tags    = "test"
transformed_tags = local.original_tags
id = var.enabled ? local.transformed_tags : "test3"
}
```
2. On the initial first pass of the module the `Evaluator` builds an `EvaluationContext` with the local attributes.
3. In this case `transformed_tags` attribute returns an error as the `EvaluationContext` does not mention locals (this is the first pass of the context, so there are no Variables outside of things like `terraform.cwd` and other …
=> fix: passing `cty.NilVal` to hcl expressions when in a partial evaluation state

cmd/infracost/hcl_test.go, cmd/infracost/testdata/hclmodule_count/hclmodule_count.golden, cmd/infracost/testdata/hclmodule_count/main.tf, cmd/infracost/testdata/hclmodule_count/modules/test/main.tf, cmd/infracost/testdata/hclmodule_for_each/hclmodule_for_each.golden, cmd/infracost/testdata/hclmodule_for_each/main.tf, cmd/infracost/testdata/hclmodule_for_each/modules/test/main.tf, internal/hcl/evaluator.go
This updates the module key matching to ignore anything inside square brackets so we can match what is stored in the manifest
=> fix: support modules with `for_each` or `count`

internal/output/combined.go
@hugorut I'm not sure if there's a better way to handle this, feel free to push/take-over this branch, if you think it's needed also add a warning for "error reading Infracost JSON file"
Thanks to Benjamin Riou for the suggestion!
=> chore: add friendly error message that tells user what to do

internal/hcl/evaluator.go
* Fixes for modules that contain the word 'module' by matching only 'module.' at the beginning or '.module.' in the middle of the resource address.
* Fixes for_each and count support for submodules by making sure it only matches non [] characters inside [].
=> fix: fix HCL parsing module regex

internal/providers/terraform/hcl_provider.go, internal/providers/terraform/hcl_provider_test.go, internal/providers/terraform/testdata/hcl_provider_test/does_not_panic_on_double_attribute_definition/expected.json, internal/providers/terraform/testdata/hcl_provider_test/does_not_panic_on_double_attribute_definition/main.tf
Fixes #1871
Resolves interface conversion panic when an block has an attribute which has been redeclared as a child block.
This is an invalid state and would be incorrect Terraform, hence why we haven't encountered this problem before.
We now handle this case by ignoring the child block definition and putting an entry into the debug log.
=> fix: halts panic when attribute has been redeclared as a child block

internal/hcl/modules/registry.go
Fixes: #1873
Resolves panic that originating from the `github.com/hashicorp/terraform-svchost` library because the host passed for
credential discovery was invalid and could not be converted back to a string.
=> fix: panic on invalid hostname used in credential discovery for private modules

internal/hcl/attribute.go, internal/hcl/attribute_test.go, internal/hcl/parser.go, internal/providers/terraform/hcl_provider.go
fixes #1876
Changes parser and hcl_provider files that were previously using AsString methods behind a
switch statement to use the `gocty.From` function. This handles unknown types and won't
panic if one is provided.
All other instances throughout the codebase (outside of the funcs package, which we don't tend to touch)
use `Attribute.AsString` or `Attribute.AsInt` method which use the `gocty` conversion methods.
I've also added additional `conversion` logic to the native cty functions and added additional null
type checking.
This should resolve most cty panics moving forward.
=> fix: protect cty conversion types against unknown types

.github/dependabot.yml
Make Dependabot update GitHub Actions. This will ensure that GitHub Actions used by the repo are kept up to date.
=> Update dependabot.yml to manage GitHub Actions.

internal/resources/aws/codebuild_project.go
Fixes https://github.com/infracost/infracost/issues/1874
Resolves issue where an environment.compute_type having an unexpected format caused a panic.
We now return a blank string for the name label if the compute_type is invalid.
=> fix: `aws_codebuild_project` with invalid ComputeType causes index panic

internal/clierror/error.go
This is more useful than the import path when debugging since it matches the line number
=> enhance: use relative source path in panics

internal/vcs/metadata.go
This change enables TFC run tasks to show up in Infracost Cloud. It uses OS vars passed from the Cloud worker CLI run.
Cloud changes here: https://github.com/infracost/dashboard/pull/208
=> feat: add TFC run task vcs metadata

internal/comment/azure_repos.go, internal/comment/azure_repos_test.go, internal/schema/project_test.go
Resolves https://github.com/infracost/infracost/issues/1857
Solves an issue where an encoded space was getting encoded twice, resulting in `%2520`.
We now parse the URL before splitting it by `_git` and then rebuilding the path.
=> fix: Azure Repos url with a space returns 404

internal/resources/aws/lambda_function.go
This doesn't fix https://github.com/infracost/infracost/issues/1949 yet, but it does make sure that the existing resources consistently uses the first tier pricing for the Duration cost component.
We will want to update to add proper support for tiers but this fixes inconsistent prices and the tests for just now.
=> fix: use first tier for Lambda duration prices

cmd/infracost/breakdown_test.go, cmd/infracost/testdata/breakdown_with_workspace/breakdown_with_workspace.golden, cmd/infracost/testdata/breakdown_with_workspace/main.tf, internal/hcl/parser.go, internal/providers/terraform/hcl_provider.go
fixes: https://github.com/infracost/infracost/issues/1938
This change resolves `--terraform-workspace` flag being ignored for the HCL provider. User provided
workspaces are now set on the `Parser` so they can be used in context evaluation.
=> fix: use terraform workspace for evaluator if provided

internal/hcl/block.go, internal/hcl/block_test.go
fixes: https://github.com/infracost/infracost/issues/1930
This change resolves a panic when a Block is in an incomplete state and Infracost attempts to build a local
name for the block.
* we now check that the reference returned for the block is valid and did not encounter any errors
* log problems to the debug log so that we can trace errors in future
* added tests to cover specific bug
=> fix: reference panic caused when block has no valid labels

internal/providers/terraform/google/testdata/container_node_pool_test/container_node_pool_test.golden, internal/providers/terraform/google/testdata/container_node_pool_test/container_node_pool_test.tf, internal/resources/google/compute_cost_component_helpers.go, internal/resources/google/compute_instance.go, internal/resources/google/compute_instance_group_manager.go, internal/resources/google/compute_region_instance_group_manager.go, internal/resources/google/container_node_pool.go
fixes: https://github.com/infracost/infracost/issues/1932
This change resolves a panic where a nil `CostComponent` was being attributed to a `Resource` if a
`guest_accelerator.type` was an unexpected string. Fixes include:
* Altered all callers to expect that `guestAcceleratorCostComponent` could return nil if the `type` is invalid.
* Added unhandled `nvidia-tesla-a100` type to list of supported valid guest accelerator types
=> fix: panic caused from invalid guest accelerator cost component

internal/apiclient/errors.go
This change skips sending error traces to any self-hosted cloud pricing instance. These
reports are already skipped server side: https://github.com/infracost/cloud-pricing-api/blob/master/src/events/events.ts#L15-L17.
So ignoring them in the CLI avoids confusion for self-hosted users.
=> chore: skip sending error reports to self hosted cloud pricing API

internal/providers/terraform/azure/mysql_flexible_server.go, internal/providers/terraform/azure/postgresql_flexible_server.go, internal/providers/terraform/azure/testdata/postgresql_flexible_server_test/postgresql_flexible_server_test.golden, internal/providers/terraform/azure/testdata/postgresql_flexible_server_test/postgresql_flexible_server_test.tf, internal/resources/azure/mysql_flexible_server.go, internal/resources/azure/postgresql_flexible_server.go
fixes: https://github.com/infracost/infracost/issues/1884
This change resolves bugs both with PostgreSQL & MySQL Azure flexible server instances.
* changes cost component `productName` filter to match the updated values
* updates flexible server instances to use the `lookupRegion` functionality, which converts commonly used location formats
* adds test case to PostreSQL to account check that cli name conversion works as expected
=> fix: azure flexible server broken cost component filters and region lookup

cmd/infracost/comment_github.go, internal/output/combined.go, internal/output/markdown.go, internal/output/output.go, internal/providers/terraform/azure/testdata/postgresql_flexible_server_test/postgresql_flexible_server_test.tf
GitHub has a limit of 262,144 characters per comment body.
https://github.com/orgs/community/discussions/27190#discussioncomment-3254953
=> enhance: Truncate GitHub comment if it's too large

internal/vcs/metadata.go
Resolves issue where providing Infracost PR env variable `INFRACOST_VCS_PULL_REQUEST_URL` for a VCS provider that doesn't have specific metadata logic (e.g. Jenkins) will send a blank pr url to the dashboard.
See this slack thread for more info: https://infracost-community.slack.com/archives/C01G63Q4HS7/p1660511891023239
=> fix: use pr URL for local git metadata if provided

cmd/infracost/hcl_test.go, cmd/infracost/testdata/hcllocal_object_mock/hcllocal_object_mock.golden, cmd/infracost/testdata/hcllocal_object_mock/main.tf, internal/hcl/attribute.go, internal/hcl/context.go, internal/hcl/parser_test.go
This is a potential fix for https://github.com/infracost/infracost/issues/1760.
This fixes 2 underlying issues:
1. When evaluating local objects with mocks, bad variables from objects weren't supported, which meant the whole object is mocked instead of specififc values
2. When merging object variables the arg order was incorrect, which meant a mocked value was overritten as an unknown type
=> fix: fix HCL parsing values within local objects

cmd/infracost/breakdown_test.go, cmd/infracost/testdata/breakdown_terragrunt_iamroles/breakdown_terragrunt_iamroles.golden, cmd/infracost/testdata/breakdown_terragrunt_iamroles/main.tf, cmd/infracost/testdata/breakdown_terragrunt_iamroles/terragrunt.hcl, internal/providers/terraform/terragrunt_hcl_provider.go
Previously if the user had `iam_role` set in their Terragrunt config we were assuming the role like Terragrunt does. This was failing in cases where the AWS credentials were not availability in the environment. Since we're parsing the HCL we don't make any calls to the AWS APIs so don't need to assume the role.
=> fix: don't assume role when parsing Terragrunt

go.mod, go.sum
fixes: https://github.com/infracost/infracost/issues/1987
This change updates the `go-git` module to the latest master snapshot. Which includes fixes for the panics reported by a user.
=> chore: update go-git to use the latest master hash

internal/providers/terraform/azure/linux_virtual_machine.go, internal/providers/terraform/azure/testdata/linux_virtual_machine_test/linux_virtual_machine_test.golden, internal/providers/terraform/azure/testdata/linux_virtual_machine_test/linux_virtual_machine_test.tf
Regarding [issue 1982](https://github.com/infracost/infracost/issues/1982), VM size in Azure needs to be case insensitive.
=> feat(Azure): Add support for case insensitive Azure VM sizes

cmd/infracost/main.go
Uses the correct IsCloudEnabled method to set `cloudEnabled` telemetry.
=> fix: use context method for cloud enabled telemetry value

cmd/infracost/testdata/upload_help/upload_help.golden, cmd/infracost/upload.go
=> fix: break help text into multiple lines

internal/vcs/metadata.go, internal/vcs/metadata_test.go
Changes the metadata fetcher to set a vcs provider from the host if it has not been provided already. This is useful for deployment platforms like atlantis.
=> fix: detect vcs provider from remote if not provided

internal/apiclient/client.go
adds debug line to log similar to following:
```
'POST' request to '/graphql' using trace_id: '4af66d3e-38a7-4ef6-85ee-0b327125eca2'
```
which means we can trace the cli run through the graphql server.
=> chore: add debug line on client requests

internal/apiclient/pricing.go
removes `repoMetadata` key from `env` sent to `/events`
=> fix: filter `repoMetadata` from telemetry

.github/workflows/create-release.yml
GitHub runner-images have removed homebrew from the $PATH on Ubuntu images. See https://github.com/actions/runner-images/issues/6283 for more information.
This changes add linuxbrew to the release path so that prior steps work as intended.
=> fix: add linuxbrew to release path

cmd/infracost/run.go, cmd/infracost/testdata/breakdown_with_actual_costs/breakdown_with_actual_costs.golden, internal/apiclient/usage.go, internal/hcl/block.go, internal/prices/usages.go, internal/providers/terraform/aws/aws.go, internal/providers/terraform/azure/azure.go, internal/providers/terraform/google/google.go, internal/providers/terraform/parser.go, internal/providers/terraform/registry.go, internal/schema/core_resource.go, internal/schema/project.go, internal/schema/registry_item.go
This collects and uploads aws arns to the usage API when it is enabled.  There is additional work needed to collect non-arn aws ids and (eventually) google and azure ids.
=> feat: Upload cloud resource ids when usage api is enabled

internal/providers/terraform/azure/application_gateway.go, internal/providers/terraform/azure/cdn_endpoint.go, internal/providers/terraform/azure/cosmosdb_cassandra_keyspace.go, internal/providers/terraform/azure/dns_zone.go, internal/providers/terraform/azure/event_hubs_namespace.go, internal/providers/terraform/azure/lb.go, internal/providers/terraform/azure/lb_rule.go, internal/providers/terraform/azure/managed_disk.go, internal/providers/terraform/azure/mysql_server.go, internal/providers/terraform/azure/mysql_server_test.go, internal/providers/terraform/azure/public_ip.go, internal/providers/terraform/azure/testdata/mysql_server_test/mysql_server_test.golden, internal/providers/terraform/azure/virtual_machine.go, internal/resources/aws/kinesis_firehose_delivery_stream.go, internal/resources/aws/s3_intelligent_tiering_storage_class.go, internal/resources/azure/frontdoor.go, internal/resources/azure/frontdoor_firewall_policy.go, internal/resources/azure/log_analytics_workspace.go, internal/resources/azure/sql_database.go, internal/resources/azure/sql_managed_instance.go
The Azure API updated a lot of meter names.
This will fail the tests until the API is also updated with changes, but I've validated against a dev Cloud Pricing API.
=> fix(azure): fix cost component regexes

internal/resources/aws/s3_storage_class_helpers.go
Relax the usage type regex since the usage type key for regions other than us-east-1 are prefixed by the region code, e.g. "USE2-Requests-Tier4"
=> fix: s3 bucket "No products found for Lifecycle transition" in us-east 2

cmd/infracost/run.go
@aliscott I dunno if we want to merge this, but it simplifies generating resource ids by letting us run with `--config-file=infracost.yml --terraform-force-cli --terraform-use-state`
=> enhance: Allow --terraform-use-state flag with --config-file

internal/hcl/parser.go
fixes issue where module exclusion was not working as the path was not relative to the working directory. This meant that modules like `module/t` was being marked as `../module/t`. We now join the path to the working directory evaluating `..module/t` under the `./dev` path would result in `module/t`
=> fix: module source path

internal/providers/terraform/aws/testdata/waf_web_acl_test/waf_web_acl_test.golden, internal/providers/terraform/aws/waf_web_acl_test.go, internal/resources/aws/db_instance.go
This fixes the AWS DB instance so it uses the price for the io1 IOPs instead of the new gp3 IOPs.
We should add support for gp3 for RDS after https://github.com/hashicorp/terraform-provider-aws/pull/27670 is finalized. I had a quick look, but it's not clear yet what the attribute for throughput will be called.
=> fix(aws): fix DB instance cost component lookup

internal/providers/terraform/azure/kubernetes_cluster.go, internal/providers/terraform/azure/kubernetes_cluster_node_pool.go, internal/providers/terraform/azure/testdata/kubernetes_cluster_node_pool_test/kubernetes_cluster_node_pool_test.golden, internal/providers/terraform/azure/testdata/kubernetes_cluster_node_pool_test/kubernetes_cluster_node_pool_test.tf, internal/providers/terraform/azure/testdata/kubernetes_cluster_test/kubernetes_cluster_test.golden, internal/providers/terraform/azure/testdata/kubernetes_cluster_test/kubernetes_cluster_test.tf
Resolves issue where users specifying only `min_count` for node pools were receiving count = 1;
=> fix: use min_count for node pool size if node_count not specified

internal/resources/aws/util.go
Currently, CPAPI doesn't have any products with this region or location. However, this will automatically start working when the products are added.
https://aws.amazon.com/blogs/aws/now-open-aws-region-in-spain/
=> chore(aws): Add new region mapping for eu-south-2

internal/providers/terraform/aws/instance.go, internal/providers/terraform/aws/testdata/instance_test/instance_test.golden, internal/providers/terraform/aws/testdata/instance_test/instance_test.tf, internal/resources/aws/instance.go
=> enhance(aws): Skip compute cost component when AWS instance has an EC2 host

internal/providers/terraform/google/compute_instance.go, internal/resources/google/compute_cost_component_helpers.go, internal/resources/google/compute_instance.go, internal/resources/google/compute_instance_group_manager.go, internal/resources/google/compute_region_instance_group_manager.go, internal/resources/google/container_node_pool.go
**Why is this PR necessary**?
In order to provide the pricing for GCP custom instances (e.g custom-20-20480),, we need to adapt the attribute filters not to search by machine type but by the amount of CPU and RAM specified.
**What does it do**?
This PR creates a new function `customComputeCostComponent` similar to `computeCostComponent`. 
Also, it adds conditionals for verifying whether the node pool or the VM are using a custom machine type or not.
**References**:
https://github.com/infracost/infracost/issues/1447
https://cloud.google.com/compute/docs/instances/creating-instance-with-custom-machine-type#create
=> feat(google): Handle custom compute instances

cmd/infracost/breakdown_test.go, cmd/infracost/testdata/breakdown_with_depends_upon_module/breakdown_with_depends_upon_module.golden, cmd/infracost/testdata/breakdown_with_depends_upon_module/main.tf, cmd/infracost/testdata/breakdown_with_depends_upon_module/tf-module/main.tf, cmd/infracost/testdata/breakdown_with_depends_upon_module/tf-rds/main.tf, cmd/infracost/testdata/breakdown_with_depends_upon_module/tf-rds/test/main.tf, internal/hcl/evaluator.go
fixes: https://github.com/infracost/infracost/issues/1983
Resolves issue where a `depends_upon` block that held a module lower down in the file context was causing the module to re-evaluate. This is because the first evalutation of the file sees that the input for `depends_upon` was a `cty.unkown` value because the context did not contain the evaluation context. When the module has been properly evaluated and exported to outputs, e.g. `module.mymodule` we then reevaluate the module. However, this time the module uses the old module contained in `e.evaluatedModules` cache, meaning it had `Blocks` that were marked as expanded but where not added to the `EvaluationContext`. Therefore they were emitted from the output. We should always pass a fresh `evaluatedModules` cache to a child …
=> fix: pass fresh evaluation lookup map to child module evaluation

internal/hcl/evaluator.go, internal/hcl/funcs/debug.go
adds support for infracost specific debug functions, that print/log inputs during the Terraform evaluation. This will help us resolve HCL issues quicker.
=> feat: hcl debug funcs

cmd/infracost/testdata/breakdown_terragrunt_hcldeps_output/breakdown_terragrunt_hcldeps_output.golden, cmd/infracost/testdata/breakdown_terragrunt_hcldeps_output/dev/terragrunt.hcl, cmd/infracost/testdata/breakdown_terragrunt_hcldeps_output/modules/example/main.tf, cmd/infracost/testdata/breakdown_terragrunt_hcldeps_output/modules/example2/main.tf, cmd/infracost/testdata/breakdown_terragrunt_hcldeps_output/prod/terragrunt.hcl, internal/hcl/attribute.go, internal/hcl/parser_test.go, internal/providers/terraform/terragrunt_hcl_provider.go
* Resolves issues where Terragrunt cannot parse an input file because the dependency outputs are not available. This can happen if outputs are mocked and a complex object or list is unavailable. This PR fixes this by merging actual Terraform outputs with missing outputs identified using regular expressions.
* Resolves an issue where mocked values which used index entries were returning an incorrect value type of an empty object. This meant that we were passing an unknown type into the Terragrunt inputs.
=> fix: merge terraform outputs with built naive regexp output mocks

cmd/infracost/comment.go, cmd/infracost/comment_github_test.go, cmd/infracost/run.go, cmd/infracost/testdata/changes.json, cmd/infracost/testdata/comment_git_hub_show_changed_projects/comment_git_hub_show_changed_projects.golden, internal/config/config.go, internal/hcl/module.go, internal/hcl/parser.go, internal/hcl/parser_test.go, internal/hcl/project_locator.go, internal/hcl/project_locator_test.go, internal/output/markdown.go, internal/output/output.go, internal/output/templates.go, internal/providers/terraform/hcl_provider.go, internal/schema/project.go, internal/vcs/metadata.go, internal/vcs/metadata_test.go, schema/infracost.schema.json
Adds support to track git changes for HCL projects. If changes can be detected, we set the `vcsCodeChanged` project metadata field on any projects that have been modified. This behaviour is works with the `show-changed` flag that `infracost comment` supports.
=> feat: track git changes in project metadata

internal/output/markdown.go
Increment the skipped code changes projects if the flag has been set and there are **no** code changes
=> fix: use correct metric to display skipped unchanged project

.github/workflows/create-pr-assets.yml, internal/providers/terraform/google/container_cluster_test.go, internal/providers/terraform/google/testdata/container_cluster_test/container_cluster_test.golden, internal/providers/terraform/google/testdata/container_cluster_test/container_cluster_test.tf, internal/resources/google/container_cluster.go
fixes: https://github.com/infracost/infracost/issues/2180
With the changes in `0.10.15` we have introduced a helper function `computeCostComponents` to help with custom instance types. However this now returns an error and alters `ContainerNodePool` to return nil on unsupported machine types. See https://github.com/infracost/infracost/blob/master/internal/resources/google/container_node_pool.go#L48-L52. The `ContainerCluster` resource was incorrectly setting these nils as valid sub resources which caused a panic.
Adds an additional pipeline step to build and upload release assets to the PR so that we can send these to contributors to review and see if it fixes there issue.
=> fix: container_cluster setting nil node pool as sub resource

cmd/infracost/run.go, internal/config/run_context.go, internal/providers/terraform/hcl_provider.go, internal/providers/terraform/hcl_provider_test.go
Changes the auto-detection functionality to run discovered projects in parallel. This is faster and inline with the `config-file` behaviour.
=> feat: run auto-detected projects in parallel

internal/hcl/attribute.go, internal/hcl/evaluator.go, internal/hcl/remote_variables_loader.go, internal/providers/terraform/hcl_provider.go, internal/providers/terraform/terragrunt_hcl_provider.go
gocty.ToCtyValue panics if any type provided to it is nil. This can happen if we use NilVal at any point in the context evaluation. I've removed all references of NilVal for attributes/variable evaluation in favour of DynamicVal which is an Unknown type, and should be conversion safe. I've also wrapped the problem function in a recover statement to catch any panics that might arise due to unforseen evaluation problems. This means that the terragrunt inputs would use a safe default of mocked values rather than just exiting.
=> fix: panic arising from cty conversion of cty.NilVal

cmd/infracost/testdata/breakdown_terragrunt_hcldeps_output/breakdown_terragrunt_hcldeps_output.golden, cmd/infracost/testdata/breakdown_terragrunt_hcldeps_output/dev/terragrunt.hcl, cmd/infracost/testdata/breakdown_terragrunt_hcldeps_output/modules/example3/main.tf, cmd/infracost/testdata/breakdown_terragrunt_hcldeps_output/stag/terragrunt.hcl, internal/providers/terraform/terragrunt_hcl_provider.go
Resolves issue where the object attribute to mock had a trailing `]` appended to the key if the dependency was within a array.
=> fix: array notation causing issues with mocking terragrunt deps

internal/hcl/block.go, internal/hcl/evaluator.go, internal/hcl/module.go, internal/hcl/parser_test.go, internal/providers/terraform/terragrunt_hcl_provider.go
Resolves various issue within the Evaluator which was causing module for_each attributes to not be expanded correctly.
* Solves issue where for_each that references a Block that doesn't need to be expanded was never getting expanded as we were always checking if Block.expanded was true even if the Block had no count/for_each
* When modules are expanded we now set the EvaluationContext to have the correct Variables. Prior to this change expanded modules were being set with their expansion key in the name. e.g:
```
module "foo" {
source = "../foo"
for_each = {
"one" = {
"bar" = "bat"
}
"two" = {
...
}
}
bar      = each.value.bar
}
```
would have been set in the context to:
```
module
foo
foo[one]
bar: bat
foo[two]
...
```
instead of of the correct format:
```
module
foo
one
bar: bat
two
... …
```
=> fix: module for_each attributes not expanding correctly

cmd/infracost/hcl_test.go, internal/providers/terraform/hcl_provider.go
fixes #2231
With the change to the top-level .infracost folder, if an absolute path is used for config-file or path resolution then we fail to build the correct paths for modules. This PR changes the project path passed to the `Parser` to be abs if the initial path (--config-file/--path) is absolute.
=> fix: change project paths to absolute path if initial --config-file path is abs

cmd/infracost/testdata/comment_git_hub_show_all_projects/comment_git_hub_show_all_projects.golden, cmd/infracost/testdata/output_format_bitbucket_comment_with_project_names/output_format_bitbucket_comment_with_project_names.golden, cmd/infracost/testdata/output_format_git_hub_comment_show_all_projects/output_format_git_hub_comment_show_all_projects.golden, cmd/infracost/testdata/output_format_git_hub_comment_with_project_names_with_metadata/output_format_git_hub_comment_with_project_names_with_metadata.golden, cmd/infracost/testdata/output_format_git_hub_comment_without_module_path/infracost.json, cmd/infracost/testdata/output_format_git_hub_comment_without_module_path/output_format_git_hub_comment_without_module_path.golden, internal/output/markdown.go
We should still take into account skipped projects when showing the comment summary so users can still identify which project changed.
=> fix: comment is hiding module path when projects are skipped

internal/hcl/attribute.go, internal/hcl/block.go, internal/hcl/evaluator.go, internal/hcl/parser_test.go, internal/providers/terraform/registry.go, internal/providers/terraform/terragrunt_hcl_provider.go
When expanding a module we pass the `each.value` to it's definition block to set as initial vars in the child `Evaluator`. If the module `for_each` depends on a value that is yet to be known in the evaluation `Context` then the `each.value` will be incomplete.
This PR fixes this issue by:
1. Checking if `Blocks` in the evaluation loop `HaveChanged` to their `for_each` attribute. If they do then we expand these blocks again, setting the lower level `each.value` to the correct value.
3. We now keep track of `ModuleCalls` as a map, which allows us to lookup if the changed `Blocks` correspond to a loaded `ModuleCall`. If they do we reset the `Definition` block to the newly expanded one with the correct value.
4. This means that in `evaluateModules` call in the `Evaluator` that we see that the …
=> fix: reload ModuleCall when `each.value` changes

internal/providers/terraform/azure/mssql_database.go, internal/providers/terraform/azure/testdata/mssql_database_test/mssql_database_test.golden, internal/providers/terraform/azure/testdata/mssql_database_test/mssql_database_test.tf
The costs apply on azure_sql_elastic_pool resource.
From #569:
> If this is ElasticPool then this resource has no cost since it will be handled by the azurerm_sql_elastic_pool resource.
Related to #1259.
=> fix(azure): Mark MSSQL database as free when its SKU is ElasticPool

cmd/infracost/run.go, cmd/infracost/testdata/config_file_nil_projects_errors/config_file_nil_projects_errors.golden, internal/config/config_file.go, internal/config/config_test.go
I don't think we really need to show an error in this case, and this makes it a lot easier to work with config templates.
=> enhance: allow an empty list of projects to be run

scripts/install.sh
This PR allows the installer to download a specific version of infracost based on the INFRACOST_VERSION variable. Default to latest
=> feat(installer): Allow installer to download any version

internal/hcl/evaluator.go, internal/providers/terraform/testdata/hcl_provider_test/populates_warnings_on_missing_vars/main.tf
Removes sensitive variables from warnings output. Variables are omitted if they are:
* marked as `sensitive`
* contain a substring from a predetermined list of strings
=> refactor: ignore sensitive vars from warnings

internal/providers/terraform/parser.go, internal/providers/terraform/tftest/tftest.go, internal/schema/core_resource.go, internal/schema/project.go
This prevents the warning logs from being outputted twice.
We could improve this further by checking the existence of each resource individually, but for now this only handles the case where there is no diff.
=> fix: don't query resources twice if past resources are the same as current resources

cmd/infracost/breakdown_test.go, cmd/infracost/testdata/breakdown_terraform_directory_with_default_var_files/abs.tfvars, cmd/infracost/testdata/breakdown_terraform_directory_with_default_var_files/hcl.tfvars, internal/hcl/parser.go
Fixes https://github.com/infracost/infracost/issues/2166
This change enables users to pass absolute paths to the `--terraform-var-file` flag. This allows for greater composability of projects, and helps users who have a top level global var file directory.
=> feat: support absolute filepaths for terraform var files

internal/config/run_context.go
Resolves panic for unguarded write to `r.contextVals`.
=> fix: concurrent write to `RunContext` context values

cmd/infracost/output_test.go, cmd/infracost/run.go, cmd/infracost/testdata/breakdown_init_flags_error/breakdown_init_flags_error.hcl.golden, cmd/infracost/testdata/breakdown_invalid_path/breakdown_invalid_path.golden, cmd/infracost/testdata/breakdown_multi_project_with_all_errors/breakdown_multi_project_with_all_errors.golden, cmd/infracost/testdata/breakdown_multi_project_with_error/breakdown_multi_project_with_error.golden, cmd/infracost/testdata/breakdown_plan_error/breakdown_plan_error.golden, cmd/infracost/testdata/config_file_nil_projects_errors/config_file_nil_projects_errors.golden, cmd/infracost/testdata/errors.json, cmd/infracost/testdata/no_project.json, cmd/infracost/testdata/output_format_git_hub_comment_no_project/output_format_git_hub_comment_no_project.golden, cmd/infracost/testdata/output_format_git_hub_comment_with_all_error/output_format_git_hub_comment_with_all_error.golden, cmd/infracost/testdata/output_format_table_with_error/output_format_table_with_error.golden, internal/output/markdown.go, internal/output/table.go, internal/output/templates.go, internal/providers/detect.go
This change removes the early exit in the CLI if all projects have errored. This means that the CLI output will always return a successful list of projects even if all of them have errored. This means that the output JSON will be generated correctly if all projects have errored. This change also removes the output table from the comment if there are no projects in the output JSON.
=> feat: show all errored project

cmd/infracost/testdata/output_format_git_hub_comment_with_all_error/output_format_git_hub_comment_with_all_error.golden, internal/output/markdown.go, internal/output/templates.go
Resolves issue where the template attempts to render a single errored/invalid project.
=> fix: hide table if all projects are invalid

internal/hcl/block.go, internal/hcl/evaluator.go, internal/hcl/parser_test.go
Resolves issue where dynamic blocks add duplicate expanded blocks into the `childBlocks` of the parent module. For example:
Take the following root module definition:
```
data "bad_state" "bad" {}
module "reload" {
source         = "./baz"
input = [
{
"ip"        = "10.0.0.0"
"mock" = data.bad_state.bad.my_bad["10.0.0.0/24"].id
},
{
"ip"        = "10.0.1.0"
"mock" = data.bad_state.bad.my_bad["10.0.0.0/24"].id
}
]
}
```
which calls out to a module with the following terraform:
```
variable "input" {}
resource "dynamic" "resource" {
dynamic "child_block" {
for_each = {
for i in var.input : i.ip => i
}
content {
bar = child_block.value.mock
foo = child_block.value.ip
}
}
}
```
Prior to this change the `length` of `child_block` would be 4 instead of the expected 2. This is because on first …
=> fix: prevent expanding dynamic blocks injecting more than once

cmd/infracost/run.go
Removes the requirement for projects with the same path to be run sync. Speeds up config file runs for HCL.
=> fix: only lock terraform cli projects to run sync

infracost-usage-example.yml, internal/providers/terraform/aws/lambda_function.go, internal/providers/terraform/aws/lambda_provisioned_concurrency_config.go, internal/providers/terraform/aws/lambda_provisioned_concurrency_config_test.go, internal/providers/terraform/aws/registry.go, internal/providers/terraform/aws/testdata/lambda_provisioned_concurrency_config_test/lambda_provisioned_concurrency_config_test.golden, internal/providers/terraform/aws/testdata/lambda_provisioned_concurrency_config_test/lambda_provisioned_concurrency_config_test.tf, internal/providers/terraform/aws/testdata/lambda_provisioned_concurrency_config_test/lambda_provisioned_concurrency_config_test.usage.yml, internal/resources/aws/lambda_provisioned_concurrency_config.go
Adds new resource `aws_lambda_provisioned_concurrency_config` to support provisioned concurrency in lambda. I think there's potentially more that can be done to merge with `aws_lambda_function`. I did try to use the references logic within the code but couldn't get it to work. This resource provides 2 cost components, duration & concurrency. 
Closes more of #2138
=> Feat:(AWS) Adds Lambda provisioned concurrency

go.mod, go.sum, infracost-usage-example.yml, internal/providers/terraform/azure/mssql_database.go, internal/providers/terraform/azure/mssql_elasticpool.go, internal/providers/terraform/azure/mssql_elasticpool_test.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/sql_database.go, internal/providers/terraform/azure/sql_elasticpool.go, internal/providers/terraform/azure/sql_elasticpool_test.go, internal/providers/terraform/azure/sql_managed_instance.go, internal/providers/terraform/azure/sql_managed_instance_test.go, internal/providers/terraform/azure/testdata/mssql_database_test/mssql_database_test.golden, internal/providers/terraform/azure/testdata/mssql_database_test/mssql_database_test.tf, internal/providers/terraform/azure/testdata/mssql_database_test/mssql_database_test.usage.yml, internal/providers/terraform/azure/testdata/mssql_database_test_with_blank_location/mssql_database_test_with_blank_location.golden, internal/providers/terraform/azure/testdata/mssql_elasticpool_test/mssql_elasticpool_test.golden, internal/providers/terraform/azure/testdata/mssql_elasticpool_test/mssql_elasticpool_test.tf, internal/providers/terraform/azure/testdata/sql_database_test/sql_database_test.golden, internal/providers/terraform/azure/testdata/sql_database_test/sql_database_test.tf, internal/providers/terraform/azure/testdata/sql_database_test/sql_database_test.usage.yml, internal/providers/terraform/azure/testdata/sql_elasticpool_test/sql_elasticpool_test.golden, internal/providers/terraform/azure/testdata/sql_elasticpool_test/sql_elasticpool_test.tf, internal/providers/terraform/azure/testdata/sql_managed_instance_test/sql_managed_instance_test.golden, internal/resources/azure/mssql_elasticpool.go, internal/resources/azure/sql_database.go, internal/resources/azure/sql_managed_instance.go, internal/schema/cost_component.go
This adds support for the `azurerm_mssql_elasticpool` resource and the deprecated `azurerm_sql_elasticpool` resource.
It also fixes some issues with the existing `azurerm_mssql_database` resource:
1. Fix zone redundancy costs. These are added on top of the compute costs, not instead of.
2. Don't show extra data prices if there's no usage.
3. Support the different storage types for long term retention
4. Add PITR cost component
5. Show DTU cost components as hours so the units and costs match the Azure dashboard and pricing calculator.
6. Fix some issues to support non-case-sensitive attribute values
I think we can remove the `extra_data_storage_gb` usage param from `azurerm_mssql_database` since its value is always defined in Terraform. I haven't done that as part of this PR though.
=> Add MSSQL Elastic Pool

cmd/infracost/breakdown_test.go, cmd/infracost/testdata/breakdown_terragrunt_with_parent_include/breakdown_terragrunt_with_parent_include.golden, cmd/infracost/testdata/breakdown_terragrunt_with_parent_include/infra/us-east-1/dev/terragrunt.hcl, cmd/infracost/testdata/breakdown_terragrunt_with_parent_include/infra/us-east-1/modules/example/main.tf, cmd/infracost/testdata/breakdown_terragrunt_with_parent_include/infra/us-east-1/regions.yml, cmd/infracost/testdata/breakdown_terragrunt_with_parent_include/terragrunt.hcl, internal/providers/terraform/terragrunt_hcl_provider.go
Resolves issue when a parent `terragrunt.hcl` file was using any `find` or `get` functions. These functions are called relative to the original Terragrunt config (the child `terragrunt.hcl` file). Thus any file include would fail with a not exists error. We now ignore parent `terragrunt.hcl` from initial evaluation and only read it when it is included by a child `terragrunt.hcl` (expected behaviour).
=> fix: ignore parent terragrunt.hcl files in a Terragrunt directory

internal/hcl/block.go
Adds `self_link` to the supported hcl generated uuid references. `self_link` is a specific google provider way to link resources (like id), see: https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/getting_started#linking-gcp-resources, for more information.
=> fix: support google self_link as a uuid attribute

internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/service_plan.go, internal/providers/terraform/azure/service_plan_test.go, internal/providers/terraform/azure/testdata/app_service_plan_test/app_service_plan_test.golden, internal/providers/terraform/azure/testdata/app_service_plan_test/app_service_plan_test.tf, internal/providers/terraform/azure/testdata/service_plan_test/service_plan_test.golden, internal/providers/terraform/azure/testdata/service_plan_test/service_plan_test.tf, internal/resources/azure/app_service_plan.go, internal/resources/azure/service_plan.go
closes https://github.com/infracost/infracost/issues/2329
* adds `service_plan` resource
* changes `app_service_plan` resource to pick up new plan types
* marks web apps as free resource as these have no costs associated with then, due to the service plan
=> feat: add remaining azure app service terraform components

internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/storage_account.go, internal/providers/terraform/azure/storage_queue.go, internal/providers/terraform/azure/storage_queue_test.go, internal/providers/terraform/azure/testdata/storage_account_test/storage_account_test.golden, internal/providers/terraform/azure/testdata/storage_account_test/storage_account_test.tf, internal/providers/terraform/azure/testdata/storage_account_test/storage_account_test.usage.yml, internal/providers/terraform/azure/testdata/storage_queue_test/storage_queue_test.golden, internal/providers/terraform/azure/testdata/storage_queue_test/storage_queue_test.tf, internal/providers/terraform/azure/testdata/storage_queue_test/storage_queue_test.usage.yml, internal/resources/azure/storage_account.go, internal/resources/azure/storage_queue.go
* Adds BlobStorage costs 
* Adds Storage v1 costs
* Adds Queue Storage costs with support for Storage v1 and Storage v2 accounts
=> Add Azure storage costs (BlobStorage, StorageV1, QueueStorage)

infracost-usage-example.yml, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/storage_share.go, internal/providers/terraform/azure/storage_share_test.go, internal/providers/terraform/azure/testdata/storage_share_test/storage_share_test.golden, internal/providers/terraform/azure/testdata/storage_share_test/storage_share_test.tf, internal/providers/terraform/azure/testdata/storage_share_test/storage_share_test.usage.yml, internal/resources/azure/storage_account.go, internal/resources/azure/storage_share.go
This adds support for Azure File Shares. There's some overlap with `azurerm_storage_account` when `account_kind = FileStorage`, but I think that's okay since there's more flexibility with what they can do with `azure_storage_share` and we shouldn't break backwards compatibility. Everything can be adjusted with the usage file to make sure one resource get the cost.
There's also some overlapping logic with this and `azurerm_storage_account` but I decided to keep it separate for just now - unpicking the `azurerm_storage_account` resource was getting a bit messy.
=> feat(azure): add support for Storage File Shares

cmd/infracost/generate.go, internal/config/template/parser.go, internal/config/template/parser_test.go, internal/config/template/testdata/with_top_level_template_data/infracost.golden.yml, internal/config/template/testdata/with_top_level_template_data/infracost.yml.tmpl
Adds support for default data to be passed into the template parser. This allows up to provide top level metadata variables that users can interact with. Currently the only supported variable is `.branch` which represents the current branch name of the repo, e.g. `main`, `test`.
=> feat: default variables for infracost config template files

internal/hcl/block.go, internal/hcl/parser_test.go, internal/providers/terraform/aws/aws.go, internal/providers/terraform/aws/testdata/autoscaling_group_test/autoscaling_group_test.golden, internal/providers/terraform/aws/testdata/autoscaling_group_test/autoscaling_group_test.tf
This PR adds support to use `name` as a global resource reference. This resolves issues with resources that reference dependent resources with `name`. For example aws_autoscaling_group.launch_configuration:
```
resource "aws_autoscaling_group" "asg_lc_min_size_name_ref" {
launch_configuration = aws_launch_configuration.lc_basic.name
max_size             = 3
min_size             = 2
}
```
Prior to this change `asg_lc_min_size_name_ref` would have blank references. I've decided to put move the `name` into the default resource ID func as I believe referencing a resource by `name` is probably quite a common pattern across a wide range of resources.
=> fix: support name as a global aws resource ref

internal/providers/terraform/aws/db_instance.go, internal/providers/terraform/aws/testdata/db_instance_test/db_instance_test.golden, internal/providers/terraform/aws/testdata/db_instance_test/db_instance_test.tf, internal/resources/aws/db_instance.go
closes: https://github.com/infracost/infracost/issues/2284
Adds support for gp3 volumes and provisioned GP3 IOPS. These IOPS are only shown when above the stated baseline/threshold that aws provides for the DB size.
=> fix: support RDS gp3 volumes

infracost-usage-example.yml, internal/providers/terraform/azure/eventgrid_system_topic.go, internal/providers/terraform/azure/eventgrid_system_topic_test.go, internal/providers/terraform/azure/eventgrid_topic.go, internal/providers/terraform/azure/eventgrid_topic_test.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/testdata/eventgrid_system_topic_test/eventgrid_system_topic_test.golden, internal/providers/terraform/azure/testdata/eventgrid_system_topic_test/eventgrid_system_topic_test.tf, internal/providers/terraform/azure/testdata/eventgrid_system_topic_test/eventgrid_system_topic_test.usage.yml, internal/providers/terraform/azure/testdata/eventgrid_topic_test/eventgrid_topic_test.golden, internal/providers/terraform/azure/testdata/eventgrid_topic_test/eventgrid_topic_test.tf, internal/providers/terraform/azure/testdata/eventgrid_topic_test/eventgrid_topic_test.usage.yml, internal/resources/azure/eventgrid_topic.go
closes: https://github.com/infracost/infracost/issues/2303
Adds support for `azurerm_eventgrid_system_topic` and `azurerm_eventgrid_topic`. These are both usage only resources and are billed per 100k operations (over the 100k free tier).
=> feat(azure): Event Grid support

internal/providers/terraform/azure/network_connection_monitor.go, internal/providers/terraform/azure/network_connection_monitor_test.go, internal/providers/terraform/azure/network_watcher.go, internal/providers/terraform/azure/network_watcher_flow_log.go, internal/providers/terraform/azure/network_watcher_flow_log_test.go, internal/providers/terraform/azure/network_watcher_test.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/testdata/network_connection_monitor_test/network_connection_monitor_test.golden, internal/providers/terraform/azure/testdata/network_connection_monitor_test/network_connection_monitor_test.tf, internal/providers/terraform/azure/testdata/network_connection_monitor_test/network_connection_monitor_test.usage.yml, internal/providers/terraform/azure/testdata/network_watcher_flow_log_test/network_watcher_flow_log_test.golden, internal/providers/terraform/azure/testdata/network_watcher_flow_log_test/network_watcher_flow_log_test.tf, internal/providers/terraform/azure/testdata/network_watcher_flow_log_test/network_watcher_flow_log_test.usage.yml, internal/providers/terraform/azure/testdata/network_watcher_test/network_watcher_test.golden, internal/providers/terraform/azure/testdata/network_watcher_test/network_watcher_test.tf, internal/providers/terraform/azure/testdata/network_watcher_test/network_watcher_test.usage.yml, internal/resources/azure/network_connection_monitor.go, internal/resources/azure/network_watcher.go, internal/resources/azure/network_watcher_flow_log.go
Closes https://github.com/infracost/infracost/issues/1255
=> Add Azure Network Watcher

internal/vcs/metadata.go, internal/vcs/metadata_test.go
Changes pull request url to the valid https URL if provided in the `https://user@dev.azure.com/org/project/_git/repo` format.
=> fix: sanitize azure pull request URL

Dockerfile.wolfi, Dockerfile.wolfi-ci, Dockerfile.wolfi-latest
Hey, I think I owe you this from a while back.
Here's a PR with wolfi versions of the Dockerfiles. `Dockerfile.wolfi` is a straight port from the regular Dockerfile. `Dockerfile.wolfi-ci` is a straight port of `Dockerfile.ci`. You should find the wolfi images have less vulns, though there does seem to be a couple from the infracost libs ~~and also some from libssl (which seems to be an issue with our openssh-client package that I'm currently investigating).~~ (turns out the libssl vuln was my fault for building with a slightly old version of wolfi-base)
`Dockerfile.wolfi-latest` is a bit more interesting - it only includes the latest versions of terraform and terragrunt (I did notice the versions specified in the Dockerfile are pretty out-of-date). This cuts the image down to 220MB and …
=> Add example Wolfi Dockerfiles

internal/providers/terraform/google/container_cluster.go, internal/providers/terraform/google/testdata/container_node_pool_test/container_node_pool_test.golden, internal/providers/terraform/google/testdata/container_node_pool_test/container_node_pool_test.tf
This is a fix of #2359 for the spot instance pools in GKE, which are now priced like on-demand instances, while they should be priced like the preemptible instances.
=> fix: price spot like preemptible, not on-demand (#2359)

cmd/infracost/main.go, cmd/infracost/run.go, cmd/infracost/scan.go, internal/config/config.go, internal/config/config_test.go
When a config file was used, the `INFRACOST_LOG_LEVEL` env var was overriding the `--log-level` flag. The flag should have precendence over the env var.
=> fix: `INFRACOST_LOG_LEVEL` overriding `--log-level` flag

internal/hcl/parser.go, internal/providers/terraform/hcl_provider_test.go, internal/providers/terraform/testdata/hcl_provider_test/shows_correct_duplicate_variable_warning/expected.json, internal/providers/terraform/testdata/hcl_provider_test/shows_correct_duplicate_variable_warning/main.tf, internal/providers/terraform/testdata/hcl_provider_test/shows_correct_duplicate_variable_warning/terraform.tfvars
Changes terraform var file loader to ignore the Attribute Redefined errors and continue to load the var file.
=> fix: ignore duplicate variable diagnostics when loading var files

internal/hcl/parser.go
This makes sure the parsing order is consistent so we don't get differences for mocked values depending on the order the files were loaded.
=> fix: load the HCL files in a consistent order

internal/config/config.go, internal/config/config_test.go, internal/config/testdata/.gitignore, internal/providers/terraform/hcl_provider.go, internal/providers/terraform/terragrunt_hcl_provider.go
attempt to find the cache path in parent directories given a starting path. Resolves issue where multiple `.infracost` directories are created in vscode-infracost extension.
=> feat: traverse parent directories to find .infracost cache folder

internal/apiclient/auth.go
cases when user is logging in on a remote server
The output `infracost auth login` now looks like this:
```sh
We're redirecting you to our log in page, please complete that,
and return here to continue using Infracost.
If the redirect doesn't work, either:
- Use this URL:
https://dashboard.infracost.io/login?cli_port=58186&cli_state=8cxxxxxxx&cli_version=v0.10.22&os=darwin&utm_source=cli
- Or log in/sign up at https://dashboard.infracost.io, copy your API key
from Org Settings and run `infracost configure set api_key MY_KEY`
Waiting...
Error: Authentication failed. Please get your API token from https://dashboard.infracost.io
```
=> chore: tweak auth messaging to provide workaround for

internal/providers/terraform/azure/kubernetes_cluster_node_pool.go, internal/providers/terraform/azure/linux_virtual_machine.go, internal/providers/terraform/azure/testdata/image_test/image_test.golden, internal/providers/terraform/azure/testdata/kubernetes_cluster_node_pool_test/kubernetes_cluster_node_pool_test.golden, internal/providers/terraform/azure/testdata/kubernetes_cluster_node_pool_test/kubernetes_cluster_node_pool_test.tf, internal/providers/terraform/azure/testdata/kubernetes_cluster_test/kubernetes_cluster_test.golden, internal/providers/terraform/azure/testdata/kubernetes_cluster_test/kubernetes_cluster_test.tf, internal/providers/terraform/azure/testdata/linux_virtual_machine_scale_set_test/linux_virtual_machine_scale_set_test.golden, internal/providers/terraform/azure/testdata/linux_virtual_machine_test/linux_virtual_machine_test.golden, internal/providers/terraform/azure/testdata/recovery_services_vault_test/recovery_services_vault_test.golden, internal/providers/terraform/azure/testdata/virtual_machine_scale_set_test/virtual_machine_scale_set_test.golden, internal/providers/terraform/azure/testdata/virtual_machine_test/virtual_machine_test.golden, internal/providers/terraform/azure/testdata/windows_virtual_machine_scale_set_test/windows_virtual_machine_scale_set_test.golden, internal/providers/terraform/azure/testdata/windows_virtual_machine_test/windows_virtual_machine_test.golden, internal/providers/terraform/azure/windows_virtual_machine.go
This also adds `Windows` or `Linux` into the cost component name across all Azure compute resources, consistent with what we do with AWS.
Fixes https://github.com/infracost/infracost/issues/2416
=> feat: add support for AKS Windows node pools

internal/output/markdown.go
Resolves #2518.
Reason: https://github.com/golang/go/issues/45230.
=> fix: Fix templates path for Windows

internal/providers/terraform/aws/elastic_beanstalk_environment.go, internal/providers/terraform/aws/testdata/elastic_beanstalk_environment_test/elastic_beanstalk_environment_test.golden, internal/providers/terraform/aws/testdata/elastic_beanstalk_environment_test/elastic_beanstalk_environment_test.tf
* Support the deprecated InstanceType setting for EB environments
* Elastic Beanstalk uses host tenancy not dedicated tenancy
Fixes https://github.com/infracost/infracost/issues/2497
=> fix(aws): support InstanceType and use host tenancy for EB environments

internal/hcl/block.go, internal/hcl/evaluator.go, internal/hcl/parser.go
e.g:
```hcl
resource "type" "name" {
resource {}
}
```
=> fix: fix panic when a child block is a resource block without labels

cmd/infracost/testdata/breakdown_with_default_tags/breakdown_with_default_tags.golden, cmd/infracost/testdata/breakdown_with_default_tags/main.tf, internal/providers/terraform/hcl_provider.go
Fixes panic where non string tag was panicing when using `.AsString`
=> fix: support bool tags for marshalling

internal/apiclient/dashboard.go
resolves issue where workflow CI users cannot see the "View in Infracost dashboard".
=> fix: add cloudUrl to addRun response

internal/hcl/block.go
From sentry: 
```
runtime error: invalid memory address or nil pointer dereference
"stacktrace": 
"1: running [Created by terraform.(*HCLProvider).Modules @ hcl_provider.go:339]
:24                                                             Stack()
:289                                                            (*Parser).ParseDirectory.func1()
:884                                                            panic()
:126                                                            (*Entry).WithFields()
:121                                                            (*Entry).WithField()
:107                                                            (*Entry).WithError()
:980                                                            (*Block).Reference()
:991 …
```
=> fix: avoid possible nil logger when calculating block name

internal/hcl/block.go, internal/hcl/parser_test.go
Changes `GetAttr` method to use the map indexing which will not panic.
=> fix: panic when aliased provider has no region

cmd/infracost/auth.go, cmd/infracost/breakdown.go, cmd/infracost/comment.go, cmd/infracost/comment_azure_repos.go, cmd/infracost/comment_bitbucket.go, cmd/infracost/comment_github.go, cmd/infracost/comment_gitlab.go, cmd/infracost/main.go, cmd/infracost/output.go, cmd/infracost/run.go, internal/apiclient/dashboard.go, internal/config/project_context.go, internal/config/run_context.go, internal/providers/cloudformation/parser.go, internal/providers/terraform/dir_provider.go, internal/providers/terraform/parser.go, internal/providers/terraform/plan_cache.go
This change introduces the ContextValues struct to both RunContext and ProjectContext, replacing the previously used `map[string]interface{}`. This change was introduced to enhance thread safety in our codebase by preventing concurrent read/write operations to these shared resources, which could lead to unpredictable behavior or data races.
Prior to this change the `ContextValues()` could hit a conccurent write panic because it was returning the actual map and not a copy of it, so when we read from the map it could potentially be written to in a separate goroutine.
To fix this `Values` now returns a copy of the underlying map. I've also introduced a `GetValue` method to safely read values.
=> fix: replace `RunContext` and `ProjectContext` `contextValues` with concurrency safe `ContextValues`

internal/comment/github.go
Issue> Validate --github-api-url #1980 
Sorry again, creating the PR for this issue as I also added the update for the other file of other issue with the same branch which got added with this PR. I was trying to create a new PR for the other issue, but eventually ended-up discarding all the changes. When I saw the PR it was showing closed.
I added the check for the "/api/v3" for the github-api-url to make sure we remain consistent with the link.
Thanks, [Ali Khajeh](https://github.com/alikhajeh1) and [Alistair Scott](https://github.com/aliscott) for helping and guiding with my second open-source contribution.
=> updated github.go to check /api/v3 | issue> #1980

internal/providers/terraform/terragrunt_hcl_provider.go
from sentry
```
"runtime error: invalid memory address or nil pointer dereference"
], 
"stacktrace": 
"1: running [Created by errgroup.(*Group).Go @ errgroup.go:72]
:24                                                             Stack()
:270                                                            (*parallelRunner).run.func1.1()
:884                                                            panic()
:233                                                            (*TerragruntHCLProvider).LoadResources.func2()
:299                                                            order2_func()
:308                                                            median_func()
:316                                                            medianAdjacent_func()
:279 …
```
=> fix: handle nil metadata

internal/providers/terraform/azure/kubernetes_cluster_node_pool.go, internal/providers/terraform/azure/testdata/kubernetes_cluster_node_pool_test/kubernetes_cluster_node_pool_test.golden, internal/providers/terraform/azure/testdata/kubernetes_cluster_node_pool_test/kubernetes_cluster_node_pool_test.tf
Infracost uses Premium disk for AKS even though it's not available for given VM family #2407
[kubernetes_cluster_node_pool.go](https://github.com/infracost/infracost/blob/master/internal/providers/terraform/azure/kubernetes_cluster_node_pool.go)
in the below function, added the instaceType to the calling function of `aksOSDiskSubResource()`
```go
func aksClusterNodePool()
{
// rest of the code
osDisk := aksOSDiskSubResource(region, diskSize, instanceType)
}
```
in the below function `aksOSDiskSubResource()` added the call to the new function `aksGetStorageType()` which returns a string whether the OS Disk provisioned is **Premium** or **Standard** based on the naming convention subfamily has any known premium prefixes (DS, GS, and M), and if so, it returns “Premium”. If not, it checks if …
=> updated check for OS disks provisioned for AKS #2407

cmd/infracost/testdata/breakdown_with_default_tags/breakdown_with_default_tags.golden, internal/hcl/block.go, internal/hcl/evaluator.go, internal/hcl/parser_test.go
@hugorut I think the parser_test changes explain the issue, but I'm not sure what you'll think of the fix.
=> fix: don't remove overlapping blocks when expanding dynamic blocks

cmd/infracost/breakdown_test.go, cmd/infracost/testdata/breakdown_auto_with_multi_varfile_projects/breakdown_auto_with_multi_varfile_projects.golden, cmd/infracost/testdata/breakdown_auto_with_multi_varfile_projects/multi/dev.tfvars.json, cmd/infracost/testdata/breakdown_auto_with_multi_varfile_projects/multi/main.tf, cmd/infracost/testdata/breakdown_auto_with_multi_varfile_projects/multi/prod.tfvars, cmd/infracost/testdata/breakdown_auto_with_multi_varfile_projects/single/infra.tfvars, cmd/infracost/testdata/breakdown_auto_with_multi_varfile_projects/single/main.tf, internal/hcl/module.go, internal/hcl/parser.go, internal/hcl/parser_test.go, internal/hcl/project_locator.go, internal/providers/terraform/dir_provider.go, internal/providers/terraform/hcl_provider.go, internal/providers/terraform/hcl_provider_test.go, internal/providers/terraform/parser.go, internal/providers/terraform/plan_cache.go, internal/providers/terraform/terragrunt_hcl_provider.go, internal/providers/terraform/terragrunt_provider.go, internal/providers/terraform/terragrunt_registry_service.go
Changes auto detection logic so that terraform var files are automatically taken into consideration:
1. If a single terraform var file is found under a project, we add it to the evaluator
2. If more than one are found under a project, we split the project into multiples. One for each var file discovered.
This functionality is solely for auto detection and once a user defines a config file, we no longer adhear to these rules.
Also added a `jsoniter` refactor into this pr to speed up the parsing logic. Let me know if you want me to separate it out.
=> refactor: change auto detect logic to include tfvars

internal/hcl/block.go, internal/providers/terraform/hcl_provider.go, internal/providers/terraform/parser.go
This ensures mocks are calculated deterministically and so resource checksums are also consistent between runs.
=> Consistent mock values

internal/apiclient/dashboard.go
Resolves issue where repo metadata is blank for `infracost comment`. This fixes a regression that was introduced with the `ContextValues` concurrency fix. Prior to the concurrency fix RunContext Values was returning the value of the underlying map and not a copy for it. So setting `ctxValues['repoMetadata']` actually altered the RunContext Values. Hence why the old code which set the key before creating a clone actually worked. The old code with comments for better understanding:
```go
// This line actually alters ctx.Values as well as the local variable.
ctxValues["repoMetadata"] = metadata
if ctx.IsInfracostComment() {
ctxValues = make(map[string]interface{}, len(ctxValues))
// now ctx.ctx.GetContextValues returns the altered map so the clone contains the "repoMetadata" key.
for k, v := …
```
=> fix: resolve blank repo metadata

go.mod, go.sum, internal/providers/terraform/terragrunt_hcl_provider.go
This change uses the updated infracost Terragrunt DownloadTerraformSource which:
* prevents duplicate downloads for remote and local modules. Terragrunt projects now use a global cache of modules.
* improves local module caching logic. We now don't recopy the a local module if an up to date hash of the module exists in the cache
=> refactor: use terragrunt global cache for modules

internal/providers/terraform/hcl_provider.go, internal/providers/terraform/hcl_provider_test.go, internal/providers/terraform/testdata/hcl_provider_test/builds_module_configuration_correctly_with_count/expected.json, internal/providers/terraform/testdata/hcl_provider_test/builds_module_configuration_correctly_with_count/main.tf, internal/providers/terraform/testdata/hcl_provider_test/builds_module_configuration_correctly_with_count/module/gateway/main.tf, internal/providers/terraform/testdata/hcl_provider_test/builds_module_configuration_correctly_with_count/module/gateway_proxy/main.tf
Default tags were not applied to the resources of a module with count:
the configuration key contained the count part, but the lookup used just
the module name. Thus the tags were not found.
=> fix: Strip count from module name as configuration key when marshalling

internal/hcl/block.go, internal/hcl/evaluator.go, internal/hcl/parser_test.go, internal/providers/terraform/hcl_provider.go
Adds support for the `data.aws_default_tags` which returns the provider default tags. This PR also adds support to save the infracost generated plan JSON to the local filesytem. This aids debugging, in particular seeing what final values are for the evaluated blocks.
Work on this PR exposed a serious limitation to the HCL evaluator. See this issue https://github.com/infracost/infracost/issues/2596 for more info. The code changes in this PR go some way to solving this issue but we need more work to fully solve it.
=> feat: add support for data.aws_default_tags block

cmd/infracost/testdata/breakdown_format_json_with_tags/breakdown_format_json_with_tags.golden, cmd/infracost/testdata/breakdown_format_json_with_tags/main.tf, cmd/infracost/testdata/breakdown_with_default_tags/breakdown_with_default_tags.golden, internal/providers/terraform/aws/aws.go
Resolves issue where resources that contained tag blocks that defined `progagate_at_launch` as false to still pass tag policies.
=> fix: propagate tags at launch

go.mod, go.sum, internal/providers/terraform/terragrunt_hcl_provider.go
This reverts commit 610eb5ca315b9dc12524bc7468ba70f58e49363b.
Reverting this just now since it's causing issues with project warnings.
=> Revert "refactor: use terragrunt global cache for modules (#2584)"

cmd/infracost/breakdown_test.go, cmd/infracost/cmd_test.go, cmd/infracost/testdata/breakdown_terragrunt_with_remote_source/breakdown_terragrunt_with_remote_source.golden, cmd/infracost/testdata/breakdown_terragrunt_with_remote_source/infracost.yml, cmd/infracost/testdata/breakdown_terragrunt_with_remote_source/ref1-submod/terragrunt.hcl, cmd/infracost/testdata/breakdown_terragrunt_with_remote_source/ref1/terragrunt.hcl, cmd/infracost/testdata/breakdown_terragrunt_with_remote_source/ref2/terragrunt.hcl, cmd/infracost/testdata/breakdown_terragrunt_with_remote_source/submod-ref1-2/terragrunt.hcl, cmd/infracost/testdata/breakdown_terragrunt_with_remote_source/submod-ref1/terragrunt.hcl, cmd/infracost/testdata/breakdown_terragrunt_with_remote_source/submod-ref3/terragrunt.hcl, cmd/infracost/testdata/breakdown_terragrunt_with_remote_source/testdata/breakdown_terragrunt_with_remote_source/breakdown_terragrunt_with_remote_source.golden, go.mod, go.sum, internal/providers/terraform/terragrunt_hcl_provider.go
Resolves issue where modules using refs where being downloaded to same directory. We now encode the ref/query into the directory hash: https://github.com/infracost/terragrunt/pull/4/commits/a0a234c6387888404e78489071bc78cde25abd06 so the directories are unique. The source lock is updated to use the download directory that terragrunt checks to ensure that goroutines are synced with the downloading logic.
=> fix: ensure that terragrunt remote source modules with refs and versions are downloaded to different directories

cmd/infracost/testdata/diff_with_free_resources_checksum/diff_with_free_resources_checksum.golden, internal/providers/terraform/google/testdata/compute_instance_test/compute_instance_test.golden
These appear to be valid cost changes, validated against the Google Pricing Calculator, although the Google Pricing page has incorrect pricing for the pre-emptible GPUs.
=> chore(google): fix golden tests

cmd/infracost/breakdown_test.go, cmd/infracost/testdata/breakdown_with_data_blocks_in_submod/breakdown_with_data_blocks_in_submod.golden, cmd/infracost/testdata/breakdown_with_data_blocks_in_submod/main.tf, cmd/infracost/testdata/breakdown_with_data_blocks_in_submod/modules/vpc/main.tf, internal/hcl/block.go, internal/hcl/evaluator.go, internal/hcl/parser.go
Resolves issue where data blocks such as `data.aws_availability_zones` was returning the default value in a submodule. This was because the provider context was not properly set when evaluating submodules. Also adds support for `data.aws_region` block.
=> fix: return correct values from stubbed data blocks in submodules

cmd/infracost/testdata/breakdown_with_optional_variables/breakdown_with_optional_variables.golden, cmd/infracost/testdata/breakdown_with_optional_variables/main.tf, internal/hcl/context.go, internal/hcl/evaluator.go
This change adds support for type definitions which contain optional defaults. For example:
```
variable "my_var" {
type = object({
attr1 = string
attr2 = optional(string, "value2")
})
default = {
attr1 = "value1"
}
}
```
would resolve to:
```
my_var = {
attr1 = "value1"
attr2 = "value2"
}
```
This solves cost estimate inconsistencies various users experienced when using variables attributes that contained optional defaults.
=> fix: support optional defaults

internal/providers/terraform/terragrunt_hcl_provider.go
@hugorut I think this is ok, but can you confirm that it's correct to only download the terragrunt sourceURL once?
=> fix: avoid race conditions by only downloading tg sources once

cmd/infracost/testdata/breakdown_with_optional_variables/breakdown_with_optional_variables.golden, cmd/infracost/testdata/breakdown_with_optional_variables/main.tf, internal/hcl/evaluator.go
Switches `convertType` logic to use `Defaults.Apply` which handles other complex types other than objects. This means types like `list(object(...` or `map(...` are properly converted.
=> fix: cty panic when variable type definition is not an object

internal/output/output.go
From the Go docs:
> "If the map is nil, the number of iterations is 0." https://go.dev/ref/spec#For_range
Therefore, an additional nil check for before the loop is unnecessary. Example: https://go.dev/play/p/Cw_wnqYzemu
=> refactor(output): remove redundant nil check

cmd/infracost/comment_azure_repos.go, cmd/infracost/comment_bitbucket.go, cmd/infracost/comment_github.go, cmd/infracost/comment_gitlab.go, cmd/infracost/diff.go, cmd/infracost/main.go, cmd/infracost/output.go, cmd/infracost/run.go, cmd/infracost/upload.go, go.mod, go.sum, internal/apiclient/errors.go, internal/apiclient/pricing.go, internal/apiclient/pricing_test.go, internal/comment/handler.go, internal/config/config.go, internal/prices/prices.go, internal/scan/terraform.go
Introduces an persisent and in memory query cache for the pricing api. As part of this change the PricingApiClient is now shared across the application codebase so that we maintain a consistent cache used across goroutines. Furthermore, we now dedupe pricing api queries sent to the pricing API, further reducing request size made by the CLI.
Caching functionality can be controlled by the new configuration parameters:
* `INFRACOST_PRICING_CACHE_DISABLED` which, if set to true, completely removes caching functionality
* `INFRACOST_PRICING_CACHE_OBJECT_SIZE` which can control the size of the cache. This is useful for memory requirements.
=> feat: pricing client cache

internal/apiclient/pricing.go
Resolves panic when `GetPricingAPIClient` is called for the first time when flushing the cache.
=> fix: fix panic from cache flush when not initialized

internal/apiclient/pricing.go
@aliscott I'm not sure what you were thinking for the timeout.  I looked at cloudwatch for the max TargetResponseTime from the HCPAPI ELBs and 60s covers all outliers, but it does seem ridicuously high.
=> fix: add timeout for hcpapi requests

Makefile, internal/config/run_context.go
Does anyone object to removing the `-v` option from our makefile rules?  I feel like it takes a bunch of scrolling or  grepping to find test failures.
=> chore: remove verbose flag from make test_*

internal/hcl/modules/loader.go, internal/hcl/modules/loader_test.go
Fixes issue where source map that contained a mapped source with a ref would build the incorrect url to fetch a submodule.
e.g:
if a source was mapped to: `git::git@github.com:org/repo?ref=v1.4.1`, and we tried to fetch the `backup` submodule we would append it onto the mapped source like so:
```
git::git@github.com:org/repo?ref=v1.4.1//backup
```
when the url should be:
```
git::git@github.com:org/repo//backup?ref=v1.4.1
```
=> fix: build correct mapping url if mapped source contains a ref

cmd/infracost/comment.go, cmd/infracost/comment_azure_repos.go, cmd/infracost/comment_bitbucket.go, cmd/infracost/comment_github.go, cmd/infracost/comment_gitlab.go, cmd/infracost/testdata/comment_bitbucket_with_fin_ops_policy_checks/comment_bitbucket_with_fin_ops_policy_checks.golden, cmd/infracost/testdata/comment_git_hub_with_fin_ops_policy_checks/comment_git_hub_with_fin_ops_policy_checks.golden, internal/output/output.go
* adds support for finops policies using old comment output
* refactors comment error handling so it's a bit easier to use
Note: this was not moved to the API as previously discussed as Ali wants the old style comment output until
phase 3. See: https://infracost.slack.com/archives/C025MSU0US3/p1695068299141909?thread_ts=1695040182.419469&cid=C025MSU0US3
=> feat: add finops policy output to comment

cmd/infracost/breakdown_test.go, cmd/infracost/testdata/breakdown_with_mocked_merge/breakdown_with_mocked_merge.golden, cmd/infracost/testdata/breakdown_with_mocked_merge/main.tf, internal/hcl/attribute.go, internal/hcl/evaluator.go, internal/hcl/funcs/collection.go, internal/hcl/funcs/general.go, internal/hcl/funcs/json.go, internal/hcl/funcs/yaml.go, internal/providers/terraform/terragrunt_hcl_provider.go
Ensure `merge` can handle values that have already been mocked but then are discovered to be objects, e.g:
```
locals {
value1 = data.terraform_remote_state.env
value2 = merge(
data.terraform_remote_state.env["test"],
{
instance_type = "m5.4xlarge"
}
)
}
```
=> Merge mock values

cmd/infracost/breakdown_test.go, internal/hcl/attribute.go
This reverts commit efb33289a4c7e11e4b296b19c601b10fffb77e37. This change caused more issues, so we need to find an alternative fix.
=> Revert "fix: fix handling of unknown objects"

cmd/infracost/breakdown_test.go, cmd/infracost/testdata/breakdown_with_mocked_merge/breakdown_with_mocked_merge.golden, cmd/infracost/testdata/breakdown_with_mocked_merge/main.tf, internal/hcl/attribute.go
This change alters the mocking logic in Attribute to skip modifying the context to instead retry the function call with a mocked argument. This is preferable in most cases as modifying the Context with mocked values can result in unexpected outputs.
=> fix: skip context mocking if expression is a function call

cmd/infracost/breakdown_test.go, cmd/infracost/testdata/breakdown_with_dynamic_iterator/breakdown_with_dynamic_iterator.golden, cmd/infracost/testdata/breakdown_with_dynamic_iterator/main.tf, internal/hcl/evaluator.go
This PR adds support for expanded Dynamic block child context support. Normally, in the context of a for_each expansion we set the child context to have a prefix of "each". This allows correct evaluation of attributes referencing "each.value." or "each.key.". However, dynamic blocks are special cases. Not only can they use "each" in the content block, but they also are able to refer to the dynamic block label, e.g:
```
dynamic "setting" {
for_each = var.settings
content {
namespace = setting.value.namespace.
...
}
}
```
additionally they have an "iterator" block:
https://developer.hashicorp.com/terraform/language/expressions/dynamic-blocks which allow the user to specify a different prefix for a for_each expansion. For example:
```
dynamic "foo" {
for_each = {
...
}
iterator = device …
```
=> fix: support dynamic iterator attribute

cmd/infracost/testdata/breakdown_terragrunt_hcldeps_output/dev/terragrunt.hcl, go.mod, go.sum
Bumps the version to the `infracost/terragrunt` dependency so it contains https://github.com/infracost/terragrunt/pull/11. This resolves the early exit from the TerragruntProvider when unknown inputs cannot be "mocked".
**Note:** updated sha currently points to the  https://github.com/infracost/terragrunt/pull/11 commit sha, once it is reviewed and merged I'll update it here to point to the new master sha
=> fix: complex unknown values provided as inputs

internal/providers/terraform/azure/private_dns_resolver_dns_forwarding_ruleset.go, internal/providers/terraform/azure/private_dns_resolver_dns_forwarding_ruleset_test.go, internal/providers/terraform/azure/private_dns_resolver_inbound_endpoint.go, internal/providers/terraform/azure/private_dns_resolver_inbound_endpoint_test.go, internal/providers/terraform/azure/private_dns_resolver_outbound_endpoint.go, internal/providers/terraform/azure/private_dns_resolver_outbound_endpoint_test.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/testdata/private_dns_resolver_dns_forwarding_ruleset_test/private_dns_resolver_dns_forwarding_ruleset_test.golden, internal/providers/terraform/azure/testdata/private_dns_resolver_dns_forwarding_ruleset_test/private_dns_resolver_dns_forwarding_ruleset_test.tf, internal/providers/terraform/azure/testdata/private_dns_resolver_dns_forwarding_ruleset_test/private_dns_resolver_dns_forwarding_ruleset_test.usage.yml, internal/providers/terraform/azure/testdata/private_dns_resolver_inbound_endpoint_test/private_dns_resolver_inbound_endpoint_test.golden, internal/providers/terraform/azure/testdata/private_dns_resolver_inbound_endpoint_test/private_dns_resolver_inbound_endpoint_test.tf, internal/providers/terraform/azure/testdata/private_dns_resolver_inbound_endpoint_test/private_dns_resolver_inbound_endpoint_test.usage.yml, internal/providers/terraform/azure/testdata/private_dns_resolver_outbound_endpoint_test/private_dns_resolver_outbound_endpoint_test.golden, internal/providers/terraform/azure/testdata/private_dns_resolver_outbound_endpoint_test/private_dns_resolver_outbound_endpoint_test.tf, internal/providers/terraform/azure/testdata/private_dns_resolver_outbound_endpoint_test/private_dns_resolver_outbound_endpoint_test.usage.yml, internal/resources/azure/private_dns_resolver_dns_forwarding_ruleset.go, internal/resources/azure/private_dns_resolver_inbound_endpoint.go, internal/resources/azure/private_dns_resolver_outbound_endpoint.go
Add support for :
* azurerm_private_dns_resolver_inbound_endpoint
* azurerm_private_dns_resolver_outbound_endpoint 
* azurerm_private_dns_resolver_dns_forwarding_ruleset
* azurerm_private_dns_resolver
Fixes #2778.
PR on the documentation : https://github.com/infracost/docs/pull/594
Price for a each endpoint (inbound or outbound): 180$/month
Price for a each ruleset : 2.50$/month
None
=> feat(azure): add support for Azure DNS Private Resolver (endpoints and ruleset)

cmd/infracost/testdata/generate_config_auto_detect/generate_config_auto_detect.golden, internal/hcl/parser.go
Fixes project auto-detection so we do not treat `terraform.tfvars` as an environment var file, but instead, correctly mark them as auto-applied to the project.
=> fix: include `terraform.tfvars` as "auto" file

internal/hcl/project_locator.go
Changes auto-detect logic so that the max search depth is 14 for `use-all-paths` and `7` as default. This change is required to support better discovery of nested Terraform projects in user repositories.
=> refactor: change max search depth for auto-detect

.github/workflows/go.yml, internal/hcl/modules/fetch.go, internal/hcl/modules/fetch_test.go, internal/providers/terraform/terragrunt_hcl_provider.go
Changes Terraform and Terragrunt getter logic to force a https `Get` before attempting a ssh `Get`. The Terraform logic now uses a custom `GitGetter` which transforms the URL before `Get`. The Terragrunt provider cannot use this as the `Getters` are hidden below in the lib, so we try and transform the `sourceUrl` before Download.
=> refactor: force https module get logic

cmd/infracost/comment_github_test.go, cmd/infracost/testdata/comment_git_hub_no_diff/comment_git_hub_no_diff.golden, cmd/infracost/testdata/no_diff.json, internal/output/format.go, internal/output/markdown.go, internal/output/output.go
Changes the markdown templates so that the `displayOutput` always shows if there are unsupported resources. This ensures we always show more information to the user even with 0 cost PRs. This means that users can understand why certain PRs, where cost changes are expected, are showing 0 costs.
=> fix: show details section when there are unsupported resources IC-562

internal/hcl/modules/registry.go
* Introduces a retryablehttp client to the `RegistryLoader` and `Disco` structs which communicate with Terraform registry. These now adhear to the proper 429 backoff and retry logic if we've made too many requests to the registry.
=> fix: handle backoff and retry with terraform registry modules IC-556

internal/hcl/modules/registry.go
Following https://github.com/infracost/infracost/pull/2803, by default this is logging all DEBUG lines
=> fix: don't use default retryablehttp client logger

cmd/infracost/testdata/comment_bitbucket_commit/comment_bitbucket_commit.golden, cmd/infracost/testdata/comment_bitbucket_pull_request/comment_bitbucket_pull_request.golden, cmd/infracost/testdata/output_format_bitbucket_comment_with_project_names/output_format_bitbucket_comment_with_project_names.golden, internal/output/templates/markdown.tmpl
fixes #2799
Adds spacing between markdown table and header in the markdown.tmpl. This resolves issue where the header was being appeded as a table row.
=> fix: correct markdown spacing for Bitbucket IC-559

internal/providers/terraform/google/sql_database_instance.go, internal/providers/terraform/google/sql_database_instance_test.go, internal/providers/terraform/google/testdata/sql_database_instance_test/sql_database_instance_test.golden, internal/providers/terraform/google/testdata/sql_database_instance_test/sql_database_instance_test.tf, internal/resources/google/sql_database_instance.go
This also fixes the legacy tiers for PostgreSQL and MSSQL.
Google has introduced new tiers of the form `db-standard-1`. The legacy tiers are `db-n1-*`. The new tiers don't have a single price in the pricing API, so we map them to the equivalent CPU and memory prices, similar to how custom instances work.
There's still 2 unsupported issues with this resource that I will separate into separate issues:
1. SQL Server Licensing isn't supported
2. Enterprise Plus pricing isn't supported.
=> fix(google): update `google_sql_database_instance` resource to work with new tiers

cmd/infracost/generate.go, cmd/infracost/generate_test.go, cmd/infracost/testdata/generate/env_names/expected.golden, cmd/infracost/testdata/generate/env_names/infracost.yml.tmpl, cmd/infracost/testdata/generate/env_names/tree.txt, cmd/infracost/testdata/generate/excluded_dirs/expected.golden, cmd/infracost/testdata/generate/excluded_dirs/infracost.yml.tmpl, cmd/infracost/testdata/generate/excluded_dirs/tree.txt, cmd/infracost/testdata/generate/include_dirs/expected.golden, cmd/infracost/testdata/generate/include_dirs/infracost.yml.tmpl, cmd/infracost/testdata/generate/include_dirs/tree.txt, internal/config/config.go, internal/hcl/parser.go, internal/hcl/parser_test.go, internal/hcl/project_locator.go, internal/hcl/project_locator_test.go, internal/providers/terraform/hcl_provider.go
Adds new autodetect section to configuration file which passes configuration down to the `ProjectLocator`. This adds the ability to:
* add projects which haven't been detected with - included_dirs
* exclude bad projects from the autodetection with - excluded_dirs
* change the naming conventions for the env var files with - env_names
The `generate` functionality has had to be changed to accomodate this new functionality. We now need to "partially" unmarshal the template before running autodetect. This is not supported natively by the goyml package so we need to seek the file to build a partial YAML that can be marshalled without errors.
=> feat: add autodetect configuration to config file IC-604

cmd/infracost/generate.go, cmd/infracost/testdata/generate/detected_root_modules/expected.golden, cmd/infracost/testdata/generate/detected_root_modules/infracost.yml.tmpl, cmd/infracost/testdata/generate/detected_root_modules/tree.txt, internal/config/template/parser.go
Adds support for a DetectedRootModules variable which is a deduped list
of DetectedProjects by path. The variable contains a list of Projects for
each corresponding path to facilitate composability in the template.
depends on https://github.com/infracost/infracost/pull/2820
=> feat: add DetectedRootModules template variable IC-603 

cmd/infracost/generate.go
fixes issue with runner which doesn't execute generate properly with `--template`. This is an interim fix until we get another solution in.
=> fix: has template logic

internal/hcl/attribute.go, internal/hcl/attribute_test.go, internal/hcl/evaluator.go, internal/hcl/parser.go, internal/hcl/parser_test.go
This PR changes the mocking logic in the graph evaluator to an expression based approach. Now instead of changing the global Context we instead traverse any expression that is found with a Diagnostic. We walk this expression tree until we hit an expression that is a candidate for mocking. These are:
* hclsyntax.AnonSymbolExpr:
* hclsyntax.LiteralValueExpr
* hclsyntax.ScopeTraversalExpr:
and occasionally hclsyntax.FunctionCallExpr
These are Expressions that likely correspond to "incomplete" values that infracost cannot build. E.g. hclsyntax.ScopeTraversalExpr directly relates to a "missing attribute" or "invalid attribute" diagnostics that are 95% of the cases that we handle. These come about through lack of complete information because attributes/blocks which are populated from the cloud, …
=> refactor: use different mocking logic for graph evaluator IC-608

cmd/infracost/generate.go, cmd/infracost/generate_test.go, cmd/infracost/testdata/generate/include_dirs/expected.golden, cmd/infracost/testdata/generate/include_dirs/infracost.yml.tmpl, cmd/infracost/testdata/generate/include_dirs/tree.txt, internal/hcl/project_locator.go
This PR adds support for the autodetect section when using the `--template` command line arg.
=> fix: handle autodetect section with `--template` arg

cmd/infracost/generate.go, cmd/infracost/testdata/generate/excluded_dirs/expected.golden, cmd/infracost/testdata/generate/excluded_dirs/infracost.yml.tmpl, cmd/infracost/testdata/generate/include_dirs/expected.golden, cmd/infracost/testdata/generate/include_dirs/infracost.yml.tmpl, internal/config/config.go, internal/providers/terraform/hcl_provider.go
renames included and excluded to be present tense so that they are more compatible with cmd line flags in the future.
=> refactor: change naming for autodetect fields

cmd/infracost/testdata/generate/cousin/expected.golden, cmd/infracost/testdata/generate/cousin/tree.txt, cmd/infracost/testdata/generate/cousin_flat/expected.golden, cmd/infracost/testdata/generate/cousin_flat/tree.txt, internal/hcl/parser.go, internal/hcl/project_locator.go
Adds support for var files found in cousin directories, or put another way any var files found in sub directories of aunts. I have also added additional env names to the global list, to improve env var file detection.
=> feat: add auto-detect cousin support

internal/providers/terraform/azure/testdata/mysql_flexible_server_test/mysql_flexible_server_test.golden, internal/providers/terraform/azure/testdata/mysql_flexible_server_test/mysql_flexible_server_test.tf, internal/providers/terraform/azure/testdata/postgresql_flexible_server_test/postgresql_flexible_server_test.golden, internal/providers/terraform/azure/testdata/postgresql_flexible_server_test/postgresql_flexible_server_test.tf, internal/resources/aws/lightsail_instance.go, internal/resources/azure/mysql_flexible_server.go, internal/resources/azure/postgresql_flexible_server.go
=> fix(azure): Fix pricing for Azure MySQL/Postgres flexible servers

cmd/infracost/generate.go
We should just use the defined projects in this case.
=> fix: don't error if there's no projects in generate config

internal/providers/terraform/dir_provider.go, internal/providers/terraform/parser.go, internal/providers/terraform/plan_json_provider.go, internal/providers/terraform/plan_provider.go, internal/providers/terraform/state_json_provider.go, internal/providers/terraform/terragrunt_provider.go, internal/schema/resource_data.go
The main memory leak was from putting gjson result strings into output structs.  If you do something like:
```
json := `{"name":"woofy","age":12}`
gjsonResult := gjson.Parse(json).Get("name")
name := gjsonResult.String()
```
`name` is a slice of the `json` string, so `json` cannot be garbage collected until `name` is released.
Since our output structs live for the life of the program, none of the underlying json was ever released even though only use a small subset of the values in the output.
=> perf: fix memory leaks

cmd/infracost/testdata/generate/aunt_filename_matches_project/expected.golden, cmd/infracost/testdata/generate/aunt_filename_matches_project/tree.txt, cmd/infracost/testdata/generate/aunt_filenames_with_env/expected.golden, cmd/infracost/testdata/generate/aunt_filenames_with_env/tree.txt, cmd/infracost/testdata/generate/env_dirs/expected.golden, cmd/infracost/testdata/generate/env_dirs/tree.txt, cmd/infracost/testdata/generate/parent_filename_matches_project/expected.golden, cmd/infracost/testdata/generate/parent_filename_matches_project/tree.txt, cmd/infracost/testdata/generate/shared_env_var_files/expected.golden, cmd/infracost/testdata/generate/shared_env_var_files/tree.txt, internal/hcl/project_locator.go
Changes `ProjectLocator` functionality so that tfvars are scoped to a project by their name.
=> feat: match tfvar naming to project names

internal/hcl/project_locator.go, internal/hcl/project_locator_test.go
Changes env matching logic to use a list and string matching based approach. This is done in favour of the old regxp based method so that we can better environment names that have other environment names as substrings. e.g. dev-legacy.
=> fix: env matching logic

cmd/infracost/generate.go, cmd/infracost/testdata/generate/path_overrides/expected.golden, cmd/infracost/testdata/generate/path_overrides/infracost.yml.tmpl, cmd/infracost/testdata/generate/path_overrides/tree.txt, go.mod, internal/config/config.go, internal/hcl/project_locator.go, internal/providers/detect.go
Adds the ability to configure which envs apply to different paths using a new `path_overrides` autodetect config key.
**Note**: I've had to include the github.com/gobwas/glob package as the builting `filepath.Match` function could not accomodate the glob syntax that we want to use for the `path` field.
=> feat: add path_overrides autodetect configuration

cmd/infracost/testdata/generate/path_overrides/expected.golden, cmd/infracost/testdata/generate/path_overrides/tree.txt, internal/hcl/project_locator.go
changes "only" configuration logic to only filter on tfvar files that are defined as "env" tfvars.
=> fix: don't exclude global var files from path_overrides

cmd/infracost/diff.go, cmd/infracost/generate.go, cmd/infracost/run.go, cmd/infracost/testdata/breakdown_terragrunt_diff_project_error/breakdown_terragrunt_diff_project_error.golden, cmd/infracost/testdata/breakdown_terragrunt_get_env_with_whitelist/breakdown_terragrunt_get_env_with_whitelist.golden, cmd/infracost/testdata/breakdown_terragrunt_with_remote_source/breakdown_terragrunt_with_remote_source.golden, cmd/infracost/testdata/generate/terragrunt/expected.golden, cmd/infracost/testdata/generate/terragrunt/tree.txt, cmd/infracost/testdata/generate/terragrunt_and_terraform_mixed/expected.golden, cmd/infracost/testdata/generate/terragrunt_and_terraform_mixed/infracost.yml.tmpl, cmd/infracost/testdata/generate/terragrunt_and_terraform_mixed/tree.txt, internal/hcl/parser.go, internal/hcl/project_locator.go, internal/providers/detect.go, internal/providers/terraform/hcl_provider.go, internal/providers/terraform/terragrunt_hcl_provider.go, internal/testutil/generate.go
Changes the ProjectLocator to support Terragrunt projects. For the time being I have not change the `TerragruntHCLProvider` to take into account that it has a 1-1 link with a Terragrunt project (e.g. no need to find stacks in the Provider). I didn't want to change to many things as this is quite a dramatic change to how we do things. I will follow up later with a refactor to remove unecessary code.
=> feat: add terragrunt auto-detect support

internal/providers/terraform/terragrunt_hcl_provider.go
This switches the Terragrunt output cache to use a sync.Map instead so we don't hit concurrent map access panics when we're adding output values to the map.
=> fix: concurrent map read and write error

cmd/infracost/testdata/generate/with_no_directories_with_providers/expected.golden, cmd/infracost/testdata/generate/with_no_directories_with_providers/tree.txt, internal/config/run_context.go, internal/hcl/project_locator.go, internal/providers/detect.go
Changes autodetect functionality so that if no paths are detected from an initial provider/backend block project detection we fallback to include all paths. This is particularly usefull for module repositories which often do not contain provider/backend blocks.
=> feat: add fallback to include all paths functionality

cmd/infracost/testdata/generate/tfvar_json/expected.golden, cmd/infracost/testdata/generate/tfvar_json/tree.txt, internal/hcl/project_locator.go
Adds autodetect support for tfvar files named `tfvars.json`.
=> feat: add tfvars.json autodetected variable support

internal/providers/terraform/azure/testdata/mssql_database_test/mssql_database_test.golden, internal/providers/terraform/azure/testdata/sql_database_test/sql_database_test.golden, internal/providers/terraform/azure/testdata/storage_account_test/storage_account_test.golden, internal/providers/terraform/azure/testdata/storage_account_test/storage_account_test.tf, internal/providers/terraform/google/testdata/compute_address_test/compute_address_test.golden, internal/providers/terraform/google/testdata/compute_ha_vpn_gateway_test/compute_ha_vpn_gateway_test.golden, internal/providers/terraform/google/testdata/compute_instance_test/compute_instance_test.golden, internal/providers/terraform/google/testdata/compute_vpn_gateway_test/compute_vpn_gateway_test.golden, internal/providers/terraform/google/testdata/container_node_pool_test/container_node_pool_test.golden, internal/providers/terraform/google/testdata/service_networking_connection_test/service_networking_connection_test.golden, internal/resources/aws/db_instance.go, internal/resources/aws/rds_cluster.go, internal/resources/azure/sql_database.go, internal/resources/google/compute_address.go
1. Google introduced several pricing changes on 1 Feb, so this fixes up them.
2. Fix the Azure golden tests now that `access_tier` is validated as not allowed for block blob storage.
3. Fix AWS RDS cost component lookups
=> Fix cost components/golden tests

.github/workflows/check-resources.yml, .github/workflows/code-scanning.yml, .github/workflows/create-pr-assets.yml, .github/workflows/create-release.yml, .github/workflows/create-test-image.yml, .github/workflows/go.yml, go.mod
- fix: specify go toolchain for `Update Fig autocomplete spec` job
- also improve the setup-go usage
- relates to https://github.com/Homebrew/homebrew-core/pull/162174
=> fix: specify go toolchain for `Update Fig autocomplete spec` job

internal/hcl/graph_vertex_module_call.go
This was causing a case where variables could not be evaluated properly if they were nested inside a module, that was inside another expanded module.
The moduleConfig would incorrectly store `module.parent[0].module.child` as the key instead of `module.parent.module.child`, since the `unexpandedName` was only making sure the child module part was unexpanded, not the full module address. This meant that the module was being skipped when evaluating the variable because at that stage we are looking up `module.parent.module.child` in the moduleConfig.
To fix this we use the block's original name to add the module to the moduleConfig since that should be fully unexpanded.
=> fix: module variables not evaluated properly

internal/providers/terraform/google/testdata/compute_instance_test/compute_instance_test.golden, internal/providers/terraform/google/testdata/compute_instance_test/compute_instance_test.tf, internal/resources/google/compute_cost_component_helpers.go
=> refactor(google): Generate guest accelerator name/desc prefix programmatically

infracost-usage-example.yml
wrong comment on usage example file for aws_rds_cluster.write_requests_per_sec and aws_rds_cluster.read_requests_per_sec
this resolve #2885
=> fix: wrong comment on usage example file for aws_rds_cluster

.github/workflows/check-resources.yml, .github/workflows/code-scanning.yml, .github/workflows/create-pr-assets.yml, .github/workflows/create-release.yml, .github/workflows/create-test-image.yml, .github/workflows/go.yml
- feat: bump actions/checkout to v4 (use nodejs20 runtime)
- feat: bump actions/upload-artifact to v4 (use nodejs20 runtime)
- feat: bump aws-actions/configure-aws-credentials to v4 (use nodejs20 runtime)
- feat: bump docker/login-action to v3 (use nodejs20 runtime)
- feat: bump docker/metadata-action to v5 (use nodejs20 runtime)
- feat: bump docker/setup-buildx-action to v3 (use nodejs20 runtime)
----
closes #2679
closes #2680
closes #2681
closes #2682 
closes #2683
=> feat: bump action dependencies (use nodejs20 runtime)

cmd/infracost/breakdown_test.go, cmd/infracost/cmd_test.go, cmd/infracost/comment_github_test.go, cmd/infracost/comment_test.go, cmd/infracost/testdata/comment_git_hub_guardrail_failure_with_comment/comment_git_hub_guardrail_failure_with_comment.golden, cmd/infracost/testdata/comment_git_hub_guardrail_failure_with_comment_and_block/comment_git_hub_guardrail_failure_with_comment_and_block.golden, internal/config/config.go, internal/hcl/attribute.go, internal/hcl/attribute_test.go, internal/hcl/block.go, internal/hcl/evaluator.go, internal/hcl/graph.go, internal/hcl/graph_vertex_module_call.go, internal/hcl/graph_vertex_module_exit.go, internal/hcl/parser.go, internal/hcl/parser_test.go, internal/providers/terraform/hcl_provider.go, internal/providers/terraform/tftest/tftest.go, internal/usage/usage_file_test.go
Adds coverage for HCL graph evaluator. Also removes the onlyRunCLI option for the test suite as this is not used.
=> feat: add HCL graph tests

internal/hcl/evaluator.go, internal/hcl/parser_test.go
When the `Evaluator` expands dynamic blocks it sets the evaluated `content` on the module context. This means that any resources that depend on the dynamic blocks can use the correct context. Take the following example:
```hcl
variable "my_config" {
default = [
{"location": "eu1"},
{"location": "eu2"}
]
}
resource "aws_instance" "dynamic" {
dynamic "block" {
for_each = var.my_config
content {
location = block.value.location
}
}
}
resource "aws_instance" "example" {
tags = {
one = aws_instance.dynamic.block[0].location
two = aws_instance.dynamic.block[1].location
}
}
```
In this example we see that `aws_instance.example` uses the `aws_instance.dynamic.block`
values in the tags block. Prior to this fix the `Evaluator` was using incorrect keys in
the `SetByDot` context function. This meant …
=> fix: set correct block context when expanding dynamic blocks

internal/hcl/modules/registry.go
It looks like the default logic does what we need with 429 errors. This fixes a nil pointer issue that happens when resp is nil, but err is set, since this checks the err as well.
=> fix: use default retry logic

internal/hcl/project_locator.go
The cached hclparse.Parser.Files can sometimes contain nil values if there's invalid code, tso we should check for these before decoding them.
=> fix: avoid nil ptr for invalid files

internal/providers/terraform/azure/cosmosdb_account.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/testdata/cosmosdb_sql_database_test/cosmosdb_sql_database_test.tf
This fixes some `account_name` not found issues for CosmosDB resources
=> fix(azure): allow CosmosDB Accounts to be referenced by name

cmd/infracost/breakdown_test.go, cmd/infracost/testdata/breakdown_with_nested_provider_aliases/account_lookup/main.tf, cmd/infracost/testdata/breakdown_with_nested_provider_aliases/breakdown_with_nested_provider_aliases.golden, cmd/infracost/testdata/breakdown_with_nested_provider_aliases/main.tf, cmd/infracost/testdata/breakdown_with_nested_provider_aliases/region_lookup/main.tf, internal/hcl/attribute.go, internal/hcl/graph.go
A circular dependency was possible in the graph evaluator. We were adding edges for every data and resource vertex to their provider. For cases where the provider was aliased in the parent module and then implicitly passed to a child module, instead of adding an edge to the aliased provider, we were adding an edge to the root provider.
This fixes that by decoding the providers blocks before creating the edges so we can keep track of all aliased providers and add the correct edges.
=> Fix circular dependency issue when an alias provider is used

go.mod, go.sum
Bumps the Terragrunt lib to include changes to ignore duplicate generate block warning. More information on this change can be found here: https://github.com/infracost/terragrunt/pull/14
=> refactor: bump Terragrunt lib to ignore dup blocks warning

cmd/infracost/diff_test.go, cmd/infracost/run.go, cmd/infracost/testdata/breakdown_invalid_path/breakdown_invalid_path.golden, cmd/infracost/testdata/diff_prior_empty_project/base.json, cmd/infracost/testdata/diff_prior_empty_project/diff_prior_empty_project.golden, cmd/infracost/testdata/diff_prior_empty_project/main.tf, internal/output/combined.go, internal/output/diff.go, internal/schema/project.go
Resolves issue where projects that were previously "empty" (i.e. with no infrastructure configuration files) were showing an error and zero costs with `diff`. We now instead show a 100% cost increase in the project.
=> fix: show a 100% cost increase with prior empty projects

infracost-usage-example.yml, internal/providers/terraform/azure/machine_learning_compute_cluster.go, internal/providers/terraform/azure/machine_learning_compute_cluster_test.go, internal/providers/terraform/azure/machine_learning_compute_instance.go, internal/providers/terraform/azure/machine_learning_compute_instance_test.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/testdata/machine_learning_compute_cluster_test/machine_learning_compute_cluster_test.golden, internal/providers/terraform/azure/testdata/machine_learning_compute_cluster_test/machine_learning_compute_cluster_test.tf, internal/providers/terraform/azure/testdata/machine_learning_compute_cluster_test/machine_learning_compute_cluster_test.usage.yml, internal/providers/terraform/azure/testdata/machine_learning_compute_instance_test/machine_learning_compute_instance_test.golden, internal/providers/terraform/azure/testdata/machine_learning_compute_instance_test/machine_learning_compute_instance_test.tf, internal/providers/terraform/azure/testdata/machine_learning_compute_instance_test/machine_learning_compute_instance_test.usage.yml, internal/resources/azure/machine_learning_compute_cluster.go, internal/resources/azure/machine_learning_compute_instance.go
Adds support for `azurerm_machine_learning_compute_cluster` and  `azurerm_machine_learning_compute_instance`. These resources use the same pricing as Azure VMs.
=> Azure Machine Learning Compute Instance and Cluster

internal/providers/terraform/azure/redis_cache.go, internal/providers/terraform/azure/testdata/redis_cache_test/redis_cache_test.golden, internal/providers/terraform/azure/testdata/redis_cache_test/redis_cache_test.tf
In this case we should still calculate the cost of 2 nodes, since the cache will be set up in HA mode
=> fix(azure): support Azure Redis when shards is set to 0

internal/schema/usage_data.go
Refactors `Get` so that if the underlying Usage is nil we return an empty value and don't try and index the map resulting in a panic.
Changing here means we don't have to constantly fix `u != nil` in resources.
=> fix: return empty value if usage is nil

internal/hcl/attribute.go
If a logical expression (|| or &&) had a sub-expression that was mocked to a non-boolean value, this would always mean the expression always returned false. We now handle this in the same way that we had condition expressions to ensure the mocked expressions return a boolean value if the operator expects boolean values.
=> fix: ensure expressions that expect bools return bools

cmd/infracost/testdata/upload_with_blocking_fin_ops_policy_failure/upload_with_blocking_fin_ops_policy_failure.golden, cmd/infracost/testdata/upload_with_blocking_guardrail_failure/upload_with_blocking_guardrail_failure.golden, cmd/infracost/testdata/upload_with_blocking_tag_policy_failure/upload_with_blocking_tag_policy_failure.golden, cmd/infracost/upload.go
People who need to check for failures can run upload with --format=json and check the "governance_failures" key.
=> enhance: do not exit with error when governance failures happen on upload

internal/clierror/error.go
This fixes 2 issues:
1. The goroutine number was in the sanitized stacktrace, which could be different for equivalent stack traces
2. The path to the function was not showing for certain builds. Using import path should make this work consistently
Before:
```
1: running [Created by errgroup.(*Group).Go in goroutine 12 @ errgroup.go:72]
runtime/debug/stack.go:24                        Stack()
:272                                             (*parallelRunner).run.func1.1()
runtime/panic.go:770                             panic()
:341                                             (*parallelRunner).runProvider()
:282                                             (*parallelRunner).run.func1()
:75                                              (*Group).Go.func1()
```
After:
```
1: running [Created by …
```
=> fix: ensure sanitized stacktraces match for equivalent stacktraces

internal/hcl/evaluator.go
We have a check for the max int size already, so just adding an extra one for negative numbers.
This ensures we don't try to make a slice with a negative length.
=> fix: this can cause a panic if count is set to a negative number

cmd/infracost/generate.go, cmd/infracost/testdata/generate/max_search_depth/expected.golden, cmd/infracost/testdata/generate/max_search_depth/infracost.yml.tmpl, cmd/infracost/testdata/generate/max_search_depth/tree.txt, internal/config/config.go, internal/hcl/project_locator.go, internal/providers/detect.go
Adds a new `max_search_depth` key to the `autodetect` config file configuration. This enables users to specify the depth that Infracost should search to to try and locate different infrastructure projects (Terraform/Terragrunt).
=> feat: allow configuration of max search depth for autodetect

.github/workflows/go.yml, cmd/infracost/breakdown.go, cmd/infracost/breakdown_test.go, cmd/infracost/cmd_test.go, cmd/infracost/comment.go, cmd/infracost/diff.go, cmd/infracost/run.go, cmd/infracost/testdata/breakdown_empty_apikey/breakdown_empty_apikey.golden, cmd/infracost/testdata/breakdown_invalid_apikey/breakdown_invalid_apikey.golden, cmd/infracost/upload.go, cmd/infracost/upload_test.go, internal/apiclient/client.go, internal/apiclient/dashboard.go, internal/apiclient/policy.go, internal/apiclient/pricing.go, internal/apiclient/usage.go
Changes the `breakdown`, `diff`, `upload` and `comment` commands to exit early if the INFRACOST_API_KEY is invalid. This is done so that users can better debug their pipelines where an API key might be incorrectly set.
To accomodate this change i've introduced the idea of command middleware which will wrap commands before their execution. This means we can easily chain on additional functionality/checks in the future if required. The specific checkAPIKeyIsValid middleware works by making a empty request to the pricing API service and check if the error returned has an Invalid API Key code. I think this the simplest and most effective way to achieve the API key validation. But you have thoughts of a better way, please let me know.
I have checked with @alikhajeh1 to make sure the error …
=> feat: exit early if Infracost API Key is invalid

cmd/infracost/breakdown_test.go, cmd/infracost/cmd_test.go, cmd/infracost/testdata/breakdown_with_providers_depending_on_data/breakdown_with_providers_depending_on_data.golden, cmd/infracost/testdata/breakdown_with_providers_depending_on_data/main.tf, cmd/infracost/testdata/breakdown_with_providers_depending_on_data/mod/main.tf, internal/hcl/attribute.go, internal/hcl/evaluator.go, internal/hcl/graph_vertex_data.go, internal/hcl/module.go
This fixes the case where a `provider` block depends on an output of a module and then that provider is passed to the module and used in a data resource.
Before this would create a circular dependency in the graph evaluator because we were treating providers passed into modules as an edge in the graph. Instead now we just maintain a reference to providers when a module is created and then evaluate them and add them to the context at various points in the evaluation process:
1. Before we evaluate a data block, since for special data attributes we might need the provider on the context (e.g. `aws_current_region`)
2. When we are closing out the module, since after this we collect the default tags values from the module to add to any of the resources.
We could improve this in two ways, but …
=> Fix providers that depend on output of module

internal/providers/terraform/aws/testdata/config_organization_custom_rule_test/config_organization_custom_rule_test.tf, internal/providers/terraform/aws/testdata/neptune_cluster_instance_test/neptune_cluster_instance_test.golden, internal/providers/terraform/azure/testdata/linux_virtual_machine_test/linux_virtual_machine_test.golden
I have updated the relevant prices for the failing tests. However, the warnings about multiple prices look like azure is just switching over as they are present using latest products dump.
=> fix: update golden test prices

.github/workflows/create-release.yml
Resolves where the clean images step exited when trying to remove a image used by the actual actions process.
=> fix: only remove image that build step created

cmd/infracost/testdata/breakdown_terraform_use_state_v0_12/breakdown_terraform_use_state_v0_12.golden, cmd/infracost/testdata/breakdown_terraform_use_state_v0_14/breakdown_terraform_use_state_v0_14.golden, cmd/infracost/testdata/breakdown_terraform_v0_12/breakdown_terraform_v0_12.golden, cmd/infracost/testdata/breakdown_terraform_v0_14/breakdown_terraform_v0_14.golden, cmd/infracost/testdata/diff_terraform_v0_12/diff_terraform_v0_12.golden, cmd/infracost/testdata/diff_terraform_v0_14/diff_terraform_v0_14.golden, internal/providers/terraform/aws/db_instance.go, internal/providers/terraform/aws/rds_cluster_instance.go, internal/providers/terraform/aws/testdata/db_instance_test/db_instance_test.golden, internal/providers/terraform/aws/testdata/db_instance_test/db_instance_test.tf, internal/providers/terraform/aws/testdata/rds_cluster_instance_test/rds_cluster_instance_test.golden, internal/providers/terraform/aws/testdata/rds_cluster_instance_test/rds_cluster_instance_test.tf, internal/resources/aws/db_instance.go, internal/resources/aws/rds_cluster_instance.go
Adds cost component to `db_instance` and `rds_cluster_instance` for an extended support cost. This cost is only shown if the instnce engine and version fall into AWS's extended support category, and the current date is within the extended support window.
This is currently only applicable for mysql 5.7, for which extended support started March 2024. However, I have added tests for the rest of the versions listed in AWS docs so that we catch them in future.
The implementation for this feature means we hard code the support window in the resource. This is less than ideal but is the simplest way to accomodate the functionality right now. The pricing API response does contain an `effectiveStartDate` which we could use to filter the prices.
I avoided this, however, as it would involve a decent …
=> feat: add support for `RDS` `ExtendedSupport` cost component

internal/providers/terraform/aws/eks_cluster.go, internal/providers/terraform/aws/testdata/eks_cluster_test/eks_cluster_test.golden, internal/providers/terraform/aws/testdata/eks_cluster_test/eks_cluster_test.tf, internal/resources/aws/eks_cluster.go
Changes the eks resource to use the extended support cost for the management cost of the cluster if the version specified in the resource is past the AWS support date. Extended support is charged at $0.6 per hour per cluster and replaces old management cost of $0.1.
We currently hard code the cost ($0.6) as this cost is not currently available in the pricing API.
=> feat: add eks extended support cost

cmd/infracost/testdata/breakdown_terragrunt_with_remote_source/breakdown_terragrunt_with_remote_source.golden, internal/hcl/block.go, internal/providers/terraform/hcl_provider.go
These meta attributes never need to be evaluated since they will never affect the costs/tags.
Additionally, since `depends_on` attributes point to entire resources, we run into problems marshaling them, since the type of the object includes the types of any nested resources referenced by the `depends_on` attribute.
=> fix: don't evaluate or marshal `depends_on` or `lifecycle` meta attributes

cmd/infracost/testdata/breakdown_terragrunt_with_remote_source/breakdown_terragrunt_with_remote_source.golden
I'm not sure what happened but the update you did yesterday is now failing.
This reverts commit ab7e3c23e21718c4a642309f051a804813136ab9.
=> test: Revert "chore: update golden file test"

cmd/infracost/testdata/generate/force_project_type/expected.golden, cmd/infracost/testdata/generate/force_project_type/tree.txt, internal/hcl/project_locator.go
changes the force project type logic to only work with projects that have been detected as duplicates (they have been detected as both Terraform and Terragrunt project types).
=> fix: only apply `force_project_type` on project duplicates

cmd/infracost/diff_test.go, cmd/infracost/testdata/diff_prior_empty_project_json/base.json, cmd/infracost/testdata/diff_prior_empty_project_json/diff_prior_empty_project_json.golden, cmd/infracost/testdata/diff_prior_empty_project_json/main.tf, internal/output/combined.go, internal/schema/project.go
Changes the combined logic so that we filter any empty path errors that originate from the baseline of a current project. This is done because in the majority of cases an empty path error on the baseline just means that the project was simply added.
This resolves a UI error in Infracost Cloud where newly added projects were not shown because of the basline error.
=> fix: filter empty path error from diff baseline

cmd/infracost/testdata/generate/env_var_extensions/expected.golden, cmd/infracost/testdata/generate/env_var_extensions/infracost.yml.tmpl, cmd/infracost/testdata/generate/env_var_extensions/tree.txt, internal/config/config.go, internal/hcl/parser_test.go, internal/hcl/project_locator.go, internal/hcl/project_locator_test.go, internal/providers/detect.go, internal/providers/terraform/hcl_provider.go, internal/providers/terraform/hcl_provider_test.go, internal/testutil/generate.go
Some projects contain env vars that are have non-standard naming conventions and don't follow the common `.tfvars` and `.tfvars.json` patterns. In this case autodetect fails to pick up the variable files as part of the `ProjectLocator` configuration.
This change adds support for a autodetect configuration to allow us to specify non-standard naming conventions. This, alongside the existing `env_names` configuration field should satifsy most tfvar requirements. 
When specifying `env_var_extensions` we must validate that the file contents are valid HCL, as in many cases custom extensions might have collisions with other non var files. We do this by parsing the file using the hclsyntax library. We only do this validation when extensions are specified so as not to impact performance for other …
=> feat: add support for `env_var_extensions` autodetect configuration

cmd/infracost/generate.go, cmd/infracost/testdata/generate/detected_projects/expected.golden, cmd/infracost/testdata/generate/detected_projects/infracost.yml.tmpl, cmd/infracost/testdata/generate/detected_projects/tree.txt, internal/config/template/parser.go, internal/hcl/parser.go, internal/providers/terraform/hcl_provider.go, internal/providers/terraform/terragrunt_hcl_provider.go
This change adds a `Env` property to the `DetectedProject` struct. This allows users to access the Infracost autodetected `env` in the projects loop. This enables optional logic in the template. For example a common pattern is users provide environment as the `env` as a tfvar. Additionally regions/other logic can be configured with templ if/else logic.
=> feat: add `Env` to `DetectedProject`

cmd/infracost/testdata/breakdown_with_optional_variables/breakdown_with_optional_variables.golden, cmd/infracost/testdata/generate/env_var_extensions/expected.golden, cmd/infracost/testdata/generate/env_var_extensions/infracost.yml.tmpl, cmd/infracost/testdata/generate/env_var_extensions/tree.txt, internal/hcl/project_locator.go
Resolves an issue where prior `clean` functionality would return part of the file extension if the file extension had a substring that was part of two or more custom extension names.
We now just strip all the extension from the file name as we only want the name of the file to create env names/matches.
=> fix: change `clean` functionality for var files

cmd/infracost/testdata/breakdown_with_actual_costs/breakdown_with_actual_costs.golden, cmd/infracost/testdata/diff_terraform_v0_12/diff_terraform_v0_12.golden, cmd/infracost/testdata/diff_terraform_v0_14/diff_terraform_v0_14.golden, internal/resources/aws/db_instance.go, internal/resources/aws/dynamodb_table.go
Fixes the cost components to correctly indicate that DynamoDB WRU and RRU costs are usage based, and RDS storage costs are not.
=> fix: correct usage based indication

.github/workflows/create-docker-prerelease.yml, .github/workflows/create-prerelease.yml, scripts/get_version.sh, tools/release/main.go
Adds two prerelease pipelines. The first `create-prerelease` which calls the release go script with a new `RELEASE_ID` env variable. This variable is a static env variable that points to the [master github prerelease](https://github.com/infracost/infracost/releases/tag/untagged-0017de5d992d120d6984) that will have its assets overwritten on each master branch push. This enables users use a master branch build if they so wish.
The second `create-docker-prerelease` uploads docker image to the registry with the master tag. It does not set it as the latest release, as per the https://github.com/docker/metadata-action docs.
I've chosen to split these two actions to make the release step a bit quicker. We can run the two build steps concurrently on prerelease as we don't have as much worry that …
=> feat: add prerelease pipeline

infracost-usage-defaults.large.yml, infracost-usage-defaults.medium.yml, infracost-usage-defaults.small.yml, infracost-usage-example.yml, internal/providers/terraform/azure/network_ddos_protection_plan.go, internal/providers/terraform/azure/network_ddos_protection_plan_test.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/testdata/network_ddos_protection_plan_test/network_ddos_protection_plan_test.golden, internal/providers/terraform/azure/testdata/network_ddos_protection_plan_test/network_ddos_protection_plan_test.tf, internal/providers/terraform/azure/testdata/network_ddos_protection_plan_test/network_ddos_protection_plan_test.usage.yml, internal/resources/azure/network_ddos_protection_plan.go
Adds support for the Azure DDoS Protection service. This is a managed service that helps protected resources from DDos attacks. This service is enabled using the `azurerm_network_ddos_protection_plan` resource in Terraform.
The resource has two cost components associated with it:
1. DDoS Protection Plan: The cost of the DDoS Protection Plan.
2. Overage charges: The cost of the overage charges for the DDoS Protection Plan. This is the number of resources that fall outside the base coverage offered by the protection plan (100). This amount is defined in the usage file as it is difficult to infer the number of resources that fall outside the base coverage from the IaC.
=> feat(azure): add `azurerm_network_ddos_protection_plan` support

internal/output/templates/markdown-usage-api.tmpl, internal/output/templates/markdown.tmpl
To make this consistent with the other comment formats
=> fix: show cloud URL link for Bitbucket comments

infracost-usage-defaults.large.yml, infracost-usage-defaults.medium.yml, infracost-usage-defaults.small.yml, infracost-usage-example.yml, internal/providers/terraform/azure/federated_identity_credential.go, internal/providers/terraform/azure/federated_identity_credential_test.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/testdata/federated_identity_credential_test/federated_identity_credential_test.golden, internal/providers/terraform/azure/testdata/federated_identity_credential_test/federated_identity_credential_test.tf, internal/providers/terraform/azure/testdata/federated_identity_credential_test/federated_identity_credential_test.usage.yml, internal/resources/azure/federated_identity_credential.go
Adds support for Microsoft Entra (Azure Active Directory) External Identities through the `azurerm_federated_identity_credential`. This resource is only billed for monthly active users above the 50000 free limit. Monthly active users are charged differently based on the Microsoft Entra license type (P1 vs P2), however we cannot infer the license type from the IaC so I've added two usage parameters to support both.
=> feat(azure): add support for `azurerm_federated_identity_credential`

infracost-usage-defaults.large.yml, infracost-usage-defaults.medium.yml, infracost-usage-defaults.small.yml, infracost-usage-example.yml, internal/providers/terraform/azure/cognitive_account.go, internal/providers/terraform/azure/registry.go, internal/providers/terraform/azure/testdata/cognitive_account_test/cognitive_account_test.golden, internal/providers/terraform/azure/testdata/cognitive_account_test/cognitive_account_test.tf, internal/providers/terraform/azure/testdata/cognitive_account_test/cognitive_account_test.usage.yml, internal/resources/azure/cognitive_account_language.go
This adds to https://github.com/infracost/infracost/pull/2975, adding support for the Azure AI Language (TextAnalytics) service. It uses similar usage params as the previous the previous change.
=> feat(azure): add support for Azure AI Language (TextAnalytics)

internal/hcl/block.go, internal/hcl/evaluator.go, internal/hcl/funcs/datetime.go, internal/hcl/parser_test.go
This change resolves issue where usage of `formatdate` within an attribute value caused the value to resolve to a unknown dynamic value. This was especially problematic when used within maps and map funcitons as it caused the whole map to return as a unknown value.
I've fixed this issue by wrapping the formatdate function, checking the return value does not have any errors returned. If it does we return a safe default. I've also added support for the `time_static` resource, which initially caused us to stumble on this bug.
=> fix: unknown value issues with `formatdate` and invalid dates

internal/providers/terraform/azure/testdata/cognitive_deployment_test/cognitive_deployment_test.golden, internal/resources/azure/cognitive_account_language.go, internal/resources/azure/cognitive_account_luis.go, internal/resources/azure/cognitive_account_speech.go
It seems this is an alias for S0 sku.
=> fix(azure): support sku S for Cognitive Account

infracost-usage-defaults.large.yml, infracost-usage-defaults.medium.yml, infracost-usage-defaults.small.yml
@alikhajeh1 This zeros out egress costs defaults for google.  LMK if we want to zero out anything in cloudfront.
=> chore: Set default usage to zero for google egress

infracost-usage-defaults.large.yml, infracost-usage-defaults.medium.yml, infracost-usage-defaults.small.yml
The usage default keys should have the same comments so they can be picked up Infracost Cloud for use in the overrides UI.
=> chore: Add descriptions to usage default keys

internal/config/config.go, internal/hcl/parser.go, internal/hcl/remote_variables_loader.go, internal/providers/terraform/hcl_provider.go, schema/config.schema.json
Adds support to allow users to override the cloud workspace and org that are used by infracost cloud. This is useful when users want to "force" which org/workspace should be used and not rely on Infracost to infer it from the IaC.
=> feat: add support project config for cloud workspace and org

internal/hcl/block.go
I wasn't able to reproduce but we got a `runtime error: invalid memory address or nil pointer dereference`.
Stack trace is:
```
/panic.go:770                                    panic()
internal/hcl/block.go:1276                       (*Block).Label()
internal/providers/terraform/hcl_provider.go:412 (*HCLProvider).marshalModule.func1()
sort/zsortfunc.go:12                             insertionSort_func()
sort/zsortfunc.go:343                            stable_func()
sort/slice.go:44                                 SliceStable()
internal/providers/terraform/hcl_provider.go:411 (*HCLProvider).marshalModule()
internal/providers/terraform/hcl_provider.go:440 (*HCLProvider).marshalModule()
internal/providers/terraform/hcl_provider.go:440 (*HCLProvider).marshalModule() …
```
=> fix: avoid panic when calculating label for block

cmd/infracost/comment.go, cmd/infracost/testdata/comment_azure_repos_help/comment_azure_repos_help.golden, cmd/infracost/testdata/comment_bitbucket_help/comment_bitbucket_help.golden, cmd/infracost/testdata/comment_git_hub_help/comment_git_hub_help.golden, cmd/infracost/testdata/comment_git_hub_no_diff/comment_git_hub_no_diff.golden, cmd/infracost/testdata/comment_git_hub_show_all_projects/comment_git_hub_show_all_projects.golden, cmd/infracost/testdata/comment_git_hub_show_changed_projects/comment_git_hub_show_changed_projects.golden, cmd/infracost/testdata/comment_git_hub_with_additional_comment_path/comment_git_hub_with_additional_comment_path.golden, cmd/infracost/testdata/comment_git_lab_help/comment_git_lab_help.golden, internal/output/diff.go, internal/output/table.go
This brings the CLI comment command inline with the latest changes to the GitHub/GitLab apps by listing
unsupported resources in the cost details. This should not be too noisy since free resources are no longer listed.
=> enhance: comment should show skipped resources and projects by default

cmd/infracost/comment.go, cmd/infracost/testdata/comment_azure_repos_help/comment_azure_repos_help.golden, cmd/infracost/testdata/comment_bitbucket_help/comment_bitbucket_help.golden, cmd/infracost/testdata/comment_git_hub_help/comment_git_hub_help.golden, cmd/infracost/testdata/comment_git_hub_no_diff/comment_git_hub_no_diff.golden, cmd/infracost/testdata/comment_git_hub_show_all_projects/comment_git_hub_show_all_projects.golden, cmd/infracost/testdata/comment_git_hub_show_changed_projects/comment_git_hub_show_changed_projects.golden, cmd/infracost/testdata/comment_git_hub_with_additional_comment_path/comment_git_hub_with_additional_comment_path.golden, cmd/infracost/testdata/comment_git_lab_help/comment_git_lab_help.golden, internal/output/diff.go, internal/output/table.go
Reverts infracost/infracost#3002.
We don't want to show a long list of skipped projects by default, so we might need to adjust the functionality to truncate this or something. For now, I'm reverting this.
=> Revert "enhance: comment should show skipped resources and projects by default"

internal/providers/terraform/azure/testdata/postgresql_flexible_server_test/postgresql_flexible_server_test.golden, internal/providers/terraform/azure/testdata/postgresql_flexible_server_test/postgresql_flexible_server_test.tf, internal/resources/azure/postgresql_flexible_server.go
Fixes #3012.
The product name is different for v5:
- `Azure Database for PostgreSQL Flexible Server General Purpose Dadsv5 Series Compute` for Dads v5
- `Azure Database for PostgreSQL Flexible Server General Purpose - Ddsv5 Series Compute` for Dds v5
It also fixes product search for Esv3.
=> fix(azure): Fix filters for Dds v5 PostgreSQL Flexible Servers

cmd/infracost/diff_test.go, cmd/infracost/testdata/diff_terragrunt_syntax_error/baseline.withouterror.json, cmd/infracost/testdata/diff_terragrunt_syntax_error/diff_terragrunt_syntax_error.golden, cmd/infracost/testdata/diff_terragrunt_syntax_error/infracost.config.yml, cmd/infracost/testdata/diff_terragrunt_syntax_error/terragrunt/dev/terragrunt.hcl, cmd/infracost/testdata/diff_terragrunt_syntax_error/terragrunt/modules/example/main.tf, cmd/infracost/testdata/diff_terragrunt_syntax_error/terragrunt/prod/terragrunt.hcl, cmd/infracost/testdata/diff_terragrunt_syntax_error/terragrunt/terragrunt.hcl, internal/output/combined.go
If a nested terragrunt project has syntax errors, the error is reported at the parent project path. To prevent the child project from appearing as "removed" when diff'd against a baseline without the syntax error, we search for and remove child projects of the parent path. BUT, since some child projects may have been processed successfully, we should only remove past children that don't exist in the current.
=> fix: don't remove child of errored prior projects that exist in current

internal/hcl/block.go, internal/hcl/block_test.go, internal/hcl/reference.go
Previously these appeared in logs as `block_name=content.` This now fixes it so it shows `block_name=aws_security_group.my_sg.dynamic.ingress.content`.
We do this by looping through any parent blocks and prefixing the block name with their labels.
=> fix: dynamic block names in logs

internal/providers/detect.go
Resolves issue where `infracost generate` throws an panic if an error is encountered during `Detect`.
=> fix: always return `DetectionOutput` from `Detect`

cmd/infracost/testdata/generate/wildcard_env_names/expected.golden, cmd/infracost/testdata/generate/wildcard_env_names/infracost.yml.tmpl, cmd/infracost/testdata/generate/wildcard_env_names/tree.txt, internal/hcl/project_locator.go
Adds support for wildcard naming in autodetect `envNames` configuration. This enables users to define conventions for env names that can dynamically expand in the future. This greatly reduces the burden of managing the envNames section and makes it more maintainable.
=> feat: support wildcards for autodetect `envNames`

cmd/infracost/main.go
This resolves an issue where the debug-report panics when the
`--debug-report` argument is passed. This looks like its because more
characters are being assumed to have been removed that have so
simplifying it by removing the comma
Resolves #3011
```
INFRACOST_ENV=dev go run ./cmd/infracost breakdown --path examples/terraform --debug-report
panic: bytes.Buffer.WriteTo: invalid Write count [recovered]
panic: bytes.Buffer.WriteTo: invalid Write count
goroutine 1 [running]:
bytes.(*Buffer).WriteTo(0x140005a1d70, {0x103048338?, 0x14000092d80?})
/opt/homebrew/Cellar/go/1.22.2/libexec/src/bytes/buffer.go:263 +0x108
github.com/rs/zerolog.ConsoleWriter.Write({{0x103048338, 0x14000092d80}, 0x1, {0x101c0f986, 0x19}, {0x140004b7280, 0x4, 0x4}, {0x0, 0x0, ...}, ...}, ...) …
```
=> bug: debug-report panics

cmd/infracost/breakdown_test.go, cmd/infracost/cmd_test.go, cmd/infracost/testdata/breakdown_terraform_file_funcs/breakdown_terraform_file_funcs.golden, cmd/infracost/testdata/breakdown_terraform_file_funcs/instance.json, cmd/infracost/testdata/breakdown_terraform_file_funcs/main.tf, cmd/infracost/testdata/breakdown_terraform_file_funcs/modules/test/instance.json, cmd/infracost/testdata/breakdown_terraform_file_funcs/modules/test/main.tf, cmd/infracost/testdata/breakdown_terraform_file_funcs/sym-instance.json, cmd/infracost/testdata/breakdown_terraform_file_funcs/templ.tftpl, cmd/infracost/testdata/breakdown_terragrunt_file_funcs/breakdown_terragrunt_file_funcs.golden, cmd/infracost/testdata/breakdown_terragrunt_file_funcs/instance.json, cmd/infracost/testdata/breakdown_terragrunt_file_funcs/main.tf, cmd/infracost/testdata/breakdown_terragrunt_file_funcs/modules/test/instance.json, cmd/infracost/testdata/breakdown_terragrunt_file_funcs/modules/test/main.tf, cmd/infracost/testdata/breakdown_terragrunt_file_funcs/sym-instance.json, cmd/infracost/testdata/breakdown_terragrunt_file_funcs/templ.tftpl, cmd/infracost/testdata/breakdown_terragrunt_file_funcs/terragrunt.hcl, cmd/testdata/instance.json, cmd/testdata/templ.tftpl, internal/hcl/evaluator.go, internal/hcl/funcs/filesystem.go, internal/hcl/funcs/filesystem_test.go, internal/providers/terraform/terragrunt_hcl_provider.go
Changes `isPathInRepo` to use wd directory instead of `RepoPath` which is likely incorrect for Terragrunt projects.
The `RepoPath` property that is infered from detected projects was returning full project path for detected projects when the autdetected project was inferred from a config file. A fix for this will be addressed in a further PR.
To fix the templatefile logic I've opted to use the os working directory instead, as this is more robust.
=> feat: readd templatefile support

scripts/get_version.sh
Some release assets ended up with version 'Infracost v0.10.35+v0.10.35-v0.10.35' after the last release.  I wasn't able to reproduce the problem, but this change updates the version script to be more robust. It uses regex (instead of awk) to parse the expected tag format and falls back to using the full tag string as the version if it is in an unexpected format.
=> fix: use regex to handle version matching instead of awk

.golangci.yml, cmd/infracost/diff_test.go, cmd/infracost/output_test.go, cmd/infracost/run.go, cmd/infracost/testdata/diff_prior_empty_project_json/diff_prior_empty_project_json.golden, cmd/infracost/testdata/diff_with_compare_to_format_json/diff_with_compare_to_format_json.hcl.golden, cmd/infracost/testdata/diff_with_compare_to_format_json/prior.json, cmd/infracost/testdata/diff_with_compare_to_no_metadata_format_json/diff_with_compare_to_no_metadata_format_json.golden, cmd/infracost/testdata/diff_with_compare_to_no_metadata_format_json/diff_with_compare_to_no_metadata_format_json.hcl.golden, cmd/infracost/testdata/diff_with_compare_to_no_metadata_format_json/main.tf, cmd/infracost/testdata/diff_with_compare_to_no_metadata_format_json/prior.json, cmd/infracost/testdata/diff_with_compare_to_with_current_and_past_project_error/diff_with_compare_to_with_current_and_past_project_error.golden, cmd/infracost/testdata/diff_with_compare_to_with_current_project_error/diff_with_compare_to_with_current_project_error.golden, cmd/infracost/testdata/diff_with_compare_to_with_past_project_error/diff_with_compare_to_with_past_project_error.golden, cmd/infracost/testdata/diff_with_free_resources_checksum/diff_with_free_resources_checksum.golden, cmd/infracost/testdata/diff_with_policy_data_upload/diff_with_policy_data_upload.golden, cmd/infracost/testdata/example_diff_out.json, cmd/infracost/testdata/output_diff_format_json/output_diff_format_json.golden, internal/output/metadata.go, internal/vcs/metadata.go, schema/infracost.schema.json
It's empty on breakdown, and base branch's HEAD SHA on diff/output.
NB: When combining several JSONs in output command latest item's metadata will be used in the output.
=> feat: Add vcsBaseCommitSha to estimate metadata

internal/output/table.go, internal/providers/terraform/aws/testdata/eks_cluster_test/eks_cluster_test.golden, internal/providers/terraform/aws/testdata/lightsail_instance_test/lightsail_instance_test.golden, internal/providers/terraform/azure/testdata/cognitive_account_test/cognitive_account_test.golden, internal/resources/azure/cognitive_account_speech.go
Commits the extended support costs for eks cluster and lightsail instance test. Changes the Azure AI services tests meter naming to fix prices not found. This also includes minor changes to the cognitive service pricing.
=> fix: aws/azure failing tests

cmd/infracost/generate.go, cmd/infracost/testdata/generate/module_calls/expected.golden, cmd/infracost/testdata/generate/module_calls/tree.txt, cmd/infracost/testdata/generate/module_calls_with_template/expected.golden, cmd/infracost/testdata/generate/module_calls_with_template/infracost.yml.tmpl, cmd/infracost/testdata/generate/module_calls_with_template/tree.txt, internal/config/template/parser.go, internal/hcl/parser.go, internal/hcl/project_locator.go, internal/providers/terraform/hcl_provider.go, internal/providers/terraform/terragrunt_hcl_provider.go, internal/testutil/generate.go
Resolves issues where local module changes were not triggering project reruns. This has been addressed in this PR by adding the detected module calls from the `ProjectLocator` to the `dependency_paths` for each auto detected project.
**Note:** This does not solve explicitly solve issues with dependencies and Terragrunt projects. These are more nuanced and require additional work. For example handling Terragrunt `include` blocks with a `src` that resides outside the project path.
=> fix: create `dependency_paths` for auto generated config

cmd/infracost/generate.go, cmd/infracost/testdata/generate/module_calls/expected.golden, cmd/infracost/testdata/generate/module_calls/tree.txt, cmd/infracost/testdata/generate/module_calls_with_template/expected.golden, cmd/infracost/testdata/generate/module_calls_with_template/infracost.yml.tmpl, cmd/infracost/testdata/generate/module_calls_with_template/tree.txt, internal/config/template/parser.go, internal/hcl/modules/loader.go, internal/hcl/modules/manifest.go, internal/hcl/parser.go, internal/hcl/project_locator.go, internal/providers/terraform/hcl_provider.go, internal/providers/terraform/terragrunt_hcl_provider.go, internal/testutil/generate.go
Reinstates the work done in https://github.com/infracost/infracost/pull/3063 but with an additional fix that can be viewed in 0dd176e293d763c5956db78bac18d66c72e0499d, This Removes remote modules from the `ProjectLocator` moduleCall list as these module calls are only designed to build a local dependency tree. Excluding remote modules also indirectly fixes an issue with YAML parsing the generated config where remote module strings were causing errors, e.g:
```
dependency_paths:
- golden_tests/test_https_module/git::https:/github.com/infracost/terraform-private-module-example.git
```
Would cause the YAML validate step for the infracost config file to error.
=> fix: readd autogenerated `dependency_paths` with remote module fix.

internal/hcl/block.go, internal/providers/terraform/aws/eks_node_group_test.go, internal/providers/terraform/aws/testdata/eks_node_group_test/eks_node_group_test.golden, internal/providers/terraform/aws/testdata/eks_node_group_test/eks_node_group_test.tf
This PR adds support for launch templates which are referenced by `name` in a resource but use a `prefix` to launch. This means that the `name` attribute can be `null` and prior to this change, references would not work. This change adds a Infracost generated `name` if it is detected that the `launch_template` has a `null` name.
=> fix: support launch templates references which use `prefix`

cmd/infracost/diff_test.go, cmd/infracost/generate_test.go, cmd/infracost/testdata/generate/include_dirs/expected.golden, cmd/infracost/testdata/generate/include_dirs/infracost.yml.tmpl, cmd/infracost/testdata/generate/include_dirs/tree.txt, internal/config/config_test.go, internal/hcl/parser_test.go, internal/hcl/project_locator.go, internal/providers/terraform/hcl_provider.go, internal/providers/terraform/tftest/tftest.go
If we specify a hidden directory in `include_dirs` in the autodetect config, it should be detected correctly.
By default, hidden directories will still be excluded.
=> fix: support hidden directories in autodetect

cmd/infracost/breakdown_test.go, cmd/infracost/testdata/breakdown_format_json_with_tags/breakdown_format_json_with_tags.golden, cmd/infracost/testdata/breakdown_format_json_with_tags/main.tf, cmd/infracost/testdata/breakdown_format_json_with_tags_version_less_than5point39/breakdown_format_json_with_tags_version_less_than5point39.golden, cmd/infracost/testdata/breakdown_format_json_with_tags_version_less_than5point39/main.tf, cmd/infracost/testdata/breakdown_with_policy_data_upload_hcl/breakdown_with_policy_data_upload_hcl-upload.golden, cmd/infracost/testdata/breakdown_with_policy_data_upload_hcl/breakdown_with_policy_data_upload_hcl.golden, cmd/infracost/testdata/breakdown_with_policy_data_upload_plan_json/breakdown_with_policy_data_upload_plan_json-upload.golden, cmd/infracost/testdata/breakdown_with_policy_data_upload_plan_json/breakdown_with_policy_data_upload_plan_json.golden, cmd/infracost/testdata/breakdown_with_policy_data_upload_terragrunt/breakdown_with_policy_data_upload_terragrunt-upload.golden, cmd/infracost/testdata/breakdown_with_policy_data_upload_terragrunt/breakdown_with_policy_data_upload_terragrunt.golden, cmd/infracost/testdata/diff_with_policy_data_upload/diff_with_policy_data_upload.golden, internal/hcl/constraints.go, internal/hcl/module.go, internal/hcl/parser.go, internal/providers/terraform/aws/tags.go, internal/providers/terraform/hcl_provider.go, internal/providers/terraform/parser.go, internal/providers/terraform/testdata/hcl_provider_test/builds_module_configuration_correctly_with_count/expected.json, internal/providers/terraform/testdata/hcl_provider_test/does_not_panic_on_double_attribute_definition/expected.json, internal/providers/terraform/testdata/hcl_provider_test/populates_warnings_on_missing_vars/expected.json, internal/providers/terraform/testdata/hcl_provider_test/renders_module_resources/expected.json, internal/providers/terraform/testdata/hcl_provider_test/renders_multiple_count_resources_correctly/expected.json, internal/providers/terraform/testdata/hcl_provider_test/shows_correct_duplicate_variable_warning/expected.json, internal/providers/terraform/testdata/hcl_provider_test/structures_module_expressions_correctly_with_count/expected.json
Fixes issue where provider tags were not being used as defaults in volume tags. Provider defaults propagating to `volume_tags` was introduced in version `v5.39.0` of the aws provider https://github.com/hashicorp/terraform-provider-aws/issues/19890. 
To accomodate this functionality we add any of the default tags with the `volume_tags` prefix if the current resource supports `volume_tags` (currently just `aws_instance`). This is only done if the version constraint specified at the root level `terraform` `require_providers` block is compatible with the `5.39.0` version. e.g. `>= 5.0`. Versions which specify a maximum version, e.g. `~> 3.0` below `5.39` will not have the default tags passed to volume tags. If no version constraint is found/can be parsed we add default tags to volume_tags by …
=> fix: propagate default provider tags to volume tags

cmd/infracost/testdata/generate/module_calls/expected.golden, cmd/infracost/testdata/generate/module_calls_with_template/expected.golden, internal/hcl/parser.go
Adds the project path to the generated project `dependency_paths`. This is because `dependency_paths` are treated as a change detection override. Meaning that prior to this change Infracost hosted runners would only see a project as changed if a folder in its `dependency_paths` changed.
=> fix: add the project path as a dependency in generated output

internal/hcl/evaluator.go, internal/hcl/graph_vertex_data.go, internal/hcl/graph_vertex_provider.go, internal/hcl/graph_vertex_resource.go
The `SetByDot` function handles the merging anyway, so we don't need to pull out the existing values. I've left the old functionality in the `evaluateResource` and `evaluatorProvider` functions because the legacy evaluator needs it.
This also fixes an issue where the data blocks were using `e.ctx.Get(b.TypeLabel())` which was getting the wrong context. The correct functionality would have been to use `e.ctx.Get("data")`. Otherwise, this caused issues where the type of a data block matched the name of a resource, e.g. `data.aws_lb.anything` and `aws_lb.aws_lb`. In this case it would pull the context of the resource, which could cause a panic if the resource had been expanded, because it would be an array instead of the expected map.
=> fix: don't use existing context when evaluating resources, data or provider blocks

internal/providers/terraform/azure/firewall_policy.go, internal/providers/terraform/azure/firewall_policy_rule_collection_group.go, internal/providers/terraform/azure/registry.go
Add forward and backward references for the Azure Firewall Policy to lookup the Firewall Policy Rule Collection Group. 
This is required for the Azure Firewall Finops policy so that it can check if there are application rules associated with the Firewall Policy
=> Configure references for the Azure Firewall Policy

internal/providers/terraform/aws/testdata/eks_cluster_test/eks_cluster_test.golden
v1.26 is on extended support since June 11th 2024.
=> chore: Update AWS EKS Cluster resource tests

internal/apiclient/policy.go, internal/providers/terraform/hcl_provider.go, internal/providers/terraform/hcl_provider_test.go, internal/providers/terraform/testdata/hcl_provider_test/.gitignore, internal/providers/terraform/testdata/hcl_provider_test/adds_source_url_from_remote_module/expected.json, internal/providers/terraform/testdata/hcl_provider_test/adds_source_url_from_remote_module/main.tf
Adds additional metadata to Infracost resources which are used in external modules. This adds a fully qualified external URL to the remote where the resource lives, referencing the file and version used. Additionally this PR adds helper metadata to flatten the first module call into the resource metadata so it is easier for the dashboard to work with.
=> feat: add external module metadata to resources

internal/providers/terraform/hcl_provider.go, internal/providers/terraform/hcl_provider_test.go, internal/providers/terraform/testdata/hcl_provider_test/adds_source_url_from_remote_module_chdir/expected.json, internal/providers/terraform/testdata/hcl_provider_test/adds_source_url_from_remote_module_chdir/main.tf
Changes the remote module cache dir matcher to have optional directories in front of the `.infracost` cache dir. This is likely to happen when infracost is run with a path in the same working directory. As is most often the case with config files. Prior to this change the regex matcher was not matching module files such as `.infracost/terraform_modules/foo/main.tf` and therefore not sending the required `moduleFilename` to the API to identify the file as originating from a remote module.
=> fix: `.infracost` cache dir regex matcher

internal/apiclient/policy.go
Fixes issue where parent values for filename and line numbers were being used for the `Calls` values of a block when sent to policy set API. Instead these values should come from the `ModuleMetadata` so that we can correctly infer the callstack.
=> fix: use correct values for module calls

internal/config/template/parser.go
Adds some more config template functions.
Also updates the `parseJson` and `parseYaml` functions to not panic on errors. We don't want to stop the whole config template execution on this. It seems safer to log and not panic on these errors, since we shouldn't fail runs if we're unable to parse them. In the future if we want an option that does return error we can do what sprig does and create `mustParseYaml` and `mustParseJson` functions.
=> Add more config template functions

internal/config/template/parser.go
This makes it consistent with sprig's implementation. The last argument is the src string, so using it as a filter like `"I Am Henry VIII" | replace " " "-"` works.
=> fix: fix config template replace function so it works as filter

cmd/infracost/breakdown_test.go, cmd/infracost/testdata/breakdown_format_json_with_tags_google/breakdown_format_json_with_tags_google.golden, cmd/infracost/testdata/breakdown_format_json_with_tags_google/main.tf, internal/hcl/constraints.go, internal/hcl/constraints_test.go, internal/hcl/parser_test.go, internal/providers/terraform/google/google.go, internal/providers/terraform/hcl_provider.go, internal/providers/terraform/parser.go
Adds support for the Google providers `default_labels`. We only attempt to parse these when the provider version is constrained at `>= v5.0.0`.
Once default values are parsed, works in entirely the same way as AWS `default_tags`.
I added default labels to the `breakdown_format_json_with_tags_google` tests/golden file. I also refactored the contraints code to gather version constraints for Google, and to make it trivial to add further providers.
See https://www.hashicorp.com/blog/terraform-google-provider-adds-updates-to-default-labels for more info.
=> feat: Add Google provider default labels

cmd/infracost/testdata/breakdown_format_json_with_tags_aft_module/breakdown_format_json_with_tags_aft_module.golden, internal/hcl/block.go
we got a prod error with this stacktrace
/panic.go:770                                    panic()
internal/hcl/block.go:1385                       launchTemplateValues()
internal/hcl/block.go:1062                       (*Block).Values()
internal/hcl/evaluator.go:962                    (*Evaluator).evaluateResourceOrData()
...
=> fix: don't panic if the launchTemplateData map is nil

cmd/infracost/breakdown_test.go, cmd/infracost/run.go, cmd/infracost/testdata/breakdown_help/breakdown_help.golden, cmd/infracost/testdata/breakdown_with_complex_config_file_vars/breakdown_with_complex_config_file_vars.golden, cmd/infracost/testdata/breakdown_with_complex_config_file_vars/infracost-usage.yml, cmd/infracost/testdata/breakdown_with_complex_config_file_vars/infracost.yml, cmd/infracost/testdata/breakdown_with_complex_config_file_vars/main.tf, cmd/infracost/testdata/breakdown_with_complex_var_flags/breakdown_with_complex_var_flags.golden, cmd/infracost/testdata/breakdown_with_complex_var_flags/infracost-usage.yml, cmd/infracost/testdata/breakdown_with_complex_var_flags/main.tf, cmd/infracost/testdata/diff_compare_to_error/diff_compare_to_error.golden, cmd/infracost/testdata/diff_compare_to_error_terragrunt/diff_compare_to_error_terragrunt.golden, cmd/infracost/testdata/diff_help/diff_help.golden, cmd/infracost/testdata/flag_errors_config_file_and_terraform_workspace/flag_errors_config_file_and_terraform_workspace.golden, cmd/infracost/testdata/flag_errors_no_path/flag_errors_no_path.golden, cmd/infracost/testdata/flag_errors_path_and_config_file/flag_errors_path_and_config_file.golden, internal/config/config.go, internal/hcl/parser.go, internal/providers/terraform/terragrunt_hcl_provider.go, schema/config.schema.json
This adds support for more complex shaped Terraform vars (maps, lists) passed in via the Infracost config file or the `--terraform-var` flag, like:
```
--terraform-var='instance_config={"instance_type":"t2.micro","storage":20}'
```
or in the Infracost config file like:
```yaml
terraform_vars:
instance_config:
instance_type: t2.micro
storage: 20
```
I went with the approach of using `ctyJson.SimpleJSONValue` since it seems to be the easiest and most robust way of doing this, other than recursively mapping the types ourselves.
=> enhance: support more complex Terraform vars

cmd/infracost/testdata/breakdown_terragrunt_with_remote_source/ref1/terragrunt.hcl, cmd/infracost/testdata/breakdown_terragrunt_with_remote_source/ref2/terragrunt.hcl, internal/hcl/remote_variables_loader.go
Previously this was erroring. I think it makes more sense to warn here because the user might not have any variables specified remotely, so it doesn't make sense to block the execution. Instead this should continue and show them any warnings for missing variables.
=> fix: warn on missing Terraform workspace

cmd/infracost/breakdown_test.go, cmd/infracost/testdata/breakdown_terraform_tfjson/breakdown_terraform_tfjson.golden, cmd/infracost/testdata/breakdown_terraform_tfjson/main.tf.json, internal/hcl/block.go, internal/hcl/parser_test.go
There's a typo which means when the body of the parsed HCL file is a JSON body, we're not returning the attributes correctly.
=> fix: detection of HCL attributes for *.tf.json files

cmd/infracost/generate.go, cmd/infracost/testdata/generate/repo_name/expected.golden, cmd/infracost/testdata/generate/repo_name/infracost.yml.tmpl, cmd/infracost/testdata/generate/repo_name/tree.txt, internal/config/template/parser.go
Adds support for use of logic gates within the config template based on the current repository name.
=> feat: add `RepoName` variable to config template

cmd/infracost/run.go, cmd/infracost/testdata/breakdown_plan_error/breakdown_plan_error.golden, cmd/infracost/testdata/breakdown_terragrunt_diff_project_error/breakdown_terragrunt_diff_project_error.golden, cmd/infracost/testdata/breakdown_terragrunt_diff_project_error/prior.json, cmd/infracost/testdata/diff_terragrunt_syntax_error/diff_terragrunt_syntax_error.golden
Adds `TerraformModulePath` to any errored project. This resolves an issue in the `diff` command. Errored projects that were discovered at a child path of the initial path provided in the config would have the same `Path` and or `Name` metadata. This would cause a `compare-to` conflict because we saw them as duplicate projects, even though these projects were actually located in different directories.
=> fix: adds module path to errored project

cmd/infracost/testdata/breakdown_format_json_with_tags_version_less_than5point39/breakdown_format_json_with_tags_version_less_than5point39.golden, internal/hcl/constraints.go, internal/hcl/constraints_test.go
The `~>` constraint operator should only require the rightmost _specified_ number to be greater than or equal. We were always requiring the patch version as this is the rightmost number of the actual version number. Now we check whether the user specifies a patch, minor, or major number as the rightmost level, for example: 
- `~> 3.0.1` does not allow `3.38` to be installed
- `~> 3.0` does allow `3.38` to be installed
- `~> 3` does allow `3.38` to be installed
- `~> 2.0` does not allow `3.38` to be installed
- `~> 2` does allow `3.38` to be installed
=> fix: Only check minor version in constraints check when patch is specified

cmd/infracost/testdata/generate/child_with_dot/expected.golden, cmd/infracost/testdata/generate/child_with_dot/tree.txt, internal/hcl/project_locator.go
Resolves issue where a terraform var file that started with an env name but was preceded by a `.` would fail to match an env, e.g `dev.foo.tfvars`. This was because of a typo in the prefix matching logic see [here](https://github.com/infracost/infracost/pull/3170/files#diff-169eaffd399624f8000fc1ab1f0bd319ec79ea58058f53e848ccdc16f6633710R223). Changing this logic also exposed an issue when matching hidden file var files (those starting with a `.`). As the previous typo was allowing for them to be successfully matched. Now that I've fixed the prefix matching logic, i've also changed the `clean` logic to remove `.` from the filenames so that the hidden files -> env name matching works as expected.
=> fix: terraform env matching on colon separated filenames

cmd/infracost/breakdown_test.go, cmd/infracost/run.go, internal/hcl/parser.go, internal/hcl/remote_variables_loader.go, internal/hcl/var.go, internal/hcl/var_test.go
This adds support for variables that are specified with HCL syntax.
Previously we had supported complex variables, e.g. `--terraform-vars='custom_tags={"env": "prod", "project": "myproj"}'`, but we didn't support this if using HCL syntax, e.g. `--terraform-vars='custom_tags={env = "prod", project = "myproj"}'`.
This also updates the Terraform Cloud remote variable parsing to use the same logic as other variable parsing. It also supports loading in Terraform variables from Terraform Cloud if they are set as environment variables (i.e. with a `TF_VARS_` prefix).
=> enhance: support complex remote variables

internal/providers/terraform/aws/testdata/rds_cluster_instance_test/rds_cluster_instance_test.golden, internal/providers/terraform/aws/testdata/rds_cluster_instance_test/rds_cluster_instance_test.tf, internal/providers/terraform/aws/testdata/rds_cluster_instance_test/rds_cluster_instance_test.usage.yml, internal/resources/aws/db_instance.go, internal/resources/aws/rds_cluster_instance.go
Cost components were not being identified for the retention of performance insights data for aurora clusters.
=> fix: Calculate pricing for performance insights retention (> 7 days) for Serverless v2

.github/workflows/go.yml, cmd/infracost/comment.go, cmd/infracost/comment_azure_repos.go, cmd/infracost/comment_bitbucket.go, cmd/infracost/comment_github.go, cmd/infracost/comment_gitlab.go, cmd/infracost/output.go, cmd/infracost/upload.go, internal/hcl/block.go, internal/output/format_test.go, internal/providers/terraform/azure/mssql_database.go, internal/providers/terraform/azure/sql_database.go, internal/providers/terraform/dir_provider.go, internal/resources/aws/db_instance.go, internal/resources/aws/ec2_host.go, internal/resources/aws/elasticache_cluster.go, internal/resources/aws/instance.go, internal/resources/aws/rds_cluster_instance.go, internal/resources/aws/s3_bucket.go, internal/testutil/testutil.go
I also updated the action version as it was a few major versions out and starting to cause deprecation warnings when running the linter.
=> chore: Fix linting issues detected by newer golangci-lint

go.mod, go.sum, internal/hcl/modules/loader.go, internal/providers/terraform/terragrunt_hcl_provider.go
This implements a two changes for improving the speed of Terragrunt repos which reference sources within large monorepos.
1. Enables the partial parse config cache (https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-use-partial-parse-config-cache)
2. Adds an option to use `git sparse-checkout` for downloading only specific subdirectories of remote modules. This also handles special cases for local references to other subdirectories of that module, or symlinks within that module.
=> Terragrunt speed

cmd/infracost/comment.go, cmd/infracost/comment_github.go, internal/apiclient/dashboard.go
* make sure the AddRunResponse is returned after uploading the run
* upload the pr comment when cloud upload is enabled (either explicitly or implicitly)
=> fix: save posted comment when cloud is enabled

internal/providers/terraform/parser.go, internal/providers/terraform/parser_test.go
This fixes an issue where references for count or for each resources within a count or foreach module where not correctly matched because the reference lookup function incorrectly used the module index as the resource index. 
For example, a resource referencing `module.mymod[0].aws_resource.my_resource[1]` would mistakenly be mapped to `module.mymod[0].aws_resource.my_resource[0]`.
=> fix: correct reference lookups of count/each resources in count/each modules

internal/hcl/zones_aws.go, internal/providers/terraform/aws/testdata/data_transfer_test/data_transfer_test.golden, internal/providers/terraform/aws/testdata/data_transfer_test/data_transfer_test.usage.yml, internal/resources/aws/cloudfront_distribution.go, internal/resources/aws/global_accelerator_endpoint_group.go, internal/resources/aws/util.go
NOTE: Also added `il-central-1` to the `RegionsUsage` struct as it was missing, but not sure if that was deliberate?
=> feat: Add ap-southeast-5 aws region

internal/hcl/modules/loader.go, internal/providers/terraform/terragrunt_hcl_provider.go, internal/providers/terraform/testdata/hcl_provider_test/adds_source_url_from_remote_module/expected.json, internal/providers/terraform/testdata/hcl_provider_test/adds_source_url_from_remote_module_chdir/expected.json, internal/providers/terraform/testdata/hcl_provider_test/renders_module_resources/expected.json
The updates the pre-processing of Terragrunt dependencies to take into account instances where a function is called on the dependency. For example, previous we were looking for patterns like `dependency.my-mod.my-output[0]` to be able to tell if the output should be mocked as a list. Now we also look for patterns like `tolist(dependency.my-mod.my-output)[0]`.
Eventually we will want to replace the internal Terragrunt HCL decoding to use our own so that we handle mocks better, but this unblocks us for just now.
The tests were also failing because a remote module has been updated, so I had to fix a bug with the sparse checkouts to be able to update them.
=> Fix Terragrunt dep output mocks

internal/providers/terraform/aws/testdata/vpc_endpoint_test/vpc_endpoint_test.golden, internal/providers/terraform/aws/testdata/vpc_endpoint_test/vpc_endpoint_test.usage.yml, internal/resources/aws/vpc_endpoint.go
The previous configuration had 1TB and 5TB tiers instead of 1PB and 5PB.
This fix correctly computes costs at all traffic levels rather than improperly deflating costs.
See https://github.com/infracost/infracost/issues/3228
=> fix: AWS VPC Endpoint pricing tiers are wrong #3228

internal/hcl/block.go, internal/hcl/parser_test.go
Previously this data attribute got mocked to a string value. That meant if users were doing anything like `length(data.aws_subnets.private_subnets.ids)` this could return high numbers, which was massively affecting any cost estimates where this was being used in a `count` or `for_each`.
Although we can't actually know the number of subnets, we can mock it to a more sensible value. 3 seems like the most common number of subnets used.
=> fix: add mocking for `data.aws_subnets`

cmd/infracost/testdata/breakdown_format_json_with_tags_aft_module/breakdown_format_json_with_tags_aft_module.golden, cmd/infracost/testdata/breakdown_format_json_with_tags_aft_module/main.tf, cmd/infracost/testdata/generate/excluded_dirs_glob/expected.golden, cmd/infracost/testdata/generate/excluded_dirs_glob/infracost.yml.tmpl, cmd/infracost/testdata/generate/excluded_dirs_glob/tree.txt, internal/hcl/project_locator.go
`filepath.Glob` doesn't support `**` so using the same glob library we use elsewhere.
=> fix: support "**" in excluded_dirs

internal/hcl/parser.go, internal/hcl/remote_variables_loader.go, internal/hcl/remote_variables_loader_test.go, internal/providers/terraform/hcl_provider.go
1. Update the Spacelift remote variable loader to load in variables from all 3 of the locations:
- Environment
- Spacelift environment
- Attached contexts.
We should look for any key starting with `TF_VAR_`
2. Update the Spacelift remote variable loader to better match on stack name. I think the following logic would work:
1. Match the repository name exactly
2. Match the projectRoot exactly based on the path of the module
3. Query for multiple results
4. If the project has a `moduleSuffix` then match on that using what is after the `:` in the project name. If there’s no `moduleSuffix`, then skip this step.
5. Log a warning if there’s more than one match or no matches
=> fix: fix Spacelift var loading

internal/providers/terraform/hcl_provider.go
Add a new env var `INFRACOST_JSON_DUMP_PATH` to specify a target path to
drop the plan files when the `INFRACOST_JSON_DUMP` env var has been
specified.
This is to support policy engine processing the plan file
---
Below is a concise technical summary of the changes proposed in this PR:
<p>Introduce an environment variable <code>INFRACOST_JSON_DUMP_PATH</code> in <code>HCLProvider</code> to specify a custom path for JSON plan file dumps when <code>INFRACOST_JSON_DUMP</code> is enabled.</p>
<table><tr><th>Topic</th><th>Details</th><tr><td><a href=https://baz.co/changes/infracost/infracost/3240?tool=ast&topic=JSON+Dump+Path>JSON Dump Path</a>
</td><td>Add an environment variable <code>INFRACOST_JSON_DUMP_PATH</code> to specify a custom path for JSON plan file dumps.<details><summary>Modified …
=> chore: add an env var for json dump path

cmd/infracost/testdata/generate/env_names_in_path/expected.golden, cmd/infracost/testdata/generate/env_names_in_path/infracost.yml.tmpl, cmd/infracost/testdata/generate/env_names_in_path/tree.txt, cmd/infracost/testdata/generate/modules_and_external_tfvars/expected.golden, internal/hcl/parser.go, internal/hcl/project_locator.go, internal/providers/detect.go
When an env name is in the path already, we should ignore the other envs.
=> fix: Fix config generator when env name is in the project path IC-1911

cmd/infracost/testdata/breakdown_with_actual_costs/breakdown_with_actual_costs.golden, cmd/infracost/testdata/breakdown_with_actual_costs_pitr_disabled/breakdown_with_actual_costs_pitr_disabled.golden, cmd/infracost/testdata/diff_with_compare_to_with_current_and_past_project_error/diff_with_compare_to_with_current_and_past_project_error.golden, cmd/infracost/testdata/diff_with_compare_to_with_current_project_error/diff_with_compare_to_with_current_project_error.golden, cmd/infracost/testdata/diff_with_compare_to_with_past_project_error/diff_with_compare_to_with_past_project_error.golden, internal/output/combined.go, internal/providers/terraform/aws/testdata/dynamodb_table_test/dynamodb_table_test.golden, internal/schema/project.go, schema/infracost.schema.json
The project metadata previously contained a single errors field containing any errors that occurred in either side of a diff. This change makes it possible to determine which side of the diff the errors came from.
=> enhance: Add curent and past errors to project metadata

internal/hcl/modules/loader.go
We need to clean up any partially downloaded modules if there is an error (e.g. if the module was downloaded but the ref couldn't be checked out), otherwise when another project tries to download the same module the `_, err = os.Stat(dest)` will decide that it has been previously downloaded successfully.
=> fix: cleanup bad module download directories

internal/comment/azure_repos.go
Reads the body of the response if we get a non 200 code response from posting a comment.
=> enhance: output the response body when comment fails to post

cmd/infracost/breakdown_test.go, cmd/infracost/testdata/breakdown_terraform_file_funcs/breakdown_terraform_file_funcs.golden, cmd/infracost/testdata/breakdown_terragrunt_file_funcs/breakdown_terragrunt_file_funcs.golden, cmd/infracost/testdata/breakdown_terragrunt_partial_inputs/breakdown_terragrunt_partial_inputs.golden, cmd/infracost/testdata/breakdown_terragrunt_partial_inputs/modules/example/main.tf, cmd/infracost/testdata/breakdown_terragrunt_partial_inputs/prod/terragrunt.hcl, cmd/infracost/testdata/breakdown_terragrunt_partial_inputs/terragrunt.hcl, go.mod, go.sum, internal/hcl/attribute.go, internal/hcl/attribute_test.go, internal/hcl/block.go, internal/hcl/funcs/filesystem.go, internal/hcl/funcs/filesystem_test.go, internal/providers/terraform/terragrunt_hcl_provider.go
Improves the Terragrunt parser's ability to provide a partial value for the inputs. Prior to this change any nasty hcl errors within the inputs attribute for a Terragrunt hcl file would mean that we passed empty values to the underlying Terraform module call variables. This change hooks into a new DiagnosticFunc hook (see https://github.com/infracost/terragrunt/pull/19) that allows us to fallback to our parsing/mocking logic for the inputs value.
Note: I will merge the terragrunt pull first then update the go mod with the master sha/ref
=> enhance: improve Terragrunt inputs parsing

cmd/infracost/testdata/generate/prefer_folder_name/expected.golden, cmd/infracost/testdata/generate/prefer_folder_name/infracost.yml.tmpl, cmd/infracost/testdata/generate/prefer_folder_name/tree.txt, internal/config/config.go, internal/hcl/project_locator.go, internal/providers/detect.go
Adds new configuration field which allows users to specify how envs are inferred. Setting `prefer_folder_name_for_env: true` means that the envs are inferred from folder names rather than the terraform vars contained in that folder. This is to solve the case where customers have envs defined by folder names but also with coliding tfvar names e.g:
```
.
└── infra
├── envs
│   ├── stg
│   │   └── prod.tfvars
│   └── qa
│       └── prod.tfvars
└── main.tf
```
This normally occurs if they have strange environment setup or they have mis spelled or copied a tfvar file.
=> feat: add prefer_folder_name_for_env autodetect config

go.mod, go.sum, internal/hcl/modules/loader.go
Chainguard have forked it and now maintaining it.
=> chore(deps): switch to maintained package of git-urls

cmd/infracost/breakdown_test.go, cmd/infracost/testdata/breakdown_terraform_provided_default_envs/breakdown_terraform_provided_default_envs.golden, cmd/infracost/testdata/breakdown_terraform_provided_default_envs/infracost.yml, cmd/infracost/testdata/breakdown_terraform_provided_default_envs/mod/main.tf, internal/hcl/parser.go
adds the inferred env name as a starting variable input to the terraform project if no user workspace has been defined. This is preferable over using just the base "default" workspace.
=> feat: add detected env name to input vars/workspace

internal/hcl/remote_variables_loader.go, internal/hcl/remote_variables_loader_test.go
Changes remote variable loading to ignore a matched stack if it has been previously
used by another project and updates the matching logic to also work with a prefix.
=> enhance: spacelift variable loader improvements

internal/providers/terraform/aws/cloudfront_function.go, internal/providers/terraform/aws/cloudfront_function_test.go, internal/providers/terraform/aws/registry.go, internal/providers/terraform/aws/testdata/cloudfront_function_test/cloudfront_function_test.golden, internal/providers/terraform/aws/testdata/cloudfront_function_test/cloudfront_function_test.tf, internal/providers/terraform/aws/testdata/cloudfront_function_test/cloudfront_function_test.usage.yml, internal/resources/aws/cloudfront_function.go
Add support for AWS CloudFront Function. Fixes #3268.
I am using https://aws.amazon.com/cloudfront/pricing/ as the source of my calculation. To calculate the price, users have to sum their cloudfront distribution requests, and multiply it with existing AWS prices which is $0.1 per 1M invocations / request. The difficult thing is that this resource is not on AWS Pricing calculator yet.
Fix #3268
=> feat(aws): add aws_cloudfront_function support

internal/hcl/modules/fetch.go, internal/hcl/modules/fetch_test.go, internal/providers/terraform/hcl_provider.go, internal/providers/terraform/hcl_provider_test.go, internal/providers/terraform/terragrunt_hcl_provider.go, internal/providers/terraform/testdata/hcl_provider_test/adds_source_url_from_remote_module/expected.json, internal/providers/terraform/testdata/hcl_provider_test/adds_source_url_from_remote_module_chdir/expected.json
* It now works with converting between Azure Devops SSH URLs to HTTPS URLS
* It now strips users from HTTPS URLs
* There's shared logic between using it for forcing HTTPS downloads and generating module HTTPS URLs
=> enhance: update URL normalizing to work with both SSH and HTTPS URLs

internal/hcl/modules/fetch.go, internal/providers/terraform/testdata/hcl_provider_test/adds_source_url_from_remote_module/expected.json, internal/providers/terraform/testdata/hcl_provider_test/adds_source_url_from_remote_module_chdir/expected.json
This ensures that if the user has a hardcoded HTTPS module URL like: `git::https://user@host.com/path/to/repo`
that we first try without the hard-coded user since they may have valid creds for a different user.
=> fix: ensure we try normalized HTTPs URLS when downloading modules

internal/hcl/parser.go
also adds detected env name as "environment" tfvar if not already set.
=> enhance: also add "environment" variable to input vars

cmd/infracost/testdata/breakdown_format_json_propagate_defaults_to_volume_tags/breakdown_format_json_propagate_defaults_to_volume_tags.golden, internal/providers/terraform/aws/tags.go
volume_tags are only applied when an instance is created. So to reduce the potential for drift, tagging policies should only suggest using them when they're already being used.
=> enhance: only populate default tags on aws_instance.volume_tags when they are already used

cmd/infracost/testdata/generate/force_project_type_no_valid_project/expected-tree.golden, cmd/infracost/testdata/generate/force_project_type_no_valid_project/expected.golden, cmd/infracost/testdata/generate/force_project_type_no_valid_project/infracost.yml.tmpl, cmd/infracost/testdata/generate/force_project_type_no_valid_project/tree.txt, internal/hcl/project_locator.go
Resolves issue where invalid terraform project (no backend/provider blocks) are found in the same directory as a terragrunt project. If we try and force the project type in this scenario, the project locator resolve 0 valid projects and then fell back to just adding in all projects. I've fixed this by only "forcing" the fallback projects if they are of the forced project type.
=> fix: duplicate projects with force with invalid project

internal/config/config.go, internal/hcl/modules/fetch.go, internal/hcl/modules/fetch_test.go, internal/hcl/modules/loader.go, internal/hcl/modules/public_checker.go, internal/hcl/modules/public_checker_test.go, internal/hcl/modules/s3_cache.go, internal/providers/terraform/azure/testdata/kubernetes_cluster_node_pool_test/kubernetes_cluster_node_pool_test.golden, internal/providers/terraform/azure/testdata/virtual_machine_test/virtual_machine_test.golden, internal/providers/terraform/azure/testdata/virtual_network_gateway_connection_test/virtual_network_gateway_connection_test.golden, internal/providers/terraform/azure/testdata/virtual_network_gateway_test/virtual_network_gateway_test.golden, internal/providers/terraform/hcl_provider.go, internal/providers/terraform/terragrunt_hcl_provider.go
add support for public module caching. The API will be updated to always
pass through the module cache bucket but adding a new env var for
private caching so only runners that are for repos with
`useS3ModuleCache` enabled will store private modules
=> feat: support caching public modules

internal/hcl/modules/fetch.go, internal/hcl/modules/public_checker.go, internal/hcl/modules/public_checker_test.go
we don't support git@github.com urls in the public checker so asume its
not public
=> chore: Handle git@ urls more cleanly

internal/hcl/modules/public_checker.go
When checking if a module is public, don't follow any redirects to avoid
hitting enterprise github sites. We err on the side of caution and only
treat as public if the first call is a 200 - this is the case for public
github repos
=> chore: don't follow redirects when checking public

internal/hcl/modules/public_checker.go
To prevent signed URLs being seen as public and cached, limit to
specific hosts, currently only github.com. This will still catch a
significant amount of public modules
=> chore: limit the hosts that can be classed as public

cmd/infracost/diff_test.go, cmd/infracost/testdata/diff_with_compare_to_with_past_project_error_terragrunt/diff_with_compare_to_with_past_project_error_terragrunt.golden, cmd/infracost/testdata/diff_with_compare_to_with_past_project_error_terragrunt/infracost.yml, cmd/infracost/testdata/diff_with_compare_to_with_past_project_error_terragrunt/prior.json, cmd/infracost/testdata/diff_with_compare_to_with_past_project_error_terragrunt/terragrunt.hcl, cmd/infracost/testdata/diff_with_compare_to_with_past_project_error_terragrunt/us/dev/terragrunt.hcl, cmd/infracost/testdata/diff_with_compare_to_with_past_project_error_terragrunt/us/modules/example/main.tf, cmd/infracost/testdata/diff_with_compare_to_with_past_project_error_terragrunt/us/prod/terragrunt.hcl, internal/providers/terraform/terragrunt_hcl_provider.go
Prior to this change, when evaluating a Terragrunt project, we treated the underlying Terraform module errors as just a warning diagnostic. This created issues with the diff logic as baseline Terragrunt projects would have warning metadatas but a zero cost as the project could not be evaluated. If this was an intermittent error, which is often the case with Terragrunt and the caching logic then users would see a 100% cost increase for the project as it was seen as going from 0 to the current project price.
I've changed the logic now to treat Terraform errors as first class Terragrunt evaluation errors in the evaluator. This means that when diffing we'll show that we couldn't compute the price instead of a new project addition.
=> fix: treat underlying Terraform errors as Terragrunt project errors

go.mod, internal/hcl/modules/loader.go, internal/hcl/modules/loader_test.go, internal/hcl/modules/manifest.go, internal/hcl/modules/testdata/sourcemap_local_module/main.tf, internal/hcl/modules/testdata/sourcemap_local_module/modules/local-module/main.tf
When a module's source has a relative path like `../../modules/` but needs to be mapped to another path, the module is still loaded using the original source value.
Important: this mapping only works when the path starts with the mapping value.
=> fix: Add local modules to manifest if they are source mapped

internal/providers/terraform/azure/cognitive_deployment.go, internal/providers/terraform/azure/cognitive_deployment_test.go, internal/providers/terraform/azure/testdata/cognitive_deployment_test/cognitive_deployment_test.golden, internal/providers/terraform/azure/testdata/cognitive_deployment_test/cognitive_deployment_test.tf, internal/providers/terraform/azure/testdata/cognitive_deployment_test/cognitive_deployment_test.usage.yml, internal/resources/azure/cognitive_deployment.go
adds new models to cognitive deployment with additional cost components. 
Note: we've hard coded the skus here as there is no consistency in the naming. In future we'll modify the pricing api logic to normalize on ingestion, but it was decided that we don't do this now.
=> feat: add new openai models and cost components

go.mod, go.sum, internal/hcl/modules/s3_cache.go
Switch from github.com/mholt/archiver to github.com/mholt/archives since archiver is deprecated and has open vulnerability reports
=> refactor: remove deprecated package

internal/output/diff.go
=> fix(output): guard against NPEs when output.PastBreakdown is nil

internal/output/combined.go, internal/output/markdown_test.go, internal/output/testdata/ToMarkdown_NoPreviousBreakdown.json, internal/output/testdata/ToMarkdown_NoPreviousBreakdown.md
This CL is a continuation of infracost/infracost#3409 and infracost/infracost#3419,
and fixes the source of nil `PastBreakdown`s, during `output.Load`s.
We also add a test for the entire `output.ToMarkdown` flow that is called in
`infracost comment`, hopefully giving us some resiliency to this sort of problem
in the future.
```
2025-07-08  Paul Stemmet  <paul.stemmet@infracost.io>
chore(output): add ToMarkdown test for PastBreakdown NPEs
2025-07-08  Paul Stemmet  <paul.stemmet@infracost.io>
fix(output): add nil check for Project.PastBreakdown to output.Load
The code in internal/output implicitly assumes a Project's PastBreakdown
field is non-nil (though the Breakdown fields *may* be nil / empty).
This commit adds a check to the json loader to ensure that if the
PastBreakdown is nil in the …
```
=> fix(output): ensure PastBreakdown is non nil
